### ISSUE TITLE
prepare Google Drive pivot tables

### ISSUE THREAD

**Issue by gemfarmer** [ONRR/doi-extractives-data#1447]
This issue is a subtask related to testing the site's data. We need to create pivot tables for each datatime so that they can be compared to the transformed .yml files in the _data directory. 

What data do we have in the [gDrive](https://drive.google.com/drive/u/0/folders/0B2CjDILjK8_jMHhWZVZNN0dMZ1E) now?
- production
- reconciliation
- revenue
- disbursements

What do we additionally need?
- [ ]  land stats
- [ ] exports
- [ ] gdp
- [ ] jobs
- [ ] ensure that the we have all the data for revenue and production

Once we have the right data, pivot tables should be made for each dataset and added to the project for testing.

cc @shawnbot

**Comment by gemfarmer** [comment]
For reference, steps for creating a pivot table in Excel 2016:
- Place data in a sheet
- Insert > Pivot Table
- Put all column headers under the row field
- Place value under value field
- In Design tab Click Report Layout and select "Repeat All Item Lables"
-  In Design tab Click Report Layout and select "Show in Tabular Form"

👌

**Comment by coreycaitlin** [comment]
@gemfarmer Did we do this?

**Comment by gemfarmer** [comment]
Nope, but now it is [in the documentation](https://github.com/18F/doi-extractives-data/blob/master/data/Create-pivot-table.md) for future additions. The datasets that still don't have pivots are untested at this point. It could be worthwhile to add more tests the next time we update any of the follwoing data:
- land stats
- exports
- gdp
- jobs

**Comment by coreycaitlin** [comment]
This is a dependency for #1502 and #2323

**Comment by jennmalcolm** [comment]
Next step is to determine if we will be going in a different direction for data management for NRRD.

**Comment by jennmalcolm** [comment]
Closing as we're using a different way to query data that doesn't rely on pivot tables.
