### ISSUE TITLE
Data Tests: GDP

### ISSUE THREAD

**Issue by gemfarmer** [ONRR/doi-extractives-data#1502]
Part of  #1399 
## TODO

Create pivot tables for the following
- GDP by state 

Pivot tables should match outputted yml files for the following datasets
## Steps to reproduce the behavior
- [ ] make pivot table for each dataset
-  [ ] write tests

**Comment by gemfarmer** [comment]
There are currently no GDP tests :(

**Comment by gemfarmer** [comment]
@toolness here is another data testing issue.

**Comment by jennmalcolm** [comment]
Closing as we will not be keeping GDP data on NRRD.
