### ISSUE TITLE
Idea: Show federal production rankings

### ISSUE THREAD

**Issue by coreycaitlin** [ONRR/doi-extractives-data#2310]
We got some feedback from ONRR folks that it might be interesting to see federal production rankings by state, especially compared to all-lands production. Also, distribution rankings by state.

In the past, we decided not to show this because we found that it was confusing when rankings were not out of 50 (i.e. what does "ninth for geothermal production" mean if you don't know that there are only 10 states producing geothermal?).

Before implementing, we should do some research on whether and how this would help users understand what they want to know.

**Comment by usEITI** [comment]
Thank you for documenting.  I know the Assistant Secretary for Land and Minerals would also like to see this.  We have to leave this for the innovation design Team and focus now on the 2017 report.

**Comment by coreycaitlin** [comment]
Particularly for internal users, this seems like a promising way to add meaning and context to the numbers.

**Comment by coreycaitlin** [comment]
Next steps: keep an eye on this in user research, begin design/content exploration of what potential implementation directions might be fruitful.

**Comment by jennmalcolm** [comment]
We can look at this for disbursements and incorporate into new design.

**Comment by jennmalcolm** [comment]
Next step, research this to determine if people actually want to see this @mcharg.  Also related to #3254.

**Comment by mcharg** [comment]
For research findings see: https://github.com/ONRR/doi-extractives-data/blob/research/research/researchfindingsbytopic.md#production-rankings

**Comment by mcharg** [comment]
Summary from findings: Participants would use rankings to compare against other data. One said they expected them to be wrong because EIA updates their data more frequently. One would compare against data from the states and one wants to compare changes over time.

**Comment by jennmalcolm** [comment]
This is being considered as part of #3277, and also the production filterable table.
