### ISSUE TITLE
Federal revenue by company: State-level data

### ISSUE THREAD

**Issue by coreycaitlin** [ONRR/doi-extractives-data#2315]
Soon, we will have state-level data for [federal revenue by company](https://useiti.doi.gov/how-it-works/federal-revenue-by-company/2016/) (AKA `UDR`). We'll need to decide how to present that data: whether we want to add a location element to the existing page, add this data to the national and state explore-data pages, or something new!

We should also investigate how users want to explore and use this data.

**Comment by coreycaitlin** [comment]
Noting that this is blocked until we have the data.

**Comment by coreycaitlin** [comment]
Next step: Look at test data and begin planning for the initial integration of this data.

**Comment by coreycaitlin** [comment]
We now have the draft data to work with [here (limited access)](https://docs.google.com/spreadsheets/d/1w3WMPXof7_8sOxPczSdbVMZaPFDeWHqBzfDXfs9nxUE/edit#gid=821589876), and should think about what the initial iteration of getting this online should look like.

From @mentastc:

> We will need to footnote the blanks in the table to explain why we don't have location data on all the revenues, because those revenues aren't tied to a lease.

**Comment by msecret** [comment]
Looking at the data, I have some questions:

- When it says something like `($80)`, does that mean -$80?
- There are a couple of rows with `N/A` for both state and land category. Where will we put these?

If we put this data on the state page, we'd probably write a query that goes through all 50 states, selects all entries for each state, and outputs the company, and types.

**Comment by ericronne** [comment]
`($)` and `-$` both mean neg, yep

@coreycaitlin can help with the `N/A` no doubt!

**Comment by coreycaitlin** [comment]
@mentastc We're still holding on this until we hear the go-ahead from you or Judy!

**Comment by brentryanjohnson** [comment]
Closing this for now. We can reopen this issue if and when state-level UDR data is viable for publication.
