### ISSUE TITLE
Add data test for jobs data

### ISSUE THREAD

**Issue by gemfarmer** [ONRR/doi-extractives-data#2323]
When we added the jobs by commodity issue (#2156), the source data changed so drastically that we had to scrap the old tests. Because we needed to get the data out the door and it appeared accurate, we didn't add tests at the time.  

## Expected Behavior
Data should be added and should compare source data to outputted yaml files.
- self employment data is tested. 
- wage and salary jobs data is tested.
- wage and salary jobs data by commodity data is tested. 

## Actual Behavior
None of the data is tested

**Comment by gemfarmer** [comment]
@toolness this is a can of worms and definitely an important one to check out. We have pretty poor test coverage on this project, so figuring out better ways to test the code that we have and/or re-architecting  to allow for easier testing are priorities!

**Comment by jennmalcolm** [comment]
Through content strategy decisions #2799, we have decided not to maintain job data in the future. So, I'm closing this issue.
