### ISSUE TITLE
Digging into discrepancies between Energy Jobs Report and EITI jobs numbers

### ISSUE THREAD

**Issue by onezerojeremy** [ONRR/doi-extractives-data#2329]
There are some rather large discrepancies between the number of [jobs](https://useiti.doi.gov/explore/#economic-impact) quoted on the EITI website and those stated in the Department of Energy's [2017 Energy Employment Report](https://www.energy.gov/sites/prod/files/2017/01/f34/2017%20US%20Energy%20and%20Jobs%20Report_0.pdf)

| EITI fuel | EITI employment | Jobs report employment | Jobs report fuel  | 
|-----------|-----------------|------------------------|-------------------| 
| Oil & Gas | 422,694         | 877,636                | Oil  and Gas             | 
|           |                 | 515,518                | Oil               | 
|           |                 | 362,118                | Gas               | 
| Coal      | 54,805          | 160,119                | Coal              | 
| Hydro     | 6,489           | 65,554                 | Hydro             | 
|           |                 | 9,295                  | traditional hydro | 
|           |                 | 56,259                 | low impact hydro  | 
| Wind      | 4,878           | 101,738                | Wind              | 
| Solar     | 2,766           | 373,807                | Solar             | 
| Nuclear   |                 | 76,771                 |                   | 

_(Oil includes 502,678 for fuels and 12,840 for generation)_
_(Gas includes 309,993 for fuels and 52,125 for generation)_
_(Coal includes 74,084 for fuels and 86,035 for generation)_

It seems that the discrepancies arise from the decision to use only the NAICS codes for generation for Hydro, Wind, Solar and Geo (221111, 221115, 221114, 221116, respectively), but including other NAICs codes than generation for fossil fuels (221112). This decision is noted on the page, which is good, but I'd argue that it makes the data non-comparable and could be potentially misleading. 

As is often the case, the critique is the easy part. From here, everything gets complicated and messy, and it's not hard to see how the website ended up where it did. (I'd still contend it's worth changing). 

Fundamentally, the decision seems to me to balance on whether to count supporting activities. If not, then a comparison of NAICS codes 221111, 221115, 221114, 221116, and 221112 feels sufficient, but would not allow differentiation between different fossil fuel types. 

However, the section is about economic impact, and including data simply about the actual act of turning an input fuel into electricity feels like it misses a great deal of the economic impact. For instance, in 2016 the act of turning natural gas into electricity accounted for 52,125 jobs, but the industry employed another 309,993 people (not all of those jobs were about energy generation). 

If it is desirable to include supporting activies (and I think it is), the way gets more complicated: for example, according to the report, the bulk of solar power industry jobs are from the construction of solar generating facilities. (page 28) As far as I have been able to see, while the report shows the percentage of 2016 construction jobs it determined are part of the energy sector, I did not find the list of the NAICS codes it used in coming to this. Possibly something in the 2371- family. 

I'm no expert on NAICS codes, so I'm going to go ahead and post the issue without really laying out a way forward in the hopes that folks agree and can carry it forward. 😬  ✌️  ❤️

**Comment by jennmalcolm** [comment]
First step is to determine if we will continue to include jobs data on NRRD. This could be addressed in #2799.

**Comment by jennmalcolm** [comment]
Closing as we have determined that we will not maintain this data in the future.
