### ISSUE TITLE
State hover titles cropped

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2431]
## Expected Behavior

- State titles on map display on hover

## Actual Behavior

- Northern states' titles appear to be cropped by container

![cropped_title_tags](https://user-images.githubusercontent.com/32855580/32346124-90871f88-bfc9-11e7-9a75-4a4ab1ead098.png)

**Comment by coreycaitlin** [comment]
Previously: #2118, #2146

**Comment by coreycaitlin** [comment]
We're not able to replicate this in Chrome (Mac or PC) or Safari. If you see this again, please note the browser and OS so we can track this down!

**Comment by brentryanjohnson** [comment]
It appears it's isolated to Chrome on the ONRR Windows machines for me. The cropping is still occurring for me in:
- Chrome 64.0.3282.140

I believe this was also an issue in Firefox when I tested before, but the tooltips now appear as designed in:
- Firefox Developer Edition 59.0b9 (64-bit)


IE 11, which is still on the ONRR machines, doesn't display the tooltips at all.

**Comment by jennmalcolm** [comment]
Doesn't appear to be an issue any more.
