### ISSUE TITLE
Add favicon file / site icon across mobile devices

### ISSUE THREAD

**Issue by ericronne** [ONRR/doi-extractives-data#2452]
Current iphone favorites icon, eg....
![missing-site-icon](https://user-images.githubusercontent.com/9259185/32899724-541d67a8-cab1-11e7-94ac-5b660097245e.png)

**Comment by ericronne** [comment]
Opened [favicon-for-hi-res](https://github.com/18F/doi-extractives-data/tree/favicon-for-hi-res) branch to experiment. [Preview link](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/favicon-for-hi-res/).

**Comment by ericronne** [comment]
Online favicon checker …
https://realfavicongenerator.net/favicon_checker#.Wljo65M-cUG

Results for revenuedata.doi.gov ...
https://realfavicongenerator.net/favicon_checker?protocol=http&site=revenuedata.doi.gov#.WljouZM-cUE

**Comment by coreycaitlin** [comment]
Next step: upload a high-res version of this image, so the team has that asset for future use. @ericronne, could you help out with that?

**Comment by jennmalcolm** [comment]
Low priority, and we haven't heard this from users, so we are closing for now. We will bring it back up if we start hearing more from users about this.
