### ISSUE TITLE
Determine how to update sketch-based charts going forward

### ISSUE THREAD

**Issue by ericronne** [ONRR/doi-extractives-data#2497]
A number of bar and line charts (case studies, AML, etc.) were created "by hand" in Sketch. If ONRR is unable to obtain that (Mac-only) app, they will have to be updated in another way.

For the sake of accessibility (and other benefits), all data displays would ideally live in code, rather than as static graphics. Discuss!

**Comment by ericronne** [comment]
related: #2498

**Comment by coreycaitlin** [comment]
Next step: determine whether these charts (and the data in them) will be updated in future years.

**Comment by ericronne** [comment]
If they are to be maintained, D3 might be the way to go. Provided the tech talent is available, of course.

**Comment by brentryanjohnson** [comment]
I agree with @ericronne. First step is to determine ongoing value and maintenance burden, but should we see value in maintaining the content, I think we should convert these to D3. It's a great opportunity for @master12 and I to dig into D3.

**Comment by brentryanjohnson** [comment]
Sure, @jenniferthibault. 

Much of the data on the site is "owned" by the Office of Natural Resources Revenue. For example, production, revenue, and disbursements data from federal lands and waters comes from ONRR itself. 

Some other data on the site is updated via API, such as the GDP data.

This particular, state-level data has been pulled together by Deloitte in the past. Deloitte served as the Independent Administrator during the EITI years. Both the opt-in charts and the [case studies](https://revenuedata.doi.gov/case-studies/) charts were created to support the EITI reporting process. In other words, the generation of the content and data for these particular charts was heavily dependent on the structure and governance of the EITI.

**Comment by jenniferthibault** [comment]
Thank you @brentryanjohnson!

**Comment by jennmalcolm** [comment]
Based on our content strategy, we won't be maintaining these charts in the future. We will use D3/spark lines and take up issue 1 by 1 if we need to keep any of the charts.

**Comment by ericronne** [comment]
Awesome!
