### ISSUE TITLE
Evaluate reading data from csv or json files

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2542]
@msecret Do you mind looking into the feasibility of reading data out from csv or JSON, as opposed to YAML? Given [Jekyll can read into data files in csv, JSON, _and_ YAML](https://jekyllrb.com/docs/datafiles/), I wonder if it's possible to reduce the complexity of our data update workflow by reading directly into the origin files and eliminate the need for multiple conversions (csv-->tsv-->yml-->json).

**Comment by coreycaitlin** [comment]
This would be a significant refactoring project, but might be worth investigating in the future.

**Comment by jennmalcolm** [comment]
Going away with Gatsby GraphQL.
