### ISSUE TITLE
Refactor _includes/location directory to reduce dependencies

### ISSUE THREAD

**Issue by coreycaitlin** [ONRR/doi-extractives-data#2573]
We believe that our build times are being slowed by the sheer volume of cross-references and includes in the `_includes/location` directory. We _think_ that simplifying these files will help speed up the build.

**Comment by coreycaitlin** [comment]
Next step: I will write more about what I've envisioning here.

**Comment by jennmalcolm** [comment]
Going away with Gatsby.
