### ISSUE TITLE
learn more about the kinds of questions DOI Public Affairs offices receive about natural resources revenue

### ISSUE THREAD

**Issue by alexpandel** [ONRR/doi-extractives-data#2578]
During our last research sprint, we learned that many of the information requests ONRR received from other DOI staff originate from inquiries to the Public Affairs office.

To help us identify how we could make it easier for these Public Affairs folks to get the info they need, we should conduct more focused research with folks from various DOI Public Affairs offices, to better understand the kinds of questions they receive, and how they go about getting that information now.

**This issue is done when:**

- [ ] we've drafted a research plan to conduct this research.
- [ ] we've opened a new task related to conducting and synthesizing this research.

**Comment by coreycaitlin** [comment]
This is one of our key user groups, so we'd like to tackle this research soon!

**Comment by jennmalcolm** [comment]
Not necessary to explore this anymore as public affairs is a part of our program area, and we are hearing about any issues they're getting from DOI.
