### ISSUE TITLE
Consider adding sales year data

### ISSUE THREAD

**Issue by alexpandel** [ONRR/doi-extractives-data#2580]
We heard from several users in this research round (as well as over the past few months via ONRR’s Data Services team) that making _sales year_ data available on NRRD would be particularly useful. If this could save the Data Services team significant time currently spent fulfilling custom request for this data, the team should consider how they might go about adding sales year data to NRRD.

**Comment by jennmalcolm** [comment]
We need to explore adding sales volume and value on sales year as part of an upcoming round of user research..

**Comment by mcharg** [comment]
For research findings see:
https://github.com/ONRR/doi-extractives-data/blob/research/research/researchfindingsbytopic.md#sales-year

**Comment by mcharg** [comment]
Summary from findings: Sales year data isn't as useful. When asked a few have said it might be useful, but couldn't provide a clear use case for when they would use it.

**Comment by jennmalcolm** [comment]
We will be adding sales year data; first step is in #3744
