### ISSUE TITLE
learn more about the kinds of long-term trend analyses users are doing to determine how much historical data to include in NRRD

### ISSUE THREAD

**Issue by alexpandel** [ONRR/doi-extractives-data#2581]
We heard a desire from several of the people we talked to for "historic" data in order to observe trends that are only discernible by looking further back, but we don't know enough about the trend analyses users are conducting to know for sure how much data would be useful. 

It could be worth doing more targeted research to learn more about this particular use case in order to determine how much historical data would be worth the effort to incorporate into NRRD.

We do know that data is available going back to 1982 on the [statistics site](https://statistics.onrr.gov/Information.aspx), which could be a helpful reference point for any future research into this user need. 

**This issue is complete when:**

- [x] we've decided whether it's worth conducting more research into this topic
- [ ] if yes, we've developed a plan for this research round
- [ ] we've created issues for conducting and synthesizing this research

**Comment by jennmalcolm** [comment]
First step is to check with Data Retrieval to see how often they are answering these requests. 
Look into just providing more years of data in the raw data files.

**Comment by mcharg** [comment]
For research findings see: https://github.com/ONRR/doi-extractives-data/blob/research/research/researchfindingsbytopic.md#trend-analysis

**Comment by mcharg** [comment]
Summary from findings: Participants want the data to go back as far as possible for all time to get at what’s going on now compared to previously and understand context.

**Comment by mcharg** [comment]
See #3625 for our solution to adding more data.
