### ISSUE TITLE
Make download button style consistent

### ISSUE THREAD

**Issue by ericronne** [ONRR/doi-extractives-data#2582]
Buttons in the Downloads section ([eg here](http://localhost:3000/downloads/federal-revenue-by-location/) use the `downloads-download_links list-unstyled` classes, which generate links like look like this …
![image](https://user-images.githubusercontent.com/9259185/34628364-a355134e-f229-11e7-9722-e2c8332758c4.png)

This doesn't match the download buttons on the [executive summary](https://revenuedata.doi.gov/about/report/) and [audits and assurances](https://revenuedata.doi.gov/how-it-works/audits-and-assurances/) pages, which use the `button-tertiary` class …
![image](https://user-images.githubusercontent.com/9259185/34628448-ffd908e6-f229-11e7-9d22-40f202f02d36.png)

**Comment by ericronne** [comment]
cc @coreycaitlin @brentryanjohnson

**Comment by coreycaitlin** [comment]
It looks like we use one style for data downloads, and the other style for document downloads. Next step: verify, and document that pattern in the style guide.

**Comment by jennmalcolm** [comment]
Not an issue as these documents are not available on NRRD now.
