### ISSUE TITLE
County production map bug

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2604]
Example from [Wyoming coal production county map](https://revenuedata.doi.gov/explore/WY/#federal-production)

## Expected Behavior

* County mouse hover should only be active for counties with some production level (>0)
* Table below map should only include counties with production >0

## Actual Behavior

* In the example linked above, two counties have a hover activated, but zero production (Lincoln, Carbon)

* Lincoln is shown in the table when expanded, although it has 0 coal production.
* Carbon county is correctly omitted from the table, despite having an active hover.

**Comment by coreycaitlin** [comment]
There's a _chance_ that this is an artifact of `withheld` data, so we should look into that when we go to debug this.

**Comment by coreycaitlin** [comment]
Next step: validate whether this is the same bug as #2641, and clarify this issue if not.

It looks like this may also be an issue in some [jobs](https://revenuedata.doi.gov/explore/WY/#employment) charts, as well.

**Comment by mentastc** [comment]
Related to #2641 

The "0" in Lincoln county should actually be a "W" for withheld

**Comment by jennmalcolm** [comment]
The issue with withheld data showing zero in the table is fixed through #2765.

County hovers are still active for counties that have data or withheld data during any of the time frame of the data. Ideally, the hover would only be active when there is data or withheld data for the year selected. 

![image](https://user-images.githubusercontent.com/30806839/38807096-6ba3428a-4149-11e8-8cf2-7b7fde2c35e1.png)
