### ISSUE TITLE
Configure CircleCI to use .ruby-version and .nvmrc

### ISSUE THREAD

**Issue by jeremiak** [ONRR/doi-extractives-data#2653]
We have a few places you have to update language version numbers, including the [`Dockerfile`](https://github.com/18F/doi-extractives-data/blob/dev/Dockerfile),
 [`.ruby-version`](https://github.com/18F/doi-extractives-data/blob/dev/.ruby-version), [`.nvmrc`](https://github.com/18F/doi-extractives-data/blob/dev/.nvmrc), and [`circle.yml`](https://github.com/18F/doi-extractives-data/blob/dev/circle.yml).

Can CircleCI be configured to any of those other files instead? If so, we should configure it to do so.

**Comment by jennmalcolm** [comment]
Closing in favor of #3343
