### ISSUE TITLE
Data and documentation links are inconsistently styled

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2695]
Related to #2694. Our "Data and documentation" links have inconsistent alignment and font weight depending on their instances.

- We should try to make them consistent in all instances
- We should consider using the heavier font weight currently employed in the [Downloads](https://revenuedata.doi.gov/downloads/) instances to better match the stroke weight of the SVG icon.

## Explore data instances
![data and doc link explore](https://user-images.githubusercontent.com/32855580/37221876-1842d042-2380-11e8-9ac0-f473f67fbc3c.png)

## Download data instances
![data and doc link downloads](https://user-images.githubusercontent.com/32855580/37221892-2c3b700e-2380-11e8-8206-8ce2110b88c5.png)

**Comment by brentryanjohnson** [comment]
Here is another example of inconsistent styling. The [disbursements section](https://revenuedata.doi.gov/explore/#federal-disbursements) has a default underlined link (which omits underline on hover), while the [GDP section](https://revenuedata.doi.gov/explore/#gdp) has a link that isn't underlined (until hover).

## Disbursements link
![data and documentation with underline](https://user-images.githubusercontent.com/32855580/38882656-97906ebe-421f-11e8-8c1b-7520500ab681.png)

## GDP link
![data and documentation link without underline](https://user-images.githubusercontent.com/32855580/38882677-a7c3b6d8-421f-11e8-82f5-b83d9a588c00.png)

**Comment by jenniferthibault** [comment]
Definitely agree! Based on the style guide audit, this style stuck out because the font weight was inconsistent with all of the other link styles used outside of body text. 

I'd +1 for making it bold like all of the other non-paragraph links!

**Comment by mcharg** [comment]
@brentryanjohnson Did this get fixed when we implemented the new download icons?

**Comment by brentryanjohnson** [comment]
Indeed!
