### ISSUE TITLE
Exports subheading missing from Washington, DC

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2708]
## Expected Behavior

- Every location page has "Exports" subheading

## Actual Behavior

- [Washington DC](https://revenuedata.doi.gov/explore/DC/#exports) is missing the Exports subheading, but does have Exports content

![exports subheading missing](https://user-images.githubusercontent.com/32855580/37546492-4c7e440e-292a-11e8-85a9-1fb616f9bf6f.png)

**Comment by jennmalcolm** [comment]
Going away with new content strategy and recoding.
