### ISSUE TITLE
Inconsistent table labels for Pacific maps

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2721]
We have inconsistent labels on the Pacific offshore maps. The [production map](https://revenuedata.doi.gov/explore/offshore-pacific/#production) has the region labeled as "Region," while the [revenue map](https://revenuedata.doi.gov/explore/offshore-pacific/#revenue-by-area) has the region labeled as "Pacific." 

We should consider using consistent labels for the table columns.

![pacific production map](https://user-images.githubusercontent.com/32855580/37671669-76a7de46-2c29-11e8-998f-983cff516b21.png)

![pacific revenue map](https://user-images.githubusercontent.com/32855580/37671709-933d7908-2c29-11e8-94f5-f5af359ca2f2.png)

**Comment by echang97** [comment]
I've made a branch, but I can't seem to preview it properly on Federalist
[❔ Preview](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/pacific-table-labels/explore/offshore-pacific/)

**Comment by jennmalcolm** [comment]
I think the issue is that the offshore pages are static. @master12 will be working on them in Gatsby this sprint.

**Comment by mcharg** [comment]
@master12 Edward attempted to fix this while you were moving the offshore pages to Gatsby.  Is his fix something that can be brought into the new pages or do we need to move this back to the backlog (it's sitting in In Progress)?
