### ISSUE TITLE
Implement transitional styling for EITI archive

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2722]
We have a lot of content that supported USEITI, but isn't likely to be updated and maintained in the future. For example, [reconciliation data](https://revenuedata.doi.gov/downloads/#reconciliation) was generated to support the implementation of the EITI standard, but will probably not be updated beyond 2015. **The majority of data, content, and documentation will be continue to be updated and maintained.**

We should consider creating transitional styling to mark for users content that will be migrated to an EITI archive.

To this end, I created [a prototype](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/eiti-archive/downloads/#reconciliation) (excuse the messy CSS) for review and comment to test assumptions about the value and effectiveness of marking content for archiving.

![eiti archive section prototype](https://user-images.githubusercontent.com/32855580/37684684-0f9edf72-2c4e-11e8-9286-7879c7ed3a52.png)

If we choose to go this route, it might make sense to create an archive tag, whereby we can aggregate the content into one place, but also leave it in context for now while we scope and test this approach.

**Comment by mcharg** [comment]
https://hp1ins.axshare.com/#g=1&p=archived_page

**Comment by jennmalcolm** [comment]
Fixed by #3125.
