### ISSUE TITLE
Understand tech requirements for making components transposable

### ISSUE THREAD

**Issue by jenniferthibault** [ONRR/doi-extractives-data#2770]
### Goal:
**Transposable: it will transfer to a different place or context without breaking**
____

### User story
As a member of the team who implements new components in code, I want to be able to copy and paste component code from the style guide and have it render as expected with as few adjustments as possible. Copy & paste ready.

**Steps for this issue's completion:**
- [ ] Find out if there is a solution for mirroring the master site image path in the style guide: identify tradeoffs/opportunity costs to this approach
- [ ] If needed, identify minimum set of adjustment steps needed when copy+pasting—set/adjust expectations
- [ ] Identify other areas where the components are not transposable and create follow-up issues

**Comment by adborden** [comment]
@master12 have you thought about how the styleguide will play with Gatsby? I have some thoughts, but if you already have thought about it then it would good to mention in this discussion.

**Comment by adborden** [comment]
There is an experimental [react-adapter](https://github.com/frctl/react-adapter) for Fractl that would allow rendering React components. This strategy should work okay with Gatsby, but it would be on us to bring that adapter to a working state.

**Comment by jennmalcolm** [comment]
Handled by #3093
