### ISSUE TITLE
Make components in style guide imitate actual functionality

### ISSUE THREAD

**Issue by jenniferthibault** [ONRR/doi-extractives-data#2771]
### Goal:
**Interactive: it replicates behavior and operation**
_Other issues connected to this goal: #2522_
____

### User stories
- As a UX designer I want to be able to see and understand how the component moves and works in order to assess whether it will fit user needs  
- As a member of the team who implements new components in code, I want to be able to see and understand how the component moves and works so that when I re-use it, I can verify that it’s working as intended and has the correct styles at each state of interaction

**Steps for this issue's completion:**
- [ ] Identify components with functionality that isn't being demonstrated — learn why & create necessary follow up issues
- This issue may or may not be blocked or taken care of entirely by https://github.com/18F/doi-extractives-data/issues/2522
(_I'm not sure if that will be the extent of the needs for this, so this is sort of a backup issue that captures the need and goal_)

**Comment by jenniferthibault** [comment]
Components that have broken interactions in the style guide:

- [ ] Accordions (toggling open/closed)
- [ ] Buttons (hover states)
- [ ] Charts (hover states, mobile accordion open/closed)
- [ ] Global header (mobile menu doesn't work)
- [ ] Selectors (the first two work, but something is broken about the third one)
- [ ] Side navigation (Not expecting sticky functionality, but would be good to show the toggle states if you click into another sub-section)

**Comment by el-mapache** [comment]
@jenniferthibault I've been taking a look at this, and managed to get the buttons and accordion working properly, as well as the chart hover and accordion functionality. However, there is still weirdness with the other components. I will probably open additional tickets for those, as they appear to share an implementation with the actual components in the site, but don't work.

**Comment by el-mapache** [comment]
@jenniferthibault I'm actually not sure what the hover interaction should be, and there aren't too many buttons on the site for me to reference 😄
