### ISSUE TITLE
Make the component documentation clear and understandable

### ISSUE THREAD

**Issue by jenniferthibault** [ONRR/doi-extractives-data#2772]
### Goal:
**The style guide is _clear and understandable_**
_Other issues connected to this goal: #2773_
____

### User stories
- As a UX designer I want to feel confident that I understand what a component is used for, and am choosing to use a component consistently with the project’s design vernacular. 

**Steps for this issue's completion:**
- [x] Create a content model or template for component documentation
- [x] Identify specific gaps and areas for expansion in component documentation.
- [ ] Make the changes!

**Comment by adborden** [comment]
I started including a "How to use" header to capture implementation specific details in the component docs.
