### ISSUE TITLE
Adjust components so that the examples are within sight of the component viewer

### ISSUE THREAD

**Issue by jenniferthibault** [ONRR/doi-extractives-data#2773]
### Goal:
**The style guide is _clear and understandable_**
_Other issues connected to this goal: #2772_
____

### User stories
- As a designer comparing components, I want to be able to find and identify the component quickly and easily within the component viewer.

**Steps for this issue's completion:**
- [ ] Find out why some components are mysteriously out of view, such as https://revenuedata.doi.gov/styleguide/components/detail/map-button-panels.html
- [ ] Adjust components so that the examples are within view

It's unknown at this point, but possible that this issue may be at odds to https://github.com/18F/doi-extractives-data/issues/2770

**Comment by jennmalcolm** [comment]
problem is specific to old styleguide
