### ISSUE TITLE
Fix Montana county spelling

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2781]
Our data currently refers to [`Mccone County`](https://github.com/18F/doi-extractives-data/blob/0ad96e494d22e70a656042fa851936e1b8b609e4/_data/county_revenue/MT.yml), but it should be `McCone County`. This could be due to a programmatic re-casing of the strings.

**Comment by mcharg** [comment]
Not currently fixed in production.  Jeff will need to figure out why it's half not working.

**Comment by brentryanjohnson** [comment]
This is odd...we have duplicate tooltips (addressed in a separate issue), and one has the proper casing, while the other, along with the table entry, do not. @master12 

![County map of montana with spelling issues with mccone county](https://user-images.githubusercontent.com/32855580/47873590-e16fc480-ddce-11e8-8bd6-db73248858db.png)

**Comment by brentryanjohnson** [comment]
This is a problem in the origin data file. We should fix it there. Closing.
