### ISSUE TITLE
Apply glossary functionality to JavaScript output

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2782]
## Glossary terms in Jekyll

We have a custom format in Jekyll that outputs a glossary term, allowing the user to click on the word to reveal the glossary and define the term.

For example: `{{ "ONRR" | term }}`

This essentially applies a `class` that styles the terms and can be targeted by JavaScript to toggle the glossary.

## D3 content

Some of our content is evaluated and output with D3 (our data viz library), such as #2765. In this example, a value of `0` is replaced with the word `Withheld`, which more accurately describes the status of the value in question.

In order to turn this into a glossary term, we _could_ conditionally apply the same styling that's generated by our Jekyll output, but we would likely have to maintain that code and the Jekyll code separately. This would lead to redundant code for the same functionality. 

## Explore options to apply glossary styling to D3 output

Ideally, we would be able to apply glossary functionality to content that is generated by D3 (or other JS) without regenerating code specific to that context.

**Comment by jennmalcolm** [comment]
D3 won't be used for content related to glossary terms, so closing.
