### ISSUE TITLE
Update federal revenue by company data to 2017

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2804]
We have [2016 federal revenue by company data](https://revenuedata.doi.gov/how-it-works/federal-revenue-by-company/2016/). We should update this data to 2017.

#2805 covers moving this data out of [How it works](https://revenuedata.doi.gov/how-it-works/#revenues) to an explore data section.

**Comment by brentryanjohnson** [comment]
There are a few link changes and redirects with this data. For example, the `permalink` in the [`federal-revenue-by-company.html`](https://github.com/ONRR/doi-extractives-data/blob/dev/_layouts/federal-revenue-by-company.html) front matter links to a particular (most recent) year's asset.

Other hard-coded redirect or permalink instances:

- [`_explore/revenue/federal-revenue-by-company/index.html`](https://github.com/ONRR/doi-extractives-data/blob/d2c1d65f8b1bd81f0d10ef174aca5245fb12b271/_explore/revenue/federal-revenue-by-company/index.html)

👆 Federal Revenue by Company is in `how-it-works`, not `explore`, but we plan to move it to 'explore'. Does this file path imply that it started in `explore` and was moved to `how it works`?

- [`_how-it-works/federal-revenue-by-company/index.html`](https://github.com/ONRR/doi-extractives-data/blob/5690026735084717d418a4214df1649093a2136a/_how-it-works/federal-revenue-by-company/index.html)

**Comment by mentastc** [comment]
@brentryanjohnson Here is the new and improved data set that has the below threshold companies rolled up.

[Federal_revenue_by_company_CY2013-CY2017 (1).xlsx](https://github.com/ONRR/doi-extractives-data/files/2397087/Federal_revenue_by_company_CY2013-CY2017.1.xlsx)
