### ISSUE TITLE
Update download link style to download button on state revenue page template

### ISSUE THREAD

**Issue by jenniferthibault** [ONRR/doi-extractives-data#2808]
From #2769 

So that link patterns indicating downloadable content is used consistently across the site, update an instance of a downloadable PDF to use the correct style. The instance occurs on the template for each state's revenue section within Explore data. 

`Explore data` > `State` > `Revenue` > `State revenue`
such as this example from Alaska: https://revenuedata.doi.gov/explore/AK/#state-local-revenue

## Current status 
![screen shot 2018-04-24 at 3 55 52 pm](https://user-images.githubusercontent.com/11636908/39210896-0ede9208-47d8-11e8-9a88-00b7bf3e2301.png)

## Correct pattern(s)

**Download button**
The first, which seems to be used when there is only one item to download available is a download button.
Example: https://revenuedata.doi.gov/how-it-works/audits-and-assurances/

![screen shot 2018-04-24 at 4 03 51 pm](https://user-images.githubusercontent.com/11636908/39211355-58a19d12-47d9-11e8-9719-ab804a21fae9.png)

**Comment by jennmalcolm** [comment]
Closing as many of the buttons will be going away with archiving EITI era content. We will open a new issue as we find any instances of inconsistent icons.
