### ISSUE TITLE
Add hover states and icon example to button component

### ISSUE THREAD

**Issue by jenniferthibault** [ONRR/doi-extractives-data#2810]
From #2769 

So that the button component is complete and accurate:

- [ ] Add hover states to primary and secondary button examples
- [ ] Add example of button with icons
        -  ![screen shot 2018-04-24 at 6 35 36 pm](https://user-images.githubusercontent.com/11636908/39217494-4c0d1c38-47ee-11e8-9631-92ebe3afbfdf.png)

**Comment by jennmalcolm** [comment]
Happening with new pattern library work.
