### ISSUE TITLE
Clarify select component styles and use guidance

### ISSUE THREAD

**Issue by jenniferthibault** [ONRR/doi-extractives-data#2817]
From #2769 
https://revenuedata.doi.gov/styleguide/components/detail/selectors.html

The style guide includes three styles for select components, but not much guidance on how to know when to use each.

![screen shot 2018-04-27 at 10 29 21 am](https://user-images.githubusercontent.com/11636908/39367938-3202f6cc-4a06-11e8-971d-f134dcf6e9db.png)
![screen shot 2018-04-27 at 10 29 43 am](https://user-images.githubusercontent.com/11636908/39367939-320f81da-4a06-11e8-8b6a-4aeda6c94033.png)

To clarify, we could pursue a few different approaches:

1. Simplify number of styles for dropdown select by reducing the number of style options; or
2. If three distinct styles are necessary, add more clear guidance on when and where to use each style.

**Comment by jennmalcolm** [comment]
Happening with new pattern library.
