### ISSUE TITLE
Collect intentional, reusable chart examples and include them in the style guide 

### ISSUE THREAD

**Issue by jenniferthibault** [ONRR/doi-extractives-data#2833]
From #2769 

In #2768 we discovered several examples of charts that aren't represented in the style guide [chart component](https://revenuedata.doi.gov/styleguide/components/detail/charts.html).

**Completion criteria**
- [ ] Determine which chart styles are meant to be re-used 
- [ ] Add those chart types and styles to the style guide
- [ ] Provide notes and use guidance for each chart type
 

Here are the examples found in #2768:

![screen shot 2018-04-20 at 5 42 56 pm](https://user-images.githubusercontent.com/11636908/39456033-b90d4afc-4cb1-11e8-933d-020f980a7732.png)
![screen shot 2018-04-20 at 5 44 11 pm](https://user-images.githubusercontent.com/11636908/39456034-b9214c64-4cb1-11e8-9288-c2b97778569f.png)
![screen shot 2018-04-20 at 5 45 40 pm](https://user-images.githubusercontent.com/11636908/39456035-b92e46c6-4cb1-11e8-88c8-e3f0791dad16.png)
![screen shot 2018-04-20 at 5 38 30 pm](https://user-images.githubusercontent.com/11636908/39456040-bf4f0644-4cb1-11e8-9072-f344420ca908.png)
![screen shot 2018-04-20 at 5 38 35 pm](https://user-images.githubusercontent.com/11636908/39456041-bf5ff9cc-4cb1-11e8-8391-38ffeac9d398.png)
<img width="741" alt="screen shot 2018-04-20 at 5 39 26 pm" src="https://user-images.githubusercontent.com/11636908/39456042-bf707e64-4cb1-11e8-93ad-dd8d8fc069c7.png">
![screen shot 2018-04-20 at 7 16 24 pm](https://user-images.githubusercontent.com/11636908/39456046-ca8afd7e-4cb1-11e8-9e14-2eb76dba2863.png)
![screen shot 2018-04-20 at 7 17 04 pm](https://user-images.githubusercontent.com/11636908/39456047-ca9c7234-4cb1-11e8-9d63-99ab088d9fcc.png)
![screen shot 2018-04-20 at 7 17 13 pm](https://user-images.githubusercontent.com/11636908/39456048-caac5488-4cb1-11e8-89aa-6d049af43943.png)
![screen shot 2018-04-20 at 7 19 10 pm](https://user-images.githubusercontent.com/11636908/39456049-cac7c63c-4cb1-11e8-9069-c41f6e69f669.png)

**Comment by jennmalcolm** [comment]
Closing because the static image charts should be built in D3. Other charts will come over with new pattern library work.
