### ISSUE TITLE
Add example of table with note to components

### ISSUE THREAD

**Issue by jenniferthibault** [ONRR/doi-extractives-data#2835]
From #2769 

So that the style guide includes components that have been or will be re-used, add example of table with a note to style guide.

Seen on the how it works pages: https://revenuedata.doi.gov/how-it-works/reconciliation/2016/
![screen shot 2018-04-20 at 7 25 41 pm](https://user-images.githubusercontent.com/11636908/39457147-b07db126-4cb9-11e8-87ed-c6dda7d77b0f.png)

 
Seems plausible that the pattern solved here (a table cell that needs explanation in context) could be a recurring need and will want to be re-used. We could demonstrate this with content in [an existing table example](https://revenuedata.doi.gov/styleguide/components/detail/tables.html), or in a new one.

**Comment by jennmalcolm** [comment]
We will re-evaluated with new pattern library.
