### ISSUE TITLE
Test Tag Manager

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2847]
- [x] Explore whether the free version of Google Tag Manager will meet our needs.
- [x] Put code in page headers for test.

See discussion in #2816 for background.

Tag Manager training video: https://www.youtube.com/watch?v=TUJ5tyXOQNg&list=PLd9b-GuOJ3nFwlyvLFUtmDpYFKezhot8P&index=10

**Comment by jennmalcolm** [comment]
Start with explore data page as test.

**Comment by mcharg** [comment]
Tag manager account: https://tagmanager.google.com/?hl=en#/container/accounts/3121275747/containers/8989411/workspaces/1

**Comment by jennmalcolm** [comment]
First discuss with Lauren if this will conflict with existing tag manager. Then test in one branch.

**Comment by mcharg** [comment]
What I think we should tag on Explore Data:
- Right nav
- States in Map and drop down
- Year selector for graphs
- Tabs on Revenue graph
- Glossary links
- Glossary search terms 
- Any anchor links that scroll up or down the page.

**Comment by jennmalcolm** [comment]
That looks like a good list, @mcharg, but I'm wondering if we would need to do the states in the map and the drop down. Can't we already find out how many people visit each state pages? Would we be using tag manager on the map and drop down just to find out which method they like to use to get to the state pages?

**Comment by mcharg** [comment]
@jennmalcolm You're right, we shouldn't need it on the states, since they are separate pages.

**Comment by brentryanjohnson** [comment]
I believe we've fulfilled the scope of this issue, as we've determined (1) the free version of GTM is suitable for our needs and (2) we have the GTM code on the site driving the recruitment screener. We should consider opening a new issue to cover what and how we want to measure.
