### ISSUE TITLE
Replace glossary font icon with SVG

### ISSUE THREAD

**Issue by jenniferthibault** [ONRR/doi-extractives-data#2849]
So that we can get closer to eliminating font icons from the site, replace the glossary book icon in the [Glossary Ruby plugin](https://github.com/18F/doi-extractives-data/blob/2a686b05ef20309c00b7c7332dd21e48fe6fb96f/_plugins/glossary.rb) with an SVG instance.

Discussed this as the first approach we're interested in pursuing (if it's possible) with @el-mapache & @brentryanjohnson

**Comment by el-mapache** [comment]
@brentryanjohnson Hey! I might be missing something, but I don't see the glossary icon in the `_includes/svg` folder. Was it given a new name? I'll need that icon file to finish up this ticket!

Thanks!

**Comment by brentryanjohnson** [comment]
@el-mapache Icon added in #2927.

**Comment by jennmalcolm** [comment]
Working in Gatsby, so this is not a priority.
