### ISSUE TITLE
Create archive for EITI content that will no longer be maintained

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2863]
Part of #2799.

- Relocate (or archive in place) USEITI-specific content that is unlikely to be maintained in the future
- Develop unobtrusive design pattern to indicate archived content and succinctly communicate to users why the content has been archived

**Comment by jennmalcolm** [comment]
Let's have a team discussion to ensure we have a group strategy defined since we are starting to archive items already.

**Comment by brentryanjohnson** [comment]
The proposed design pattern for in-place archiving works well on pages of content, but not list items (e.g., data downloads). I'm going to explore alternatives that make use of the current 'data and documentation' link style.

## Full page archive
![Reconciliation archive](https://user-images.githubusercontent.com/32855580/43983515-c83958e2-9caf-11e8-9b67-8a4757bcaac6.png)

## Downloads list items
![archive in place of many list items](https://user-images.githubusercontent.com/32855580/43983489-a2817e7c-9caf-11e8-94e6-9a232eb5ab0b.png)

**Comment by brentryanjohnson** [comment]
I'm considering a separate pattern for a list of items, some of which are archived. I'd like to hear your thoughts on this approach @mcharg and @jennmalcolm.

![data list items with one as archive](https://user-images.githubusercontent.com/32855580/43984248-3503ee16-9cb4-11e8-89b2-37fbad08da45.png)

**Comment by mcharg** [comment]
I think we may need to include the line about the content being a part of USEITI and not being updated, so people know why it's archived.

**Comment by mcharg** [comment]
It could be as simple as putting"(USEITI content is no longer being updated)" after the link text.

**Comment by brentryanjohnson** [comment]
Here are a couple more options.

## Plain text notice and archive link
![plain text archive notice with data archive icon](https://user-images.githubusercontent.com/32855580/44046242-ae7d785c-9edf-11e8-9b62-b71c58a993a1.png)

## Plain text notice with icon and conventional data and docs link pattern
![Data and documentation link pattern with plain text archive statement with icon](https://user-images.githubusercontent.com/32855580/44046271-c526637a-9edf-11e8-80e3-5010decc97ee.png)

**Comment by mcharg** [comment]
@brentryanjohnson I like the first one if all the links in a section are archived, but are there instances where some links are archived in a list and some are not?

**Comment by brentryanjohnson** [comment]
@mcharg Yes, the [downloads page](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/eiti-archive/downloads/) is presenting the banner problems. The full colored backgound breaks up the flow and structure of content in a way that makes it difficult to determine which content the banner belongs to. 

By contrast, the banner works great for [full pages of archive content](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/eiti-archive/downloads/reconciliation/). 

To bridge this, I'm iterating on a plain-text option for the downloads list items that are to be archived.

**Comment by mcharg** [comment]
I think the plain text option works for those cases, but I was thinking that we still need a better option for cases like the Disbursements page where 2 of the links in a list are archived and 2 aren't. https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/eiti-archive/downloads/disbursements/

Would it make sense to put the plain text explanation after the archived links?

**Comment by brentryanjohnson** [comment]
@mcharg Agreed. We have an archive section on that page that repeats those links. I wonder if we should just pull them out of the "Download fiscal year data" for disbursements and keep them in the Archive section until we update them. They are different than the USEITI archive because (1) we will likely update them in the future and (2) they aren't specifically part of USEITI.

I could use your help thinking through these cases in co-working sometime this week.
