### ISSUE TITLE
Add toggle pattern to style guide

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2878]
The site employs a toggle (similar to accordion behavior) on the [federal revenue by company](https://revenuedata.doi.gov/how-it-works/federal-revenue-by-company/2016/) pages. This pattern is only used in this section of the site, but we may revisit this pattern to support filtering other data.

- We should add this pattern to the [style guide](https://revenuedata.doi.gov/styleguide/).

## Desktop behavior
![federal revenue by company toggle](https://user-images.githubusercontent.com/32855580/40086222-526bcad8-5852-11e8-9776-1f8d05b25dbd.gif)

## Mobile behavior
![federal revenue by company mobile toggle](https://user-images.githubusercontent.com/32855580/40086224-5769d2e6-5852-11e8-8deb-db2bb20429d3.gif)

**Comment by jennmalcolm** [comment]
We will re-evaluated with new pattern library.
