### ISSUE TITLE
Clean out font icon markup

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2879]
As part of #2821, we should clean out the font icon markup and libraries once we replace all of the icons with SVG alternatives.

**Comment by jennmalcolm** [comment]
Dependent on #2849

**Comment by jennmalcolm** [comment]
Needs to wait until after Gatsby transition so that we do not have to do double work.

**Comment by mcharg** [comment]
This can be done now that Gatsby transition is done.

**Comment by mcharg** [comment]
@brentryanjohnson What epic does this belong in?  Is this like refactoring or content or should we create a new epic for visual design?

**Comment by brentryanjohnson** [comment]
It's not visual design...refactor is closer. The nearest existing epic would be Site Performance.
