### ISSUE TITLE
Consider stacked or "toggled" chart pattern for national production

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2880]
We've observed that users sometimes get lost between the [Energy production nationwide](https://revenuedata.doi.gov/explore/#all-production) section and the [Production on federal lands and waters](https://revenuedata.doi.gov/explore/#federal-production) section in Explore data.

- **Assumption 1:** The focus of the site is on production, revenue, and disbursements from federal lands and waters; leading with overall national production challenges our users' expectations about what they will see first.

- **Assumption 2:** Overall national production is valuable context for production on federal lands and waters.

To test these assumptions, we should consider prototyping a pattern that allows users to toggle a stacked or grouped bar chart where overall national production can be placed in context with production on federal lands and waters. 

The default view would be production from federal lands and waters, with a toggle to allow the user to introduce overall production data into the same chart.

**Comment by mcharg** [comment]
Related to #3177 & #3122

**Comment by mcharg** [comment]
I don't think this is still feasible now that we're also going to have a monthly/yearly toggle and should be helped by splitting up the Explore Data page.

**Comment by brentryanjohnson** [comment]
That's fine, @mcharg. We'll revisit down the road if the opportunity allows.
