### ISSUE TITLE
Pair on deciding between interaction patterns

### ISSUE THREAD

**Issue by jenniferthibault** [ONRR/doi-extractives-data#2895]
In our workshop, we identified that some team members were really comfortable with determining when, where, and why to use specific interaction patterns, and some weren't. Which makes a great opportunity for the team to pair through an instance where we need to make that decision.

- [ ] Ryan and/or Jeff identify scenario needing a decision between interaction patterns
- [ ] Flag for Shannon, who will coach & train through her process of making a decision around the type of component appropriate for that scenario

This is a one-time issue meant to be a conversation starter that leads to lots more collaboration on questions like this.

**Comment by mcharg** [comment]
Closing, since I think we're doing this as part of our design review process.
