### ISSUE TITLE
Update AML content

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2896]
Specific data references and content are out of date on [Abandoned Mine Land Reclamation Program](https://revenuedata.doi.gov/how-it-works/aml-reclamation-program/). Let's update it.

**Comment by brentryanjohnson** [comment]
@mentastc worked on this today, but we're still waiting for a response from OSMRE on some numbers.

**Comment by brentryanjohnson** [comment]
Updated numbers needed from OSMRE:

- Under "Areas undergoing or requiring reclamation"
> Currently, there are $488M funded but not completed projects, encompassing 118,901 GPRA acres with an estimated outstanding $9.8 billion required to reclaim remaining coal-related AML areas.

- Consider updating chart and using sufficient color contrast for accessibility

![AML chart](https://user-images.githubusercontent.com/32855580/42703195-b15ff5bc-8680-11e8-9cd0-2eee1f28dda2.png)

**Comment by brentryanjohnson** [comment]
Update or generalize this sentence under "Revenue and disbursements":

> Since 1978, the coal industry has contributed $9.2 billion to the AML fund, which has earned $1.5 billion in interest

**Comment by brentryanjohnson** [comment]
Update or generalize this chart:

![AML fee collection](https://user-images.githubusercontent.com/32855580/42703988-14d7d252-8683-11e8-91bd-c39732884bbe.png)

**Comment by mentastc** [comment]
Link to OSMRE FY2019 Budget doc: source of many of the numbers on the page.

https://www.osmre.gov/resources/budget/docs/FY2019_Budget_Justification.pdf

**Comment by brentryanjohnson** [comment]
Let's generalize this to indicate which states receive the largest share of funding and direct the user to the source document for the exact figures (as opposed to replicating them here):

![state share of grant funding](https://user-images.githubusercontent.com/32855580/42704263-0c4c1b1a-8684-11e8-97bc-c232e89b83a9.png)

**Comment by brentryanjohnson** [comment]
Content priorities for AML:

- Where the money comes from
- Program expires in 2021 (for fee collection)
- Magnitude of the fund

- Relevant to all coal production, not just federal land
- Interest from fund pays health care for coal workers
- More money is coming in than going out every year, surplus
- Money doesn't fund current sites, only sites prior to 1977
  - Mining now comes with bond that requires reclamation, but did not before 1977

**Comment by brentryanjohnson** [comment]
[AML fund total unappropriated balance](https://www.osmre.gov/resources/budget/docs/FY2019_Budget_Justification.pdf) as of 9/30/17: $2,380,300,565.16

**Comment by brentryanjohnson** [comment]
I'm reopening this issue because we received updated content from OSMRE (Office of Surface Mining Reclamation and Enforcement).
