### ISSUE TITLE
Audit fossil fuels content

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2902]
Our [fossil fuels](https://revenuedata.doi.gov/how-it-works/fossil-fuels/) content contains specific, manually curated data references that are out of date. Let's edit this contextual content to avoid specific data references.

**Comment by jennmalcolm** [comment]
First step is to audit the content for specific data points that need to be removed or replaced.

**Comment by jennmalcolm** [comment]
This issue will be to audit content and come up with proposed edits.

**Comment by lpgoldstein** [comment]
https://docs.google.com/spreadsheets/d/1kQjDsmqTpA-882mvrJ3jQwGNhkkR9lpiJUSt51gMOtI/edit?usp=sharing

@brentryanjohnson please take a look.
