### ISSUE TITLE
Develop design pattern to indicate outbound search links

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2904]
Our curated search contains numerous entries that link out to other websites, but the links supply no indication that they do so. Additionally, each result displays taxonomic tags that imply the search entry is part of the information architecture of the site.

Even though the intro text explains the results are curated from outside links, we've observed some users get confused when clicking a search result and they end up on a different website.

![Search results for texas](https://user-images.githubusercontent.com/32855580/40685974-97ac63f2-634a-11e8-800e-4ca0c873dd46.png)

**Comment by jennmalcolm** [comment]
Dependent on decision on how to manage search function.

**Comment by mcharg** [comment]
@brentryanjohnson Didn't we get rid of all external search results?

**Comment by brentryanjohnson** [comment]
Yes, @mcharg. Thank you.
