### ISSUE TITLE
Align number of search results with intro copy

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2905]
The number of search results and the leading copy explaining the number are separated by expansive white space. For this reason, it's difficult to associate the number and its explanatory text.

![number of search results](https://user-images.githubusercontent.com/32855580/40686176-459afee2-634b-11e8-9c2a-ddf66276ef99.png)

**Comment by mcharg** [comment]
@brentryanjohnson Didn't we already fix this?

**Comment by brentryanjohnson** [comment]
Yes, @mcharg. Thanks!
