### ISSUE TITLE
Add new toggle pattern to style guide

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2911]
Follow-up to #2889, which defined the design of the toggle.  Notes and documentation for the component are #2918.

Acceptance criteria:
- [ ] build the master CSS/HTML style classes
- [ ] pair with designer to check styles
- [ ] add component to mockups or prototypes (if ready)
- [ ] add component to the style guide

**Comment by adborden** [comment]
To whoever will be working on this: when you're ready, I'd like to pair with you and @mcharg on getting these into the styleguide.

**Comment by jennmalcolm** [comment]
We will re-evaluated with new pattern library.
