### ISSUE TITLE
Add ability to sign up to participate in user research to the site

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2920]
This will make it easier to build a list of people to contact for user research.

Some things to know before we do this:
https://18f.gsa.gov/2017/11/08/four-lessons-we-learned-while-building-our-own-design-research-recruiting-tool/

**Comment by brentryanjohnson** [comment]
@mcharg FYI...we had a screener on the site back in December 2017, to invite user participation. You can still see it on the [federalist `dev` preview](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/dev/).

![federalist preview with user participation screener](https://user-images.githubusercontent.com/32855580/40936128-2820d474-67ef-11e8-8aca-970ebed07a70.png)

**Comment by mcharg** [comment]
@brentryanjohnson  Thanks! Do you know how long it was up on the site?

**Comment by brentryanjohnson** [comment]
@mcharg I don't recall exactly, but I believe it was sprint-length (2 weeks). It looks like we [started working on it](https://github.com/18F/doi-extractives-data/issues/2414) earlier than I estimated in my previous comment.

It appears the plan was drafted [during this sprint](https://github.com/18F/doi-extractives-data/blob/research/research/14_sprint-inquisitive-impala/research_plan.md).

I believe the recruitment via the screener was _very_ limited...one or two people. If we do it again, we should try to coordinate with outreach and/or a data update during which we might expect increased traffic.

**Comment by mcharg** [comment]
@brentryanjohnson 1 or 2 people in two weeks actually sounds like a reasonable number to me.  I think we can also play with making the call to action more prominent or find contextual places to put it.

**Comment by brentryanjohnson** [comment]
@mcharg Sounds good.

The implementation we used should be compliant with the considerations in the blog post you alluded to ☝️; it was designed and implemented on our site by the team that wrote that post.

**Comment by brentryanjohnson** [comment]
The recruitment screener is back on the site (thank you, @laurenancona!). 

We tweaked some styling on mobile because the submit button wasn't in the viewport and the user couldn't scroll to it. We'll need to keep an eye on this and see if there's a better long-term solution.

Also, there is a "flash of unstyled content" as the screener loads, which is apparently a new phenomenon since we last deployed this. Lauren's looking into that, too.
