### ISSUE TITLE
Refine outreach messaging and draft calendar

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2939]
- Refine outreach concept art and messaging
- Draft outreach calendar to identify opportunities for coordinated messaging (e.g., data updates; press releases)

**Comment by jennmalcolm** [comment]
First step: Let's have a team meeting to determine the strategy that we want want to move forward with on this.

**Comment by mcharg** [comment]
External branding idea: a play on the rogue National Park Service where we say the open data team (the open data NRRDs?)  has taken over the social media accounts.  I don't think anyone has posted for over a year, so it could be a fun way to jump start new posts.

**Comment by brentryanjohnson** [comment]
That seems like a risky strategy to me, but I'll be interested to hear what @jennmalcolm thinks. Since NRRD is already the public face of ONRR's work in many ways, I don't think we need to do anything particularly performative to revive the social media. But let's talk about it when Jennifer returns.

**Comment by jennmalcolm** [comment]
We decided as a team to refine designs for social media cards and that we don't need to make a big splash with our posts. @brentryanjohnson, can you add in the social media cards to this issue and then close it if you agree that it is done?

**Comment by brentryanjohnson** [comment]
We've agreed on a concept to move forward with. In #3058, we'll pair these cards with boilerplate messages in the form of tweets and/or Facebook posts, and we can move forward.

![Concept for social media, your resources, your data](https://user-images.githubusercontent.com/32855580/44731992-40485300-aa99-11e8-92b1-c8b1fe0e211f.png)
![Concept for social media, your resources, your data](https://user-images.githubusercontent.com/32855580/44731993-40485300-aa99-11e8-9ef7-f0d96aae8366.png)
![Concept for social media, your resources, your data](https://user-images.githubusercontent.com/32855580/44731994-40485300-aa99-11e8-908e-d9abc318c21a.jpg)
![Concept for social media, your resources, your data](https://user-images.githubusercontent.com/32855580/44731996-40e0e980-aa99-11e8-9cc9-12ef9ea26f9d.jpg)

**Comment by brentryanjohnson** [comment]
@mentastc Here are more cards:

![twitter-card-your-resources-your-data_windonshore](https://user-images.githubusercontent.com/32855580/45834041-11e61e00-bcbb-11e8-8793-bd6e59a28c0b.jpg)

![twitter-card-your-resources-your-data_solar](https://user-images.githubusercontent.com/32855580/45834049-16123b80-bcbb-11e8-83fc-3ba3abb5e4a1.jpg)

![twitter-card-your-resources-your-data_rig](https://user-images.githubusercontent.com/32855580/45834053-18749580-bcbb-11e8-82a6-c4c8eb9bc151.jpg)
