### ISSUE TITLE
Section 508 compliance

### ISSUE THREAD

**Issue by usEITI** [ONRR/doi-extractives-data#2946]
From our metrics discussion, we identified the following tasks.
- [ ] Define which class we're using
- [ ] Conduct accessibility review
- [ ] Fix any issues found

**Comment by jennmalcolm** [comment]
First step: Look at new 508 standards to see which level of accessibility is required.

**Comment by mcharg** [comment]
New accessibility guide from 18F that highlights each team member’s role in making a site accessible. 
https://accessibility.digital.gov/

**Comment by jennmalcolm** [comment]
We will need to break this up into smaller chunks. Our first step is in #2252
