### ISSUE TITLE
Review and repair broken button icons in IE

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2950]
Related to #2942 

- It appears SVG icons in IE 11 need to have a `height` attribute to display inline
- Review and fix button icons for IE

![broken button icons in IE](https://user-images.githubusercontent.com/32855580/41434796-c93a5972-6fd1-11e8-8732-5c72a1c07d7b.png)

**Comment by mcharg** [comment]
This is fixed.
