### ISSUE TITLE
Find events where we should do outreach to external stakeholders

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2960]

**Comment by jennmalcolm** [comment]
@mentastc and @Maroyafaied  and I made a list in the outreach plan for both internal and external stakeholders. @mcharg, @brentryanjohnson, @master12, please see if you have anything to add.

Outreach Plan - Events: [Google Doc](https://docs.google.com/document/d/11QtiwgvYjXuiy1C-64rWqYGie1tkUcHlnqbijVOTXbQ/edit?usp=sharing] (limited access)

**Comment by mcharg** [comment]
Some of the organizations in the Places tab in the Market Map might have events that we could present or have tables at for external audiences.

**Comment by mentastc** [comment]
We added events to the outreach plan.
