### ISSUE TITLE
Evaluate whether we want to start a newsletter or blog

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2961]

**Comment by master12** [comment]
LOVE IT! Just need help editing...

**Comment by brentryanjohnson** [comment]
:raised_hands: Deal @master12

**Comment by jennmalcolm** [comment]
I agree, we should do it. Let me do a little research to make sure we're dotting our i's and crossing our t's with the department before we publish anything. I'll get on it.

**Comment by jennmalcolm** [comment]
Closing this issue since we have made the decision that we would like to do it. Now we will work on implementation in #3109.
