### ISSUE TITLE
Get access to data retrieval's reports on requests

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2963]

**Comment by jennmalcolm** [comment]
@NBrannberg, I don't want to scare you away with too many questions on your first day in our repo, but is this issue something you could help us with? We know you have shared the tracking sheet related to requests coming from NRRD. Could we have read access of some kind or get regular reports from your other tracking system to see if there's anything we can learn from them? Again, this relates to implementing our metrics. We think that if we're successful, the number of requests that Data Retrieval is receiving that could or should be answered by NRRD should go down over time. Thank you!

**Comment by NBrannberg** [comment]
Yes, we have the capability of providing reports from our tracking software; however, the way the data is organized isn't user friendly.  Aaron Lindquist will be doing a detail with our group and the first project I'm having him work on is to come up with a better way of displaying our stats.  We can setup regular reports for you to review.

**Comment by jennmalcolm** [comment]
We should get FY2018 first and then the first 6 months of FY19 by the end of April.

**Comment by mcharg** [comment]
We finally got this!
