### ISSUE TITLE
Reach out to FOIA representatives to determine what they are getting asked about

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2964]
See if we can get regular reports from them.

**Comment by jennmalcolm** [comment]
Regular reports are a good idea. Chris did reach out to them last year and do an analysis on the type of requests they're receiving. Have you seen that for a start?

**Comment by mcharg** [comment]
I think I have seen a spreadsheet.

**Comment by jennmalcolm** [comment]
Let's see if we can set up a regular schedule of reports from FOIA or set up a way to see them in a Google Spreadsheet.

**Comment by mcharg** [comment]
I talked with Ralph about this when I met him and he thinks everything that would be useful goes through Nathan's team and should end up in their reports.  @NBrannberg  is this true?

**Comment by mcharg** [comment]
I also met Theresa and she is going to look at getting us a list of FOIA requestors who we should do outreach with.

**Comment by mcharg** [comment]
Tracey said they have a spreadsheet that @mentastc has access to, but would like to discuss this when we're all together in DC.  She said they definitely want to be involved with figuring out what we present for lease level data.

**Comment by jennmalcolm** [comment]
Closing because @mentastc is on distribution list for FOIA request tracking. It seems to come out monthly, and @mcharg should be added too.
