### ISSUE TITLE
Rewrite site content to grade level 10 or lower

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2966]

**Comment by jennmalcolm** [comment]
@brentryanjohnson with our content strategy can we incorporate a plan to get the grade level of our content down to 10 or lower in phases?

**Comment by brentryanjohnson** [comment]
@jennmalcolm Yes! The plan is to work this sequencing in with the editorial calendar, so we can pace the work. Now that have some visibility with respect to the disbursements data publication schedule, I can draft the content calendar with more confidence.

**Comment by jennmalcolm** [comment]
This is too big to do in a sprint but will be done as we revise and develop content. Audit captures current reading grade level. We will create issues for smaller chunks at a time.
