### ISSUE TITLE
Add site prompt asking the user what they were looking for

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2967]

**Comment by jennmalcolm** [comment]
Related to #2996 for similar implementation

**Comment by jennmalcolm** [comment]
Ask Ralph if we could do this with PRA.

**Comment by mcharg** [comment]
@jennmalcom - Given how little response we've gotten to the recruiting screener, I think we should table this.  It'll only take away attention from recruiting and probably require a PRA review to implement.

**Comment by jennmalcolm** [comment]
Ok, I think that's a valid reason for not moving forward with this. I will close it.
