### ISSUE TITLE
State Revenue Streams - Assess data

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#2973]
Assess how long it takes to update data for one of the four states and what information is needed to update the data.

**Comment by jennmalcolm** [comment]
First step is to get list of contacts from Deloitte @mentastc

**Comment by jennmalcolm** [comment]
Related to #3105 which is reviewing Colorado

**Comment by mentastc** [comment]
her eis the contact list sent to me by deloitte
[USEITI State Additions Contact List.docx](https://github.com/ONRR/doi-extractives-data/files/2291440/USEITI.State.Additions.Contact.List.docx)

**Comment by jennmalcolm** [comment]
I changed the contact list to a Google Doc to make it limited access an also so it's easier to update and keep track of for future additions.
