### ISSUE TITLE
Decide what disbursements data to use on the site

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2974]
After we get the monthly and commodity file, we'll need to decide:
- At what levels do we display monthly and commodity data?
- What impact does monthly data have on annual data?
- Can we toggle between fiscal and calendar year?

**Comment by jennmalcolm** [comment]
We will only be doing annual for FY18, but should be implementing monthly after that. 

We still need to find out if we will get the commodity data and if we will have fiscal and calendar year datasets.

**Comment by mcharg** [comment]
This shows the differences between the two disbursements spreadsheets.  The boxes outlined in red are the problematic areas where we would be missing data if we only had one of the two spreadsheets.  The biggest differences are for GOMESA, county data, onshore/offshore split for U.S. Treasury, the "other funds" bucket, and years before 2014.
[Disbursements_SpreadsheetDifferences_071318.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad649002a863f001370d4d5/125516c66e82c728ace21e0d46cc9d89219791ba8ae4ba4db04ecfa7395422722d17ab2e7591c721b9447e130a011df902375f43fdfa8823b4aa2e30c80351b882294d7ed43814adedd61eea04e926d947d6b3b9834cc0ee3520b18c8c5d220c4749d7ab0268f9d31e8a4afc59e04a5fa5163562e3773774449d1e7729792a.pdf)

**Comment by mcharg** [comment]
I'm meeting with Maria next Thursday to see if we can get to one spreadsheet.  I created a separate issue for that we can pull into next sprint.
