### ISSUE TITLE
Design interaction for providing explanations about numbers

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2977]
- [ ] Define what types of explanations we want to provide
- [ ] Figure out a way to allow users to access the explanations

**Comment by mcharg** [comment]
The prototype has glossary icons on the table headers that we will test with users.
https://vavl06.axshare.com/#g=1&p=federal_disbursements_data

**Comment by mcharg** [comment]
We will have to revisit this in the next sprint.  The glossary icons in the table headers have not been clear to the users who have seen them.

**Comment by mcharg** [comment]
Added a dotted underline to the glossary terms in column headers to be consistent with other glossaries.  Also changed "Group by:" label to "Sort by:" to make that clearer.
https://vavl06.axshare.com/#g=1&p=federal_disbursements_data

**Comment by mcharg** [comment]
@brentryanjohnson Can you review these changes and let me know what you think?

**Comment by brentryanjohnson** [comment]
@mcharg I added some comments in the prototype.
