### ISSUE TITLE
Better call out what our mission is now that we're not EITI

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2979]

**Comment by jennmalcolm** [comment]
First step completed with #3025, but we should look at other places where we need to explain our vision better, especially as we begin to implement our new content strategy.

**Comment by mcharg** [comment]
@jennmalcolm @brentryanjohnson  Does the new home page content cover this?

**Comment by jennmalcolm** [comment]
Yes, @mcharg, I think it suffices.
