### ISSUE TITLE
Redesign Site Search

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2981]
- [x] Return more internal pages
- [x] Clarify which pages returned are external
- [ ] Make the tags look less like links to content

**Comment by jennmalcolm** [comment]
@brentryanjohnson did #2934 handle the first and second items on this list? Do we still want to keep this open to look at better ways of performing internal searches?

**Comment by brentryanjohnson** [comment]
@jennmalcolm I identified another step we need to complete (#3023 audit the tags themselves). Styling them is independent from the audit, so we could close this issue and create a new one for styling the tags, if you think that's a solid approach.

**Comment by mcharg** [comment]
#3144 exists for the tag styling, so closing.
