### ISSUE TITLE
Review Offshore Region Pages

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2982]
Determine whether these can better parallel state pages or if we can link to the state disbursements pages from them.

**Comment by jennmalcolm** [comment]
Work at the same time as #3123.

**Comment by jennmalcolm** [comment]
We need to answer if GOMESA should be reference in any way in the offshore pages in any way. When we tested the disbursments designs, users often went to the offshore pages expecting to find GOMESA data.

**Comment by mcharg** [comment]
Closing, since they'll be going away with new Explore Data.
