### ISSUE TITLE
Map NRRD Data Journey

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2983]
After reviewing the notes from the disbursements interviews with internal users, I think it might be helpful to map the journey from getting the data through it being used to answer someone's question.  I think we could get a good start from the notes we have from user interviews and then have meetings with stakeholder to validate the process.  It could help get people all on the same page about the amount of work that is involved in getting and processing data, how the data is used, and pain points with the current process that we can start to address.  It'll also be a good way to point out where each of our user types fall in the process.

**Comment by jennmalcolm** [comment]
I believe that the data governance pilot did this. @usEITI could you get this to share with us?

**Comment by usEITI** [comment]
The DG office only provided a partial snapshot of the work completed by Deloitte.  I will try to get the deliverable.
