### ISSUE TITLE
Data Visualization Examples

### ISSUE THREAD

**Issue by master12** [ONRR/doi-extractives-data#2985]
List of sites that have interesting visualizations

**Comment by master12** [comment]
http://www.boostlabs.com/wp-content/uploads/portfolio_videos/RMSG_V1.0.mp4

https://flourish.studio/examples/german-elections/

http://selfiecity.net/selfiexploratory/

https://informationisbeautiful.net/visualizations/common-mythconceptions/

https://informationisbeautiful.net/visualizations/which-fish-best-safest-healthy-to-eat/

http://twitter.github.io/interactive/sotu2014/#p43

**Comment by mcharg** [comment]
Here's a site we can use to try out different types of charts with our data: http://app.rawgraphs.io/

**Comment by jennmalcolm** [comment]
Next step: move these examples to Wiki.

**Comment by mcharg** [comment]
I figure I might as well do this while I'm in the wiki putting in analytics.

**Comment by mcharg** [comment]
Moved to wiki:
https://github.com/ONRR/doi-extractives-data/wiki/Data-Visualization-Examples
