### ISSUE TITLE
Move Research Google Drive folder into DOI Google Drive

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2987]
This currently lives in the 18F drive.   I'll need to look into whether I need to be the owner to move it.

**Comment by mcharg** [comment]
I reached out to Alex, who is the owner on the folder, and she's going to look into whether she can make me owner or if there's some way to export the files to put in a folder on the DOI drive without breaking links.

**Comment by mcharg** [comment]
@alexpandel, @MKathrynC, Have you had any discussion about how to transfer the Google Drive folder to us?

**Comment by MKathrynC** [comment]
@mcharg I'll set some time up with you to chat about the transfer.

**Comment by mcharg** [comment]
@MKathrynC Thanks!

**Comment by mcharg** [comment]
Exporting converts all Google Docs to Office docs, which is not what we want it to do, so we need to find another option.

**Comment by mcharg** [comment]
There's not a good way to move the Google Drive between agencies, so Kathryn and I agreed to keep the transition folder in GSA's drive, but to create new files in our drive going forward.  We should make copies of files we're using frequently (like the Market Map or Outreach Plan) in our drive.  She'll also lock down access to the GSA folder, so it's not so wide of access.

Let's use this folder to store our files going forward:
https://drive.google.com/drive/folders/1vkJJJjTFPrk-H_U8ch87eruDcqyiglj9
