### ISSUE TITLE
Build Disbursements Summary View

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2988]
https://m13r6x.axshare.com/fed_1b.html

Can we do this with our currently technology for a quick win? 

Note: Design needs a few refinements before being finalized.

**Comment by master12** [comment]
@mcharg  Where is data you used to generate this table?

**Comment by mcharg** [comment]
@master12  That is the million dollar question.  It's a combination of the two disbursements spreadsheets we have available on the site.  I made a combined version for 2017 only (see below).
[Disbursements_SingleSpreadsheet.xlsx](https://github.com/ONRR/doi-extractives-data/files/2250740/Disbursements_SingleSpreadsheet.xlsx)

**Comment by master12** [comment]
@mcharg This is not in a usable/importable format.  Basically need a sheet with just column for the fields and the corresponding values in that column. I am not sure how you took that and then generated your view? If it wont take you too long could you adjust?

**Comment by mcharg** [comment]
@master12 How's this?
[Disbursements_ForSummary.xlsx](https://github.com/ONRR/doi-extractives-data/files/2250842/Disbursements_ForSummary.xlsx)

**Comment by master12** [comment]
much better.
@mcharg 
What is "8(g)" column?

Is this new feature for 2017 only?

**Comment by jennmalcolm** [comment]
I guess that's something we hadn't discussed, but we don't have the data in the format we need for pre-2017 yet. I would say let's implement for 2017 and then add the drop down year selector when we're able to get the data. What do you think @mcharg?

**Comment by jennmalcolm** [comment]
It looks like the total disbursements in the combined spreadsheets do not match the total on ONRR.gov and the design.

**Comment by mcharg** [comment]
@jennmalcolm This is why we need an official spreadsheet with accurate numbers.  I'm sure I probably had a copy and paste error as some point.

**Comment by mcharg** [comment]
@master12 8(g) is a subset of offshore for states and counties only.  If it's too hard to call it out separately in the summary, we can call it "other offshore" like the other funds.

**Comment by jennmalcolm** [comment]
@mcharg In your design the totals add up to the number from ONRR.gov. Did you do some magic to make that happen? If we aren't matching totals with the spreadsheets we have available and the number on onrr.gov, we will put this implementation off until we get the official spreadsheet.

**Comment by mcharg** [comment]
Are they correct in this spreadsheet? 
[Disbursements_ForSummary.xlsx](https://github.com/ONRR/doi-extractives-data/files/2250961/Disbursements_ForSummary.xlsx)

**Comment by jennmalcolm** [comment]
No @mcharg that total is larger than the design. I'm doing some investigating too. I'll let you know what I find.

**Comment by mcharg** [comment]
What's on the Funds tab in this messy version of the spreadsheet is what I actually used for the design, in case it helps figure out what I did.
[DisbursementsSingleSpreadsheet.xlsx](https://github.com/ONRR/doi-extractives-data/files/2250976/DisbursementsSingleSpreadsheet.xlsx)

**Comment by master12** [comment]
The spreadsheet should have columns like:

Fund, Year, Region Type(Onshore, Offshore, Gomesa, etc..)

Basically columns are the data descriptors

**Comment by jennmalcolm** [comment]
I think this is the format you need with the correct number for 2017.Since we have both spreadsheets back through 2014, I will be able to get the data back to 2014, so please build with the drop down for year selectors.  I can add 2014-2016 to it tomorrow but wanted to let you provide feedback on this now
[disbursement data.xlsx](https://github.com/ONRR/doi-extractives-data/files/2251191/disbursement.data.xlsx)
.

**Comment by jennmalcolm** [comment]
@Maroyafaied is going to help me get the 2014-2016 data together today.

I noticed one more thing that we discussed for other designs after Shannon finalized this one. We need it to say, "American Indian tribes **and individuals**"

**Comment by mcharg** [comment]
Updated the design to reflect "and individuals"  

@jennmalcolm Are we doing the "funded by congress" piece for LWCF and HPF or does that need to come out of the design?

**Comment by jennmalcolm** [comment]
yes, @mcharg, we are going to include the dollars appropriated by congress each fiscal year to provide that information to users.  I know @brentryanjohnson  wanted to use "funded by congress," and I understand that's easier to understand but "appropriated" is more accurate. I would suggest that we use appropriated and make sure it's in the glossary.

Also, when I go to the Axure share link at the top, I don't see the "individuals" addition or "funded by congress". Do we need an updated link in this issue?

**Comment by mcharg** [comment]
That is an old link above, here's the current one:
https://qka4h2.axshare.com/#g=1&p=federal_disbursements_summary

**Comment by master12** [comment]
@jennmalcolm That last spreadsheet format is perfect. Thanks.

**Comment by jennmalcolm** [comment]
Ok @master12 I edited one line to reflect the 8(g) designation and updated the file about 15 mins ago. Also @Maroyafaied is working on the other years currently.

**Comment by Maroyafaied** [comment]
@master12 sorry it take a while, here is the data for 2014-2017
[Disbursement 2014-2017.xlsx](https://github.com/ONRR/doi-extractives-data/files/2254202/Disbursement.2014-2017.xlsx)

**Comment by jennmalcolm** [comment]
Thanks, @Maroyafaied
