### ISSUE TITLE
Create and populate teams in GitHub org to better manage permissions

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#2990]
Existing members of the repo when it lived in the 18F org migrated to the ONRR org. We should create teams (e.g. 18F) to more efficiently manage permissions in the repo.

**Comment by jennmalcolm** [comment]
@brentryanjohnson I created a couple more teams in addition to the 18F team that you created. I'm not sure whom from 18F we should add to that team. Could you take a look? https://github.com/ONRR/doi-extractives-data/settings/collaboration
