### ISSUE TITLE
Updated CY Federal Production

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#2993]
- [x] Check file format and known data issues

- [x]  Update visualizations

**Comment by jennmalcolm** [comment]
Created a new issue for download data file #3017

**Comment by mentastc** [comment]
Here is the updated CY file that should be used for the down
[CY Production Data 2008-2017 DRAFT (1).xlsx](https://github.com/ONRR/doi-extractives-data/files/2167044/CY.Production.Data.2008-2017.DRAFT.1.xlsx)
load and visualizations
