### ISSUE TITLE
Consolidate feedback for 18F about the transition

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#2994]
- [x] Create google doc for the team to put feedback in (Shannon)
- [x] Consolidate everyone's feedback and provide to 18F (Jennifer)

**Comment by mcharg** [comment]
Google doc to collect feedback:
https://docs.google.com/document/d/1LbKCzHFLDOIL3D7FYM3e9Le3rIvwi4DBHQPK5d1PusI/edit

**Comment by jennmalcolm** [comment]
@mentastc and @master12 I will send our feedback this week, so please add any feedback, or let me know here if you don't have anything to add. Thanks.
