### ISSUE TITLE
Update remote GitHub path on team's machines

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3000]
Since we changed our repo location from the 18F org to the ONRR org, our remote path has changed for pushing commits. We should [update the path](https://help.github.com/articles/changing-a-remote-s-url/) on @jennmalcolm, @mentastc, and @mcharg boxes.

**Comment by jennmalcolm** [comment]
Closing since we have not encountered any problems with this since the repo org change.
