### ISSUE TITLE
Fix Case Study Icons in IE

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3004]
They're broken.

**Comment by mcharg** [comment]
![IECaseStudyIcon.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad649002a863f001370d4d5/125516c66e82c728ace21e0d46c1b1b92291869a9bfcbb5a8d5eff9a6b0a65633b0ba92e7391a172fd172e500a0b4ff9440b5916f4aa8c2eafb63c7682595dead27f4366846c4ff8e7df46f554f832815d84bfb68b49c3e83c27e18d874f3f1c010ac4.PNG)

**Comment by jennmalcolm** [comment]
Only an issue in dev build, so we need to figure out what merge broke this.

**Comment by jennmalcolm** [comment]
Closing since this isn't important since the problem is only in dev.
