### ISSUE TITLE
Fix Case Study Drop Down in Firefox

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3005]
The headers are highlighting weird.

**Comment by mcharg** [comment]
![FirefoxCaseStudyDropDown.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad649002a863f001370d4d5/125516c66e82c728ace21e0d46ce9d8826848cb1ace8ac469749e5903062357c3920ac3c7ec7af6aaf50740b0a0c0abe4b4a5a41fdacdd2af3b36f76d85458e8d4645f74c03514fabf810da313f871d51bdaebe5c01982fa3737e682854e3b1d05198bf95531a8914acd4abb.png)

**Comment by jennmalcolm** [comment]
Closing in favor of #3131.
