### ISSUE TITLE
Mobile design for disbursements

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3007]
- [x] Define mobile wireframing strategy

**Comment by mcharg** [comment]
@master12 @brentryanjohnson  We only have one breakpoint at 768 px, correct?  Should I just do wireframes at 320 px to account for the smallest phones or is there value in seeing what the pages look like at 768 px, as well?

**Comment by brentryanjohnson** [comment]
@mcharg There are multiple breakpoints, some with more significant layout impacts than others. I've added descriptions for the "mobile" breakpoints, at least for ones that alter the arrangement of the layout, as opposed to just font size, etc.:

```
**$tiny: em(480)**;--> **Scales content to the one-column layout imposed at 600 px**
**$small: em(600)**; --> **Changes bar chart layout from three column to accordion with one column**
**$medium: em(768)**; --> **Converts side navigation from separate column to the right to a select list**
$large: em(900);
$huge: em(960);
$huge-plus: $huge + em($max-vw-margins);
$jumbo: em(1500);
$massive: em(1800);
```

**Comment by mcharg** [comment]
So, it sounds like I should do wireframes for 320 px to show what it looks like on small phones, 600 px because that's where the bar charts change (maybe this one can be optional only if something in the design changes), 768 px because that's where the nav changes, and 960 px because that's as big as the site actually scales.

@brentryanjohnson @master12 @jennmalcolm Any disagreement?

**Comment by master12** [comment]
Why do we have 600 and 768? Cant we just use one?

**Comment by master12** [comment]
Yes We should show what things look like at different resolutions if they change.

**Comment by master12** [comment]
Sorry should have mentioned. 768px is a standard breakpoint. 600px is some random number that someone picked for some reason?

**Comment by mcharg** [comment]
It's probably where the design for the graphs breaks.

**Comment by master12** [comment]
probably but its still random and unusual to use an html element instead of an actual device screen width

**Comment by mcharg** [comment]
Best design practices are to design for breakpoints where the design breaks rather than using device widths because standard device sizes change so frequently.

**Comment by brentryanjohnson** [comment]
Here are the breakpoints for the explore page (in the "mobile" direction) and how they affect they layout.

![breakpoints-animated](https://user-images.githubusercontent.com/32855580/42474831-9ae7c68a-837d-11e8-996e-34cd0a04efa7.gif)

**Comment by mcharg** [comment]
So, 600 px is where you can no longer fit 2 bar charts across.

**Comment by mcharg** [comment]
I'm going to stick with wireframing 4 breakpoints (320, 600, 768, 960).  It's not a lot of work to do them if there's nothing changing (Axure has a way to specify breakpoints, so you just move things around for each breakpoint) and it'll allow me to gauge whether any new designs break at those breakpoints and for everyone else to see what happens.

**Comment by brentryanjohnson** [comment]
The last one got cut off, so I've edited the above to show <480px.

**Comment by mcharg** [comment]
@brentryanjohnson Does anything change at 480px?

**Comment by brentryanjohnson** [comment]
Yes, @mcharg. The size of the chart changes (gets larger) in relation to the viewport at 480.

**Comment by mcharg** [comment]
Then we should add 480 as a breakpoint.  So, that leaves us with 5.

**Comment by mcharg** [comment]
And I'm now seeing that there's a break at 900 px where 3 graphs no longer fit across.

**Comment by brentryanjohnson** [comment]
Yes, it goes from 3 to 2 columns, and then back to three. The other difference is the nav column to the right becoming a select list.

**Comment by mcharg** [comment]
Here's the phase 1 version of the disbursements summary (it has no links to the table) at all 6 breakpoints.
https://qka4h2.axshare.com/#g=1&p=federal_disbursements_summary

To view a different breakpoint, use the icon highlighted in blue in the top left corner of the prototype:
![image](https://user-images.githubusercontent.com/38465926/42538053-be4ddeba-8464-11e8-9803-2facf514169c.png)
