### ISSUE TITLE
Design horizontal bar graph pattern

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3008]
Need to create a pattern for the horizontal bar graphs on the disbursements summary.

**Comment by mcharg** [comment]
# Parameters that informed the design choices
* Match to existing patterns
* User research
* Color differentiation for accessibility
# Default State
## Single Bar
This is a single bar with a chart title.
![horizontal_bar_chart](https://user-images.githubusercontent.com/38465926/42397085-8274fa0c-8132-11e8-9394-7d664c9d9944.png)

## Stacked Bars
These bars are sized relative to each other, included in a table, and have glossary links.
![stacked_bars](https://user-images.githubusercontent.com/38465926/42397073-75857f10-8132-11e8-9e84-954cf1f28ab0.png)



# Context
If a horizontal bar chart appears in the body of a page, it should have a [chart title](https://revenuedata.doi.gov/styleguide/components/detail/typography.html).

If they appear in a table, a header row can be used as the [title](https://revenuedata.doi.gov/styleguide/components/detail/basic-table.html).
# Colors
Up to 4 colors can be used in one chart.  These are the options from darkest to lightest.
 $green-dark, #2f4d26
$green-land, #69995a
$green-mid, #9dbd92
$green-light, #cde3c3

# Sizing
Horizontal bar charts should be horizontally sized appropriately for the context in which they appear and scale with the width of the viewport.  If only one bar is being used, it should be 100% wide with each segment proportional to the percentage that the associated number is.  If multiple bars are being used, they can add up to 100%.

Bars are 15 px high.

# Key
Key should display the numbers associated with the percentages and the color for each number.  Color swatches in the key are 10 px x 10 px.  Font in the key is [Para-sm](https://revenuedata.doi.gov/styleguide/components/detail/typography.html) and keys can include [glossary links](https://revenuedata.doi.gov/styleguide/components/detail/links.html).

**Comment by mcharg** [comment]
@adborden @master12 Is this enough details to get this component put into the style guide?

**Comment by adborden** [comment]
:+1: Looks good. I _think_ @master12 is going to do the implementation. I think the preferred way to do this is to implement in both the site and the styleguide together. So I'm available to pair on that.

**Comment by master12** [comment]
I think this looks good
