### ISSUE TITLE
Detailed design for federal disbursements summary

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3009]
- [x] Finalize all design elements
- [x] Make sure design complies with style guide.
- [x] Create tickets for any new elements that need to be added to the style guide.
- [x] Make sure design is accessible.
- [x] Mobile design

**Comment by mcharg** [comment]
@master12 Can you take a look at the Notes (that show up when you click on the blue icons next to components on as a list in the left Notes pane) and let me know if what I have works for you or if you need more documentation to be able to develop the page?
https://qka4h2.axshare.com/#g=1&p=federal_disbursements_summary

**Comment by mcharg** [comment]
Open question: Do we want to keep the LWCF and Historic Preservation Fund content on the Explore Data page or move it to the downloads page when we implement these changes? @jennmalcolm @brentryanjohnson @mentastc @Maroyafaied

**Comment by brentryanjohnson** [comment]
I think the full data sets and contextual narrative should probably be in Data and docs (downloads), but I also think we should update the Explore page with the actual budget appropriation for the relevant budget cycle (only a portion of the LWCF disbursement actually gets appropriated to the fund).

**Comment by jennmalcolm** [comment]
I think it's reasonable to move the contextual narrative, but if we do that, where would you suggest that we update it with the amount appropriated @brentryanjohnson?

**Comment by brentryanjohnson** [comment]
@mcharg I was thinking we would update in the actual appropriated amount in the table itself, with the disbursed amount (although the appropriated amount would be added later than the disbursed amount). It's certainly going to be challenging to convey the two processes (and why there are two numbers), but without the appropriated figure, the data implies that what was disbursed is what was received.

**Comment by mcharg** [comment]
@brentryanjohnson Is this something like what you were thinking?

![image](https://user-images.githubusercontent.com/38465926/42646840-11eb6c2e-85d0-11e8-9066-ac15faa3b68b.png)

**Comment by brentryanjohnson** [comment]
It looks good! I would add "by Congress," so "Funded by Congress".

**Comment by mcharg** [comment]
![image](https://user-images.githubusercontent.com/38465926/42647135-15e2c5b0-85d1-11e8-9865-da2f6bf33709.png)

**Comment by brentryanjohnson** [comment]
What do you think @jennmalcolm?

**Comment by jennmalcolm** [comment]
This seems like a good solution, but where will the "funding details" link go to? Can we link "Funded by Congress" to the explanation somewhere in How it Works or Data and Docs and/or add it to the glossary.

**Comment by brentryanjohnson** [comment]
I created a new issue (#3054) to address that problem, @jennmalcolm.

**Comment by mcharg** [comment]
I was thinking it would go to the LWCF section of the documentation page.

**Comment by jennmalcolm** [comment]
Ok, thanks. Maybe the link should say something like, "Understand LWCF funding" or something a little bit more explanatory.

**Comment by mcharg** [comment]
I'll leave that to @brentryanjohnson to decide.

**Comment by brentryanjohnson** [comment]
I recommend we try "How this fund works" to maintain consistency with how we label other explanatory content on the site. I'm happy to hear other suggestions, and we can also refine as we go along.

**Comment by brentryanjohnson** [comment]
Here is the ["Consolidated Appropriations Act"](https://rules.house.gov/sites/republicans.rules.house.gov/files/115/OMNI/CPRT-115-HPRT-RU00-SAHR244-AMNT.pdf), aka the budget.

**Comment by mcharg** [comment]
Prototype is updated for both the LWCF and Historic Preservation Fund. https://qka4h2.axshare.com/#g=4&p=federal_disbursements_summary

**Comment by mcharg** [comment]
@master12 Have you had a chance to look at the documentation and evaluate whether it's sufficient to build the page?

**Comment by master12** [comment]
Yes this axshare looks good to me. I feel like there are several issues for this disbursements feature. Wasnt sure which one to comment on.
