### ISSUE TITLE
Detailed design for federal disbursements table

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3010]
- [x] Finalize all design elements.
- [x] Make sure we have all the views of the table we need.
- [x] Make sure design complies with style guide.
- [x] Create tickets for any new elements that need to be added to the style guide.
- [x] Make sure design is accessible.
- [x] Mobile design

**Comment by mcharg** [comment]
@brentryanjohnson Where is a good place to put the icons used in the design?  Github won't let me attach svg files to the issue.

**Comment by mcharg** [comment]
@jenniferthibault Where did the Icon-charts that you put in the Axure widget library come from?  I'm not seeing it with the other icons we have.

**Comment by mcharg** [comment]
Here are the sort icons.  
[SortIcons.zip](https://github.com/ONRR/doi-extractives-data/files/2297710/SortIcons.zip)

They're font awesome icons that require attribution and an indication of the change.

Something along these lines needs to be added to the humans.txt file:
Sort arrows - Combined sort solid, sort-up solid, and sort-down solid icons to be able to color the arrow indicating the sort direction in a different color from the opposite arrow. (https://fontawesome.com/license)

**Comment by jenniferthibault** [comment]
Hey @mcharg — my Axure trial ended, could you post a screen cap of the icon-charts? I still have the original Sketch files so once I know which ones you're looking for I can track them down

**Comment by mcharg** [comment]
It's a combo of two icons.  The one on the right is the one I'm using in this design.
![image](https://user-images.githubusercontent.com/38465926/44281351-80037500-a225-11e8-8434-c014602c283a.png)

**Comment by jenniferthibault** [comment]
Morning! I found those in one of the previous designers' Sketch files where he was developing icons. They were grouped in an art board with this little cluster, so I'm guessing it was preparing for a design instance where you needed to be able to view a table, chart, or map of data. 

![screen shot 2018-08-20 at 8 54 40 am](https://user-images.githubusercontent.com/11636908/44341696-aeb46200-a456-11e8-8d17-3b15ce929961.png)


I can't remember seeing them on the site, but it would be possible to make sure there are/aren't instances if you search the code by starting to look in the icons files to see if they're there, and if they are, then searching the codebase for the class name it's associated with.

I included them in the Axure library so you didn't have to start from scratch if you needed them, but if you don't find any existing instances in the codebase and these designs don't fit your needs, you should absolutely change them.

**Comment by brentryanjohnson** [comment]
@mcharg Let's carve out some time to discuss what you need. Many of the SVG icon files (except those placed in-line) can be referenced via the `public` directory on the site itself. For example:

https://revenuedata.doi.gov/public/img/icons/icon-menu.svg

There are options for organizing them in a branch, if needed.

**Comment by mcharg** [comment]
# Default table
You can toggle the Organize By to Source or State.
Note: I didn't do the mobile view for Organize By State because it would have meant creating 50 cards.
Desktop: https://oajgix.axshare.com/#g=1&p=disbursements_table&view=default
Mobile: https://oajgix.axshare.com/#g=1&p=disbursements_table&view=e


# Recipient table
I mocked up LWCF as an example of a page for a recipient to show that there is custom page content for each recipient.
Desktop: https://oajgix.axshare.com/#g=1&p=lwcf&view=default
Mobile: https://oajgix.axshare.com/#g=1&p=lwcf&view=e

# Source table
I mocked up GOMESA as an example of a page for a source to show that there is custom page content for each source.
Desktop: https://oajgix.axshare.com/#g=1&p=gomesa&view=default
Mobile: https://oajgix.axshare.com/#g=1&p=gomesa&view=e

# State table
Texas is an example of a state page.
Desktop: https://oajgix.axshare.com/#g=1&p=texas&view=default
Mobile: https://oajgix.axshare.com/#g=1&p=texas&view=e

# Summary views
Links to the tables will need to be added to the national and state summary pages.
National: https://oajgix.axshare.com/#g=1&p=national_disbursements_summary__with_links_to_tabl&view=default
State: https://oajgix.axshare.com/#g=1&p=state_disbursements_summary__with_links_to_table_&view=default

**Comment by mcharg** [comment]
# Sorting Rules
* All tables can be sorted by the first column in the table or by any of the year columns both ascending and descending.
* Default sort is by the most recent year visible in the table, descending.  If no years are visible in the table, default sort is by the first column, ascending.
* Clicking on the sort arrows, cycles through sorting ascending and descending.  Numerical fields start with descending first and alpha fields start with ascending first.
* If rows have identical values, use the last field sorted by as the tie breaker.

**Comment by mcharg** [comment]
Explore table icon:
[table-solid.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad649002a863f001370d4d5/125516c66e82c728ace21e0d46fc95982f87ceba80e5b647e611b2843b492d762a10e17132d0b679ba462a045a0c48fe490b5a41f5f9892daeb36a77894e17ff933c0120996048e6edc00db513bb28814e80b5b98c49c0e13c20e28a8b5d73.zip)

Something along these lines needs to be added to the humans.txt file:
[Table solid] (https://fontawesome.com/license)

**Comment by mcharg** [comment]
Updated design after team review. https://oajgix.axshare.com/

Changes:
* Dropped "American" from all references to Indian
* Sorted by 2017 amount by default (see above for sort rules)
* Added menu that displays when you click Download that lets the user pick whether to download the current filtered view or all disbursements data.
* Dropped "amount" from all amount columns.
* Updated LWCF copy.

**Comment by mcharg** [comment]
See #3187 for additional details.  I moved everything there to keep it all in one place for dev to find.
