### ISSUE TITLE
Update CY production file for download

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3017]
The charts are updated, and we need to update the download file for CY production as well as the locations where that data is referenced. 

Here: https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/2993-cy-data-fed-prod/downloads/
![image](https://user-images.githubusercontent.com/30806839/42047934-b2b58e3e-7acf-11e8-8418-9654f6bd7493.png)

and here: https://revenuedata.doi.gov/downloads/federal-production/
![image](https://user-images.githubusercontent.com/30806839/42047908-a42ae7d8-7acf-11e8-86be-d9958e32c45d.png)

**Comment by brentryanjohnson** [comment]
I noticed an anomaly in the data; I believe @mentastc is cleaning up this minor issue with the data retrieval group.

> I noticed this odd line in the data file that combines "Southern California" and "Offshore Gulf" into a single row. Is there an explanation for this that I'm missing? Or is it a mistake in the data?

2017 | Oil (bbl) | Offshore Gulf |   | Southern California | 162,883 | Offshore | Federal
-- | -- | -- | -- | -- | -- | -- | --

**Comment by brentryanjohnson** [comment]
I have already added the file and changed the description(s), so I can push those up in a WIP PR, and we can change out the file when the row is cleaned up.

**Comment by jennmalcolm** [comment]
Thanks @brentryanjohnson. Sounds good.

**Comment by mentastc** [comment]
Here is the updated file with the fix that @brentryanjohnson  found and also some of the data was updated
[CY.Production.Data.2008-2017.DRAFT.1.xlsx](https://github.com/ONRR/doi-extractives-data/files/2167052/CY.Production.Data.2008-2017.DRAFT.1.xlsx)

**Comment by jennmalcolm** [comment]
Fixed by #3015
