### ISSUE TITLE
Write descriptions for testing and possible glossary inclusion

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3018]
- Recipient
- Source
- Commodity
- State 
- County

**Comment by jennmalcolm** [comment]
Related to #2977 
Figure out which words in disbursements tables need to go into glossary and then write those definitions.

**Comment by jennmalcolm** [comment]
Closing this, and we will come back to the glossary needs after the disbursement table detailed design.
