### ISSUE TITLE
Build horizontal bar graphs in pattern library

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3027]

**Comment by mcharg** [comment]
Acceptance criteria:
- [ ] build the master CSS/HTML style classes
- [ ] pair with designer to check styles
- [ ] add component to mockups or prototypes (if ready)
- [ ] add component to the style guide

**Comment by mcharg** [comment]
Design is #3008

**Comment by adborden** [comment]
To whoever will be working on this: when you're ready, I'd like to pair with you and @mcharg on getting these into the styleguide.

**Comment by master12** [comment]
Will wait to include this feature into the styleguide when we decide the best approach for creating/updating the styleguide.

**Comment by adborden** [comment]
I created this issue to look into new frameworks https://github.com/ONRR/doi-extractives-data/issues/3084. Once implemented, we can pick this back up.

**Comment by jennmalcolm** [comment]
@master12 I think you're done with this issue as you showed us the horizontal bar graphs in the pattern library, but maybe we still need to merge those changes? Could you confirm where we're at on this issue?

**Comment by master12** [comment]
This has been merged

**Comment by mcharg** [comment]
@master12 Do you have a link to the build with the updated pattern library?
