### ISSUE TITLE
Update Indian Revenue  Data

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#3028]
Update Indian data Revenue  section in how it works  with attached file
[FY2017 American Indian Revenue for Portal.xlsx](https://github.com/ONRR/doi-extractives-data/files/2160900/FY2017.American.Indian.Revenue.for.Portal.xlsx)

**Comment by mcharg** [comment]
@brentryanjohnson This is another data set we should look into moving out of How It Works and into Explore Data.
