### ISSUE TITLE
Move state land ownership content to block above map

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3038]
In pursuit of cleaning up the intro content on state pages, we should consider moving the land ownership stat to a block above the respective state maps. This approach places this stat in a position that is (1) predictable and consistent from a UI standpoint and (2) removes it from the relatively verbose leading paragraph, where it currently resides. Related to #2775.

![Land ownership stat mockup](https://user-images.githubusercontent.com/32855580/42465926-46103d10-8362-11e8-80bb-7a5a7904dbf4.png)

**Comment by jennmalcolm** [comment]
Related to #3277
