### ISSUE TITLE
Write notes and documentation for the horizontal bar graph pattern

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3043]
Write content for the Notes tab in the style guide.

**Comment by mcharg** [comment]
# Horizontal Bar Chart
 They should be used when we want to show data with break outs that add up to a total.  They can be presented by themselves as a percentage of 100% or in relation to each other to show how different totals relate to each other.

The figures are summarized in table form beneath the charts to serve as a key and to make the charts more accessible to those with color blindness and when very small numbers make it difficult to see a value on the chart. 

# How to use
This component is made up of several components, the chart title (or table containing the chart), the chart itself, and the table key.
## Chart Title or Table
If a horizontal bar chart appears in the body of a page, it should have a [chart title](https://revenuedata.doi.gov/styleguide/components/detail/typography.html).

If they appear in a table, a header row can be used as the [title](https://revenuedata.doi.gov/styleguide/components/detail/basic-table.html).

## Bar Chart
Up to 4 colors can be used in one chart.  These are the options from darkest to lightest.
 $green-dark, #2f4d26
$green-land, #69995a (drop this color if only 2 colors are needed)
$green-mid, #9dbd92 (drop this color if only 3 colors are needed)
$green-light, #cde3c3 (drop this color if only 1 color is needed)

Horizontal bar charts should be horizontally sized appropriately for the context in which they appear and scale with the width of the viewport.  If only one bar is being used, it should be 100% wide with each segment proportional to the percentage that the associated number is.  If multiple bars are being used, they can add up to 100%.

Bars are 15 px high.
## Key Table
Key should display the numbers associated with the percentages and the color for each number.  Color swatches in the key are 10 px x 10 px.  Font in the key is [Para-sm](https://revenuedata.doi.gov/styleguide/components/detail/typography.html) and keys can include [glossary links](https://revenuedata.doi.gov/styleguide/components/detail/links.html).

# Responsive behavior
The chart should scale proportionally with the view port size and the key table should always appear below the chart.  Stacked charts within a table may have behavior that turns each table row into an accordion, but that shouldn't affect the display of the chart itself.

# Variants
## Single bar
A single bar is displayed with a chart title.

## Stacked Bars
Multiple bars are sized relative to each other and can be included in a table.

**Comment by mcharg** [comment]
@adborden @master12 I forgot that we needed to write the content for the Notes tab in the style guide.  Let me know if you think anything's missing.

**Comment by adborden** [comment]
Awesome, looks great!
