### ISSUE TITLE
Maps expect v1 of topojson

### ISSUE THREAD

**Issue by adborden** [ONRR/doi-extractives-data#3046]
## Expected Behavior

Maps build correctly

## Actual Behavior

Maps fail to build

```
topojson -p FEATURE1 federal=data/shp/fedlanp010g.shp > land/federal.json.tmp
/bin/sh: 1: topojson: not found
Makefile:32: recipe for target 'land/federal.json' failed
make: *** [land/federal.json] Error 127
make: Leaving directory '/doi/maps'
```

## Steps to reproduce the behavior

1. `make -C maps`

**Comment by jennmalcolm** [comment]
This is an issue if we need to create new SVGs/change the maps. Otherwise, it's not a big issue, but we should look at creating a separate build package for the maps.

**Comment by mcharg** [comment]
@mojobnichols will this be needed with the new maps?

**Comment by mojobnichols** [comment]
This  seems like topojson wasn't installed.   I don't think this is an issue with the current build.  topojson is incorporated in the build so it should be installed.   I think this can be closed and am closing it, but if you disagree feel free to reopen.   If we need new topojson files from shape files we can open an issue for that.
