### ISSUE TITLE
Fix typography page in style guide

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3051]
@brentryanjohnson and I found some discrepancies between what's on the site and what's on the typography page in the style guide and it would be super helpful to have them matched and cleaned up, so we can fix some of the accessibility issues on the site and make sure we're using consistent heading levels going forward.

**Comment by mcharg** [comment]
Examples of the discrepancies:
- Default H4 has a bottom border on the site, but not in the style guide.  We had to dig around to find an H4 that uses the style guide style.   https://revenuedata.doi.gov/how-it-works/revenues/#revenue-policy-provisions
- H2 bar and H3 bar have smaller font in the style guide than on the site.
- Chart titles have inconsistent style tagging.
- Many header tags have custom styling for individual pages.
- There are H4 headers on the site that use H3 styling.

**Comment by brentryanjohnson** [comment]
Good call, @mcharg. It looks like the [style guide](https://revenuedata.doi.gov/styleguide/components/detail/typography.html) currently uses `<div>` elements with CSS classes for headings and paragraphs, which is _not_ a semantic/accessible way to structure content. We should fix this asap!

```<!-- H 1 -->
<div class="h1">h1 header</div>

<!-- H 2 -->
<div class="h2">h2 header</div>

<!-- H 3 -->
<div class="h3">h3 header</div>

<!-- H 4 -->
<div class="h4">h4 header</div>

<!-- H 5 -->
<div class="h5">h5 header</div>

<!-- Para Xl -->
<div class="para-xl">Para-xl is used for large introductory text, to make a page more inviting.</div>

<!-- Para Lg -->
<div class="para-lg">Para-lg is the default type size.</div>

<!-- Para Md -->
<div class="para-md">Para-md is medium-sized text.</div>

<!-- Para Sm -->
<div class="para-sm">Para-sm is small.</div>

<!-- H 2 Bar -->
<div class="h2-bar">h2-bar</div>

<!-- H 3 Bar -->
<div class="h3-bar">h3-bar</div>

<!-- Chart Title Large -->
<div class="chart-title-large">chart-title-large</div>
```

**Comment by mcharg** [comment]
H4 should be updated to 18 px with 30 px of line spacing to match what we're actually using in most places on the site.

**Comment by jennmalcolm** [comment]
Closing as we move to a new pattern library, and we don't expect this to be a problem any more.

**Comment by mcharg** [comment]
@jlouis-onrr This describes the h4 issue.
