### ISSUE TITLE
Write explanatory content for LWCF and HPF appropriations process

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3054]
The disbursements process for the Land and Water Conservation Fund and the Historic Preservation Fund are distinct from the disbursement process for states, the Treasury, etc., in that the amount disbursed is subject to congressional appropriation.  

We should draft content in the How it works section to explain this process, so we can include the actual amount appropriated to the respective funds versus the amount ONRR disbursed to the funds.

**Comment by Maroyafaied** [comment]
@brentryanjohnson there is a great explanation here on page 1 on the section "how it works"
https://www.everycrsreport.com/files/20160906_RL33531_ac1555f37bb1a30bee404e6a00ad1b22af2e9f8e.pdf

**Comment by usEITI** [comment]
This pdf from CRS is an excellent explanation.  Because it is an official government document, available to the public, and because the source of data is DOI, could we consider posting or linking to this pdf?  I know pdf is a no no, however in this case it provides excellent background and context that we should not be taking on ourselves.  What do you think?

**Comment by usEITI** [comment]
I still would like to see us continue posting those DOI disbursements related to LWCF as we did for USEITI if we can manage that under our current roadmap/vision for the NRRD.

**Comment by usEITI** [comment]
My bad, didn't mean to close just comment.

**Comment by Maroyafaied** [comment]
@usEITI I def think we should post it or link it to our website, it's such a great explanation and summary of LWCF. I'm still working on getting all of the disbursements data related to LWCF, I have the majority of the data.

**Comment by jennmalcolm** [comment]
I agree. We don't want to re-create the wheel so let's post this @usEITI. Thanks @Maroyafaied for your work getting us the data. Our goal is to continue to publish the LWCF data, and we're making progress toward that goal. Maroya is also working to document the process so we don't have to start from square one again next year.
