### ISSUE TITLE
Mock up disbursements table without monthly or commodity data

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3064]

**Comment by mcharg** [comment]
This is what it looks like without monthly and commodity data and with no ability to toggle to a chart, so it would be what we start with in a first version.

https://vavl06.axshare.com/#g=1&p=federal_disbursements_data_1

I think it adds enough value to be able to compare across years and states that it's worth doing.  @jennmalcolm Do you agree?

**Comment by jennmalcolm** [comment]
Yes, I do think there is still value with this. Let's move forward with it as our third phase of disbursements improvements.

One thing I would like to look at is if we need to have all results for the clickable elements open up on separate pages. Is there a reason to use separate pages rather than just drilling down on the same page @mcharg?

**Comment by mcharg** [comment]
@jennmalcolm When we tested the drilling in the first round of testing, people had difficulty understanding the nesting, especially when you got down to more than two levels.  (You can drill into States and Texas in the prototype.)
https://m13r6x.axshare.com/#g=1&p=option_a

We could try it again, but with states in particular, I think it'll get messy enough to cause confusion.

**Comment by mcharg** [comment]
Also, the design we have doesn't have to be separate pages.  It can be filtering a single table.  I only made separate pages for each fund to allow for content specific to the fund at the top of the page - particularly for LWCF and HPF.

**Comment by jennmalcolm** [comment]
Thanks,@mcharg. I didn't remember the results on the drilling down from the user research. Certainly what the users have told us is the direction that we need to go in, so don't let me distract from that. We don't need to try it again.
