### ISSUE TITLE
Move the right nav to the left in a build for user testing

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3068]
I'm thinking it would be good to test this with the home page designs to see whether the left or right nav better helps new users understand how the site is structured/how the process works.

**Comment by mcharg** [comment]
@brentryanjohnson Is this something we could do in the next sprint to test with the home page concepts?   I'm thinking we'd just need it on Explore Data and maybe the state page.

**Comment by brentryanjohnson** [comment]
@mcharg Possibly, although I'm out for a week of the next sprint. It might be something @master12 can style into a coded prototype, if I can't fit it in.

**Comment by brentryanjohnson** [comment]
I've added a branch with the nav change. @mcharg You should be able to use any state to test it with users.

- [:dog: Navigation prototype preview](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/nav-column/explore/WY/)

**Comment by mcharg** [comment]
@brentryanjohnson Can you do the main explore data page, as well, or is that too difficult?

**Comment by brentryanjohnson** [comment]
I don't think it's too difficult, @mcharg. I'll have a look today.

**Comment by brentryanjohnson** [comment]
Okay, I've added the markup to relocate the nav menu on the national `/explore/` page, @mcharg.

- [National explore nav prototype](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/nav-column/explore/)
- [State explore nav prototype](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/nav-column/explore/WY/)

**Comment by mcharg** [comment]
Looks great, @brentryanjohnson.  Thanks!

**Comment by brentryanjohnson** [comment]
It looks like that national `/explore` page isn't sticking, @mcharg. Let me see if I can fix that today.

**Comment by brentryanjohnson** [comment]
Okay @mcharg...the sticky nav should be fixed in the preview now.

**Comment by mcharg** [comment]
@brentryanjohnson Looks good.

**Comment by brentryanjohnson** [comment]
We should be ready to test this version of the nav layout with users. If and when we decide to implement this, we'll need to review the stylesheet to determine the best method for a site-wide implementation, adn we'll need to refine the alignment of elements. 

This prototyped layout only applies to the national and state `/explore/` data pages, so we'll also need to add to other templates that have the nav component.
