### ISSUE TITLE
Find new users for user research

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3069]
We should test the home page with new users and we need to decide who to test with.

Some ideas:
- Friends and family - they would be good for this study because we need to gauge whether the home page conveys what the site is about to people who don't know.
- Look at the market map for groups where potential target users are that have communities we could post about the study to.
- Reach out to open data communities.  These would be people who have enough technical knowledge to simulate the type of people who might use our site, but won't know the domain yet.

**Comment by Maroyafaied** [comment]
My husband and brother work for IHS Energy, my brother mentioned his supervisor is interested in a meeting to learn more about the website and how the data is different for EIA. I can do an outreach for them and ask for them to participate in new user research.

**Comment by mcharg** [comment]
Cool.  Let's wait until I'm back from Denver to reach out.

**Comment by mcharg** [comment]
@jennmalcolm What do you think about reaching out to family and friends for the home page study?  I think we need to put the designs in front of people who don't know what the site does to gauge effectiveness of the home page.

**Comment by jennmalcolm** [comment]
Sure @mcharg I think that makes sense as long as we're also getting some other types of users like those you mentioned in the issue.

**Comment by mcharg** [comment]
@jennmalcolm Before I post on any groups to recruit for user research, do you think we need to get any sort of permission?

This is the type of group I'm thinking of posting to:
https://www.reddit.com/r/Journalism/

**Comment by mcharg** [comment]
I posted on my Facebook page yesterday afternoon and have scheduled 3 people and am just waiting on times for a 4th.  I also posted in Maine's Code for America brigade's Slack to see if we can get any people who are interested in open data from that.

**Comment by jennmalcolm** [comment]
I think that should be fine @mcharg. Maybe check in with Jen when you meet with her to see if she knows how 18F approaches recruiting through groups and if they have anything they recommend.

**Comment by mcharg** [comment]
@Maroyafaied Can you give me email addresses for your contacts?

**Comment by jennmalcolm** [comment]
We shouldn't share emails in the GitHub issue, so maybe start a Google Doc with contact info or just share by email, etc. Thanks.

**Comment by mcharg** [comment]
I reached out to the UX COP mailing list to see if anyone else has tried posting to online communities and has lessons learned to share before I try posting to groups I'm not already a part of.  I will also ask Jen when I talk with her tomorrow.

**Comment by mcharg** [comment]
Between my Facebook post, Maroya's contacts, and the new employee orientation list, we have enough for this study.  I'll save posting in online communities for later research.
