### ISSUE TITLE
Conduct brown bag in Denver

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3072]

**Comment by jennmalcolm** [comment]
Great job. I thought it went well.

**Comment by mcharg** [comment]
Did you see how many people were on the phone?  We forgot to look at the attendee list.

**Comment by mcharg** [comment]
There were about 30 in the room.

**Comment by jennmalcolm** [comment]
And another 31 on webex/phone, with one of those being the Dallas Office, with, presumably, multiple people listening.

**Comment by mcharg** [comment]
Only 3 people signed up for user research, but people took stickers.  There are only 2 left.
