### ISSUE TITLE
Figure out where federal revenue by company should go

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3076]
- [x] Wireframe a couple of options
- [x] Get feedback from the team

This is a precursor to #2805 and we should do it in time to have an approach by the time we get the 2017 data.

**Comment by mcharg** [comment]
We might also want to think about where to put tribal revenue at the same time.

**Comment by mcharg** [comment]
Here's an initial concept. https://ug2su1.axshare.com/#g=1&p=explore_data

**Comment by mcharg** [comment]
We now have 4 options.  @brentryanjohnson  I incorporated some of your feedback.

https://ug2su1.axshare.com/

**Comment by mcharg** [comment]
@jennmalcolm  @usEITI  @mentastc @Maroyafaied  Do any of you have thoughts about whether the tribal data should be its own set of charts vs. incorporated in with the federal charts as split bars?

**Comment by Maroyafaied** [comment]
I think tribal data should be displayed on its own since tribal revenue is much smaller than the federal revenue I think it would look odd on the same chart.

**Comment by mcharg** [comment]
I tested out what it looks like with tribal on the same chart as federal and nationwide in this concept for key stats. You can toggle between just federally managed and all owners for production. 
 https://1rn7bf.axshare.com/#g=1&p=option_2

**Comment by mcharg** [comment]
I combined two of the options (B & C) for the information architecture of the Explore Data page, so we have 3.  Option A is pretty much the current state with the new sections added, so I think we only need to include options B & D in the user interviews to get feedback (since we're already testing the current state).

Option A: Add sections to current state https://ug2su1.axshare.com/#g=1&p=option_a__bare_minimum_

Option B: Shorten Explore Data screen with separate pages for Production, Revenue, and Disbursements
https://ug2su1.axshare.com/#g=1&p=option_b__shorten_page_

Option D: Traffic cop page that links to sections within the current single Explore Data page
https://ug2su1.axshare.com/#g=1&p=option_d__traffic_cop_page_

**Comment by mcharg** [comment]
I also put together 3 options for what to use for Indian revenue by phase.

A: Copies what we have for federal
https://ug2su1.axshare.com/#g=1&p=indian_revenue_a

B: Combines all "Other Products"
https://ug2su1.axshare.com/#g=1&p=indian_revenue_b

C: Uses a table instead of a graph.  Because Oil & Gas are so large compared to the other items, the other items will pretty much disappear on almost any kind of graph.
https://ug2su1.axshare.com/#g=1&p=indian_revenue_c

**Comment by mcharg** [comment]
Here's a page with just Revenue by Company to make it easier to provide feedback on just that piece.
https://ug2su1.axshare.com/#g=1&p=revenue_by_company

**Comment by jennmalcolm** [comment]
@JenniferLop @NBrannberg @grjson (and the rest of the team who aren't in the repo yet). Shannon has included a lot of links in this issue for designs she's been working on for the home page, Indian revenue, and revenue by company. With the intention of getting them reviewed and refined before user testing, we have implemented a process that gives our team two days to review the designs before we hold a meeting to discuss comments. We would really value your feedback on the different designs, and we will be discussing them in demo this week. If you have time, please look at the designs and record your comments in Axure (anonymous or create a free account).

**Comment by jennmalcolm** [comment]
@NBrannberg in looking at Shannon's designs for moving Indian data to the explore data page, I  started wondering if we could get data pre-2013 for Indian production and revenues. I would like the timeline of available data to be consistent with other available data. Could you advise on if this is possible and how much of an undertaking it would be for your team? Thanks.

**Comment by NBrannberg** [comment]
Sure, we can add more Indian data.  We just have to keep in mind that we
can't provide Indian data by state but can definitely provide high-level
data as far back as you'd like.

**Comment by jennmalcolm** [comment]
Great, thanks. @NBrannberg

**Comment by jennmalcolm** [comment]
@mcharg what do you think about trying revenue trend graphs for Indian revenues (like we have for federal?

**Comment by mcharg** [comment]
I did them, scroll down to Revene by Resource on this page:
https://ug2su1.axshare.com/#g=1&p=revenue

**Comment by jennmalcolm** [comment]
Oh, ok @mcharg now I remember seeing those there. Should we test them with the Indian revenue options, or do you think we should just automatically include those below the table or horizontal bar graphs?

**Comment by mcharg** [comment]
The other options are for the Revenue by Phase section and the trend graphs belong in the Revenue by Resource section to mimic what we do for federal.

**Comment by mcharg** [comment]
This is what it looks like if we split the Revenue by Company by revenue type.
https://ug2su1.axshare.com/#g=1&p=revenue_by_company_b
