### ISSUE TITLE
Re-enable Hound CI and linting

### ISSUE THREAD

**Issue by adborden** [ONRR/doi-extractives-data#3077]
[HoundCI](https://www.houndci.com/) gives us automated linting checks. We're currently using it for [scss, eslint, and ruby](https://github.com/ONRR/doi-extractives-data/blob/dev/.hound.yml). I think Hound was lost in the [GitHub org migration](https://github.com/ONRR/doi-extractives-data/issues/2777). We should re-enable it for the repo.

**Comment by adborden** [comment]
Alternatively, we could implement our own linting on CircleCI. eslint is pretty simple to run. The Ruby linting will go away once we move to Gatsby.

**Comment by adborden** [comment]
Scratch that, scss-lint is a ruby dependency, so if we want to drop Hounds, we'd still need some ruby deps.

**Comment by jennmalcolm** [comment]
Work to implement what we need will all be in #3343.
