### ISSUE TITLE
Download Data page - make disbursements its own tab 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3080]
In the download data page, disbursements is tucked in under revenue data. I think it should have its own tab like it does in the explore data page.
![image](https://user-images.githubusercontent.com/40175688/42953715-436f83f8-8b38-11e8-8ce0-7f2123dadc6e.png)

![image](https://user-images.githubusercontent.com/40175688/42953800-6e10cd06-8b38-11e8-9e84-ce1533430b27.png)

**Comment by jennmalcolm** [comment]
I agree with this, and while we're at it, let's make the order consistent with what we have on the explore data page and the state pages, with contact us still on the bottom. 
![image](https://user-images.githubusercontent.com/30806839/43775677-8d755a30-9a1b-11e8-8673-8b1bf5602989.png)
