### ISSUE TITLE
Home Page wrong link or change title

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3088]
This takes you to the production process rather than to the section on "what natural resources are extracted", I think either the title should change or link to the right section.
![image](https://user-images.githubusercontent.com/40175688/43108051-084be790-8e9d-11e8-9547-6a5f56a93514.png)

**Comment by brentryanjohnson** [comment]
I suppose the link is doing both: it links to a section titled "The production process," but that section also lists the natural resources that are extracted (oil and gas, coal, nonenergy minerals, renewables).

I'll think about how we can clarify the language to reduce ambiguity. Thanks @Maroyafaied. :)

**Comment by Maroyafaied** [comment]
That's true..I expected it to take me to this section because of the title https://revenuedata.doi.gov/how-it-works/#resources

**Comment by brentryanjohnson** [comment]
Great point, @Maroyafaied. We should consider changing the link to go to the section you referred to after we merge #3066.

**Comment by mcharg** [comment]
The cards are going away.
