### ISSUE TITLE
Docker containers leak build files

### ISSUE THREAD

**Issue by adborden** [ONRR/doi-extractives-data#3094]
This issue is probably specific to Linux since I believe docker isn't native to MacOS or Windows. We're currently using the CircleCI container as our base and configured as the root user. When the docker container writes output files as part of the build, if they are not written to one of the [volumes](https://github.com/ONRR/doi-extractives-data/blob/0ed8e327e92204202458e13bc9ac02a89665e3af/docker-services.yml#L5), they end up in the working directory. This means that on the host machine, we now have files with owner root that can't be edited or removed by the host user.

What makes this difficult is that there are a lot of files written that don't go into a specific directory e.g. the sqlite database. It would be a lot easier if all the generated files ended up in a single build directory.

**Comment by jennmalcolm** [comment]
First step, @master12 talk to Aaron about this to get a better understanding of this issue.

**Comment by jennmalcolm** [comment]
We're not using Docker any more, so we will close this for now.
