### ISSUE TITLE
Fix ordered list in data catalog

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3095]
[The data catalog](https://github.com/onrr/doi-extractives-data/wiki/Data-Catalog#federal-revenue)'s ordered list of items repeats number 1 and jumps back and forth instead of proceeding sequentially.

We should determine the order of the list and fix the problem with the ordering. If an ordered list doesn't convey meaning, we should convert the list to an unordered list with nested lists.

![ordered list doesn't proceed sequentially in data catalog](https://user-images.githubusercontent.com/32855580/43296670-7ddcd86e-9101-11e8-968c-ff1655c20992.png)

**Comment by jennmalcolm** [comment]
This should happen after evaluation in #3415.

**Comment by jennmalcolm** [comment]
This can happen as a part of #3415, so closing this in favor of that.
