### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3096]
We got this notification in GitHub.

We found a potential security vulnerability in one of your dependencies.
A dependency defined in package-lock.json has known security vulnerabilities and should be updated. 

It suggest that we update to mixin-deep to 1.3.1. We should review this vulnerability and update as determined necessary.

**Comment by jennmalcolm** [comment]
I just got another notification. This time it said we need to update static-eval ~> 2.0.0. in the same package-lock.json.

**Comment by jennmalcolm** [comment]
Another noticed said we need to update lodash ~> 4.17.5.

**Comment by master12** [comment]
this is related to fractal and d3. both frameworks are not update-able and the security vulnerabilities are minor. I am suggesting no changes at this time. This will be addressed when we switch over 100% to gatsby.
