### ISSUE TITLE
Address feedback on Key Stats prototypes

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3098]
Adding an issue for this, since I'm spending time making updates and Nathan's team has started reviewing the prototypes

**Comment by mcharg** [comment]
Latest prototypes:
Option 1: https://1rn7bf.axshare.com/#g=1&p=option_1
Option 2: https://1rn7bf.axshare.com/#g=1&p=option_2

**Comment by NBrannberg** [comment]
@mcharg

That trend looks great and we plan on providing monthly production and
revenue data at that level.

Monthly Indian data is perfectly kosher, as long as we don't get down to
the state level.

I love the production graphic.   The revenue graphics are a little too busy
and are very confusing; if they're confusing to ONRR employees, I think
they'll really be confusing to other users.  Just my $0.02.

I love the work you've done and how you are "thinking out of the box"
(cliche, I know), but I'm really impressed with your mock-ups being so new
to ONRR.

Keep up the hard work!

**Comment by mcharg** [comment]
Note: Options A-F were already tested with users and the best performing pieces were consolidated into Option 1 and 2 for a second round of testing.  

Here are the results from the first round of testing: https://github.com/ONRR/doi-extractives-data/blob/research/research/20_fledglingfox/Results.md

**Comment by mcharg** [comment]
@NBrannberg @grjson @hasketta @StaceyKaiser @jennmalcolm I figured out how to export the sankey diagrams to Illustrator to get more control over the colors and labels.  Take a look and see if you think they're easier to understand.

https://1rn7bf.axshare.com/#g=1&p=option_1

**Comment by mcharg** [comment]
@NBrannberg Is it possible to get last year's monthly production numbers, so I can put the trend line in the correct place in the designs?

**Comment by jennmalcolm** [comment]
yes, @mcharg I like the ones with the different colors better. I think they help with clarity.

**Comment by StaceyKaiser** [comment]
@mcharg here are 36 months of production volumes.  Please let me know if this is not 
[Production Volumes June 2015 through May 2018.xlsx](https://github.com/ONRR/doi-extractives-data/files/2250685/Production.Volumes.June.2015.through.May.2018.xlsx)
in a usable format.

**Comment by mcharg** [comment]
@NBrannberg That works.  Thanks!

**Comment by mcharg** [comment]
Option 1 now has an accurate trend line: https://1rn7bf.axshare.com/#g=1&p=option_1

**Comment by mcharg** [comment]
Updated with feedback from demo.

Option 1: https://1rn7bf.axshare.com/#g=1&p=option_1
Added a link to download a monthly data spreadsheet and changed label for "prior period" line to "prior year".

Option 2: https://1rn7bf.axshare.com/#g=1&p=option_2
Changed the toggle to switch between yearly and monthly, changed production graphs to blue, added numbers for most recent 2 months to the monthly view.
