### ISSUE TITLE
Create stand alone page for recruiter form

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3107]
@mcharg has identified a use case for having a dedicated URL to link to for our research recruitment form. Currently, the form doesn't have a distinct URL to link to, as it's toggled via JS from the button at the bottom of the screen. 

We can embed the form in a new blank page to generate a URL to send to potential research participants. I'll create a page that pulls in the template and relevant scripts, and @laurenancona can follow up with the embedded form.

**Comment by brentryanjohnson** [comment]
@laurenancona I [pushed a branch](https://github.com/ONRR/doi-extractives-data/tree/blank-recruiter-page) with a new blank page to embed the recruiter form. Do you want to pull that down and take it from there?

**Comment by laurenancona** [comment]
Taking a look at this now - thanks @brentryanjohnson

**Comment by mcharg** [comment]
We need this before we can recruit any participants via social media.

**Comment by jennmalcolm** [comment]
Move forward with putting this in a Google Form to get around blocker.

**Comment by mcharg** [comment]
Se #3255 for the Google form
