### ISSUE TITLE
Look into starting blog

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3109]
We need to figure out how to implement our blog decision from #2961:

Purpose of blog:

- document our strategy and approach to specific design, development, and content deliverables
- provide a venue for outreach and engagement for open source, open data, and agile principles- 
- provide an opportunity for interested parties to observe our process without having to track individual GitHub issues
- establish a user-friendly archive of our decisions and motivations for future development teams
- lessen the burden on other outreach vehicles (e.g., social media) to cover both content- and data- related updates and our digital practices at the same time
- reduce our reliance on other institutions' outreach channels for this type of content (but make posts available for republication on those channels)

First steps are to find out through the Department if we need permission and from whom.

**Comment by jennmalcolm** [comment]
I have some more information about what we would need to do before starting a blog. The first question I need answered is if we will allow comments from the public on the blog. If we will, we will need a policy for editing or disqualifying submissions as well as a policy for replying to comments. I'm still working to get info on who would need to approve those policies.

What do you think about comments, @brentryanjohnson?

**Comment by brentryanjohnson** [comment]
@jennmalcolm No, I don't think we should try to deal with comments. We can use twitter and/or GitHub to invite feedback and discussion. With a static site, it's very difficult to facilitate comments without third-party integration.

**Comment by jennmalcolm** [comment]
Ok @brentryanjohnson then that makes things easier. I think we can start the blog. I'll send you an email with the policy that we have to follow.

**Comment by jennmalcolm** [comment]
We have found the DOI policy, so we can start blog following that.
