### ISSUE TITLE
Evaluate moving nationwide data below federal production data

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3111]
We had the suggestion that we should move nationwide production data below the federal data since it comes from EIA and is not part of our core data sets.

**Comment by mcharg** [comment]
Related to #3177, #2880, #3122

**Comment by mcharg** [comment]
I'll probe into this when testing this page in the user interviews.
https://ug2su1.axshare.com/#g=1&p=production
