### ISSUE TITLE
Improve site performance

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3112]
## Performance audit

I ran a [performance audit](https://developers.google.com/speed/pagespeed/insights/?url=revenuedata.doi.gov) on our site, and we could be doing a lot better on that front (hopefully GatsbyJS will help somewhat). Here are the scores:

- **Mobile**: Medium (70 / 100)
- **Desktop**: Medium (73 / 100)

## How to fix
The performance audit provides some hints on how to fix these performance issues. Her are the suggestions:

- Leverage browser caching
- Eliminate render-blocking JavaScript and CSS in above-the-fold content
- Minify JavaScript
- Optimize images
- Enable compression

**Comment by master12** [comment]
Ran a test on the explore data page from gatsby

https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/gatsby-explore-data-page/explore/

Mobile:
Optimization
Good
89 / 100

Desktop:
Optimization
Good
85 / 100

**Comment by master12** [comment]
We can still do more with gatsby, such as browser cache, but this is a good start.

**Comment by jennmalcolm** [comment]
Can do another performance audit after Gatsby transition (#3416).
