### ISSUE TITLE
Negative values populate horizontal chart area

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3121]
## Expected Behavior

- Negative numbers do not show up as charted area

## Actual Behavior

- Stacked horizontal bars appear to show negative values in revenue "megachart" (e.g., [Texas](https://revenuedata.doi.gov/explore/TX/#federal-revenue))

![Texas revenue chart showing revenue by phase](https://user-images.githubusercontent.com/32855580/43862649-1e10ab78-9b0f-11e8-9e80-f23762bb58eb.png)

**Comment by jennmalcolm** [comment]
Keeping issue, but we are also looking at replacing this chart, so this may become a non-issue.

**Comment by jennmalcolm** [comment]
Until we can replace this, we could remove the negative value from the bar chart and turn the text for the negative value red, like with the design pattern for the other bar charts.

**Comment by mcharg** [comment]
Closing, since we will be replacing the chart.
