### ISSUE TITLE
Research nationwide/federal production with map icons

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3122]
Related to #3111 

I developed a [`map-icons` branch](https://github.com/ONRR/doi-extractives-data/tree/map-icons) with a working prototype of using map icons to differentiate between nationwide and federal production data. The long-term solution here is probably to use a toggle and chart 📊 them together (at the users' discretion), but perhaps we can test this as an interim solution. 

[Preview the prototype](http://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/map-icons/explore/#all-production).

If this approach helps users distinguish between the two datasets, we'll need to refine it before release. It's not responsive at the moment 📵 (the map images are locked to pixel dimensions).

![map icons to differentiate nationwide from federal production data](https://user-images.githubusercontent.com/32855580/43868577-1a2310e6-9b23-11e8-8322-3a96103a257f.png)

**Comment by mcharg** [comment]
Related to #3177 and #2880

**Comment by mcharg** [comment]
Added this to the guide for the user research.
https://github.com/ONRR/doi-extractives-data/blob/research/research/22_QuietQuail/Guide.md
