### ISSUE TITLE
Look into quick facts design on state pages

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3123]
We had a suggestion that we add quick facts at the top of each state page in a similar fashion as we're doing for the home page.

**Comment by mcharg** [comment]
I did start designs for this back when Ryan was looking at state pages, but they got buried in another issue.
https://tz1pug.axshare.com/

**Comment by mcharg** [comment]
See #3254 for ideas.

**Comment by jennmalcolm** [comment]
This issue will be complete once we determine which ideas from #3254 we should test.
