### ISSUE TITLE
Get Google Search Console up and running

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3124]
Properly configured, [Google Search Console](https://search.google.com/search-console) would allow us to optimize NRRD for search and get an idea of how users are getting to the site.

It appears to be blocked for us (redirects to gmail), so we'll need to figure out if DOI will authorize its use.

**Comment by jennmalcolm** [comment]
First step: @jennmalcolm confirm if there is a way for us to request access.

**Comment by mcharg** [comment]
Google Search Console is blocked by DOI.
