### ISSUE TITLE
Aberrant drop-down styling in Firefox

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3131]
The drop-down styling is broken on Firefox 62.0b14 (on macOS, at least). We should audit this pattern on various browsers and fix the Firefox styling.

## Firefox (macOS)
<img width="607" alt="screen shot 2018-08-13 at 9 18 38 pm" src="https://user-images.githubusercontent.com/32855580/44071570-c6faab7a-9f3e-11e8-9761-7d0e0d58167a.png">

## Chrome

<img width="762" alt="screen shot 2018-08-13 at 9 21 16 pm" src="https://user-images.githubusercontent.com/32855580/44071592-e6c4fc58-9f3e-11e8-916b-ea83968b2f5c.png">

**Comment by jennmalcolm** [comment]
Also an issue on state drop downs.

**Comment by jennmalcolm** [comment]
Issue is specific to case studies, which we are archiving, so closing.
