### ISSUE TITLE
Build instances off social media card template

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3151]
We have a conceptual direction and a template for social media outreach imagery, but we need to build out some instances to support our [content calendar](https://docs.google.com/spreadsheets/d/1H4f31rZN-d6hXnumW90FAMEqO4JFt6tK3llAfpM5bJI/edit?usp=sharing) (limited access).

- build instances with content that aligns with data releases, presentations, and other discrete events

## Boilerplate social media cards

![background of oil pumpjacks on landscape with text of your resources, your data - Natural resources revenue is a major source of funding for parks, wildlife, and public services](https://user-images.githubusercontent.com/32855580/44239984-e4b0c800-a170-11e8-95b6-1f2b57b5680c.png)

![background of oil pumpjacks on landscape with text of Your resources, your data - Natural resources revenue is the second largest source of federal funds](https://user-images.githubusercontent.com/32855580/44239994-eb3f3f80-a170-11e8-8241-46e37de5f8d8.png)

**Comment by jennmalcolm** [comment]
We need @mentastc and @Maroyafaied to first get Photoshop and develop strategy, and they we'll go forward with this.

**Comment by brentryanjohnson** [comment]
First step: schedule mini-Photoshop training for editing the template

**Comment by jennmalcolm** [comment]
@Maroyafaied and @mentastc have had Photoshop training, so I'm marking this to be worked on next sprint.

**Comment by jennmalcolm** [comment]
Draft alt text for Twitter when you create the new cards.

**Comment by Maroyafaied** [comment]
I will work on a card for the new filterable table when we are ready to release that.

**Comment by Maroyafaied** [comment]
one of the cards I have for the revenue table. Note: limited photoshop skills & experience :)
![image](https://user-images.githubusercontent.com/40175688/57394486-ea2cc300-7182-11e9-88f2-5868cb925048.png)

**Comment by brentryanjohnson** [comment]
I'm happy to help with this, @Maroyafaied. A couple observations to start:

- It could use some breathing room around the margins
- It looks like you don't have the font (Lato) that we use on the site and for these cards; perhaps request it from IT?

**Comment by Maroyafaied** [comment]
@brentryanjohnson I will request that font. I'm not sure about @mentastc, but I've been playing around the past few days and I feel like I need a session where I'm creating a card and your are watching and guiding me for practice.

**Comment by brentryanjohnson** [comment]
No problem, @Maroyafaied. I'd be happy to! Go ahead and schedule something. :)

**Comment by brentryanjohnson** [comment]
By way of reminder @Maroyafaied, we previously drafted some [sample/boilerplate social media themes and messaging](https://docs.google.com/document/d/1c_z_x7txZ-qiMaWn5wB2RojDQrUErpV6eWpNjU4stiE/edit?usp=sharing) (limited access) that might be a useful launch point for creating new cards and messages.

**Comment by Maroyafaied** [comment]
Thanks, I'll take a look.
