### ISSUE TITLE
Review the sustainability of MT opt in state content 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3155]

**Comment by Maroyafaied** [comment]
Most of the tax rates are available online, there is some revenue collected data and all of Montana's distribution data is posted publicly.  The data is not in the same format or depth as it is currently, I recommend we archive this data from Montana's state page. I also reached out to contacts from EITI but have not heard back.  all links and data found is listed here https://docs.google.com/spreadsheets/d/13N_ru7FOggJ56T18DvVCAJtv34W0vonZ65DwKzJTKIg/edit#gid=940008491

**Comment by jennmalcolm** [comment]
This was completed. Proposal for future accomplished in #3188.
