### ISSUE TITLE
Update nationwide production in Gatsby explore data

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3159]
We updated nationwide production data from EIA in #3126, but we've since deployed a Gatsby version of the explore data page. The latter has overwritten the nationwide data because they are reading off different data files.

We should update the nationwide production file in the Gatsby version of the site and include a year range of 2008–2017.

**Comment by jennmalcolm** [comment]
@master12 can we get this one done before we do the release from last sprint?
