### ISSUE TITLE
Charts don't display in new explore page on Firefox/Safari

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3163]
The charts for every other section of explore data besides disbursements no longer show up in Firefox.

![production page no charts](https://user-images.githubusercontent.com/32855580/44407150-37440880-a512-11e8-9e34-950360eac937.png)

**Comment by mcharg** [comment]
This is also an issue on my computer.

**Comment by brentryanjohnson** [comment]
This also seems to be a problem in Safari on multiple platforms.

**Comment by jennmalcolm** [comment]
Fixed by #3182
