### ISSUE TITLE
Year selector doesn't work in explore page in Firefox/Safari

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3164]
Year selectors don't change data year in Firefox for data other than disbursements.

![year selector set to 2015 while chart data set to 2017](https://user-images.githubusercontent.com/32855580/44407291-90ac3780-a512-11e8-8fc6-cfe880dfe683.png)

**Comment by mcharg** [comment]
This is also an issue on my computer.

**Comment by brentryanjohnson** [comment]
This also appears to be a problem in Safari.
