### ISSUE TITLE
Nav menu doesn't fold up on explore data page in Firefox

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3165]
The sticky nav menu reveals all subnav items all the time on the explore data page in Firefox. It doesn't fold up and reveal subnav on scroll, as it does on other pages/browsers.

![navigation menu with production, revenue, disbursements, economic impact, and sub nav items](https://user-images.githubusercontent.com/32855580/44407398-dd900e00-a512-11e8-8acc-07f57eea2bec.png)

**Comment by mcharg** [comment]
It's also not highlighting the section you're in and the primary nav isn't highlighting the selected page, as well.

**Comment by jennmalcolm** [comment]
fixed by #3182
