### ISSUE TITLE
Move right navigation to the left

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3175]

**Comment by mcharg** [comment]
This will no longer be an issue for Explore Data with the new design, but we should still consider it for How It Works and About.

**Comment by mcharg** [comment]
@jlouis-onrr Can this be done as part of the MUI transition?

**Comment by jlouis-onrr** [comment]
Yes, this can be done.  Should I create a new issue for this?

**Comment by mcharg** [comment]
@jlouis-onrr I think we can use this issue for it.
