### ISSUE TITLE
Figure out disbursements table design with FY19 data

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3183]
Ensure the design works for the following:
* Monthly commodity data (maybe rounded to nearest $1,000) for the first quarter of FY 2019 
* A field for the royalty, rents and bonuses, and other distributions break down. 

We're probably not going to get the data in that format for past years.

Design: https://wojpgc.axshare.com/#g=1&p=monthly

**Comment by mcharg** [comment]
@jennmalcolm @mentastc Will we have the commodity and revenue type breakdowns for the annual numbers or just for monthly?

**Comment by jennmalcolm** [comment]
Yes @mcharg, we shuold have commodity and revenue type for the annual numbers too starting with FY19.
