### ISSUE TITLE
Write content for disbursements filterable table

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3184]
- [x] Paragraph for Disbursements page

Paragraphs for recipient pages:
- [x] U.S. Treasury
- [x] State and local governments
- [x] Reclamation Fund
- [x] LWCF
- [x] Indian tribes and individuals
- [x] Other Funds
- [x] HPF

Paragraphs for source pages:
- [x] Onshore
- [x] Offshore
- [x] GOMESA offshore
- [x] Other offshore
- [x] 8(g) offshore

- [x] Paragraph(s) for state pages.  Decide whether we need more than one template for these (may one for opt in states and one for other states?)

- [x] Source glossary

**Comment by brentryanjohnson** [comment]
Here is the [WIP document with the descriptions](https://docs.google.com/document/d/1GewlO1mrP5M1p3BuCreugO8vd3VRcHJeNwXUqeMOqyw/edit?usp=sharing) (limited access).

**Comment by brentryanjohnson** [comment]
@jennmalcolm and @mcharg, please review these delightfully delicate disbursements descriptions when you have time. ;)

- [Disbursements table and page descriptions](https://docs.google.com/document/d/1GewlO1mrP5M1p3BuCreugO8vd3VRcHJeNwXUqeMOqyw/edit?usp=sharing), DRAFT (limited access)

**Comment by mcharg** [comment]
@brentryanjohnson I added comments to the doc.

**Comment by jennmalcolm** [comment]
I added my comments as well. Overall it looks very good and this content should provided clarity on a lot of the common questions.

**Comment by jennmalcolm** [comment]
Closing since content looks good.
