### ISSUE TITLE
Make sure we have all the data we need to build key facts

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3189]

**Comment by mentastc** [comment]
https://mail.google.com/mail/u/0?ui=2&ik=99cf791a66&attid=0.1&permmsgid=msg-f:1611239427762444705&th=165c45b90be259a1&view=att&disp=safe&realattid=f_jlwiigid0

**Comment by mentastc** [comment]
^^^^ @mcharg Production data file.

**Comment by mentastc** [comment]
[August 2018 Revenue for Portal.xlsx](https://github.com/ONRR/doi-extractives-data/files/2389357/August.2018.Revenue.for.Portal.xlsx)

Revenue file

**Comment by mentastc** [comment]
[Production Volumes as of 9_6_2018 (5).xlsx](https://github.com/ONRR/doi-extractives-data/files/2389530/Production.Volumes.as.of.9_6_2018.5.xlsx)

Use this production file they cleaned up the format

**Comment by mcharg** [comment]
@mentastc Are we just going to have one month of revenue to start with?

**Comment by mcharg** [comment]
@master12 You'll also need to weigh in on whether we have the yearly production, revenue, and disbursements data in a format that will work or if you need new spreadsheets for those.

**Comment by jennmalcolm** [comment]
As part of this issue, @master12 should review spreadsheets to see if they work correctly for the build.

**Comment by mcharg** [comment]
@mentastc We should also confirm that we're getting revenue data for all products, but only oil, gas, and coal for production.

**Comment by mentastc** [comment]
Data retrieval will be supplying production and revenue data on the 15th of every month, the historical revenue data should be coming before the October 15th data sets arrive. 
-It was suggested that we may need a new issue for process and where to put the data.
