### ISSUE TITLE
Plan for home page usability study

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3198]
- [x] Finalize prototypes
- [x] Create study plan
- [x] Create study script

**Comment by mcharg** [comment]
Draft plan: https://github.com/ONRR/doi-extractives-data/blob/research/research/22_QuietQuail/ResearchPlan.md

**Comment by mcharg** [comment]
Prototype: https://1rn7bf.axshare.com/#g=1&p=start_1

**Comment by mcharg** [comment]
Study guide: https://docs.google.com/document/d/1bxUqpYuNeilLdW6Cu0BwgJriH5NgeXlaSBJOPaCeAFM/edit#

**Comment by mcharg** [comment]
@jennmalcolm Will you please take a look at the plan and guide and let me know if you have any feedback?

**Comment by jennmalcolm** [comment]
The research plans says that we will contact people who have not used the site before (under recruitment strategy). Is that what we want for this round?

**Comment by jennmalcolm** [comment]
I also added a comment to the guide. Overall, it looks well thought out. Thanks.

**Comment by mcharg** [comment]
We do want people who haven't used the site, so we can determine whether the new home page content helps them understand the site's purpose.

**Comment by jennmalcolm** [comment]
Ok, @mcharg only people who haven't used the site or a mix with some who have?

**Comment by mcharg** [comment]
@jennmalcolm Primarily those who haven't because we already know the key stats work for those who have.
