### ISSUE TITLE
Recruit participants for home page usability study

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3200]
Dependent on #3107 and #3171

**Comment by mcharg** [comment]
This is also blocked by #3205 because recruiting shouldn't be our first Tweet.  #3205 is blocked by not having bugs in the build fixed to be able to push a release to Tweet about.

**Comment by mcharg** [comment]
@mentastc Can you please post a recruiting Tweet?

We design our site with users. Have a spare hour and want to help make it better? To sign up, email nrrd@onrr.gov or to learn more watch this video about our design process.
https://youtu.be/jVF3zo4v-Ic

**Comment by mentastc** [comment]
I sent out the tweet and fb post
