### ISSUE TITLE
Research tools available to test mobile with users

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3207]
- [x] Look into screen sharing tools we have available and whether they will allow us to see the screen for remote users on mobile.

**Comment by mentastc** [comment]
There are several apps that can be downloaded that offer complex methods to screen sharing. The best way to screen share would then instead be to use a screen record, this will allow us to get video of the user using the page.

For iPhone the user must go into settings>control center>customize controls>Screen recording
-enable screen recording

now when on your home screen swipe up, this will show your control center with the added record button. pressing this button will record the users activity, to end simply press the record button again, this will save the video to their photos that they can then email to us.

I have not found a screen recording option for android that does not require the download of an app, this may not be a big problem as most mobile users to the site are on iphones.
