### ISSUE TITLE
Draft blog post about data governance at ONRR

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3210]
How do we ensure data accuracy? What are we doing to improve ONRR data? What is the data publication process?

We should consider writing a blog post covering these questions (among others).

**Comment by jennmalcolm** [comment]
Maybe we can get Ryan Jordan involved with this too?

**Comment by brentryanjohnson** [comment]
Yes, @jennmalcolm, I think that's a great idea.
