### ISSUE TITLE
Draft publication process for blog posts

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3216]
Draft governance document for writing, reviewing, and publishing blog posts.

**Comment by brentryanjohnson** [comment]
I've completed the first draft of the [blog publication workflow](https://github.com/ONRR/onrr-innovation-blog/wiki/Publishing-a-blog-post).

It's more complicated than I'd like, but we'll start here and keep working.

**Comment by brentryanjohnson** [comment]
Please have a look, @jennmalcolm and @master12

**Comment by jennmalcolm** [comment]
This looks good, and you have documented each step of the process well. I think you're missing something on step 4 under formatting the post though. Also, I know you're still checking into options for streamlining the last two steps through Federalist, but this is a good start, with well-defined procedures. Thanks for all of your work on it @brentryanjohnson.

**Comment by brentryanjohnson** [comment]
@jennmalcolm Thanks for catching that incomplete sentence! Also, I realized there were two "step 4"s, so I folded one of the (content guide) under the actual step 4.

Thanks again. I'll continue to explore the best method of building and serving the site.
