### ISSUE TITLE
Draft chapter proposal for outreach

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3232]
There's an opportunity to put together a book chapter proposal for a book title "Advancing Diversity, Inclusion, and Social Justice through Human Systems Engineering" that would be good for outreach.

I reached out to the authors to see if they'd be interested in a proposal for a personal narrative chapter that talks about making sure open data sites are inclusive and promote social justice.  We're in a unique place with our site because we were originally created as part of the Extractive Industries Transparency Initiative (EITI), but the U.S. has since backed out of that, so we're discovering what our users actually want to do with the data and reforming the site along those lines.  The narrative would get into how we've gone about finding and talking with our users (without being able to offer incentives because of government ethics rules) and how we're adapting the site to meet their needs.

They said they're interested in seeing a proposal that is due by Sept 28.

**Comment by mcharg** [comment]
@jennmalcolm Is there anyone who will need to review the proposal before submitting?

**Comment by jennmalcolm** [comment]
@mcharg I could review it and check with Judy too.

**Comment by mcharg** [comment]
Book details: https://slatelab.engineering.asu.edu/disj-hse/
Chapter proposal requirements: https://slatelab.engineering.asu.edu/wp-content/uploads/2018/07/Call-for-Chapters-Detailed.pdf

**Comment by mcharg** [comment]
Here's a first pass at the proposal:
[BookChapterProposal_091918.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad649002a863f001370d4d5/125516c66e82c728ace21e0d46ca9b9528a18ba89ffdba51944fff842655267f1654fa7a29d4bb6af3006b1300051bff054a5556f9fc887ef2b76975d95a59e582685a7dc63d17a4bdd418bc13a632c91edbe2e3d7158abd7f37ed998e48341f001b8efc5b36a89b43ca5ff459ac.docx)

@jennmalcolm @brentryanjohnson @usEITI Can you please review?

**Comment by mcharg** [comment]
The proposal is due on Friday, so I need any feedback sooner rather than later to have time to iterate before submitting.

@jennmalcolm @brentryanjohnson @usEITI

**Comment by mcharg** [comment]
@jennmalcolm I think Ryan's revisions cover everything you suggested changing.  Can you take a look at his version and see if you're good with it?

**Comment by jennmalcolm** [comment]
Yes, @mcharg, I think Ryan's revisions work. The only suggestion of mine he didn't address is to add something where you transition to discussing the problems we encountered. That was only a suggestion though, and I'm fine with going with the version with his changes.

**Comment by brentryanjohnson** [comment]
Sorry about that, @jennmalcolm and @mcharg. I sent my changes before I read through Jennifer's. Looks like we were on the same page, though. :smile:
