### ISSUE TITLE
Add first component for key stats to the pattern library

### ISSUE THREAD

**Issue by master12** [ONRR/doi-extractives-data#3236]

**Comment by jennmalcolm** [comment]
First component will be bar charts. Detailed design is in #3146

**Comment by master12** [comment]
Ready for review
Chart
https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3192-key-stats-feature/patterns/components/stackedbarchart/

Chart title
https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3192-key-stats-feature/patterns/components/charttitle/

Chart Legend
https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3192-key-stats-feature/patterns/components/chartlegendstandard/

**Comment by mcharg** [comment]
Chart:
- Missing the top line that shows the scale of the chart.
- The bars are wider than the design.  Will this be able to accommodate 12 bars for the monthly charts?
- In the design, the hover colors are slightly different from the selected colors.  Will the ways it's built be able to accommodate that?
- The year labels should bold and change to the highlight color when the bar is either hovered or selected.

Chart title:
- Looks good.

Chart Legend: 
- See comment on #3244
- With the interactivity, the legend is supposed to change both year header and amounts when the user hovers or selects.  Will that be something that's built at the time the components are put together on the page?

**Comment by master12** [comment]
@mcharg Thanks for the feedback. Just a few comments.

1. The chart size including the bars is design to fill whatever space we specify. The bars will be adjusted based on the number of bars (12 months vs 10 years) and the width of the container it is in.  So hence we will not be specifying the widths of the individual bars the instead the chart size itself.
2. Colors will also be specified depending on what we want. They will be updated once I create the home page section. we can specifying hover, selected and not selected colors. 
3. The legend will interact with whatever chart we attach it to. the chart data will drive its details and change with the chart selections.

Will address your other points. Thanks.
