### ISSUE TITLE
Excessive margin on disbursements chart

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3240]
On wide viewports, the data values are compressed. They would look more natural pushed to the right margin.

![image](https://user-images.githubusercontent.com/32855580/45897620-8210a480-bd8c-11e8-9427-a86ebb728a27.png)

**Comment by master12** [comment]
This change was made at the request of shannon. Please discuss with her.

**Comment by mcharg** [comment]
I think a bigger issue is that they don't all align with each other.

![image](https://user-images.githubusercontent.com/38465926/45898646-9498d700-bda8-11e8-9a04-ee97e1883f43.png)

**Comment by mcharg** [comment]
That works for the two column view, in the one column view, it was too spread out at 600 and 480 px.

**Comment by mcharg** [comment]
Closing, since we can address when we do the new summary for Explore Data.
