### ISSUE TITLE
Evaluate redundant nav menu at end of explore data

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3241]
It looks like there may be a rogue sticky nav at the bottom of the explore menu on small viewports. We should look into this.

![navigation menu at the bottom of page](https://user-images.githubusercontent.com/32855580/45902161-8217a100-bd9a-11e8-9e35-4ed620fbd522.png)

**Comment by mcharg** [comment]
This is also an issue on the state pages.
