### ISSUE TITLE
Add legend for quick facts design to pattern library

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3244]
Design detail in #3146

**Comment by master12** [comment]
Ready for review:
https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3192-key-stats-feature/patterns/components/chartlegendstandard/

**Comment by mcharg** [comment]
The swatches aren't quite horizontally aligned with the labels.  Otherwise, looks good.
