### ISSUE TITLE
Consider adding social media icons and links to blog template

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3250]
We should consider adding social media icons and links to our accounts to the blog template before launch.

**Comment by brentryanjohnson** [comment]
I've created a branch without and with social media icons and links. I'm not sure about them, both from an aesthetic standpoint and from a strategic one. For example, we'll be pointing users to the blog _from_ social media...do we want to send them right back? I assume that user journey will be the primary one – at least at first. How much value do we add by including them? 

I think it makes more sense to offer up the GitHub org link than either twitter or facebook, but we can discuss during demo or retro.

In place of the social icons in the first footer version, I've include the line, "From the team that works on Natural Resources Revenue Data, "with a link to the site.

![footer without social icons](https://user-images.githubusercontent.com/32855580/46696163-597b0e00-cbc6-11e8-8d61-2d9f993775f2.png)

![footer with social media icons](https://user-images.githubusercontent.com/32855580/46696297-b5de2d80-cbc6-11e8-97c7-d01c68837738.png)

**Comment by mcharg** [comment]
I don't think it hurts to have the link because you never know where traffic will come from.
