### ISSUE TITLE
Explore making the recruiting screener more visible

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3252]
This will be easier to do once we have the stand alone page (#3107).

**Comment by mcharg** [comment]
Option 1: Footer link
https://gpwk1r.axshare.com/#g=1&p=option_1__footer_link

Option 2: Top of page alert
https://gpwk1r.axshare.com/#g=1&p=option_2__top_of_page_alert

Option 3: Floating CTA after scroll
https://gpwk1r.axshare.com/#g=1&p=option_3__floating_cta

**Comment by jennmalcolm** [comment]
My preference is for 1 or 3. Even though I know the intention is to be more visible, I think number two is taking up too prominent of a spot on the home page. Is your plan to work these options into user research in the near term?

**Comment by mcharg** [comment]
@jennmalcolm I think we should implement #1 ASAP, so the form is on the site and then do 2 and 3 as live tests (when we have spare time) on the site to see if either one ups the response rate.  I don't think we'll get a good read in user testing because the people we're testing with are probably more likely to say they'd sign up with any design because they've already done so.  I've tested both patterns with users in the past for things like credit card sign ups and they both were seen as not too much of a nuisance.

Can we spend 5 minutes in sprint planning reviewing with the team to see what others think?

**Comment by master12** [comment]
I never look at the footer of a website unless I want to contact people. So I think it make sense to start there since its not obtrusive. I also dont mind when sites have an alert header. Easy to ignore or dismiss. It does make me mad when a site has a full page modal window popup. ANNOYING. 

SO I agree. 1 to start

**Comment by jennmalcolm** [comment]
Sure @mcharg
