### ISSUE TITLE
Contemplate value-adds for geographic relevance

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3254]
Let's brainstorm ways to add specific geographic value from data we already maintaining. For example, will it add value to users to list the percent of overall production that comes from federal land in a given state? Are the units comparable?

**Comment by Maroyafaied** [comment]
Some ideas I came up with is to replace GDP statement with the state's ranking for energy production nationwide. For production, calculate % of state and federal production from EIA and ONRR data for oil, gas, and coal. For revenue, mention amount companies paid to produce on federal lands in that state and calculate % of total revenue collected by ONRR. For disbursements, mention total disbursed for most recent year and give  % of how much it accounts for total federal disbursements.  Also, add bar chart to show history of federal annual disbursements for that state.

I summarized the ideas in this document. https://docs.google.com/document/d/14TSg8TDprHWtdjvVWmObex3u70ekYFptL1qy9-OJZcA/edit

**Comment by mcharg** [comment]
I think the ideas are great and we should use them for #3123 in place of quick facts on the state page.

**Comment by jennmalcolm** [comment]
Yes @Maroyafaied I like the ideas. I think they add context more directly related to our data sets than the GDP fact.

**Comment by jennmalcolm** [comment]
@Maroyafaied do you think this issue can be closed, or do we have more work do do to complete it, or does Ryan need to have a say?

**Comment by Maroyafaied** [comment]
If you and Ryan have reviewed it, they yes it can be closed. This is the google document, we can add ideas to it in the future.
https://docs.google.com/document/d/14TSg8TDprHWtdjvVWmObex3u70ekYFptL1qy9-OJZcA/edit

**Comment by jennmalcolm** [comment]
I don't know if @brentryanjohnson has reviewed it, so I guess we can leave it open until he gets back.

**Comment by mcharg** [comment]
I think @brentryanjohnson said he'd reviewed it in one of the standups last week.

**Comment by jennmalcolm** [comment]
Ok, then I'll go ahead and close it. We can create new issues for the follow-on work. Thanks.
