### ISSUE TITLE
Update content calendar

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3267]
We should take a look at the [content calendar](https://docs.google.com/spreadsheets/d/1H4f31rZN-d6hXnumW90FAMEqO4JFt6tK3llAfpM5bJI/edit?usp=sharing) (limited access) and update it.

**Comment by brentryanjohnson** [comment]
I've added and rearranged a few things, but we can't overhaul the content calendar until we receive the updated data publication schedule. Closing for now.

**Comment by jennmalcolm** [comment]
@brentryanjohnson I talked to Nathan and we should have the data calendar next week.
