### ISSUE TITLE
Write full book chapter

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3269]
They accepted the proposal and want me to write the full chapter (which will need to be peer reviewed before final acceptance).  Chapters are due by Nov 30.

**Comment by mcharg** [comment]
[BookChapter_110618.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad649002a863f001370d4d5/125516c66e82c728ace21e0d46ca9b9528a18ba89ffdba519b0ca1c47f177f316546b3397f8fe62bab0021435a5a4ff915590a41afffdb23f5b339798a5c0de5d43b5877d42103eee9dc4be05ce36ade0d97bcae8b4acae93821e68e8c4a3e16061181f84f78.docx)

Draft attached.  @jennmalcolm @brentryanjohnson @lpgoldstein @usEITI Please review and provide feedback.

**Comment by brentryanjohnson** [comment]
@mcharg I added some suggested edits in this version. They're mostly minor changes to simplify sentences or clarify meaning.

I don't know if you're up against a word count, or if perhaps this is out of scope, but it might be useful and relevant to mention accessibility/section 508 compliance. It might be a slight tangent to the research focus, but it is well aligned with the theme.

[book-chapter-rj-edits.docx](https://github.com/ONRR/doi-extractives-data/files/2559691/book-chapter-rj-edits.docx)

**Comment by jennmalcolm** [comment]
I think this has everybody's comments incorporated.
[chapter comments jm jw lg rj.docx](https://github.com/ONRR/doi-extractives-data/files/2561964/chapter.comments.jm.jw.lg.rj.docx)

**Comment by mcharg** [comment]
Thanks.  The word count limit is 1500, which I was right about at in the draft.

**Comment by mcharg** [comment]
Here's an updated version.  

It's at 1426 words, so there's room for 74 more.  @brentryanjohnson Where were you thinking accessibility might fit in?  I couldn't find an obvious place to put it.
[BookChapter_110818.docx](https://github.com/ONRR/doi-extractives-data/files/2562254/BookChapter_110818.docx)

**Comment by brentryanjohnson** [comment]
@mcharg Since accessibility isn't an aspect of the user research, perhaps just list it under the best practices bullets near the end? Then at least it's included somewhere.

**Comment by mcharg** [comment]
@brentryanjohnson Done.

[BookChapter_110818b.docx](https://github.com/ONRR/doi-extractives-data/files/2562466/BookChapter_110818b.docx)

**Comment by lpgoldstein** [comment]
@mcharg Looks good!

**Comment by jennmalcolm** [comment]
Closing since it's ready to go.

**Comment by mcharg** [comment]
Submitted the chapter and they were impressed that I was the first one.
