### ISSUE TITLE
Restructure state summary content

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3277]
Related to #3038 and #3123 

Observing our data publication schedule, I'd like to start reformatting the state-page intros to eliminate the dependence on GDP data. We're planning to eliminate the Economic Impact section and associated data when we publish FY data in November. The economic data isn't specific to federal lands and waters, and thus doesn't align with our updated [product vision](https://github.com/ONRR/doi-extractives-data/wiki/Product-framing#our-vision).

To prepare for the removal of that data, we need to replace content that is driven by it. One obvious example of this is the state-page summary, in which GDP data drives state-level content.

I've worked on a possible prototype for this. This is fairly straight forward for Wyoming, but we'll need to draft and evaluate an example for states for which there is no production, revenue, or disbursements.

We should also consider a summary that shows the portion of state production from federal land versus all other categories of land ownership.

![State page summary content](https://user-images.githubusercontent.com/32855580/46691312-778e4180-cbb9-11e8-9f8c-9f504a5e0fe5.png)

**Comment by brentryanjohnson** [comment]
There's an idea for adding percentage of production from federal lands over in [the other issue](https://github.com/ONRR/doi-extractives-data/issues/3471#issuecomment-447930260).

**Comment by Maroyafaied** [comment]
There's also some ideas here related to issue #3254 https://docs.google.com/document/d/14TSg8TDprHWtdjvVWmObex3u70ekYFptL1qy9-OJZcA/edit

**Comment by brentryanjohnson** [comment]
I was looking for that, @Maroyafaied. Thank you!

**Comment by jennmalcolm** [comment]
comments @mcharg @lpgoldstein @jennmalcolm

**Comment by brentryanjohnson** [comment]
This is now blocked by #4554
