### ISSUE TITLE
Plan for user interviews next week

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3279]
Create a script for interviews that focuses on monthly data, lease level data, and other items we've identified we need to research.

**Comment by mcharg** [comment]
I pulled all of the latest designs into a single prototype that we can use for user testing and sharing with stakeholders.
https://u7sqr1.axshare.com/

**Comment by mcharg** [comment]
Plan: https://github.com/ONRR/doi-extractives-data/blob/research/research/23_timelyturkey/ResearchPlan.md

**Comment by mcharg** [comment]
@jennmalcolm Please review the plan and guide.

**Comment by jennmalcolm** [comment]
The plan and guide look good. I added one note on the guide.

In the design, for the overview tabs on the home page, could you change the quote marks around "revenue" to double quotation marks to be consistent with the ones around "disbursement"?

**Comment by mcharg** [comment]
Done
