### ISSUE TITLE
Make a place on the wiki for analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3280]

**Comment by mcharg** [comment]
https://github.com/ONRR/doi-extractives-data/wiki/Analytics

**Comment by mcharg** [comment]
@jennmalcolm I put content on the page that shows some historical data.  Maybe we can quickly review in sprint planning.

**Comment by jennmalcolm** [comment]
Ok @mcharg, yes we can take a look in sprint planning.
