### ISSUE TITLE
Explore different map content and coloring

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3281]
We've gotten feedback in user testing that:
- Users don't notice that the coloring is for ownership.
- The green shades don't have enough contrast.
- The coloring doesn't match to the Data Highlight section.
- The offshore regions may prevent users from recognizing that the map is the US, at a glance.

Can we use D3 to prototype some options and play with colors?

**Comment by brentryanjohnson** [comment]
I've spent just a couple minutes playing with this and observed the following;

- The offshore areas are easily targeted for color alteration, but will require an addition to the legend
- The land map features (ownership) are gradations of green; changing the "base" color alters the opacity of each ownership feature layer
  - This means we would need to refactor the styling to target each ownership feature separately

I'll keep experimenting and see what I can come up with.

## An (ugly) example
![United States map with land ownership overlays](https://user-images.githubusercontent.com/32855580/46755419-df0bc600-cc79-11e8-8e4c-a4b8e5827265.png)

**Comment by mcharg** [comment]
Can we try federal onshore (#086996), federal offshore (#086996), and Native American (#C6E9FF) in colors to match the data highlights charts and then do the state and private in the gray we use on the production summary (#A7BCC7)?

**Comment by mcharg** [comment]
Or, if we want to keep greens, we could use these 4 shades that are reasonably far apart from each other (at lease they are in a bar chart).
$green-dark, #2f4d26
$green-land, #69995a 
$green-mid, #9dbd92 
$green-light, #cde3c3

**Comment by brentryanjohnson** [comment]
So that's what I mean...if we want to change from green for onshore (for any part of the onshore map), it's a bigger lift – which is fine, we'll just need to plan for it and have a solid idea about what we are looking to do.

**Comment by jennmalcolm** [comment]
It would be helpful to have more differentiation between colors, but  I think the bigger issue we need to address is  the content of the map. A chlorapleth for the revenues by states would more closely align with the product vision and provide a scale that is easier to view on this size map. Once built to update from the data, it would also be easier to keep up with a revenue map. While we treat it as a static item, land ownership regularly changes. Since land ownership data isn't ours, it is harder to update. When it is more clear that the map is a data visualization (and not just a navigation tool in many cases), we may not need to worry about #3410. 

I updated the name of this issue so that we only work on the color as part of improving its usefulness overall.

**Comment by jennmalcolm** [comment]
After talking @mentastc about the first version of the map, he said the biggest problem they had with the revenue chlorapleth was that there was such a difference in color between the offshore areas and the states (with central gulf revenues so much higher than the highest state revenues). So, that is something we'll need to think through is we try to go back to revenues.

**Comment by mcharg** [comment]
One of the problems users currently have with the map is the offshore regions because they're not something they're familiar with seeing on US maps, they had to spend time thinking about what they are.

**Comment by brentryanjohnson** [comment]
For context, here is a screenshot of the choropleth the 18F team originally built for the homepage:

![map of the US showing relative revenue generation by state](https://user-images.githubusercontent.com/32855580/52803903-d8ca9380-3037-11e9-8ee2-be5057677646.png)

As @mentastc mentioned via @jennmalcolm, the gulf revenue is obviously a huge percentage of the overall revenue, affecting the scale of the color ramp. From a color ramp standpoint, using two different colors (not just shades of the same color) implies different categories of data, even though the legend shows they are all of the same type. If we contemplate rebuilding something like this, I think we should limit the color ramp to saturations of the same hue to make it immediately obvious the data is of the same type, just in different concentrations.

**Comment by mcharg** [comment]
Yes, we should definitely use saturation as the only differentiation.  This makes it look like there's something different about the blue sections.

**Comment by mcharg** [comment]
We've explored options, now we need to build.
