### ISSUE TITLE
Add outreach opportunities to market map

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3286]

**Comment by mcharg** [comment]
NCSE has poster submissions open until October 31. https://ncseconference.org/call-for-session-proposals/
NCSE Annual Conference
Call for Session Proposals and Posters
NCSE is now accepting additional poster sessions for the 2019 Annual Conference.  Posters are being accepted until October 31. To submit a poster, click the button below and follow the instructions…
Apr 18th at 2:01 PM

**Comment by mcharg** [comment]
The Data on Purpose conference is looking for speakers.  There's no date, but the conference is in Feburary. http://www.ssirdata.org/
ssirdata.org
Data on Purpose 2019 (9 kB)

**Comment by Maroyafaied** [comment]
I added a tab in the market map labeled "outreach opportunities" and added those two conferences.  https://docs.google.com/spreadsheets/d/1zwSwBrEPsxCN8ctZi9hzx9FVz-bE5jxM06rMxN2tKe8/edit#gid=1125437724
