### ISSUE TITLE
Add recruiting screener to footer

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3289]
Design: https://gpwk1r.axshare.com/#g=1&p=option_1__footer_link

**Comment by mcharg** [comment]
Link to the screener: https://docs.google.com/forms/d/e/1FAIpQLSe5fTZq_SCrid9N48Bh2DJ-WzHfYvo75-En6g7f9iaIK6EGiQ/viewform

**Comment by mcharg** [comment]
Icon:
[Bullhorn_White.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad649002a863f001370d4d5/125516c66e82c728ace21e0d46ca81962f8a8cbb81d6884bad49f5d665043761260ea62864c7b96aea172a040b5e1ba9125e0d4caffc8c22a6b63a788f0a0ceec3714d36976345f3e5db55ea43a82a994e83bcbd8f4fc9ee3f2ce383874a391a1755.zip)

**Comment by master12** [comment]
Ready for review:
https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3284-3289-footer-recruiter-pattern-library/patterns/components/footer/

**Comment by mcharg** [comment]
Looks good.

**Comment by mcharg** [comment]
Actually, @master12, can you make the form open in a new tab/window, since it's external to our site?

**Comment by jennmalcolm** [comment]
Work continuing in #3293
