### ISSUE TITLE
Create first NRRD outreach material

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3290]
In #2962, we identified some print materials to create for NRRD outreach. We need to start creating those materials. This issue will be done when:

- [x] we decide which material to work on 1st

- [x] we create a draft of that material

- [x] we share the draft with the team for review and feedback

**Comment by lpgoldstein** [comment]
Please review this draft brochure. I still need to work on the graphics, but Adobe kept shutting down so will try again tomorrow. [NRRD Outreach Brochure 2018_v1_11.9.2018.pdf](https://github.com/ONRR/doi-extractives-data/files/2564703/NRRD.Outreach.Brochure.2018_v1_11.9.2018.pdf)

**Comment by mcharg** [comment]
This looks good.  I did notice that the url on the cover is incorrect.  It should be revenuedata.doi.gov (it says revenuedata.onrr.gov).

**Comment by lpgoldstein** [comment]
Draft with comments incorporated. Closing issue. Will create a new issue to look at how we print and next steps. [NRRD Outreach Brochure 2018_v2_11.16.2018.pdf](https://github.com/ONRR/doi-extractives-data/files/2597164/NRRD.Outreach.Brochure.2018_v2_11.16.2018.pdf)
