### ISSUE TITLE
Receive and Prepare FY Disbursement data for publication

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3292]
We should receive the disbursement data from FM by 10/19. This issue will be complete when we have reviewed that data for anomalies and  ensured it is ready for publication (which will happen in #3291).

**Comment by brentryanjohnson** [comment]
We've prepared national disbursements data, but we need to add state-level disbursements data.

**Comment by jennmalcolm** [comment]
@brentryanjohnson could you provide an example spreadsheet to show us what format you need to get the state data? We have the data. I just want to get it in the right format to make the updates easy.

**Comment by jennmalcolm** [comment]
Also, last I heard, the go live date is Nov 1. That's what I'm operating on right now.

**Comment by brentryanjohnson** [comment]
Thank you, @mentastc. This one appears to be properly formatted for the 'Funds data by state and county" download.

We have another download: "Funds data by type," which is formatted slightly differently. See below...

![disbursements by type](https://user-images.githubusercontent.com/32855580/47725929-c0fd0a00-dc16-11e8-98f1-a34a414102c6.png)

![disbursements formatted spreadsheet](https://user-images.githubusercontent.com/32855580/47725903-ad51a380-dc16-11e8-8bc5-2681b106d82b.png)

**Comment by jennmalcolm** [comment]
@brentryanjohnson we only had two types of downloads last year because we didn't have the GOMESA data or the past years on the EITI format. Chris, Maroya, and Lindsay worked to get all of the same information into one spreadsheet. So, we want to have this file replace both on the download data page. We can still call it "Funds data by state and count" unless you think there's a better name.

Could you let us know if we need to format the file any differently to run the state updates script? I'm not sure if I looked at the right file from last year.

**Comment by brentryanjohnson** [comment]
@jennmalcolm That makes sense. I noticed the year range was expanded to match the other file's scope.

I relabeled it "Funds data by state, county, and type," and I pushed it to the staged branch.

I'll look into the data script with @master12 to see if the format will work for state updates.
