### ISSUE TITLE
Add footer section to pattern library

### ISSUE THREAD

**Issue by master12** [ONRR/doi-extractives-data#3294]

**Comment by mcharg** [comment]
Related: #3289 to add the recruiting screener link to the footer.

**Comment by master12** [comment]
Ready for review:
https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3284-3289-footer-recruiter-pattern-library/patterns/components/footer/

**Comment by brentryanjohnson** [comment]
I added a period to the imperative sentence "Help make this site better."

**Comment by brentryanjohnson** [comment]
In the inspector, I see there is a margin imposed here, which provides breathing room between the edge and the logo:

![footer of website with margin shown](https://user-images.githubusercontent.com/32855580/47190401-073c9a00-d2f6-11e8-94e0-bcfb000d3880.png)

But for some reason, the margin doesn't appear in the default view:

![footer without margin](https://user-images.githubusercontent.com/32855580/47190439-3eab4680-d2f6-11e8-8c40-48c9954bfed4.png)

It's a minor issue, but it doesn't present the component as it's marked up.

**Comment by mcharg** [comment]
I agree that we need to fix the padding on the logo.

**Comment by master12** [comment]
Its because out pattern library css sux. If you view it in responsive mode it is the same as what is on the site now.

**Comment by jennmalcolm** [comment]
Work continuing in #3293
