### ISSUE TITLE
Add header to pattern library

### ISSUE THREAD

**Issue by master12** [ONRR/doi-extractives-data#3297]

**Comment by master12** [comment]
For review:
https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3297-header-pattern-library/patterns/components/header/

**Comment by mcharg** [comment]
Should the nav be going into the hamburger menu in the smaller viewports?  The hamburger isn't showing up in Chrome.

**Comment by jennmalcolm** [comment]
Work continuing in #3293
