### ISSUE TITLE
Compile old user research findings by topic

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3300]
This way we can track things over time.  For example, I'll pull together all of the things we've heard about lease level data before into one place.

**Comment by mcharg** [comment]
Here's the spreadsheet of findings (limited access): https://docs.google.com/spreadsheets/d/1CnQVlDRCnstzw0SqQfpRAj8u4-af2qp4ycE6jNgKXIw/edit#gid=0

And a start to the Github version (will finish tomorrow): https://github.com/ONRR/doi-extractives-data/blob/research/research/researchfindingsbytopic.md

**Comment by mcharg** [comment]
@jennmalcolm @brentryanjohnson @Maroyafaied @lpgoldstein @mentastc Any feedback on format?  The markdown was painful on the Github version, but I wanted to be able to have headers to link to from issues related to specific topics and the default alignment and wrapping in tables made it hard to read when I went with a straight up table.

**Comment by jennmalcolm** [comment]
I like how you link to the issues. For the spreadsheet, could we split the user types and the findings sections into two tabs? Also, the term "frequency" does confuse me a bit. Is that the number of people you've asked about the issue or the number of people who think it's a problem. Maybe we could state "Number of Interviews" if that is what it represents.

**Comment by mcharg** [comment]
@jennmalcolm It's the number of people who think it's a problem.  What would be good wording for that?

**Comment by mcharg** [comment]
I added a second row under the headers that explain the columns.
