### ISSUE TITLE
Audit how ARIA attributes are used for buttons

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3313]
One of our accessibility audits flagged our ARIA labels for buttons. We should further examine.

`[aria-*] attributes are not valid or misspelled`

![button aria label alert](https://user-images.githubusercontent.com/32855580/47235391-c1cbab80-d38d-11e8-829e-7fe5e0022c01.png)

**Comment by mcharg** [comment]
Closing in favor of new accessibility audit.
