### ISSUE TITLE
Change unordered list to only contain li and script-supporting elements

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3315]
One of our accessibility audits flagged an unordered list that contains improper elements.

`Lists do not contain only li elements and script supporting elements (script and template)`

![list item accessibility error flag](https://user-images.githubusercontent.com/32855580/47238264-81246000-d396-11e8-8173-fd7fcfa88d06.png)

**Comment by mcharg** [comment]
Closing in favor of new accessibility audit.
