### ISSUE TITLE
Reduce excessive space before Production section

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3318]
There is an alignment issue between the Production subheading and the nav menu and an
 excessive margin before the Production subheading (on desktop, at least).

We should reduce the amount of white space here and align the nav with the opening subheading section.

![excess space before production section](https://user-images.githubusercontent.com/32855580/47247137-90b3a100-d3b6-11e8-8336-b636c9392fc8.gif)

**Comment by mcharg** [comment]
Should we close this since it will be irrelevant with the new explore data page or do we want to fix in the interim? @brentryanjohnson @jennmalcolm

**Comment by jennmalcolm** [comment]
I'd say close.
