### ISSUE TITLE
Plan for how it works content for disbursements

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3321]
We  need to look at creating a new section on the how it works page for disbursements content.

My initial feeling is that under "Resources to Revenue," we could add a disbursements section. We need to have some type of overview content, but then we could also have sections for the LWCF and HPF content that already exists. That would make it easier to find that information too.

This issue will be done when we have a plan for what content to add and we have created follow-on issues for the creation of that content.

**Comment by brentryanjohnson** [comment]
We have a scope for disbursements context in how-it-works. Here is the outline for what we're planning to provide:

- Laws and regulations that govern each disbursement
- Frequency of disbursement to each fund
- Which are subject to Congressional appropriations
- Provide layout that brings together existing disbursements contextual narrative (GOMESA, Land and Water Conservation Fund, Historic Preservation Fund)

**Comment by lpgoldstein** [comment]
I was able to connect with another person re the HPF content and she will hopefully get back to us next week as she is on leave/work travel this week.
