### ISSUE TITLE
Fix width/range of disbursements bar 

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3326]
## Expected Behavior

- Larger values will result in longer bars than smaller values

## Actual Behavior

- Because they're relative to each other, a larger value may result in a shorter bar year to year

## Steps to reproduce the behavior

- Toggle disbursements between 2017 and 2018 years and watch Treasury

![disbursements chart change 2017 to 2018](https://user-images.githubusercontent.com/32855580/47452974-823ffd80-d799-11e8-813a-6a973e5a56b9.gif)

**Comment by jennmalcolm** [comment]
Adding to this sprint so we can improve this before we release the new data by changing the max value to the max for the data set. This presents a different problem visually, but we've determined it's a better solution for now than having the bars grow when the numbers are going down.

**Comment by mcharg** [comment]
It could help to take away the animations.

**Comment by brentryanjohnson** [comment]
I think it's a good idea to temporarily remove the animations until we decide how to handle this. The effect will by much less jarring without the animation.

**Comment by jennmalcolm** [comment]
In reviewing the preview builds for the disbursements data release, I noticed that the overall widths for general treasury by year are not all the full width. If we could change that so that they are all an even width for the general treasury (since I think that is the max value for each year's data set), then maybe that would also help with this problem (at least for the treasury bar). @master12 what do you think about doing that and taking away the animations temporarily until we figure out a better solution? I do like the animations, but they seem to be giving a misleading message given the bar graph design.

**Comment by mcharg** [comment]
That’s the way it was in the design we tested with users (U.S. Treasury at full width), though we didn’t have the year drop-down working, so we don’t know what users expect to happen when changing years.

**Comment by mcharg** [comment]
Potential long-term fix - add a column with a spark line showing the trend across years.  That would satisfy users who want to know what’s changed and leave the detailed breakdown for the bar graph.  We could put a dot in the spark line showing where the selected year falls.

**Comment by master12** [comment]
@jennmalcolm The overall width is now at max length. It was a rounding issue. Easy fix. Do you mind if I include that change on the  Home page release?

**Comment by jennmalcolm** [comment]
@master12 thanks, glad to give you a little break from all the complicated problems. Could you add it to the outfall branch instead so it the fix can go out to coincide with the disbursements release?

**Comment by master12** [comment]
outfall branch updated @jennmalcolm

**Comment by brentryanjohnson** [comment]
This corrected the relative display for treasury, but we still have issues with the relative display of individual lines below it. The rest of the funds shown _grow_ to lesser values between 2015 and 2016. Relativity is fickle.

![subdisbursements-grow-shrink](https://user-images.githubusercontent.com/32855580/47818766-ecb2e980-dd15-11e8-9fa5-18848d66a265.gif)

**Comment by mcharg** [comment]
This is what I was thinking we could do with a sparkline.  It might also be a solution we could use to incorporate monthly data on this page, though it may get tricky if some years are monthly and some are yearly.

The green dot would move to the year you have selected in the drop-down.

![image](https://user-images.githubusercontent.com/38465926/47860173-54287200-ddc6-11e8-8bb7-46b65cd28a49.png)

**Comment by mcharg** [comment]
Also, once we have the filterable table, will we need to have the year selection on this page?  Could we just show the most recent year here and send the user to the filterable table to see the detail for prior years?

**Comment by jennmalcolm** [comment]
@mcharg could you create a new issue for looking into incorporating spark lines in the disbursements section? This looks like an interesting concept to explore more. It might also work as part of a replacement for the revenues graphs.

**Comment by master12** [comment]
yes i can deanimate

**Comment by jennmalcolm** [comment]
Closing this since we did what we could to de-emphasize the visual of growing bars with smaller numbers. We will have to look at alternative designs to eliminate this effect.
