### ISSUE TITLE
Write script for lease level data interview(s)

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3327]
We should have a script for talking with people about lease level data.

**Comment by mcharg** [comment]
Draft script (limited access): https://docs.google.com/document/d/1t67Fn4itxZbd9wMAX9CbYPBuoBpKNVVa6NBPSjfHfDU/edit?usp=sharing

@jennmalcolm Any feedback?

**Comment by jennmalcolm** [comment]
I added my comments to the document.
