### ISSUE TITLE
Establish data publication schedule for FY19

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3332]
We have received the draft schedule for receiving data from DR for FY19. We need to fill in the column for when we will have the data published on NRRD.

[Data Publication Schedule](https://docs.google.com/spreadsheets/d/1u0NSMqA30UgRl92AQJ1fFfungmmRLxXe8wvc1wf_3M4/edit?usp=sharing) (limited access)

**Comment by jennmalcolm** [comment]
@brentryanjohnson I put some proposed dates for data publication in the schedule. Could you take a look and see what you think? I figured about a week to review the data and then two to update for each data set.

**Comment by brentryanjohnson** [comment]
I think it looks reasonable. I suppose we should remove "state level" from the UDR row, since it looks like that isn't going to happen.

**Comment by jennmalcolm** [comment]
Let's leave the state level on there as I haven't given up on that yet. If we can't publish it this year, then we can remove the requirement for next year. 

@NBrannberg we filled in our dates in the data calendar in case you're interested in reviewing. 

[Data Publication Schedule](https://docs.google.com/spreadsheets/d/1u0NSMqA30UgRl92AQJ1fFfungmmRLxXe8wvc1wf_3M4/edit?usp=sharing) (limited access)
