### ISSUE TITLE
Double-check LWCF appropriation numbers

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3333]
We're finding some discrepancies in the Land and Water Conservation Fund appropriation numbers. Let's resolve these before we publish the disbursements update for FY 2018.

**Comment by jennmalcolm** [comment]
@brentryanjohnson are you satisfied that this is complete?

**Comment by brentryanjohnson** [comment]
@jennmalcolm It might be prudent to have @lpgoldstein's contact at NPS take a look, but from our own research, I think we're as close as we can get.
