### ISSUE TITLE
CircleCI informs repo followers of failed builds

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3337]
I received several CircleCI build-fail emails to my personal email account, and it turns out CircleCI is now sending repository followers build-fail notices. So apparently anyone who follows our repo receives the notices.

We should prioritize a fix for CircleCI to deal with this.

**Comment by master12** [comment]
This is a user preference under notifications. The failing build is a sqlite3 lib. this will be fixed in gatsby transition
