### ISSUE TITLE
Explore sparklines for disbursements

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3341]
See #3326

![image](https://user-images.githubusercontent.com/38465926/47866694-dbc9ad00-ddd5-11e8-889e-ca1778a048ae.png)

**Comment by brentryanjohnson** [comment]
I've coded [a D3 sparkline](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/aml-spark/how-it-works/aml-reclamation-program/#the-aml-fund) in the [`aml-branch`](https://github.com/ONRR/doi-extractives-data/blob/aml-spark/_includes/sparkline.html) that we may be able to modify for this purpose @jennmalcolm @mcharg @master12.

**Comment by mcharg** [comment]
@brentryanjohnson Does D3 have a way to combine monthly and yearly data, such that we could have monthly data points for the more recent years and yearly data points for further back, but keep the years spaced out evenly?

**Comment by jennmalcolm** [comment]
We can run this design by some users in our next rounds of research to gauge reactions to the additional sparkline.

**Comment by jennmalcolm** [comment]
@mcharg should this be a part of #4721 or just closed given our new explore data shaping?

**Comment by mcharg** [comment]
It could be part of #4721.

**Comment by mcharg** [comment]
Closing in favor of new Explore Data.
