### ISSUE TITLE
Document manual processes for data management

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3344]

**Comment by mentastc** [comment]
Created a document for the data management process in drive here: https://docs.google.com/document/d/1_NYficPWCBol8smYYY-HLC9Qgf6eyogTure10nW30iw/edit?usp=sharing

**Comment by jennmalcolm** [comment]
@mentastc are you going to document the process for production datasets too? Then @lpgoldstein can add what she has for disbursements once that's final.

Should we move this to AngryAlligator?

**Comment by mentastc** [comment]
@jennmalcolm , the steps should be used for both production and revenue files. I updated one of the steps that was specific to revenue to include a production step.

**Comment by jennmalcolm** [comment]
Ok, @mentastc should we close this issue then?

**Comment by mentastc** [comment]
yes, I'll close
