### ISSUE TITLE
Mobile menu missing from GatsbyJS pages

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3349]
Our mobile menu is missing from the GatsbyJS pages:

- `explore`
- `about`

We should add header and utility navigation in the form of a mobile menu component for GatsbyJS.

![revenue data website interface animation showing missing mobile menu](https://user-images.githubusercontent.com/32855580/47945964-3ab92000-dec3-11e8-88e8-223dfe2f2542.gif)

**Comment by mcharg** [comment]
Isn't this what I kept bringing up in the review and you both told me it would resolve in the build?

**Comment by brentryanjohnson** [comment]
@mcharg That was a separate issue, if we’re talking about the same problem. We had a problem before where the icon wouldn’t be placed in the preview, only in the production build.

**Comment by mcharg** [comment]
@brentryanjohnson This is fixed, correct?

**Comment by master12** [comment]
Shoudl be

**Comment by brentryanjohnson** [comment]
Yes, it appears to be working as designed.
