### ISSUE TITLE
Add mobile review to release checklist 

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3350]
Our [production release checklist](https://github.com/ONRR/doi-extractives-data/wiki/Releasing-changes-to-production) doesn't include a review on specific viewports and what to check there. We should add a mobile/browser review to the checklist and make it part of our workflow.

**Comment by mcharg** [comment]
Related to #3535.

**Comment by Maroyafaied** [comment]
I added devices and browsers to check for on the checklist. https://docs.google.com/document/d/1Do-u6P3ZpgA_53_pdQZhNCT0SNSiPFIWCwsIeiLpe00/edit
