### ISSUE TITLE
Combine revenue by location files into one

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3355]
Let's look into combining the federal revenue by company data sets into one instead of three

**Comment by brentryanjohnson** [comment]
We discussed this with Data Retrieval on 11/15/18, and it sounds like they can help consolidate these into one file.

**Comment by mentastc** [comment]
Met with Andrew they will be using the new format for the FY2018 rev data file. 

New format is here: https://docs.google.com/spreadsheets/d/1YBKclvK8cAsvAVv9M14eJDQ7mYXlvGzqvMzeNycTlPk/edit#gid=668740044

**Comment by mcharg** [comment]
Done.  Has been handed off to Data Retrieval to consolidate the file.
