### ISSUE TITLE
Create download and docs page for monthly production data

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3363]
We have a new download and docs page and "tab" pattern for monthly revenue (#3358), but we need one for production as well. We can use a similar pattern to revenue.

**Comment by jennmalcolm** [comment]
This includes documenting the scope for the production data.

**Comment by jennmalcolm** [comment]
@brentryanjohnson for now could you just change one of the files so that we're consistent? In the near term, we should be going to a field each for month and year and get rid of the day, but we haven't completed that yet. It is part of #3385.
