### ISSUE TITLE
Initiate collaboration to have an IDM page on ONRResource

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3364]
Talk to web team and other team within IDM about creating a page for the program. Related to issue #3246

**Comment by mcharg** [comment]
@Maroyafaied On today's telework toolbox call, Pat Olshaw and Lori Yokomizo said they're in the process of reorganizing ONRResource, so it might be a good time to insert our section.  Let me know if you want me to reach out to them to see if we can get a new section added as part of the reorganization.

**Comment by Maroyafaied** [comment]
Sure , that would be great start, feel free to give them my contact information.

**Comment by Maroyafaied** [comment]
Chris and I have been added to Ektron, I need to arrange for training on the system. I'm also added to the web content team meetings and workshops.

**Comment by Maroyafaied** [comment]
Jennifer send an email to all the supervisors in IDM to designate a person on their team to help with this effort.

**Comment by Maroyafaied** [comment]
We got a couple of supervisors from IDM that responded to the email and designated a person to collaborate on this. Will create another issue for next step.
