### ISSUE TITLE
Create process for tracking bugs in PRs

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3365]

**Comment by mcharg** [comment]
One idea - use the checkbox feature in github to mark things off as fixed and retested.
![image](https://user-images.githubusercontent.com/38465926/48224324-67f44b00-e367-11e8-8114-f9d5781098d0.png)

**Comment by jennmalcolm** [comment]
@master12, do you think the check box system is working well for you? If so, we can close this issue.

**Comment by mcharg** [comment]
We're going to try tracking bugs as individual github issues this sprint.

**Comment by mcharg** [comment]
We're going to continue tracking bugs as individual github issues, so they can be prioritized individually.
