### ISSUE TITLE
SOL Discussion

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#3370]
Evaluate and Discuss lease/well level production data with the SOL, to ensure we can release the data via NRRD.

**Comment by jennmalcolm** [comment]
I talked to Ralph about this, and I think we may have enough already to know what we can publish. Let's discuss this @mentastc and maybe make a call to a contact at ONRR to confirm.

**Comment by mcharg** [comment]
@mentastc talked with the regional solicitor and it will be assigned, but not for a couple weeks.  Will open a new issue when they get back to us.
