### ISSUE TITLE
Final release changes to home page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3372]

**Comment by master12** [comment]
No problem. This is for disbursements?

**Comment by mentastc** [comment]
correct

**Comment by mcharg** [comment]
I do think combining the colors for onshore and offshore make sense.  Axure can't handle doing patterns on the bars.  @master12 Can you prototype something in the build for us to review?

**Comment by mcharg** [comment]
Either diagonal lines or dots with the dark color over the lighter color would be good.

**Comment by mentastc** [comment]
@jennmalcolm  @master12  @brentryanjohnson , good news we received the data needed to update the file and break out onshore & offshore,  for 2009-2011 the updated file is in the google drive folder NRRD Data. I didn't update the file name but the data inside should have the needed breakout.

**Comment by jennmalcolm** [comment]
Home page is live. Remaining bugs/updates are reflected in #3392.
