### ISSUE TITLE
Write documentation for GatsbyJS site

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3378]
We should write documentation for the GatsbyJS version of the site.

- How to install and instantiate the Gatsby site
- How to update data in the Gatsby site
- How we're using GraphQL to query data files
- CSS modules transition

Anything else, @master12?

**Comment by master12** [comment]
- How to create a component

**Comment by mcharg** [comment]
Closing in favor of the epic #3939

**Comment by mcharg** [comment]
Closing in favor of the epic #3939
