### ISSUE TITLE
Add scope and documentation to monthly production data

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3384]
I've added the page and nav for monthly production data in #3377, but we need to add the scope and documentation.

We can't merge the PR until the content is there, so I'm leaving #3377 WIP until we finish the docs.

**Comment by jennmalcolm** [comment]
@brentryanjohnson I know we merged #3377, but do you want to keep this open to add something about why the monthly numbers will not add up to the annual numbers like we discussed last week?

**Comment by brentryanjohnson** [comment]
@jennmalcolm Yes, I can do that. I may need you and/or @mentastc to help me think through the wording.
