### ISSUE TITLE
Standardize fields and formatting for spreadsheets

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3385]
We need to standardize the field names and formatting on our various source data spreadsheets. Here are some notes on what we discussed: 

Change date for monthly to Month and Year fields.
Land Category - Onshore Offshore
Need solution for Federal, Indian, 8g, GOMESA, Source Issue?
Authorization as an idea
Product vs Commodity
Same breakdowns (Sodium vs Sodium BiCarbonate, Soda Ash)?
Product is higher level, would prefer that for all our data sets
Capture hierarchical relationships?
State, Offshore Region, Region, CPS, Planning Area
Define consistent columns for geographic breakdowns

**Comment by mentastc** [comment]
Here is our proposed standardization, I sent it over to Data Retrieval and they will give there feedback: 

https://docs.google.com/spreadsheets/d/1YBKclvK8cAsvAVv9M14eJDQ7mYXlvGzqvMzeNycTlPk/edit#gid=668740044

**Comment by mcharg** [comment]
May get additional feedback from Data Retrieval, so leaving open.
