### ISSUE TITLE
Fix remaining homepage bugs

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3392]
Fix the issues that weren't show stoppers for the release.

On hover, the swatches in the table should change to the hover color.

- [x] Fixed

- [x] Tested

Table header for the month should have the year after the month name. (e.g. Mar 2018)

- [x] Fixed

- [x] Tested

Production charts aren't moving together on click.
- [x] Fixed

- [x] Tested

Could use a bit more space between the primary nav and tabs.
- [x] Fixed

- [x] Tested

Period drop-down is misaligned and missing the arrow on IE.  It does at least work, so users can get to the content, so I'm not putting this in show stoppers.
![image](https://user-images.githubusercontent.com/38465926/48629466-a8675080-e987-11e8-8500-89416ff33035.png)
![image](https://user-images.githubusercontent.com/38465926/48629478-aef5c800-e987-11e8-9f8a-2487e55a60fb.png)

- [x] Fixed

- [x] Tested

**Comment by jennmalcolm** [comment]
Update monthly data through most recent available.

- [ ] fixed 

- [ ] tested

**Comment by mcharg** [comment]
Underlines on links on hover in Firefox are misaligned.
![image](https://user-images.githubusercontent.com/38465926/48844858-0b326080-ed69-11e8-90b9-4d94b010d49e.png)

- [ ] Fixed

- [ ] Tested

**Comment by mcharg** [comment]
Make sure anchor links on Explore Data page are working correctly.  These have inconsistent behavior and often don't scroll to the correct place on the page.
- [ ] Fixed

- [ ] Tested

**Comment by jennmalcolm** [comment]
The download data link is not working from my iphone. I get a 404 error.

- [ ] Fixed

- [ ] Tested

**Comment by brentryanjohnson** [comment]
#3400 should fix the mobile download link, @jennmalcolm and @master12

**Comment by brentryanjohnson** [comment]
I marked ✅ fixed above: _Could use a bit more space between the primary nav and tabs_. It's included in #3441.

**Comment by mcharg** [comment]
Created #3453 for the anchor links.
