### ISSUE TITLE
Create/Print Outreach Business Cards 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/doi-extractives-data#3396]
Design NRRD business cards to hand out during outreach sessions. Cards will include url and email address as well as include a call to action. Issue will be closed when the cards are printed.

**Comment by lpgoldstein** [comment]
I've uploaded a few example cards. Looking forward to feedback. 
[NRRD Business Card Vertical 2.pdf](https://github.com/ONRR/doi-extractives-data/files/2631052/NRRD.Business.Card.Vertical.2.pdf)
[NRRD Business Card Vertical Blue Background 3.pdf](https://github.com/ONRR/doi-extractives-data/files/2631053/NRRD.Business.Card.Vertical.Blue.Background.3.pdf)
[NRRD Business Card 1.pdf](https://github.com/ONRR/doi-extractives-data/files/2631038/NRRD.Business.Card.1.pdf)

**Comment by lpgoldstein** [comment]
No call to action. Seemed to be too much.

**Comment by lpgoldstein** [comment]
Please give feedback @brentryanjohnson @Maroyafaied @mcharg @mentastc

**Comment by mcharg** [comment]
I think the blue one would stand out in someone's wallet more than the white ones and we need to add something that's a call to action to help us out by signing up for user research.

**Comment by Maroyafaied** [comment]
I like the information on the last link  with blue background but not sure what this link is supposed to go to "nrrd@onrr.gov".

**Comment by lpgoldstein** [comment]
creating a new issue that addresses printing
