### ISSUE TITLE
Fix withheld maps for states

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3407]
Withhelds aren't being handled properly. For example, county maps are being generated for withheld products in this PR for coal and potash in New Mexico.
![image](https://user-images.githubusercontent.com/38465926/49041381-1505fa80-f193-11e8-863c-2fdb4d740530.png)

![image](https://user-images.githubusercontent.com/38465926/49041362-0cadbf80-f193-11e8-8f87-1ce199022bd2.png)

Whereas in prod, withhelds do not generate charts or maps, but are rather listed below the maps.

![image](https://user-images.githubusercontent.com/38465926/49041396-1d5e3580-f193-11e8-9585-00648726a58e.png)

**Comment by mcharg** [comment]
Still an issue in #3408

**Comment by jennmalcolm** [comment]
Goal is to keep the charts and map but change the language that says there is no production for these areas when it is withheld.

**Comment by jennmalcolm** [comment]
To be considered as part of new explore data production cards.
