### ISSUE TITLE
Map isn't clickable on iPhone

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3410]
This issue is just to comment out the code that makes the map unclickable on small viewports.

Created #3426 to explore a zoomable map in the future.

**Comment by brentryanjohnson** [comment]
@mcharg The map has never been clickable on a phone viewport, presumably because many of the states would be virtually impossible to tap at that size. Previously and now, there is a select list to choose the location.

I think this is desirable, because it would be easy to inadvertently tap a state while scrolling down the page on a phone (if they were all active links).

**Comment by master12** [comment]
Actually I am not sure I agree with functionality all being the same at all viewports. I mean the menu is different. I dont think the map is a good thing at small viewports, but I also agree the dropdown is the not best idea either. 

If we did a more interactive map where the user could tap on the map and then the map would zoom into that region and then tap on the state. Would that be better?

**Comment by mcharg** [comment]
The issue isn't with having different functionality, but with having a map that looks the same and doesn't function the same.  With the menu, it's obvious that it changed because it looks different.  The map looks the same in both cases.  If the map isn't going to be clickable, it needs to look not clickable.

I do think it's worth exploring having a map that can be zoomed into.

**Comment by mcharg** [comment]
The zoomable map would also help people on desktop who want to click on a small state.

**Comment by master12** [comment]
I agree if the map is there it should behave the same. I gotcha

**Comment by brentryanjohnson** [comment]
@mcharg As far as how it behaved before, you can bring up an old branch preview and observe its previous behavior (e.g. https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/sankey-trial/). 

My phone is so small, I can't imagine being able to interact with that map via touch, at least most of it. Yes, perhaps breaking it into quadrants, with each quadrant being a touch target that zooms into that region, might work.

The map becomes static at the 768px break point.

I don't think we have a significant enough mobile user base right now to make this a high priority behavior, but I don't mind scoping it with lease-level. If we settle on a geographic pattern for lease-level, we'll likely need a zoomable map to get at that level of detail.

**Comment by mcharg** [comment]
I agree that we should look at this when we scope other map changes.

If it changes at 768, does that mean an iPad user gets a clickable map in landscape mode, but it's unclickable in portrait?

**Comment by mcharg** [comment]
I also think that people are used to pinching to zoom in on the browser on mobile to get to a clickable size (which is what my daughter did).

**Comment by brentryanjohnson** [comment]
Yes, @mcharg, that is exactly what happens on my iPad mini.

**Comment by mcharg** [comment]
That's really bad to change behavior on the same device.

**Comment by mcharg** [comment]
Is it an easy fix to comment out whatever code makes it unclickable and leave it up to the user to decide whether they want to click on the map?

**Comment by mcharg** [comment]
Then we can revisit zooming later.

**Comment by mcharg** [comment]
Addressed with new homepage.
