### ISSUE TITLE
We should only have one <main> element

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3417]
For accessibility, [we should only have one](http://adrianroselli.com/2015/09/use-only-one-main-on-a-page.html) `<main>` element on the homepage (and all others).

![code shows multiple main elements](https://user-images.githubusercontent.com/32855580/49124303-c3cc3880-f270-11e8-8bb1-796602f44d53.png)

**Comment by jennmalcolm** [comment]
Redoing accessibility audit in #4010, so we will get the full scope of work from there.
