### ISSUE TITLE
Missing Inspection Fees in Chart

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#3451]
Data retrieval didn't add that inspection fees are offshore in the data for January to September of 2018, this under represents offshore revenues by 38 million dollars for that time period. 

We need to update the download and the file feeding the chart to correct this error, see the screenshot for the blank cells that need to say "Offshore" 

![image](https://user-images.githubusercontent.com/15347998/49603622-c823e000-f959-11e8-884b-29d1f83242c3.png)

**Comment by mentastc** [comment]
Here is an updated file:
[monthly_revenue_10-2018.xlsx](https://github.com/ONRR/doi-extractives-data/files/2654349/monthly_revenue_10-2018.xlsx)

**Comment by jennmalcolm** [comment]
@mentastc, do you want to practice what we learned earlier this week and update the data file?

**Comment by brentryanjohnson** [comment]
@jennmalcolm Do you have time today? I think it would be good to fix this prior to release, so let me know if you don't have time, and I'll take care of it. :)

**Comment by jennmalcolm** [comment]
Yes, I'm working on it now.
