### ISSUE TITLE
 Outreach material for RMMLF conference on Feb 28

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3454]
Come up with ideas for a big visual to attract people to the outreach table. Jennifer suggested a pop up poster that is easy to travel with.

**Comment by Maroyafaied** [comment]
This is what I'm thinking for a visual, it's easy to travel with. Thoughts? @lpgoldstein @jennmalcolm 
https://www.vistaprint.com/signs-posters/retractable-banners?GP=02%2f05%2f2019+13%3a45%3a22&GPS=5305543963&GNF=1

**Comment by jennmalcolm** [comment]
Yes, these work pretty well for travelling. The big version is kind of heavy, so maybe we should go with a mid size. What do you think we should put on there? Maybe we can reuse some of the design elements from the brochure.

**Comment by lpgoldstein** [comment]
We need to decide what kind of sign we want to use - a talk to me/attention grabber sign or informational sign. Then we can decide on the level of detail.

**Comment by jennmalcolm** [comment]
I would say a talk to me/attention grabber. I don't think we need to put a lot of information on there. We have more info on our handout and card. Also, at the outreach tables, we can have our computers to actually walk people through the site.

**Comment by Maroyafaied** [comment]
another option that is meant more for a table display rather than a floor stand up,  so not as big as the first one. https://www.postupstand.com/table-top-display-24-x-40-narrow-base.html

**Comment by jennmalcolm** [comment]
The table top version is probably a good size to transport.

**Comment by lpgoldstein** [comment]
[TABLE TOP BANNER link on top.pdf](https://github.com/ONRR/doi-extractives-data/files/2866216/TABLE.TOP.BANNER.link.on.top.pdf)
