### ISSUE TITLE
Figure out Tribal Governance 404 page

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3459]
We've had a lot of visits (110 sessions in the last week) from Google to this 404 page in the last week.  Is there anything we can do to figure out how they're getting there and prevent the 404 error?

	
revenuedata.doi.gov/vpv404/how-it-works/tribal-ownership-governance//https://www.google.com/

**Comment by mcharg** [comment]
@brentryanjohnson Could this be related to changing tribal to Native American?

**Comment by brentryanjohnson** [comment]
It certainly could be, @mcharg. The path for that page changed to `https://revenuedata.doi.gov/how-it-works/native-american-ownership-governance/`.

When I changed these paths, I searched through the codebase to find all links. It's still showing we don't have remaining links to that path.

![Search results for tribal-ownership-governance](https://user-images.githubusercontent.com/32855580/49663391-5a33f300-fa03-11e8-90f2-9c8261856aa3.png)

That could mean the path is still indexed in google search, and users are linking to it for there. That will take care of itself at some point, but we could look at a redirect in the meantime. I'll take it up next week.

**Comment by mcharg** [comment]
Redirects would be good.  That way if anyone has old bookmarks to the page, they still get the content.  I noticed in the analytics that a few people came to it from a Blackboard site, so someone has it linked as part of a course curriculum.
