### ISSUE TITLE
Create ONRResource Data Display Page

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#3466]
Create wire-frame of data display ONRResource page, to be submitted to ONRR's web team for consideration and creation.

**Comment by mentastc** [comment]
I've created a wire frame that can be viewed here: https://docs.google.com/document/d/191UMAaQqONOF8ObXRRou3mvq4UyxsBq8LDLv-VhP4ck/edit

**Comment by mentastc** [comment]
@Maroyafaied will you look at the wire frame and make any edits

**Comment by Maroyafaied** [comment]
@mentastc  I looked at it back in December, the only comment I had was if it would be a  good idea to add the team members names and their role and mentioning nrrd@onrr.gov for comments and suggestions.

**Comment by mentastc** [comment]
Submitted to web team to create.
