### ISSUE TITLE
Obtain solicitor's feedback on lease level data

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3470]
When we receive feedback, address it.  See #3370 for previous tasks.

**Comment by mentastc** [comment]
SOL responded that they were backlogged due to shutdown.

**Comment by jennmalcolm** [comment]
@mentastc have we received a response yet?

**Comment by jennmalcolm** [comment]
We  need to start with the DOJ on lease level due to the RPC legal decision, so we will close this one for now.
