### ISSUE TITLE
Rewrite state page summary content

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3471]
Design content for state pages template redesign that works for all states.
 
Related to: #3277

**Comment by brentryanjohnson** [comment]
Contemplating adding a line for major commodity production and what portion of that production originated from federal lands in a given state.

![Wyoming state page mockup with summary data for production, revenue, and disbursements](https://user-images.githubusercontent.com/32855580/50104351-a5f25380-01de-11e9-9cc0-bcdc841f658a.png)

**Comment by brentryanjohnson** [comment]
I'm looking at content designs for state pages for which there is little or no production, revenue, or disbursements. These states generally fall into a few categories (or a combination of them):

- state has energy production, but no production, revenue, or disbursements from federal lands ([Maine, 2017](https://revenuedata.doi.gov/explore/ME))
- state has revenue or disbursements for a given year, but no production ([Indiana, 2017](https://revenuedata.doi.gov/explore/IN/))
- state has production from federal lands, but no revenue or disbursements for a given year

Here's what the summary content might look like for Maine (for example). Heavy use of passive voice here, so I'm going to work on the wording a bit. Also, using the word "reported" might imply there was data "not reported." I've used it here, because we use it elsewhere, but I'm going to revisit that wording, too.

![Sample mockup for Maine, showing no federal lands production, revenue, or disbursements](https://user-images.githubusercontent.com/32855580/50108091-39308680-01e9-11e9-86b1-157f9aa4fa17.png)

**Comment by brentryanjohnson** [comment]
Also, the word "represents" strikes me as odd in the federal land ownership box . We might want to rewrite that...It doesn't "represent" land; it is land.

**Comment by mcharg** [comment]
"1.1% of land in Maine is federal land." seems like a clearer way to say it.

**Comment by mcharg** [comment]
Do we need all the "probably"s or can we make real inferences about if there is no revenue that's why there's no disbursements?

**Comment by mcharg** [comment]
Without talking to users about what facts they find important, I guess it doesn't hurt to add the additional percentage to WY if it's easy to maintain.

**Comment by mcharg** [comment]
I wonder whether doing a Twitter poll about what facts people find important would violate PRA or if we'd be able to get people to respond to it.

**Comment by brentryanjohnson** [comment]
Starting sentences with digits can be difficult to read, but I really like the direction you're thinking about.

Here's an idea I've been considering:

![Image of Maine map and federal land accounts for 1.1 percent of all land in Maine](https://user-images.githubusercontent.com/32855580/50118281-1069ba80-0204-11e9-9a80-657abaefe0a6.png)

**Comment by brentryanjohnson** [comment]
The "probably" issue is one we should discuss with Jennifer, when she returns. It's my understanding that we may not have data for a variety of (rare) reasons besides no production or revenue, but I want to scope that further.

**Comment by mcharg** [comment]
I like what you have for the percentage.
