### ISSUE TITLE
Add map to state nav component

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3474]
The "miniature" state-highlight map is missing from the state page navigation.

We should add this back in to the new state page template.

## Production
![state map with navigation](https://user-images.githubusercontent.com/32855580/49817000-fae82280-fd23-11e8-8775-1e1ccf2d78b0.png)

## Gatsby state page template
![missing state map with navigation](https://user-images.githubusercontent.com/32855580/49817091-2cf98480-fd24-11e8-9ecf-3220be9804d0.png)

**Comment by mcharg** [comment]
This disappeared in the 8/19 release.
