### ISSUE TITLE
Update Monthly  November Production and Revenue Files

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#3479]
Update Monthly November Production and Revenue Files:

- [x] Check file adheres to format

- [x] Check file for obvious data issues

- [x] Check to ensure previous issue with land category isn't occurring

- [x] Upload Production File

- [x] Upload Revenue File

- [ ] Update Revenue Visual

- [x] Update Production Visual

**Comment by mentastc** [comment]
Attached are the two files to be added to the site and used to update the visuals
[monthly_revenue_11-2018.xlsx](https://github.com/ONRR/doi-extractives-data/files/2676525/monthly_revenue_11-2018.xlsx)
[Production Volumes as of 12_10_2018.xlsx](https://github.com/ONRR/doi-extractives-data/files/2676526/Production.Volumes.as.of.12_10_2018.xlsx)

**Comment by brentryanjohnson** [comment]
It looks like these files update the structure to include a month column and a year column. Consequently, I assume it will require some refactoring of the GraphQL query before we can ship the update, @master12 and @mentastc.

**Comment by mentastc** [comment]
@jennmalcolm I've updated the production file.

**Comment by mentastc** [comment]
Since the shutdown has occurred since this issue was created we now have updated monthly production file (to Oct 2018) and updated Revenue files (to january 2019) THOSE FILES ARE ATTACHED HERE:
[monthly_revenue_01-2019.xlsx](https://github.com/ONRR/doi-extractives-data/files/2829605/monthly_revenue_01-2019.xlsx)
[Production Volumes as of 02_04_2019.xlsx](https://github.com/ONRR/doi-extractives-data/files/2829606/Production.Volumes.as.of.02_04_2019.xlsx)

**Comment by jennmalcolm** [comment]
Opened #3582 for monthly revenue visual.
