### ISSUE TITLE
Document charts and text that need to labeled Natural Gas instead of Gas

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3486]
Also, suggestion from internal outreach to label charts as Natural Gas instead of Gas incase users confuse it with gasoline.

**Comment by jennmalcolm** [comment]
Yes, I think this is a good idea. It will be clearer for people who don't know a lot about oil/gas, as I'm sure some would think of gasoline when they see gas. Let's see if we can change it in our data files by working with Data Retrieval.

**Comment by jennmalcolm** [comment]
@Maroyafaied, could you document in this issue each instance where you think this needs to be changed?

Do you think that is should be changed in the downloads as well or can we assume that those downloading the files know more about the data and will understand gas?

**Comment by Maroyafaied** [comment]
@jennmalcolm  Yes, I can do that. I think it would be better to change it in the downloads to be consistent.

**Comment by Maroyafaied** [comment]
This is all the texts and charts where I found the word "gas" that should be changed to "natural gas" . This does not document download page or the files, I created another issue for those #3603,
https://docs.google.com/document/d/1s4ZRYbEhRVD_m64LklUTvdoDE-Ik9Z1Lv8CwkJm3eG8/edit
