### ISSUE TITLE
Finalize OLT agenda

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3488]
I have created a draft agenda for the OLT meeting on February 20th. @jennmalcolm please review and assign a person to each topic.
this is the draft agenda, will need @jennmalcolm to review and assign who will discuss each topic. https://docs.google.com/document/d/1Pm1q7ve9pZhhBDA9K_qwSTz_SzPftmwNPFWypoohkR8/edit

**Comment by Maroyafaied** [comment]
I still don't have the dates for the OLT meetings in March or April but this is the draft agenda. @jennmalcolm please review and we need to decide who will discuss each topic. https://docs.google.com/document/d/1Pm1q7ve9pZhhBDA9K_qwSTz_SzPftmwNPFWypoohkR8/edit

**Comment by jennmalcolm** [comment]
I made a few changes with suggestions for possible presenters. We will have to see when we can get on the agenda and who is available to present before we finalize that, but  I think you can close this issue for now. Once we get closer to the presentation, we can make assignments and put the presentation together. Thanks.

**Comment by Maroyafaied** [comment]
Sounds good, thanks!
