### ISSUE TITLE
Final approval for IDM's page on ONRResource

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3489]
This is related to issue #3452 , @jennmalcolm all the IDM teams gave input but haven't heard from Data Retrieval. Please review before I send it to the web team.

https://docs.google.com/document/d/1GEeXKfneCRVXi_7U2BbUmgzDXMVcnkXtspkIzaJi3f4/edit

**Comment by jennmalcolm** [comment]
I made a few changes, and it's ready to send to the web team. Thanks @Maroyafaied.

**Comment by Maroyafaied** [comment]
I send the final proposal to the web team this morning. I will close this issue and create another one if needed.
