### ISSUE TITLE
Plan user interviews for production filterable table and lease level data

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3499]
Will start with plan created as part of training.

**Comment by mcharg** [comment]
Let's wait until after we have an answer on location/mapping data to do this.  We can either build a prototype using the data we have or use the Publish What You Pay site to probe into user needs if we think we have the data to do something similar.

**Comment by mcharg** [comment]
Blocked until after the design studio.

**Comment by jennmalcolm** [comment]
@mcharg should we keep this issue open? I think it has it been superseeded by the need to test our builds in progress since it may be a while before we get to focus on lease level data again.

**Comment by mcharg** [comment]
We can close this one and open a new one when we get to it, since the production tables will likely be tested before we get back to lease level stuff.
