### ISSUE TITLE
Create logic to drive state page restructure

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3512]
Next step from #3277

**Comment by brentryanjohnson** [comment]
## Notes on state intro logic research

These notes relate to evaluating the portion of commodity production in a state from federal lands compared to all lands in the state. This approach requires continued use of the [EIA data](https://www.eia.gov/) via API.

### Method
- Evaluated states with high relative share of federal commodity production to overall production in the state (e.g., Wyoming) versus states with high overall commodity production but lower federal production as a percentage (e.g., Texas). So in Wyoming, the share of coal production from federal land is between 82% and 86% of total, while in Texas, the share of federal oil production is 0.02%.

- The goal is to evaluate whether it makes sense to maintain nation-wide, all-lands production for context (we’ve heard this from time to time from users). This would allow us to retain the context, without the confusion that resulted from charting all national production figures along with federal production

- Some commodities don’t work: for instance, geothermal units are a problem

### Questions
- What to do about states that only have mineral production? Any QUARTZ CRYSTAL (tickets/pounds) fans out there?

- Is “crude oil” as defined by EIA the same as “oil” as defined by ONRR? Are there oil products rolled up in one or the other that complicates the comparison?

### Alternatives
- We could simply list the commodities the state produced in the intro (for those that produced commodities)

- Offshore is all federal, so we'll need a different pattern regardless of what we decide for states

- We could simply eliminate the summary and get into the date (if there is any)

- The choropleth will provide summary data up front...we may not need dedicated state pages at some point. For instance, we could toggle summary state data when that state is selected on the map, assuming we pare down the content.

**Comment by brentryanjohnson** [comment]
Closing in favor of #4231.
