### ISSUE TITLE
Review Native American revenue data

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3516]
Complete review of Native American revenue data after receiving from DR.

**Comment by mentastc** [comment]
Attached is the Native American revenue data for FY18 that has been reviewed, they only did the one year and I feel like we need a bigger data set. I can't remember if we agreed to just one year or if there's some other reason (dang shutdown).
[Native American Revenues FY 2018 (1).xlsx](https://github.com/ONRR/doi-extractives-data/files/2818523/Native.American.Revenues.FY.2018.1.xlsx)

**Comment by mcharg** [comment]
I thought we wanted to get more historical data because we currently only have back to 2013.

**Comment by jennmalcolm** [comment]
Yes, @mcharg, that would be ideal, and I thought DR had said that would be possible. As they catch up, maybe we can just update with 2018 and give them some time to get back to the historical data.

**Comment by mentastc** [comment]
So in the email they said they pulled this data a bit differently which makes it in line with how they pull all our other revenue data.

**Comment by jennmalcolm** [comment]
Check with DR to see if you can get 10 years before we close this issue and update the data.

**Comment by NBrannberg** [comment]
Yes, we can pull ten years.  Andrew will be the lead on this data.

**Comment by jennmalcolm** [comment]
Thanks @NBrannberg and @hasketta, I'm sure this is a busy time post-shutdown, and we appreciate your extra effort to help us provide complete and consistent Native American data sets.

**Comment by mcharg** [comment]
@NBrannberg @hasketta Will we be able to get both FY and CY data for Native American revenue?  Once we have the filterable tables, it'll be important to have consistency across all data that's included in the table.

**Comment by mcharg** [comment]
See #3881 for FY data, but we still need the CY data.

**Comment by mcharg** [comment]
@mentastc Is this one done now that we have the CY file?
