### ISSUE TITLE
Determine how to handle sales year data

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3517]
We have received sales year data from DR. We need to determine:

What's the MVP?
How do we document what this data set is and difference?

This issue will be complete after the following are done

- [x] Come up with a proposal on how to incorporate sales year data on NRRD
- [x] Present the proposal to the team for any feedback 
- [x] Receive approval from product manager
- [x] Create follow-on issue(s) for implementation

**Comment by mentastc** [comment]
Shared proposal with Data Display team for feedback here: https://docs.google.com/document/d/1_IxiaKoG2tsAEI4k13arWdIm4nd2_tI4gEMzNc0nR-A/edit?usp=sharing

**Comment by mcharg** [comment]
How sales data works:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/af0fb9b5-8a99-4060-a6fe-5a790ceabf23)

**Comment by mcharg** [comment]
Updated:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c074ee7b-f275-4dbb-acb9-c2ed1b3ba5b7)

**Comment by mentastc** [comment]
Follow on issues are #3744 & #3743
