### ISSUE TITLE
Create a design pattern to label year types

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3518]
How do we label sales year, production year, accounting year?

**Comment by mcharg** [comment]
Here's one idea I'm incorporating into the lease level data design.

![image](https://user-images.githubusercontent.com/38465926/51926743-f5bc6100-23bf-11e9-8d15-4a41efa5fd0f.png)

**Comment by mcharg** [comment]
I took this out of the production prototype and put it in the revenue one, since it makes more sense there.  We can test it with users when we test the revenue prototype.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/fc6954e1-7261-4dea-a92b-10f6738d10c6)

**Comment by jennmalcolm** [comment]
@mcharg are we going to skip this in the new revenue table? I don't see it in that design. Also, "data uses" seems a bit confusing. I think "data type" would make more sense.

**Comment by mcharg** [comment]
I did change it to Data Type, but forgot to put it in the last iteration of the design.  I think it's a low priority, but we should put it in at some point.  There is an issue (#3912) to add it.
![image](https://user-images.githubusercontent.com/38465926/56906648-b2ca6200-6a70-11e9-95e1-2ec96d843b15.png)

**Comment by mcharg** [comment]
I added it back into the new design: https://t81vx1.axshare.com/#g=1&p=revenue_table_-_stats_plus

**Comment by jennmalcolm** [comment]
So I think this issues is done. Do you agree @mcharg?

**Comment by mcharg** [comment]
Sure
