### ISSUE TITLE
Proposal for US Association of Energy Economics Presentation Prep

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/doi-extractives-data#3522]
http://www.usaee.org/usaee2019/
Conference will take place November 3-6, 2019. 
Proposals not due until May

Government Track session on government data/statistics at the Denver conference (with ONNR data as one of the sub-topics)
Possible ONNR "booth" or display of some sort at a reception.  (If that happened, presumably, the session would be Monday sometime, and with a conference-wide reception that evening.  EIA would likely have an exhibit/booth as well.)  

Panel members would be expected to be registered attendees, but that might not be the case for everyone involved with the booth.

The committee hasn't decided on the exact topic and panel makeup yet, but someone from EIA might be on the panel, or the topic could energy-related statistics other than those collected by EIA.  Other possible sub-topics could be state-held data and a developing tri-lateral website (U.S., Canada, and Mexico).

**Comment by jennmalcolm** [comment]
This issue will be to put the proposal together.

**Comment by lpgoldstein** [comment]
Moving this issue to backlog/next sprint again. I spoke with Kim and we won't need to submit a formal presentation by the deadline that is listed on the website. The government track is less formal and have the same submission requirements and they will send us a speaker confirmation letter that will allow us to us to register at the discounted rate. I will begin participating in the planning sessions so we can stay updated.

**Comment by jennmalcolm** [comment]
@lpgoldstein do we need to do a proposal at all? I just want to make sure I'm clear on what this issue is. If we don't need to do a proposal, perhaps we close this and then open an issue to develop the presentation when that's appropriate.

**Comment by jennmalcolm** [comment]
We don't need to do a proposal, so I'm closing. We will open an issue to prepare the presentation when we are closer to the conference.
