### ISSUE TITLE
Due 2/25: DotGov Design proposal

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3523]
DotGov Design is looking for speakers for our bi-annual conference in May 2019. Speakers do not need to be working in the government space to present, but topics should be relevant to designers working within and around the context of government. Pitches relevant to local, state and federal government are welcome.

The deadline to submit a pitch is Monday, February 25!

Submission link:
https://dotgovdesign.typeform.com/to/Nmw6OY

Q&A:
https://dc.aiga.org/programs-initiatives/dotgovdesign/

Conference date and location:
May 6th at USPTO in Alexandria, VA

**Comment by mcharg** [comment]
Not sure what to propose for this.  Maybe something around designing open data to be tailored to your users, since the Open Data Act was just passed, there will likely be experience designers newly interested in that topic.

Conference audience:
DotGov is focused on advanced and in-depth content around design in government, so while the conference is open to every level, the majority of the audience will be practiced designers, thought leaders, academics, and beyond. 

Available formats:
Talk: A 60 minute lecture or interactive session presented by one or two speakers. We recommend planning for 45 minutes of content, 10 minutes of Q&A, and 5 minutes each for set-up and wrap-up.
Lightning Talk: A 10-15 minute brief presentation with a single presenter. This session type will likely be grouped back-to-back with other talks and include a potential Q&A at the end of a full session of lightning talks.
Panel: A 45 minute small group of people brought together to discuss, investigate, or decide on a particular topic, moderated by a single individual. We recommended 25 minutes of moderator-prepared questions, 10 minutes of audience-driven questions, and 10 minutes for set-up and wrap-up.
Unconference Session: 30 minute, informal sessions to discuss relevant topics with a small group of attendees.
Workshop: A highly interactive 90 minute session featuring small group exercises lead by one or two individuals. We recommended 60 minutes of activities, 15 minutes of reflection, and 15 minutes for set-up and wrap-up.

**Comment by mcharg** [comment]
Working draft:
https://docs.google.com/document/d/1BUasFpOgwULivqcdnYQBKdXei73lFF7-WeZp0FieAi0/edit

**Comment by mentastc** [comment]
@mcharg there wasn't much I felet needed to be added so I added some additional background text, feel free to take it or leave it.  Jennifer said that she would present.

**Comment by mcharg** [comment]
@jennmalcolm This one's ready for you to review.

**Comment by jennmalcolm** [comment]
Looks good. I made a few suggestions in the document.

**Comment by mcharg** [comment]
Submitted
