### ISSUE TITLE
Due Feb 17: Government UX Summit proposal

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3524]
I'm thinking we could propose something around training non-UX people to conduct user research and talk about how I've been training Maroya and Lindsay.
---
We are looking for presenters for the 2019 Government UX Summit, which will take place at the Bureau of Labor Statistics on May 15, 2019 from 9 am to noon.  This is a great opportunity to share your experience and lessons learned with your government UX colleagues.
 
Last year we had approximately 160 attendees, attending in-person and remotely, with registrations from more than 80 government agencies!  We are looking forward to another great UX Summit again this year!
 
Participation is open to government employees (all levels) and contractors with government email addresses.  Registration is FREE for remote and in-person attendance. 
 
The UX Summit covers topics related to User Experience work in the government.  Topics appropriate for presentation include, but are not limited to:
 
Design and/or evaluation methods, either basic or more advanced methods (especially more applied topics, such as training with a particular method)
Case studies of user experience projects or programs
UX tools
Starting and/or building a government UX program
Lessons learned in managing a user experience program
Government-specific challenges and obstacles
UX and Agile
Using UX to innovate
UX Research
 
Attendees at the summit will have a range of experience in UX.  If you’re interested in presenting, please send your proposal, which should include:
 
The presenters and their affiliations
Contact information for the primary presenter
Title
250 word (or so) abstract describing the presentation and what the attendees will learn
Target audience for the presentation (e.g., novice or experienced, technical vs not)
150 word (or so) description of why you are qualified to give this presentation
 
Submissions will be due roughly mid-February, but we will revise the deadline as needed.
---
I think we just email Jean Fox (Fox.Jean@bls.gov) to submit the proposal.

**Comment by Maroyafaied** [comment]
This is the first draft (limited access), I left the presenter information and qualifications blank till we know who is presenting. 
https://docs.google.com/document/d/1b8gVL3GrycuCd49Cx9nzrSBYBpRgja-4Q5JVWthYcJI/edit

**Comment by Maroyafaied** [comment]
@jennmalcolm  can you give this proposal a final review before we send it? Thanks https://docs.google.com/document/d/1b8gVL3GrycuCd49Cx9nzrSBYBpRgja-4Q5JVWthYcJI/edit

**Comment by jennmalcolm** [comment]
Looks good to me.

**Comment by Maroyafaied** [comment]
I send the proposal via email to Jean Fox. Closing this issue.
