### ISSUE TITLE
Investigate adding "and water" to revenue titles that include "federal land" to improve clarity

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/doi-extractives-data#3529]
We received an email that indicated some confusion regarding wind revenues. See direct quote below and screen shots. Identify text where "and water" should be added and update accordingly. 

https://revenuedata.doi.gov/explore/#federal-revenue
"Wind is listed under offshore renewable energy under federal revenue by phase but listed as being on federal land under federal revenue trends by resource."
Section: 
![image](https://user-images.githubusercontent.com/39419003/51928649-62395f00-23c4-11e9-9cca-a6cbc411d160.png)

![image](https://user-images.githubusercontent.com/39419003/51928451-fc4cd780-23c3-11e9-8ab1-2e1b1f3cca11.png)

**Comment by jennmalcolm** [comment]
We'll change these two instances to handle this issue.
