### ISSUE TITLE
Widen the site

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3531]
We stop expanding the width of the site at about 980 px.  We should look at the analytics to see if a large number of users are on wider screens and widen the maximum width to 1200 px or higher.  Given the number of columns in the tables for lease level data, we will have a lot of horizontal scrolling at the current site width and widening the site would reduce that for people on large monitors.

**Comment by brentryanjohnson** [comment]
It's worth exploring increasing our max-width, but we should also keep in mind research related to [optimal line length for readability](https://practicaltypography.com/line-length.html). We could look into allowing images, tables, maps, etc., to occupy more horizontal space while constraining paragraphs for comfortable reading.

**Comment by mcharg** [comment]
Definitely.

**Comment by jennmalcolm** [comment]
This issue will be to review the analytics and make a decision for going forward.

**Comment by mcharg** [comment]
We decided to widen to 100% width as part of the Explore Data redesign.

**Comment by jennmalcolm** [comment]
This issue will be for @brentryanjohnson and @mcharg to review what is built in MUI so far with @jlouis-onrr.
