### ISSUE TITLE
Fix blog analytics

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3533]
The blog config file contains the same analytics variable declarations as the site, but it doesn't appear to be firing. I suspect this is because the DAP code is missing.

The blog uses the `gatsby-plugin-google-analytics` plugin, so its implementation is different than that of the main gatsby configuration for the rest of the site.

**Comment by brentryanjohnson** [comment]
Reopening because blog analytics are still broken.

**Comment by brentryanjohnson** [comment]
I've confirmed the blog is generating analytics, but it is also (along with the main site) generating duplicate script source tags for the main analytics script. Changing the scope of this issue to deal with cleaning up script source tags.

**Comment by mcharg** [comment]
Could the duplicate script source tags be inflating the analytics?

**Comment by brentryanjohnson** [comment]
@mcharg No, it shouldn't inflate the analytics, since the duplicate script is for the google analytics library code. That should just be the reference "toolkit" to make analytics work; not the script that actually harvests the data.

**Comment by brentryanjohnson** [comment]
Closing this issue (since the blog analytics are working); I've opened #3672 to deal with the duplicate script instances in both the blog and main site.
