### ISSUE TITLE
Develop release review protocol

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3535]
- Come up with review protocol for release review (i.e. distribute sections of the site, someone verify data)
- Document in Wiki

**Comment by Maroyafaied** [comment]
This is the proposed checklist for release review. I will close this issue and create another one to publish on wiki. 
https://docs.google.com/document/d/1Do-u6P3ZpgA_53_pdQZhNCT0SNSiPFIWCwsIeiLpe00/edit
