### ISSUE TITLE
Review and Publish blog post for User Testing Training

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3537]
Related to issue #3437 . The draft is created, we need to review it and publish it.

**Comment by jennmalcolm** [comment]
I did a review and added my suggestions and comments in the Google Doc. Most of the suggestions relate to getting rid of passive voice in spots.

I think it is looking pretty good.

**Comment by brentryanjohnson** [comment]
Looking great! I added some comments and suggestions yesterday, and I'm happy to help format it for the blog, if needed.
