### ISSUE TITLE
Test tools to replace Waffle

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3567]
https://www.zenhub.com/
https://github.com/features/project-management/

**Comment by mcharg** [comment]
Zenhub Board: https://app.zenhub.com/workspaces/doi-extractives-data-5464fa79c3cc8d7f4c384eaf/boards?repos=21627244

**Comment by mcharg** [comment]
GitHub Project: https://github.com/orgs/ONRR/projects/1

**Comment by mcharg** [comment]
I think I have enough in ZenHub to evaluate whether it's more useful than Waffle.

https://app.zenhub.com/workspaces/doi-extractives-data-5464fa79c3cc8d7f4c384eaf/boards?repos=21627244

Pros:
- Has the ability to add releases and epics to better track those.
- Has the ability to add sizes (but doesn't port from Waffle, so we have to add them again)
- More robust reporting than Waffle

Cons:
- Doesn't automatically put things in columns based on labels the way Waffle does (at least I haven't found a way to do it).  I had to manually put everything except the closed stuff in columns.

If we like this, we should consider testing it out in Thursday's backlog grooming meeting.  Note: Anything we do either in here or Waffle doesn't carry to the other tool.

@brentryanjohnson @Maroyafaied @jennmalcolm Thoughts? I put in the releases that are in the roadmap and a couple of epics and a few sizes for stories.
@lpgoldstein You may also want to take a look at the reports to see if they're better for your metrics work.

**Comment by Maroyafaied** [comment]
@mcharg for the con you mentioned on Zenhub, it says in the tutorial that you have to do it manually but you can select more than one at a time. "You can also organize Issues on the Board using multi-select. Enter multi-select by clicking on the avatar photo of any Issue. A multi-action toolbar will appear on the top right of the Board. Select the Issues you’d like to move, then use the Move to Pipeline option to move multiple Issues at once."

**Comment by mcharg** [comment]
Multi select is also a pro. It made it easy to pick a bunch of stuff to add to a release.

**Comment by mcharg** [comment]
I don't think GitHub projects is going to solve any problems.  They have some automation in moving between columns, but they're missing the ability to add size, release, and epic and don't really have reporting capability.

https://github.com/orgs/ONRR/projects/1

**Comment by mcharg** [comment]
I have a call schedule with ZenHub on Tuesday to walk through out setup and get feedback and, hopefully, to find out whether we can fix the label issue.

**Comment by mcharg** [comment]
They thought it was a permissions thing preventing the label edits, but that doesn't appear to be the case.  She took a screenshot of errors being thrown when I change labels and will have her dev team look into it.  She said this is an anomaly and they should be able to get it to work.
