### ISSUE TITLE
Due 2/6: Open Government Partnership Global Summit proposal

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3571]
The 6th Open Government Partnership Global Summit will be in Ottawa, Canada, from May 29-31, 2019. You are invited to submit proposals to organize sessions or participate as a speaker.

The deadline to submit proposals is February 6, 2019. Please consult the Call for Proposals Guide to ensure that your proposal has the best chance possible of being selected. Note: each person can submit a maximum of two proposals and speakers will participate on a volunteer basis.

An editorial committee will evaluate proposals and build a final agenda. If your session proposal is selected, you will be notified by email by early March. If a session organizer selects you from the database of individual speakers, they will contact you in March or April. Please note that we expect the selection process to be very competitive. We will only contact session organizers that have been selected.

Registration to attend the OGP Global summit will open early in 2019. Contact summit@opengovpartnership.org with any questions. Thank you for your interest in the OGP Global Summit!

https://ogpsummit.org/en/summit-program/call-for-proposals/guide

**Comment by jennmalcolm** [comment]
That sounds like a stretch. Let's let this one go by. After I find out about more about international conferences, we can consider adding this back in to our plan for next year.
