### ISSUE TITLE
Add more space between home page production graphs

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3573]
When I make my window smaller, the production commodity graphs get too close together. We could just add more padding between them or make the third graph go below sooner.

![image](https://user-images.githubusercontent.com/30806839/52224160-555db500-2875-11e9-9e0b-0a077d57b8cc.png)

![image](https://user-images.githubusercontent.com/30806839/52224332-bb4a3c80-2875-11e9-8358-52dbc99df8fa.png)

**Comment by jennmalcolm** [comment]
This is in Chrome.

**Comment by mcharg** [comment]
@jennmalcolm Did you hit refresh after resizing?  Sometimes the responsive changes don't take effect unless you refresh.

**Comment by jennmalcolm** [comment]
I had not hit refresh, but I just did with this screenshot. It doesn't look as bad as the ones earlier, but I still don't like how all of the graphs squeeze together to look like one. This is not a huge priority, but make it so they all don't merge, I think it would be easier for users to differentiate what they're looking at.

![image](https://user-images.githubusercontent.com/30806839/52226712-b7b9b400-287b-11e9-94e4-61f7b0366c47.png)

**Comment by mcharg** [comment]
Definitely agree.

**Comment by jennmalcolm** [comment]
Also a problem with rotating at phone.

**Comment by jennmalcolm** [comment]
This is what it looks like on the horizontal view on my iphone 6s. 
![image](https://user-images.githubusercontent.com/30806839/52789984-69eb3b80-3033-11e9-8f8c-5fc76a0fbfcf.png)

**Comment by jennmalcolm** [comment]
Checked the width when shrinking my window, and the lines merge with widths between about 765 and 1020px. The graphs still look a little close to me until about 1060px.

**Comment by mcharg** [comment]
@mojobnichols Can you try to fix this when cleaning up the responsive/mobile views on the new homepage?

**Comment by mcharg** [comment]
Can be addressed as part of #4474 if it's still an issue on the new homepage.
