### ISSUE TITLE
Determine content strategy role for timeline and enact

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3583]
There is a [timeline on the about page](https://revenuedata.doi.gov/about/) that we haven't updated since we last updated the USEITI executive summary.

We should determine the role of the timeline post-EITI. Here are some questions we need to answer first:

- Is the timeline specific to the EITI era of the site?
  - Should we archive it accordingly, with the rest of the USEITI content?
- Is the "What's new" section on the homepage a viable replacement for the timeline for the current iteration of the site?
  - Should we archive the "What's new" section entries?
  - Are our [release notes](https://github.com/ONRR/doi-extractives-data/releases) sufficient to serve as our "What's new" archive?

**Comment by mcharg** [comment]
At one point I was going to suggest replacing it with the timeline graphic from the brown bag.

**Comment by mcharg** [comment]
![image](https://user-images.githubusercontent.com/38465926/52285517-79cc9680-2934-11e9-8682-0865818c7c6d.png)

**Comment by brentryanjohnson** [comment]
That's a good idea, @mcharg, but if we do that, we should create it with markup. It's too much content to make it properly accessible and responsive as an image.

**Comment by jennmalcolm** [comment]
I don't think adding a replacement is necessary. What's more important is to evaluate the role of this page in #3584. Moving it as part of the archive design in #3539 should take care of this issue.

**Comment by jennmalcolm** [comment]
We are moving the timeline to the archive and closing this issue.
