### ISSUE TITLE
Perform privacy threshold analysis for NRRD

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3597]
Rich will be sending the template, and we will need to work with him to work through filling it out.

**Comment by mentastc** [comment]
Started work in the template but we were told we no longer needed to do it. the work is in the drive here: https://docs.google.com/document/d/1e4a_OMRdM-VSCZpqfgTadNxhyFB5q962QJ8FI4UgXos/edit?usp=sharing

**Comment by jennmalcolm** [comment]
We can close this for now, so we are no longer supposed to complete this.

**Comment by jennmalcolm** [comment]
Opening back up since we have to do it again.

**Comment by mentastc** [comment]
@jennmalcolm you can review the form in the link above.

**Comment by jennmalcolm** [comment]
Took a look but couldn't edit, so I sent you my comment. Now you can talk to Rich to see what he thinks.
