### ISSUE TITLE
Change content from gas to natural gas in all charts and texts

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3603]
Relates to issue #3486. link to documented all text and charts that need to be changed from gas to natural gas, this does not include text or files in the download section.

https://docs.google.com/document/d/1s4ZRYbEhRVD_m64LklUTvdoDE-Ik9Z1Lv8CwkJm3eG8/edit

**Comment by brentryanjohnson** [comment]
Step 1: I'll work with @master12 to figure out the best way to create an alias, so we don't have to change the source data. Partially dependent on #3659.

**Comment by Maroyafaied** [comment]
We decided not to move forward with this change.
