### ISSUE TITLE
No county-level data for Wyoming commodities

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3608]
We should figure out why there's no county-level data shown for Sodium Sesquicarbonate and Trona Ore for Wyoming. The data is there, so it shouldn't be an issue with withheld data.

If there is an explanation given the data, we should consider a different approach to the map or content that explains why there isn't any data mapped by county.

![Wyoming map shown with no counties displaying data](https://user-images.githubusercontent.com/32855580/52498665-41c09000-2b8e-11e9-966a-74aa32f55898.png)

**Comment by jennmalcolm** [comment]
no longer an issue
