### ISSUE TITLE
Add monthly disbursements data to home page graph

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3617]
We should be receiving monthly disbursements data 2/15.

We need to change the disbursements chart on the home page to accommodate the monthly data. It should be designed like the production and revenue charts.

**Comment by mcharg** [comment]
@master12 Do you need a wireframe for this or can you just copy what we have for revenue?  I took a look and there won't be any differences for disbursements.

**Comment by mcharg** [comment]
@jennmalcolm We probably also need to think about updating the downloads page to reflect that we'll now have monthly data.

**Comment by jennmalcolm** [comment]
Yes, @mcharg that should be a separate issue. I just created one at #3619.

**Comment by mcharg** [comment]
I'll do a wireframe, since we only have back to October 2018.  We'll need to think about whether we display the months without data as empty or adjust the graph to only show the months we have.

**Comment by mcharg** [comment]
The design is Option B on this page:
https://u7sqr1.axshare.com/#g=1&p=monthly_disbursements_options

**Comment by lpgoldstein** [comment]
[1Q Total Web Data Disbursements 022019.xlsx](https://github.com/ONRR/doi-extractives-data/files/2894966/1Q.Total.Web.Data.Disbursements.022019.xlsx)

**Comment by mcharg** [comment]
Note: We had slated this for Cobbler, but I think we need to move it up to Peeps if we're going to be expected to have the monthly disbursements on the site when the press release goes out.

**Comment by jennmalcolm** [comment]
@mcharg, we might need to think through some other options for providing this data on the site because I don't think the monthly graphs will work well.

**Comment by mcharg** [comment]
I forgot that there’s no GOMESA breakout on the bar charts.  What if we add a 4th breakout for that? @jennmalcolm

**Comment by jennmalcolm** [comment]
The timing would still be an issue. I think it would be strange to have part of the data for April before we even have the data for March. We can discuss our options more when we add this to a sprint. I think we need to create a separate issue for figuring out the GOMESA data.

**Comment by mcharg** [comment]
OK. I’ll need to see what the GOMESA data is going to look like.  I thought it was going to be I. The regular monthly data file.
