### ISSUE TITLE
Update downloads page to add monthly disbursement data

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3619]
We need to update the scope on the disbursements download page to reflect our addition of monthly data. We should get the data 2/15/19.

**Comment by lpgoldstein** [comment]
Closing this because we opened issue #3654 when we couldn't find this issue.

**Comment by jennmalcolm** [comment]
@lpgoldstein this issue also requires changing the architecture of the disbursements download page and including scope info. I thought I opened one similar to #3654, but that must have been in my dreams. I'm going to open this one back up because this will be the next step once #3645 is done.

**Comment by lpgoldstein** [comment]
[1Q Total Web Data Disbursements 022019.xlsx](https://github.com/ONRR/doi-extractives-data/files/2894965/1Q.Total.Web.Data.Disbursements.022019.xlsx)
