### ISSUE TITLE
Build Offshore Page in Gatsby

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3620]
https://revenuedata.doi.gov/explore/offshore-alaska/

**Comment by brentryanjohnson** [comment]
I assume this is done, since we no longer have a Jekyll build.

**Comment by mcharg** [comment]
@brentryanjohnson We left this one open because @master12 didn't finish converting the page and it's mostly static right now.

**Comment by mcharg** [comment]
Reopening because the pages are still static.
