### ISSUE TITLE
Write blog post about becoming a product manager

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3630]
I think a post about how @jennmalcolm became product manager for our team and site would be an awesome read.

What do you think, @jennmalcolm?

**Comment by jennmalcolm** [comment]
I won't commit to awesome, but I will commit to writing something.

**Comment by jennmalcolm** [comment]
[Draft blog post](https://docs.google.com/document/d/1LJTF9TDdNyccRCwuoNDXi-Gjte7cNEcVX5b_tH0BVhY/edit) (limited access)  

Review and publication will take place in #3722
