### ISSUE TITLE
Broken Link: The last link on Native American Ownership

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3634]
This is in both production and #3540.  The page we're linking to doesn't appear to exist anymore.
https://teeic.indianaffairs.gov/abouttera/
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/7ee52ae9-c760-4da9-928d-9a519ab807f9)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/fc1b1e5f-fafd-48d4-b85e-8cd8d96d722a)

**Comment by master12** [comment]
DO we have a new link? Or do we want to remove the link?

**Comment by mcharg** [comment]
@brentryanjohnson Thoughts on whether we should remove the broken link or find a new one?

**Comment by brentryanjohnson** [comment]
@master12 and @mcharg Let's just remove the last line containing the link. I'm discovering some additional needs for this page, so I may add a different link later.

**Comment by mcharg** [comment]
Fixed in 3540
