### ISSUE TITLE
Determine if we should update Native American governance content

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3642]
In exploring options for a broken link on [Native American governance](https://revenuedata.doi.gov/how-it-works/native-american-ownership-governance/), I noticed [amendments have been passed](https://www.congress.gov/bill/115th-congress/senate-bill/245) to the Indian Tribal Energy Development and Self-Determination Act.

We should research the scope of the amendments and determine if we should edit/add to this page's content.

@jennmalcolm I've tentatively assigned @Maroyafaied in this issue to (eventually) help me with this, but please let me know how you would like to proceed.

**Comment by Maroyafaied** [comment]
I researched the scope of amendments and drafted content that I think needs to be added in the link below (limited access)
https://docs.google.com/document/d/1k-njJkIckxGxZQsdFh6_z4BrxLK1ONcvC_CIEajE8tk/edit

**Comment by jennmalcolm** [comment]
@brentryanjohnson do you and @Maroyafaied need to do more before this issue is done, or should we create a new issue to edit that page?

**Comment by brentryanjohnson** [comment]
@jennmalcolm I still need to review the draft content, but we've fulfilled the scope of this issue (as worded). I recommend we create a new issue.

**Comment by Maroyafaied** [comment]
I'm closing this issue and created a new one #3723.
