### ISSUE TITLE
Wireframe for monthly disbursements on the homepage

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3643]
I'll do a wireframe, since we only have back to October 2018. We'll need to think about whether we display the months without data as empty or adjust the graph to only show the months we have.

**Comment by mcharg** [comment]
We have two options.

Option A: Replicate what we have now, with a drop-down that doesn't really add value.
The drop-down would have Most recent 12 months and Calendar year 2018.  Both options will show the same thing until we get the Q2 numbers, but it's consistent with the other monthly views.  If you click on a year with no data, the values would show as "No data", which is consistent with the other bar charts.


Option B: Leave out the drop-down until we get 12 months of data.
This makes it clearer that we're just getting the data set up and running and doesn't make the user unnecessarily use the drop-down that doesn't add value yet.

**Comment by mcharg** [comment]
@jennmalcolm @brentryanjohnson @mentastc @master12 Thoughts on the two options above?

**Comment by master12** [comment]
We can easily hide the drop down and add it later so really up to you all. No impact on dev either way

**Comment by mcharg** [comment]
@jennmalcolm @brentryanjohnson @mentastc Have any of you had a chance to look at this, so we can pick an approach and close it out?

**Comment by jennmalcolm** [comment]
I think we should hide the drop down until it is useful.

**Comment by brentryanjohnson** [comment]
I agree with @jennmalcolm.

**Comment by mcharg** [comment]
Cool.  Option B, it is.
