### ISSUE TITLE
Audit glossary behavior in Gatsby

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3656]
In the Jekyll portion of the site, the glossary looks up the exact entry declared by `term`. In this example, the glossary in the Jekyll portion of the site looks up "surface rights," as declared in the markup.

![glossary examples for surface rights and subsurface rights](https://user-images.githubusercontent.com/32855580/53036260-4148b480-342c-11e9-80bb-b14d82857fd5.png)

## Jekyll portion of site 
![glossary activated for surface rights](https://user-images.githubusercontent.com/32855580/53036288-4f96d080-342c-11e9-8640-da65b9de0182.png)

## Gatsby component

In the Gatsby component, the glossary appears to pattern match, and thus brings up both entries that contain "surface," even thought the term is tied specifically to "surface rights."

![glossary activated showing entries for both surface rights and subsurface rights](https://user-images.githubusercontent.com/32855580/53036325-62110a00-342c-11e9-938a-c00f7dff102c.png)

We should decide which of these behaviors is most desirable.

**Comment by jennmalcolm** [comment]
I think it's easier for the user if it links only to the one entry when you use the little icon to link directly to a term. On the other hand, I can see the benefit of having the pattern match when you're typing something in to search the glossary. I think that's the way it's working now in the Jekyll version.
