### ISSUE TITLE
Audit renewables content

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3657]
Like how-it-work -->fossil fuels (#3653), we should audit [our renewables](https://revenuedata.doi.gov/how-it-works/renewables/) content for specific year/data references.

In order to keep our content manageable, our how-it-works content should be contextual and supportive content, free from hard-coded data points.

**Comment by lpgoldstein** [comment]
https://docs.google.com/spreadsheets/d/1kQjDsmqTpA-882mvrJ3jQwGNhkkR9lpiJUSt51gMOtI/edit#gid=1424384472
