### ISSUE TITLE
Update links to DOI Economic Report and AML Grant Distribution Report

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3660]
A new version of the DOI Economic Report is available. We should update the link to it. 

Here is the new link: https://www.doi.gov/sites/doi.gov/files/uploads/fy_2017_econ_report_final_11_1_18.pdf

This is linked to on the [Impact of natural resource extraction on Native American land page](https://revenuedata.doi.gov/how-it-works/native-american-economic-impact/). A specific page is referenced, so we should verify if that is correct. Also, we should determine if this report is referenced in other places on the site.

There is also a link to the AML Grant distribution report on this page. That should be updated to this: https://www.osmre.gov/resources/grants/docs/FY18GrantDist.pdf.

@Maroyafaied I'm going to assign this issue to you and squeeze it into this sprint, but we can work on it together if you want.

**Comment by Maroyafaied** [comment]
I didn't find anywhere else on the site where the DOI Economic report is mentioned. The page number should be corrected to page 12 instead of page 10.

**Comment by mentastc** [comment]
I checked the production numbers in the production table they appear to match our data, there number is a combination of our indian production data set and our federal production data set.

**Comment by Maroyafaied** [comment]
The report of the AML grant distribution is mentioned a few times on this site but to the link to  the landing page not to a specific year's report.  @brentryanjohnson should we change this link to the landing page of all the reports instead of updating it every year? This is the link to all the reports https://www.osmre.gov/resources/grants.shtm

**Comment by brentryanjohnson** [comment]
Yes, @Maroyafaied; it's preferable to link to the landing page for the reports. If you want to do it, I'd be happy to pair with you to make the change and open a pull request.

**Comment by Maroyafaied** [comment]
@brentryanjohnson I set up a time next Monday to do it with @jennmalcolm but I will add you to the invite. Thanks!

**Comment by Maroyafaied** [comment]
Updated links and created pull request #3674 , waiting review before closing.
