### ISSUE TITLE
Correct or remove link on Native American production page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3661]
This link on the [Native American production](https://revenuedata.doi.gov/how-it-works/native-american-production/) page doesn't seem to provide what it describes:

[Information on tribes actively seeking mineral development on their reservations](https://www.bia.gov/as-ia/ieed/division-energy-and-mineral-development/minerals)

Is there a link we should replace this with, or should we just get rid of it?

Also, this link is not working: [Oil and Gas Outlook in Indian Country (PDF)](https://www.bia.gov/cs/groups/xieed/documents/document/idc1-024535.pdf)

**Comment by Maroyafaied** [comment]
The  link on the[Native American production](https://revenuedata.doi.gov/how-it-works/native-american-production/) could be replaced with this link and titled "Information on Tribal assistance with exploration, development, and management of their energy and mineral resources"
https://www.bia.gov/as-ia/ieed/division-energy-and-mineral-development/business-development

This is the right link to the report titled " Oil and Gas Outlook in Indian Country" but it is outdated, I could not find an updated report.  I would suggest removing it.
https://www.bia.gov/sites/bia.gov/files/assets/as-ia/ieed/ieed/pdf/DEMD_OG_Oil_Gas_Outlook_508.pdf

**Comment by jennmalcolm** [comment]
Yes, it is quite out of date, and it even refers to the old stats site. 
@brentryanjohnson, do you agree with getting rid of the link to that outdated report?

@Maroyafaied could you set up a time on our calendars to set up a PR? Maybe we can do these and the changes in #3660 at the same time.

**Comment by brentryanjohnson** [comment]
I think it makes sense to remove it. If we can link to a landing page, that would be ideal. 

So instead of linking to each individual report/document, if we can identify a landing page where these (or similar) documents are linked to, that would be better. There is some interesting, if outdated, content in that outlook doc.

**Comment by Maroyafaied** [comment]
Updated links and created pull request #3674 , waiting review before closing.
