### ISSUE TITLE
Explore Data page mobile table of contents--change location and what it says

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3663]
For the mobile table of contents on the explore data page, it says "Nationwide," which is confusing. Could we change it to "Table of contents," like on the How it Works page? Also could it sit closer to the top and not overlap the page content?

Here's what it looks like now:

![image](https://user-images.githubusercontent.com/30806839/53107858-f39f7b00-3503-11e9-8ab3-b6de72b31767.png)

**Comment by mcharg** [comment]
@jennmalcolm The image didn't finish uploading.

**Comment by mcharg** [comment]
The location is covered in #3494
