### ISSUE TITLE
Audit and inventory all external links that need to be regularly updated

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3664]
Some of the links throughout our site go directly to annual reports or other time-specific material. To supplement the content audit, we should inventory external pages or reports we link to that are for specific time frames and approximately when they are updated so that we could include that info on the content calendar.

**Comment by jennmalcolm** [comment]
Or, ideally, we should reduce or eliminate these types of links if we can find more general pages to link to without losing the relevant content.

**Comment by lpgoldstein** [comment]
Just found a few....

https://docs.google.com/spreadsheets/d/1ziZsTGwh1Vuk4YDaycCRGlsNiWxwN06E8GNv5QxhCXc/edit?usp=sharing
