### ISSUE TITLE
Write copy for monthly disbursements

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3667]
Add to this doc:
https://docs.google.com/document/d/1GewlO1mrP5M1p3BuCreugO8vd3VRcHJeNwXUqeMOqyw/edit

New Recipients
- [ ] U.S. Forest Service
- [ ] BOEM
- [ ] BSEE
- [ ] BLM
- [ ] BLM Lease Process Improvement
- [ ] U.S. Fish and Wildlife Service

New Fields
- [ ] Commodity - Need intro copy for one page when the user picks any commodity https://oajgix.axshare.com/#g=1&p=by_commodity
- [ ] Revenue Type - Need intro copy for one page when the user picks any revenue type https://oajgix.axshare.com/#g=1&p=by_revenue_type

New Help
- [ ] Non-commodity production - explains why some disbursements can't be tied to a single commodity

**Comment by jennmalcolm** [comment]
@mcharg are you suggesting the revenue type additions on the How it works/Disbursements page or somewhere else? Also, will the new fields copy be relevant any more since you will be doing #4000 first?

**Comment by mcharg** [comment]
This copy was for the top of the page that was supposed to change when you drilled from the top level page.  That will probably change with #4000.

**Comment by mcharg** [comment]
I think we can close this one and open a new one after #4000, if needed.
