### ISSUE TITLE
Plan for more lease level data interviews

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3668]
- Reach out to FOIA requesters and the person we had scheduled in January
- Write a script to use with these people and people at the Open Maine meeting

Study Goal:
- Learn more about how non-industry people might use lease-level data

**Comment by mcharg** [comment]
Draft script (limited access).

https://docs.google.com/document/d/1g5fcMVyv9XBQPX1pL3Qfq6TIPpSlhsulslRpAD4d4a4/edit

@jennmalcolm @brentryanjohnson @lpgoldstein Do you have anything to add?

**Comment by jennmalcolm** [comment]
I added a couple comments.

**Comment by mcharg** [comment]
Here's a first pass at creating a spreadsheet for notetaking instead of individual docs to save analysis time.  Thoughts?
https://docs.google.com/spreadsheets/d/1jWvE7BNeDggwot5BOPjfcmrY_W5B71sE9ZN67InQOnE/edit#gid=0

**Comment by lpgoldstein** [comment]
I really like it. It will be easier to pull out the trends and recommendations at the end.
