### ISSUE TITLE
Deduplicate analytics scripts in main site and blog

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3672]
Google analytics script tags are being loaded into the main site and blog multiple times. We should figure out why and deduplicate the instances.

![multiple script tags with the same google analytics script loaded in](https://user-images.githubusercontent.com/32855580/53255025-962d3a80-3679-11e9-9457-1083d3eedddc.png)

**Comment by echang97** [comment]
This seems to be a problem with having both Analytics and Tag Manager code snippets.
Tag Manager seems to be making two requests to the same ID.
Meanwhile, the Analytics code snippet makes requests to a completely different ID.

**Comment by jlouis-onrr** [comment]
It does appear to be an issue with both Analytics and GTM code snippets not playing nice together.  I can successfully deduplicate by removing the GTM code snippet.  My initial guess is that the universal tag is configured within GTM to get fired on page views.  Would it be possible for me to gain access to the GTM account to verify this?

**Comment by brentryanjohnson** [comment]
I've given you access to the GTM container, @jlouis-onrr.

**Comment by jlouis-onrr** [comment]
Awesome, thanks!

**Comment by jlouis-onrr** [comment]
Helpful history on the use of the id "UA-48605964-8", legacy Id
[https://github.com/ONRR/doi-extractives-data/issues?utf8=%E2%9C%93&q=48605964-8](https://github.com/ONRR/doi-extractives-data/issues?utf8=%E2%9C%93&q=48605964-8)

**Comment by jlouis-onrr** [comment]
According to google having multiple occurences of analytics.js scripts for multiple tracking snippets is fine.  See [GA Multiple Tags](https://support.google.com/analytics/answer/1032400?hl=en).

Updates made to this branch include:
- Remove all occurrences of old GA Id "UA-48605964-8"
