### ISSUE TITLE
Audit data figure for offshore lease acres

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3675]
We should audit the figure for offshore lease acres. For instance, did GOMESA phase 2 change the number of viable offshore lease acres?

> The Outer Continental Shelf Lands Act (OCSLA) of 1953 grants the Secretary of the Department of the Interior (DOI) the authority to manage offshore energy resources and to develop regulations to carry out that authority. Three agencies within DOI — BOEM, BSEE, and ONRR — work together to manage, regulate, and collect revenue from **33 million leased acres** across the Outer Continental Shelf.

**Comment by usEITI** [comment]
GOMESA would not have changed the viable number of acres.  However and international settlement between Mexico and the US may have slightly modified the acres in US jurisdiction.  Karen discovered the slight variation while trying to confirm the GOMESA 2 allocations.  I would also therefore, check with Karen Osborne.

**Comment by mentastc** [comment]
The current number can be found here: https://www.boem.gov/Combined-Leasing-Report-May-2019/

13,624,959
