### ISSUE TITLE
Coal Excise Tax rate updates needed

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3676]
In addition to a static revenue chart that we can no longer update, the [Coal Excise Tax content](https://revenuedata.doi.gov/how-it-works/coal-excise-tax/) refers to a rate change on Jan. 1, 2019. We should research if this change occurred, or better yet, rewrite this content so that it only includes supporting context and omits specific, mutable data figures.

> The coal excise tax rates are scheduled to decline to $0.50 per ton for underground mines and $0.25 per ton for surface mines (both limited to two percent of the coal’s selling price). This change will occur either on January 1, 2019, or the first January 1 when there are no more repayable advances from the General Fund to the Trust Fund and no unpaid interest on previous such advances.

**Comment by mentastc** [comment]
Updated chart numbers: 
[Coal excise tax data 1999-2017.xlsx](https://github.com/ONRR/doi-extractives-data/files/2931657/Coal.excise.tax.data.1999-2017.xlsx)

**Comment by mentastc** [comment]
The new rates did take effect, here's the language from a CRS paper dated mid January 2019:

 Effective January 1, 2019, the tax on undergroundmined coal is the lesser of (1) $0.50 per ton, or (2) 2% of the sale price. The tax on surface-mined coal is the lesser of (1) $0.25 per ton, or (2) 2% of the sales price.

**Comment by mentastc** [comment]
@brentryanjohnson , I found the updated information should I create a new issue or do you want ot update the data inside this issue?

**Comment by brentryanjohnson** [comment]
I think we can use this issue for the update, @mentastc. Let me know if you would like to pair on the update.

**Comment by mentastc** [comment]
@brentryanjohnson , We'll need to update the chart so we should pair, I'll put some time on the calendar.

**Comment by brentryanjohnson** [comment]
We can't update that chart, since it was created in Sketch, and Sketch is macOS only. Perhaps we can replace it with a table.
