### ISSUE TITLE
Fix broken BLM link on renewables

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3678]
This link is broken on [onshore renewables diving graphic](https://revenuedata.doi.gov/how-it-works/onshore-renewables/). We should fix this link.

![broken link to BLM in aside about renewables](https://user-images.githubusercontent.com/32855580/53434566-c2afc200-39ab-11e9-8159-799e61cab7cc.png)

**Comment by mentastc** [comment]
Fix in PR #3764
