### ISSUE TITLE
Audit rates for fees, bonuses, rent, royalties

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3679]
We have rate information for fees, bonuses, rents, and royalties in two places: [how it works diving graphics](https://revenuedata.doi.gov/how-it-works/minerals/) and the [revenue "megachart"](https://revenuedata.doi.gov/explore/#revenue). 

We haven't audited these numbers in quite some time. We should review them and make sure they're correct in both instances.

**Comment by brentryanjohnson** [comment]
We also have the rates on the [how-it-works revenue page](https://revenuedata.doi.gov/how-it-works/revenues/). So we have these rates in **3** places. We should audit each instance, and we should decide how many places we need this content. 

We could create components for each commodity and place them in various places, instead of managing the content separately.

**Comment by jennmalcolm** [comment]
We need to decide where these should go on NRRD and then audit BOEM and BLM sources info to see if rates are accurately reflected.

**Comment by Maroyafaied** [comment]
After my audit, I recommend this content to be in how-it-works revenue page but to include all the commodities. There are a few rates that need to be updated and I have made the recommended content in this excel sheet (limited access). @jennmalcolm @brentryanjohnson please review.
- Oil and Gas Offshore- rental fees and royalty rates need to be updated
-"Hard rock minerals"/ "non-energy minerals"- Fees need to be updated
-Solar and wind onshore - all rates need to be updated
-Geothermal competitive leasing - update nomination fee, per acre fee, application fee
-Geothermal non competitive leasing- update application fee
https://docs.google.com/spreadsheets/d/1lAJ5UQXGiCRe6BM9Fmd4DAet6g5yeXaRM0L4p1H0nIk/edit#gid=985594313

**Comment by jennmalcolm** [comment]
Thanks, this looks good. I agree that it should go in how it works, and the revenue page seems appropriate.

**Comment by brentryanjohnson** [comment]
@Maroyafaied What do the "deep well extensions" refer to? They appear to be present only for shallower depths, and appear to modify rents for years 6–8.

**Comment by brentryanjohnson** [comment]
@Maroyafaied Is there no longer a distinction between "acquired lands" and "public domain lands" with respect to hardrock minerals rates?

**Comment by Maroyafaied** [comment]
For the deep well extension questions, from my understanding the primary term for a lease in 5 years and the lessee can earn additional years if a well is extended to a certain depth during the first fiver years of the lease. In those cases, the rental rates changes at year 6 going forward. I took it out in my spreadsheet since it is confusing if it's not explained. Here is a table explaining it
![image](https://user-images.githubusercontent.com/40175688/54377711-57245080-464b-11e9-99f8-38948548c128.png)

**Comment by Maroyafaied** [comment]
Also, this is the rental rate table from the Federal Register which does not mention the deep well extension so I think we are ok leaving that description out. 
![image](https://user-images.githubusercontent.com/40175688/54377852-9f437300-464b-11e9-8099-39a16eeb3a38.png)

**Comment by Maroyafaied** [comment]
There is a distinction between public and domain lands but I could not find any sources to verify the rates for the prospecting permit fees that we currently have listed on our website.

**Comment by Maroyafaied** [comment]
I was able to find information on hardrock minerals on acquired land, I have updated the excel sheet. I will close this issue.
