### ISSUE TITLE
Set up Tag Manager to track ids

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3683]
The explore data page is quite long with several sections. We aren't currently able to track interaction with the navigation that would convey users to sections within the page.

We should set up Google Tag Manager to track the partials.

**Comment by brentryanjohnson** [comment]
And behold! I included a new custom JS variable and trigger, and I've added the trigger to the existing page view tag to start tracking the fragments. I've previewed it, and it looks like it's working, but we should leave this issue open until we can confirm in analytics.

![google tag manager preview showing fragment for federal disbursements being tracked](https://user-images.githubusercontent.com/32855580/53457757-53a48e80-39e8-11e9-9d5b-e36b71ffd787.png)

**Comment by brentryanjohnson** [comment]
@mcharg Do you mind helping me confirm it's working?

**Comment by mcharg** [comment]
@brentryanjohnson If you show me how.

**Comment by brentryanjohnson** [comment]
@mcharg it’s basically just reviewing the page views analytics to see if the partials show up. We’ll probably need to pull unsampled.

**Comment by brentryanjohnson** [comment]
Looking at the analytics report, it doesn't appear to be listing the fragments. Back to the drawing board!

**Comment by brentryanjohnson** [comment]
Testing with GTM preview registers results, but we aren't seeing the fragment views in our pageviews yet. I'm closing this issue, because the setup is complete, but we may need to open another for testing and revisiting if the results don't show up.

**Comment by brentryanjohnson** [comment]
Using the browser inspector, this new tag appears to be firing, but it isn't producing results in our Pageviews. I'm reopening this issue to attempt a different method of setting up the tag.

**Comment by brentryanjohnson** [comment]
It works!

To view the analytics for the Explore Data in-page navigation:

1. Select our segment in Google analytics
1. Select Behavior-->Events
1. Select "Explore data clicks"
1. Select "Event Label"

![Shows interface with Event Label selected and highlighted and page labels underneat, with revenue, economic impact, federal disbursements, federal tax revenue, and production](https://user-images.githubusercontent.com/32855580/54709759-5421d800-4b03-11e9-9980-ab363be79f13.png)

**Comment by brentryanjohnson** [comment]
FYI: `(not set)` likely corresponds to "Top" in the nav menu, since that link is to a hash (#) without anything following it. The "event label" corresponds to the text that follows the hash.
