### ISSUE TITLE
Due 3/29: Finish lit review and format book chapter

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3701]
And finish any clean up reviews.
Also need review by @brentryanjohnson and @jennmalcolm.

**Comment by mcharg** [comment]
@jennmalcolm @brentryanjohnson This is ready for you to review. 
[https://app.zenhub.com/files/21627244/1a1ddf06-6e2d-4cd7-9694-86bc6a5d6791/download](https://app.zenhub.com/files/21627244/1a1ddf06-6e2d-4cd7-9694-86bc6a5d6791/download)

**Comment by brentryanjohnson** [comment]
I've added some comments and suggestions, @mcharg . 📝 

[lit-rj-edits.docx](https://github.com/ONRR/doi-extractives-data/files/2933964/lit-rj-edits.docx)

**Comment by mcharg** [comment]
Here's the version I sent to the editors.[https://app.zenhub.com/files/21627244/b88bc2ca-dbda-41a3-911a-63667578d2a4/download](https://app.zenhub.com/files/21627244/b88bc2ca-dbda-41a3-911a-63667578d2a4/download)
