### ISSUE TITLE
Populate market map with potential participants

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3716]
- [ ] Google to find people who have referenced our site
- [ ] Go through analytics and back track to find what sites people are coming from and see if we can find names of people to contact

**Comment by mcharg** [comment]
Here's one site that we should contact somebody from: https://corising.org/contact-us/

**Comment by Maroyafaied** [comment]
I have started two tabs in the market map, one for "sites from analytics" and one for "academics"
https://docs.google.com/spreadsheets/d/1zwSwBrEPsxCN8ctZi9hzx9FVz-bE5jxM06rMxN2tKe8/edit#gid=807031006

**Comment by Maroyafaied** [comment]
https://eiti.org/ has a list of articles mentioning need for transparency, we can go through the articles to find contacts as well. @mcharg @mentastc @brentryanjohnson

**Comment by Maroyafaied** [comment]
https://eiti.org/mentions this is the right link.
