### ISSUE TITLE
Re-style input field for company revenue

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3721]
The migration to Gatsby has resulted in a change to the styling of our input field for revenue by company. We should give that field some breathing room, rounded corners, and a thinner stroke, as it was styled before.

![input field for filter by company name](https://user-images.githubusercontent.com/32855580/53743903-a8189580-3e50-11e9-849f-6c9f6de0ed37.png)

**Comment by jennmalcolm** [comment]
This is duplicate from #3720, which you fixed, right, @brentryanjohnson?

**Comment by brentryanjohnson** [comment]
No, this is a separate issue, @jennmalcolm. This one is related to the input field to filter by company.

It used to look like this:

![form field with rounded corners and the words filter by company name](https://user-images.githubusercontent.com/32855580/55347438-c4b4e700-5469-11e9-87d0-a7c4867acb44.png)

Now, it's missing some input field and padding styling, and it looks like this:

![form field with sharp 90 degree angles, smaller than the previous, with the words filter by company name](https://user-images.githubusercontent.com/32855580/55347522-f75edf80-5469-11e9-8f2b-c692fefc8112.png)

**Comment by jennmalcolm** [comment]
Ok thanks @brentryanjohnson.
