### ISSUE TITLE
Do interview on NRRD with intern

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3730]

**Comment by mcharg** [comment]
@usEITI Which day is the intern going to be in the office?

**Comment by Maroyafaied** [comment]
I will be interviewing the intern and @lpgoldstein will be interviewing Nancy from ONRR.

**Comment by mcharg** [comment]
Here's the guide from the homepage study we did with the general public that might be a good starting point for this study:
https://docs.google.com/document/d/1VUNA19VrGhVxMbKisWiTA0Yb-okLma5BI3B20tGYVbU/edit#heading=h.9tpuhoasg8xo

**Comment by Maroyafaied** [comment]
Here is a draft of the plan and guide for the interviews (limited access) https://docs.google.com/document/d/1ENreBSMbHnALYYkYsbGf6W-6ox6beQp5o8fiOzPHo6w/edit#

**Comment by mcharg** [comment]
Quick compilation of findings (limited access): https://docs.google.com/presentation/d/11SZm2FbKaE5NIPwqkxzLwb5Ec9kuotsneg_oxx_Bluk/edit#slide=id.p

**Comment by mcharg** [comment]
Plans and results for all the interviews we did this sprint: https://github.com/ONRR/doi-extractives-data/tree/research/research/25_bodaciousbaboon_leases_filterabletables
