### ISSUE TITLE
Use active state for how it works and state data nav items

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3738]
Our navigation shows which section of the site is active by bolding that item in the nav. For example, if one is on the Explore data page, the Explore data nav item is bolded.

![navigation items with home, about, how it works, explore data, and case studies, with explore data bolded](https://user-images.githubusercontent.com/32855580/53771488-96a6ac00-3e97-11e9-9bf1-003f6ee6dbd6.png)

Our refactored how-it-works pages do not trigger active nav state for the How it works nav item.

![navigation items again, this time with no bolded items](https://user-images.githubusercontent.com/32855580/53771540-d2da0c80-3e97-11e9-8726-9de8703a969e.png)

We should:

- use active state for pages in the respective sections, including:
  - bold state for "Explore data" when user is on state pages (since state pages are in the `explore` directory)
  - bold state for How it works nav item for all pages in `how-it-works`

**Comment by mcharg** [comment]
@brentryanjohnson This looks like it's fixed.  Correct?

**Comment by brentryanjohnson** [comment]
Yes.
