### ISSUE TITLE
Change titles of revenue by phase to be consistent

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3745]
As I was going through the different pages for rates, I noticed  revenue phase1 is titled differently in the how it works page and the explore data page.

![image](https://user-images.githubusercontent.com/40175688/53828916-2dc53f80-3f3c-11e9-81c4-d8baa53cb2af.png)

![image](https://user-images.githubusercontent.com/40175688/53828997-5fd6a180-3f3c-11e9-963c-8cc6aa73fef9.png)

**Comment by brentryanjohnson** [comment]
Has this issue been resolved, @Maroyafaied?

**Comment by Maroyafaied** [comment]
No, I did not mean to close it. I will reopen it.

**Comment by jennmalcolm** [comment]
has been fixed
