### ISSUE TITLE
Fix duplicate homepage active bars on iPhone

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3753]
## Expected Behavior

- Only one bar is highlighted on homepage

## Actual Behavior

- Most recent year's bar stays highlighted, even when another bar is selected

## Steps to reproduce the behavior

- View the homepage on iPhone and select a bar other than the most recent year

**Comment by brentryanjohnson** [comment]
There are a few more issues I discovered on iPhone. 

- Charts sometimes required a double tap to change to
- Tapping "show details" and "hide details" reverts chart back to 2018, regardless of which year was selected
- "show/hide details" requires double tap

## Screen capture

![iphone-bugs](https://user-images.githubusercontent.com/32855580/54940092-44c9d280-4ee7-11e9-8f8f-b79372bb2e66.gif)

**Comment by mcharg** [comment]
See #3442 and #3457 for background on previous fix for this.

**Comment by mcharg** [comment]
@mojobnichols @jlouis-onrr Will this be fixed in the new repo or do we need to transfer?

**Comment by mcharg** [comment]
Not an issue in the new repo.
