### ISSUE TITLE
Send thank you emails to usability study participants when we launch features we've implemented based on their feedback

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3776]
This might make them more willing to participate in the future and is also an opportunity to ask them again for referrals for others who should participate.

For this issue, we should:
- [x] Create a template for these emails.
- [ ] Send emails to those who participated in the home page studies.

Things to include in the email:
- [x] Thank your for giving us feedback
- [x] Take a look at our new homepage that we designed with your help
- [x] Are you interested in lease level production data, detailed revenue data, or sales data?  We're conducting research on those topics now, let us know if you're interested.
- [x] Do you know of anyone else we should talk with?

**Comment by lpgoldstein** [comment]
Link to a sample template: https://docs.google.com/document/d/1rByfkxA_XVF35aN74knyLsWmvWsuOXnLq2fjALg8f7w/edit?usp=sharing

**Comment by mcharg** [comment]
Should this email come from me, since the participants all interacted with me for the study, or from the NRRD email address?  I'm thinking they'll be more likely to open an email directly from me, since the name will be familiar.

**Comment by mcharg** [comment]
@jennmalcolm Do you want to review this before I send the emails?

**Comment by lpgoldstein** [comment]
It should come from you so it is more personal. You could cc or bcc the NRRD email address so we have a record of the emails.

**Comment by jennmalcolm** [comment]
Looks good to me.

**Comment by mcharg** [comment]
Email sent
