### ISSUE TITLE
Look into whether we could use services that have user panels

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3781]
Sites like usertesting.com and optimalworkshop.com have user panels and would be a good place to test small things that we can test with a general audience, things like whether people get how hover behavior on graphs works.

**Comment by mcharg** [comment]
This is another one to look into: https://maze.design/?utm_source=densediscovery&utm_medium=email&utm_campaign=newsletter-issue-29

**Comment by lpgoldstein** [comment]
Moving this to the next sprint because I wasn't able to get a demo/meeting from usertesting until next week.

**Comment by lpgoldstein** [comment]
So the bottom line is that yes we probably could use these services. Services confirmed that they recruit testers through Facebook and LinkedIn paid ads. That might be a cheaper way to target users if we wanted to use a paid route. 

Attaching notes document
https://docs.google.com/document/d/18UH4pxtLTRnKDaKGJMntGFtUHKUu4qpimp8c8IacHmY/edit?usp=sharing
