### ISSUE TITLE
Due March 22nd: Finalize and practice OLT presentation

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3784]
Related to issue #3682 . Christina would like a copy of the power point presentation by Monday, March 25th.  We need to finalize the power point and schedule a time for Lindsay and Shannon to practice presentation.  Here is the draft of the power point 

https://docs.google.com/presentation/d/1TuW248D7uf-VUq3FdOkumyIXUPt1MoopY1qwBpxjmrM/edit#slide=id.g3d0ee0d9f2_0_0

**Comment by mcharg** [comment]
My pieces are now in the deck: https://docs.google.com/presentation/d/1TuW248D7uf-VUq3FdOkumyIXUPt1MoopY1qwBpxjmrM/edit#slide=id.g52b065063c_0_88

**Comment by Maroyafaied** [comment]
I just got the agenda for the OLT , we are scheduled at 10:25 am for 30 minutes.

**Comment by Maroyafaied** [comment]
It look like the OLT would like a copy of the powerpoint by this Friday. Do you guys think you will have your slides finalized by then? I can set up a time tomorrow or Thursday to go over them and practice if you'd like.

**Comment by mcharg** [comment]
Let's setup a time on Thursday.  I just set up one on Monday, so Jennifer can be there.
