### ISSUE TITLE
Write blog post on how NRRD aligns with IDEA and OPEN Data acts

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3788]
We should write a blog post about how revenuedata.doi.gov aligns with the provisions of the [21st Century Integrated Digital Experience Act](https://www.congress.gov/bill/115th-congress/house-bill/5759/text) and the [OPEN Government Data Act](https://www.congress.gov/bill/115th-congress/house-bill/4174/text). Major provisions of the legislation include:

## 21st Century IDEA (Integrated Digital Experience Act)
- Section 508 compliance (accessibility)
- does not overlap with or duplicate any legacy websites, and, if applicable, ensures legacy websites are reviewed, eliminated, and consolidated
- contains a search function
- **is designed around user needs with data-driven analysis influencing management and development decisions, using qualitative and quantitative data to determine user goals, needs, and behaviors, and continually test the website, web-based form, web-based application, or digital service to ensure that user needs are addressed**
- is fully functional and usable on common mobile devices
- head of each executive agency shall regularly review public-facing applications and services to ensure that those applications and services are, to the greatest extent practicable, made available to the public in a digital format

## OPEN (Open, Public, Electronic and Necessary) Government Data Act
- federal agency responsibilities to make data open by default
- facilitate collaboration with non-Government entities (including businesses), researchers, and the public for the purpose of understanding how data users value and use government data
- identifies and implements methods for collecting and analyzing digital information on data asset usage by users within and outside of the agency, including designating a point of contact within the agency to assist the public and to respond to quality issues, usability issues, recommendations for improvements, and complaints about adherence to open data requirements within a reasonable period of time
- develops and implements a process to evaluate and improve the timeliness, completeness, consistency, accuracy, usefulness, and availability of open Government data assets
- includes requirements for meeting the goals of the agency open data plan, including the acquisition of technology, provision of training for employees, and the implementation of procurement standards, in accordance with existing law, regulation, and policy, that allow for the acquisition of innovative solutions from public and private sector
- make each data asset of the agency available in an open format and make each public data asset of the agency available—as an open Government data asset; and under an open license
- **ensure that any public data asset of the agency is machine-readable**
- engage the public in using public data assets of the agency and encourage collaboration by:
  - publishing on the website of the agency, on a regular basis (not less than annually), information on the usage of such assets by non-Government users
  - providing the public with the opportunity to request specific data assets to be prioritized for disclosure and to provide suggestions for the development of agency criteria with respect to prioritizing data assets for disclosure
  - assisting the public in expanding the use of public data assets
  -  hosting challenges, competitions, events, or other initiatives designed to create additional value from public data assets of the agency

**Comment by lpgoldstein** [comment]
Draft
https://docs.google.com/document/d/1DirgPwSljfGDByXdT3_1jQ0oWGZl5croNH7R1nG49ZQ/edit#

**Comment by lpgoldstein** [comment]
Blog post is written, but will publish next sprint since we just published another blog post today.
