### ISSUE TITLE
Determine if we need a Contributor License Agreement

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3808]
We don't receive many contributor pull requests, but apparently some agencies require a Contributor License Agreement to accept GitHub contributions.

We should determine if we should have such an agreement requirement, and if our current licensing information in [`CONTRIBUTING.md`](https://github.com/ONRR/doi-extractives-data/blob/dev/CONTRIBUTING.md#public-domain) is sufficient.

**Comment by jennmalcolm** [comment]
@lpgoldstein, you think you canwork on this?

**Comment by lpgoldstein** [comment]
Given the limited scope of our website, limited public contributions and all contributions are reviewed prior to acceptance I don't think we need a CLA. I found that NASA requires CLAs from contributors, but they release software.
