### ISSUE TITLE
Consider removing EIA production data

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3809]
User confusion and guidance from DOI leadership indicate that we should consider removing the EIA "all lands" production data from the site. We've retained the data for context, but it (1) doesn't align well with our product vision (2) we can't verify its accuracy (3) it requires a separate, API-driven data management workflow (4) users expect to see federal production data first, since that's the focus of the site (5) the data is available elsewhere.

**Comment by mcharg** [comment]
Do we want to remove it altogether or still have it at a summary level?  Users seemed to get it in the production summary that's slated for the new Explore Data page.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/65526f08-f451-4ec7-854f-95a322da0cc7)

**Comment by brentryanjohnson** [comment]
Let's talk with @jennmalcolm about this, @mcharg. 👍

**Comment by mcharg** [comment]
Here's an idea for an alternative production summary that doesn't use EIA data.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a490113c-3cd2-4e0e-a430-9a605b5ea7a1)

**Comment by jennmalcolm** [comment]
Let's consider using the first design with only federal and Native American on the bars (so they are not dwarfed by the state and private. Still, I don't want to lost all the context that the EIA data provides, so we should consider options. Maybe in a sentence on the state pages and/or for each graph, we state that federal and Native American production represents XX% of the US total.

**Comment by mcharg** [comment]
@jennmalcolm The problem with using the first design with only federal and Native American on the bars is that it will be no different from the diagram on the homepage.  It might not be a big deal if we change the links on the homepage to go to the Production page instead of Explore Data after we split up the pages, but it's something we should think through.

**Comment by jennmalcolm** [comment]
Since we have removed this data, I will close this issue.
