### ISSUE TITLE
Due 3/27: Abstract and author bios for Government UX Summit

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3812]
Send me the final details about your presentation, including the title and all the authors as you want them to appear in the program, along with a 100-word abstract (please do try to keep it short).

**Comment by mcharg** [comment]
Here's a draft:
https://docs.google.com/document/d/1k3rbWwNxYf0Tr7Sg9FvkvrmtRUcdSi5ewhm5DcOMcRY/edit

@Maroyafaied @jennmalcolm Any edits?

**Comment by Maroyafaied** [comment]
@mcharg no edits from me, looks good.

**Comment by jennmalcolm** [comment]
Looks fine to me too.
