### ISSUE TITLE
Update Indian Production numbers (FY09-18)

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#3816]
Update website with attached Production Data. 
[FY Indian Production Data 2009-2018.xlsx](https://github.com/ONRR/doi-extractives-data/files/3004651/FY.Indian.Production.Data.2009-2018.xlsx)

Also, the site above the data it says "this is accounting year data", may need to remove that language,

**Comment by jennmalcolm** [comment]
Yes, we should remove account year. That doesn't make sense for production data.
