### ISSUE TITLE
Due 5/15 (or sooner): Presentation for Government UX Summit

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3817]
We need to turn the proposal into a presentation.  We don't have a defined due date yet, but the conference is 5/15.

**Comment by Maroyafaied** [comment]
We started the first draft of the presentation in Microsoft powerpoint since they might not support google slides.

**Comment by mcharg** [comment]
Version 2: 
[UX Summit Presentation_041919_SM.pptx](https://github.com/ONRR/doi-extractives-data/files/3099113/UX.Summit.Presentation_041919_SM.pptx)

**Comment by mcharg** [comment]
Version 3: 
[UX Summit Presentation_042419.pptx](https://github.com/ONRR/doi-extractives-data/files/3113378/UX.Summit.Presentation_042419.pptx)

**Comment by mcharg** [comment]
@jennmalcolm Do you want to review?

**Comment by jennmalcolm** [comment]
Looks good. I'll also attend the first half hour of the practice session.

**Comment by mcharg** [comment]
@Maroyafaied I pulled in some formatting changes to the Who We Are section from the presentation Ryan and I are working on.
[UX Summit Presentation_042519.pptx](https://github.com/ONRR/doi-extractives-data/files/3117703/UX.Summit.Presentation_042519.pptx)
