### ISSUE TITLE
Due 5/1: DotGov Design Presentation

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3818]
We were accepted for this one, as well, so we need to turn the proposal into a presentation.

**Comment by mcharg** [comment]
https://docs.google.com/presentation/d/1gxYkpMrzKntEuv7cAsst3Sj6C9RxYjj_j8d-SdBd3a8/edit#slide=id.p5

**Comment by mcharg** [comment]
@jennmalcolm Do you want to schedule a practice session for this one?

**Comment by jennmalcolm** [comment]
I'm sure I could use some practice. Could you see if you can find a half hour next week?

**Comment by lpgoldstein** [comment]
@jennmalcolm  and @mcharg  - I added images into the presentation. Please take a look and let me know if you like them and I will format. Happy to dig around for more if these don't work well.

**Comment by mcharg** [comment]
The only one that doesn't make sense to me is the smoothies.

Also, the one you pulled from the peer training presentation requires attribution.  See the last slide in that one for that.
