### ISSUE TITLE
Create D3 sparkline component for data trending

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3827]
I built a sparkline include in D3 for Jekyll, but we need a Gatsby component for simple conveyance of data trends.

Here are the sparkline includes I built:

- [sparkline.html](https://github.com/ONRR/doi-extractives-data/blob/aml-spark/_includes/sparkline.html)

- [aml-sparkline.html](https://github.com/ONRR/doi-extractives-data/blob/aml-spark/_includes/how-it-works/aml-sparkline.html)

**Comment by jennmalcolm** [comment]
Moving out of this sprint so that we can decide on which design (other options in #3950) to move forward with before spending valuable development time on this.
