### ISSUE TITLE
Publish blog post on NRRD alignment with IDEA and OPEN Data acts 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/doi-extractives-data#3828]
Publish blog post written last sprint on how NRRD aligns with IDEA and OPEN Data acts#3788

**Comment by lpgoldstein** [comment]
@jennmalcolm - this is ready for your erview - https://docs.google.com/document/d/1DirgPwSljfGDByXdT3_1jQ0oWGZl5croNH7R1nG49ZQ/edit#heading=h.jg8xpdeu3iow

**Comment by jennmalcolm** [comment]
I made some changes rather than suggestions since I thought we might publish before @lpgoldstein is back. Aside from implementing search, the only thing I think it needs before publishing is a short conclusion.

**Comment by jennmalcolm** [comment]
@lpgoldstein could you get a branch ready with this blog post so we can publish it with our next release?
