### ISSUE TITLE
Facilitate usability testing for GIS team

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/doi-extractives-data#3831]
I walked the GIS team through our usability testing process and they have requested our help to learn our process and use to test internal GIS apps that are in the creation process.  We are going to help them develop usability testing materials and assist with testing. We will create more issues and close this one once we have more clarity with the process.

**Comment by lpgoldstein** [comment]
We set our next meeting on April 16, 2019 so I'm going to move this issue to the next sprint.

**Comment by Maroyafaied** [comment]
We met with the GIS team, they will work on writing a study plan and a study guide then we will meet again to give them feedback. We also offered to be pretend participants for them to practice conducting the interviews and offered they attend one of our user testing session as observers.  Closing this issue and will create another one as the process moves a long.
