### ISSUE TITLE
Build MVP revenue filterable table

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3835]
I pulled out the charts from the design and also created a version without the sparklines, since I think those could be added after the MVP.  I also made it color and not sketchy again in this version, so Jeff knows what the desired colors are.

With Sparklines:
https://t81vx1.axshare.com/#g=1&p=revenue_table_-_alt

Without Sparklines:
https://t81vx1.axshare.com/#g=1&p=revenue_table_-_no_sparkline

**Comment by master12** [comment]
https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/3835-filterable-table/explore/revenue/
