### ISSUE TITLE
Review and rewrite copy for revenue filterable table MVP

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3838]
https://t81vx1.axshare.com/

Components to review:
- [x] Intro copy 
- [x] Table copy

New glossaries:
- [x] Non-commodity revenue
- [x] Accounting year
- [x] Withheld (organize by location or drill to oil)
- [x] Not tied to a lease (organize by location)

**Comment by brentryanjohnson** [comment]
You write the best comments, @mcharg. :)

**Comment by brentryanjohnson** [comment]
✔ The glossary already contains "accounting year."

**Comment by brentryanjohnson** [comment]
@mcharg @jennmalcolm @mentastc 

One issue with that "accounting year" glossary entry...

> Accounting year data contains transactions for sales that took place in the current year, as well as adjusted or corrected transactions for sales that took place in previous years. Because they include adjusted or corrected transactions for previous sales periods, **accounting year data should not be used for trending purposes** or for analyzing sales volumes.

Our revenue table literally has a column titled **Trend**. 

So we need to deal with that. I think it still makes sense to present the sparkline, and it still makes sense to call that column "Trend," so we need to figure out how to convey what we mean by "trending" in that glossary entry.

**Comment by brentryanjohnson** [comment]
@mcharg 

🐉 Components to review:
- [x] Intro copy [_In this file (limited access)_](https://docs.google.com/document/d/17OdI43AOrlDCpyNMN1hYsl0pk5xjnOLWeo5HmKa-ylI/edit)
- [x] Table copy _[In Axure](https://t81vx1.axshare.com/#g=4&p=revenue_table_-_alt)_

New glossaries:
- [x] Non-commodity revenue [_In the same as above (limited access)_](https://docs.google.com/document/d/17OdI43AOrlDCpyNMN1hYsl0pk5xjnOLWeo5HmKa-ylI/edit)
- [x] Accounting year _Already in glossary, but see comment above_

**Comment by mcharg** [comment]
I'll update the prototype to match the new copy, so @master12 only has to look in one place.

**Comment by mcharg** [comment]
@brentryanjohnson there are some additional glossaries needed in some of the other views.  I'll add them as checkboxes above as I notice them.

**Comment by brentryanjohnson** [comment]
Withheld is also already in the glossary, @mcharg. What do you mean by "(organize by location or drill to oil)"?

**Comment by mcharg** [comment]
@brentryanjohnson Those are the ways you can view where the glossary is in the prototype.

**Comment by mcharg** [comment]
Updates are made in the prototype.  @brentryanjohnson Some open questions are noted in responses to your Axure comments.

**Comment by jennmalcolm** [comment]
Yes, @brentryanjohnson I think the trend column is fine. I think we need to re-work the accounting year definition. Maybe even an example would help for understanding. I don't think that we can fit that into the glossary, but we should make sure our whole team understands it so that we can refine the definition at least.

**Comment by brentryanjohnson** [comment]
"Non-commodity revenue" and "Revenue not tied to a lease" are essentially the same, as I understand it. Please review @mentastc...

>Non-commodity revenue is not tied to a single commodity. It includes revenue collected from a contract or company, such as inspection fees and civil penalties.

>Revenue not tied to a lease includes revenue collected from a contract or company (such as civil penalties) that are related to accounting or reporting rather than specific commodities or leases.

**Comment by jennmalcolm** [comment]
What does revenues collected from a contract mean?

**Comment by brentryanjohnson** [comment]
@jennmalcolm "Contract" was referenced in some of the language for these definitions in the back and forth last week. I was going to follow up with @mentastc this week on the meaning of "contract" here (agreement?), since we don't want a term in a glossary definition that we further need to define.

**Comment by mcharg** [comment]
Data Governance has decided to use "contract" to mean either lease or agreement.  I know I talked about it with one user and it was a new word for him, but said he was going to use it going forward after thinking about it.

**Comment by jennmalcolm** [comment]
Yes, I have heard people at ONRR use contract as a stand-in for lease or agreement, but even when money is collected for a specific lease or agreement, it is paid by a company. Maybe we can just take out the contract part to make it simpler. Either that or we need to reword it so it's clear that the payment relates to a specific contract, not that it's paid by a contract. Maybe just changing the from to a for is better. Also for the second definition, if it is not tied to a lease, then it has to be on a company basis, so you should take contract out of that one.

**Comment by brentryanjohnson** [comment]
How about these edits, @jennmalcolm?

>Non-commodity revenue is not tied to a single commodity. It includes revenue collected from a company, such as inspection fees and civil penalties, that doesn't derive from the production of a specific natural resource commodity.

>Revenue not tied to a lease includes revenue collected from a company (such as civil penalties) that are related to accounting or reporting, rather than specific natural resource commodities or leases.

**Comment by jennmalcolm** [comment]
Yes @brentryanjohnson, much better!
