### ISSUE TITLE
Build GOMESA Phase II disbursements tables

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3851]
https://jg5zya.axshare.com/#g=1&p=gomesa_c

**Comment by jennmalcolm** [comment]
Build tables on GOMESA page and 4 states.

**Comment by jennmalcolm** [comment]
Could we do something to the table or copy for the main disbursements table that indicates that those numbers are totals for the disbursements to state and local governments within those states? That doesn't seem clear to me right now. 

![image](https://user-images.githubusercontent.com/30806839/56292472-41e08d00-60f5-11e9-9303-32f8eb409429.png)
