### ISSUE TITLE
Normalize capitalization and glossary entries for chart units

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3855]
Some chart captions have units capitalized and omit the glossary explanations:

![show bar charts with captions with units Mwh and Mcf](https://user-images.githubusercontent.com/32855580/55571012-8150b780-56b9-11e9-8af7-3de66f85a6a4.png)

While other, more common terms are lower case and carry glossary entries:

![shows charts with lower case captions and glossary entries for tons](https://user-images.githubusercontent.com/32855580/55571073-9cbbc280-56b9-11e9-806a-a3f7c8399015.png)

**Comment by jennmalcolm** [comment]
Now that we've removed EIA data, this isn't a problem any more.
