### ISSUE TITLE
Update monthly files & homepage charts

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#3859]
Attached are the two monthly files that need to be uploaded.

- [x] Update homepage

- [ ] update download page language

- [x] Update download files
[monthly_production_04-2019.xlsx](https://github.com/ONRR/doi-extractives-data/files/3048808/monthly_production_04-2019.xlsx)
[monthly_revenue_03-2019.xlsx](https://github.com/ONRR/doi-extractives-data/files/3048810/monthly_revenue_03-2019.xlsx)

**Comment by mentastc** [comment]
@brentryanjohnson  any chance after stand up you wanna help me make this update, I might not need too much help.

**Comment by brentryanjohnson** [comment]
Sure, @mentastc.
