### ISSUE TITLE
Fix "jumpy" chart bug on homepage

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3873]
The homepage bar charts "jump" vertically on hover. The height appears to grow very slightly.

![Revenue and disbursements charts animation where chart unintentionally grows when user hovers on bar with mouses](https://user-images.githubusercontent.com/32855580/55839925-798c7b00-5ade-11e9-8334-f9d7f06f2e3a.gif)

**Comment by mcharg** [comment]
This is still an issue on the new homepage.

**Comment by mcharg** [comment]
@mojobnichols @jlouis-onrr Will this be fixed in the new repo?
