### ISSUE TITLE
Add Native American FY Data to downloads page

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#3881]
-Add Data to Native American revenues
-consider rework or adding a Native american revenue downloads page
-Add Native American data to the revenue tables. 

[Native American Revs FY06-18.xlsx](https://github.com/ONRR/doi-extractives-data/files/3069001/Native.American.Revs.FY06-18.xlsx)

[Native American Revenues CY06-18.xlsx](https://github.com/ONRR/doi-extractives-data/files/3074521/Native.American.Revenues.CY06-18.xlsx)

**Comment by mcharg** [comment]
I created #3901 for the filterable table, so I'm making this one be just for the downloads page.

**Comment by brentryanjohnson** [comment]
As I anticipated, one more link item in this list drops it onto a new line. I don't think this is a particularly intuitive nav pattern, so I'm exploring alternatives to the current sub-link layout.

![tab items for revenue by year, revenue by month, revenue by company, and native american revenue, with the latter on a new line](https://user-images.githubusercontent.com/32855580/56435225-8e120580-628c-11e9-908b-7416f16d5f8b.png)
