### ISSUE TITLE
Explore having additional columns broken out in filterable tables

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3889]

**Comment by mcharg** [comment]
Here's the table organized by revenue type with commodity broken out.  
https://docs.google.com/spreadsheets/d/1imb4Ai5pzvTief0DpcvcpcyxYSSvkmd39u_Q7BaGRBg/edit#gid=0

I'm now exploring what the worst case scenario looks like if you add all columns to see to what level we would want to allow users to do that.

**Comment by mentastc** [comment]
I like it, in the design I would make revenue type display in the following order: Bonuses, Rent, Royalties, Other Revenue
