### ISSUE TITLE
Make total revenue sentence interactive like the disbursement total sentence

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3890]
I think we should relocate the total revenue collected sentence under "Revenue trends by resources" so it can be interactive and the year & total can change like it does for disbursements.

![image](https://user-images.githubusercontent.com/40175688/55974497-fc2f4a80-5c44-11e9-9538-5bdbc4ac9e90.png)

![image](https://user-images.githubusercontent.com/40175688/55974542-16692880-5c45-11e9-8771-26634c0c0194.png)

![image](https://user-images.githubusercontent.com/40175688/55974565-28e36200-5c45-11e9-8865-456f02ed1c9e.png)

**Comment by jennmalcolm** [comment]
The sentence will be updated and corresponds to the megachart, which only has the most recent year. When we work on the new explore data page, we should keep it in mind that the behavior should be consistent between the sections, especially if we remove the megachart.
