### ISSUE TITLE
Build revenue trends section on home page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3892]
Build revenue trends and move well/dollar graphic on home page

https://bghlq2.axshare.com/#g=1&p=a__replace_land_category_with_revenue_type

**Comment by jennmalcolm** [comment]
Moving out of this sprint so that we can decide on which design (other options in #3950) to move forward with before spending valuable development time on this.

**Comment by mcharg** [comment]
Updated link above to reflect the change to revenue type instead of land category.
