### ISSUE TITLE
Decide what to test with users and make a plan

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3898]
Do we test:
- Current state of live site to see what's broken
- Prototypes of filterable tables
- Lease level data concepts

We need to decide on the next priority.

**Comment by mcharg** [comment]
We're going to plan on testing live builds and documenting usability issues, even if we don't fix them right away.  We'll start with the revenue table.  @Maroyafaied is starting a plan for testing that.

**Comment by Maroyafaied** [comment]
This is my first draft for a plan and interview guide (limited guide) https://docs.google.com/document/d/1mN9zkgkNkNgkrca7MsiDq0iVhGb_t48N8RlTqM3dqHg/edit

**Comment by mcharg** [comment]
@Maroyafaied Great start!  I put comments and edits in the doc.

**Comment by Maroyafaied** [comment]
I have incorporated the comments and edits. Is this good to close?

**Comment by mcharg** [comment]
Has @jennmalcolm reviewed the plan?

**Comment by jennmalcolm** [comment]
I reviewed it, made a few minor changes, and left a few comments in the document. Thanks!
