### ISSUE TITLE
Add sorting functionality and arrows to revenue filterable table

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3906]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/38ab1f83-fe6b-4ca3-b63b-19c628f4e715)

**Comment by jennmalcolm** [comment]
Taking this out of this sprint until #3954 is complete. I think we may need to discuss how we want things to sort before this can be worked.

**Comment by jennmalcolm** [comment]
I think this functionality will be added in #3954. We can verify once that issue is complete.

**Comment by mcharg** [comment]
Addressed in #3954
