### ISSUE TITLE
Consider adding "Not tied to a location" category to revenue homepage graph

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3929]
We should consider whether we need to add a new category to the revenue home page graph so that we do not confuse people when the totals do not equal the totals on the filterable table or the downloads page.  For the revenues that are blank in the onshore/offshore category, should we use "not tied to a lease federal" or something similar to what we will use on the filterable table?

I made the decision to leave non-royalty, bonus or rent revenues out of the graph rather than stick them into one of the categories we have, but if we can add a category so that the total is accurate, I think that would be helpful. 

There doesn't seem to be a totals problem for the disbursements graph, but I'm not sure what methodology is used to break those numbers down fully when presumably the source data for those categories are also coming from the royalty reports. I guess we could explore whether a similar methodology would allow us to fully break down revenues into the given categories.

![image](https://user-images.githubusercontent.com/30806839/56130591-56851f80-5f53-11e9-8bc6-3d9224a1cb43.png)

Alternatively, we have heard the suggestion that it might be nice to breakdown the revenues by revenue type. I'm not sure if we should go down this road since we would lose the consistency with the other graphs, but I'm open to others' opinions.

**Comment by mcharg** [comment]
I think we should be consistent across the graphs, since we saw in user testing that users expected the same colors to mean the same things even across the graphs and the map.

**Comment by mcharg** [comment]
We also need to consider adding "mixed exploratory" for production.  Maybe we combine that and the not tied to a lease into an "other".

**Comment by jennmalcolm** [comment]
A couple of things to consider:

1. I think labels like "federal - not tied to a location" and "mixed exploratory" are more useful than creating an "other" bucket. Either way, we might get more questions, but I think in the first case, we could put them in the glossary, and the "other label would be hard to explain since we're putting dissimilar items together. Could we just have two separate colors for those? We would only use the "federal - not tied to a location" for revenues and the "mixed exploratory" for production.

2. Before we add mixed exploratory to the homepage production graphs, we will need to work with DORC to get that production added to the monthly files. They have not been including that on the monthly data thus far.

**Comment by jennmalcolm** [comment]
Until we get the new categories figured out, maybe we should remove the word total from the revenue and production tabs. Could we say something like "Revenue/Production by land class/ownership" instead since neither of those are truly representing totals right now? What do you think @mcharg and @brentryanjohnson?

![image](https://user-images.githubusercontent.com/30806839/66493774-9e10e200-ea84-11e9-8ec5-b010e04a2886.png)

**Comment by mcharg** [comment]
I think we could just have one color for the additional item on each graph - no need to have different colors if they're not on the same graph.

I'm okay with dropping the "total" from the label until it's total, though we probably should also change the label for the total at the bottom of the legend, as well.

**Comment by mcharg** [comment]
Here's a fourth blue we can add to the graphs #032435. It probably makes sense to shift the colors so that the new one is the lightest, since that is likely to be the smallest number.

**Comment by jlouis-onrr** [comment]
thanks, that totally makes sense to me
