### ISSUE TITLE
Explore associating bar charts with the filterable table and/or trend lines

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3949]
"Can we see bar charts associated with the filterable tables and/or trend lines? Bar charts are preferable."

**Comment by mcharg** [comment]
This shows what we looked at for bar charts in place of the sparklines (option C).
https://4cawh1.axshare.com/#g=1&p=sparklines

**Comment by mcharg** [comment]
This prototype has the chart toggle that incorporates charts (some of which are bar) into the filterable table.
https://gy12zi.axshare.com/#g=1&p=revenue_table_-_alt

**Comment by mcharg** [comment]
@jennmalcolm I'm assuming further work on this can wait until a later sprint after we finalize the filterable table, correct?  In the meantime, we can show the above if we want to show progress and get some feedback on direction.

**Comment by mcharg** [comment]
The new Explore Data page is also heavy on bar charts.
https://4cawh1.axshare.com/#g=1&p=explore_data

**Comment by jennmalcolm** [comment]
Let's come to a direction for explore data first or as a part of this exploration.

**Comment by mcharg** [comment]
@jennmalcolm Do you think we're covering this with Explore Data or do we need to keep it open?

**Comment by jennmalcolm** [comment]
Since this would allow very customized graphs, I think it is somewhat different. It seems like there wasn't much of a user need for this though based on the reserach we've done. Is that correct? If so, we can close it and do more research once explore data is done.

**Comment by mcharg** [comment]
We haven't heard from any users who want to make graphs out of the filterable tables.  They would do that in Excel after downloading the data.
