### ISSUE TITLE
Add revenue types to homepage trends

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3950]
"Trends in revenue types would be good information – Bonus, royalties, rents."

**Comment by mcharg** [comment]
@jennmalcolm Should this issue come into the current sprint?

**Comment by jennmalcolm** [comment]
If you can fit it in to figure out how to incorporate this, that's the first step. We can do that this sprint. Can you @mcharg and @mentastc work on ideas together?

**Comment by mentastc** [comment]
Here's my first take at how to add reveneu type to the bar chart.

![image](https://user-images.githubusercontent.com/15347998/56215252-56f1e900-602d-11e9-8705-269bff5e658d.png)

**Comment by jennmalcolm** [comment]
I don't think it necessarily needs to be in the graph (and Shannon has documented some reasons for keeping the graph colors consistent in #3929 , so we should also explore ways to incorporate it into the trends section. One idea I had is to add a percentage breakdown of the current year revenue totals by royalties, bonuses, and other. We could do that under each section (Native American, fed offshore, fed onshore) or just as a whole if it would get too crowded. I'm sure there are other ideas to explore.

**Comment by jennmalcolm** [comment]
Or maybe add a pie graph somewhere. There seems to be a lot of focus on pie graphs.

**Comment by mcharg** [comment]
If anyone can get Excel to behave, we could do a snappy nested pie chart that shows a different ring for each year.  I wanted to get all the pieces for each land category to be the same color as the bar charts with a different pattern for each revenue type, but I couldn't get it to do that.  It only lets me change the legend color for each category, but it doesn't update the section on the pie. :(

It's hard to tell whether this could work if we can't get the tools to work.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ce851909-1abc-4e4e-83a2-d5865752530b)

**Comment by mcharg** [comment]
I figured out the coloring.  It's not pretty, but it shows what it looks like if we try to make a pie chart show trends.  
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ed05086a-cdac-4573-9292-fdac9088a0ef)

**Comment by jennmalcolm** [comment]
This looks interesting. I would have a hard time figuring out trends from this because of its complexity, but we could show it to users to see if they understand how it shows trends. It also doesn't provide trends with the overall totals. I assume we would be keeping the revenue graph that we have now for that. 

Could we also try a simpler pie graph by revenue type for the most recent month or year to date to correspond with the new revenue trends section?

**Comment by mcharg** [comment]
Here's what a sankey diagram looks like.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e767a7b2-2934-43c9-b58e-392c0794d869)

**Comment by mcharg** [comment]
Here's a single year pie.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f4d8d735-c96c-4a3b-a0c2-bd7284d3c8f0)

**Comment by mcharg** [comment]
And a simpler one that removes land category.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/aa360a1c-0168-472c-a6e9-f38359c81331)

**Comment by mcharg** [comment]
This is what it looks like if we swap out land category for revenue type.  We've got land category covered in the bar chart.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/218dca4b-7f28-4368-9f3e-0c0fefc318cc)

**Comment by mcharg** [comment]
And if we add a selector to let the user pick whether they want revenue type or land category.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/523ce95e-d90d-4c77-8e2e-a5c2fc8a46cc)

**Comment by mcharg** [comment]
The spot on the homepage is too small for the nested pie or the sankey.

The simpler pies don't show trends, so they don't belong under a "revenue trends" heading, so not sure where to put them.

**Comment by mcharg** [comment]
We could also try a line chart that shows trends for each of the revenue types and land categories.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/fb16cd75-1084-4bc8-b369-b24eaf0e969c)

**Comment by mentastc** [comment]
Could we do a pie chart with a drop down box for land class?

**Comment by mcharg** [comment]
@mentastc and a drop-down for year, as well?

**Comment by mentastc** [comment]
I guess, it felt simple when I saw the simple pie chart but having two drop down might be strange. May be a slider for year, idk

**Comment by mentastc** [comment]
![image](https://user-images.githubusercontent.com/15347998/56373207-78d6a180-61ce-11e9-9929-864e698be4e1.png)

**Comment by mcharg** [comment]
@mentastc ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c15016ee-b475-4533-8fcd-88fd7b922d8b)

**Comment by mentastc** [comment]
I like that and think its fairly simple to understand.

**Comment by mcharg** [comment]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/36d8433b-99fb-4feb-953b-f9e1f3f19af8)

**Comment by jennmalcolm** [comment]
@mcharg can you make the royalty and bonus color vary more? They are hard for me to differentiate.

**Comment by mcharg** [comment]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/05e90674-53eb-487f-82cb-5529f9b0f51f)

**Comment by mcharg** [comment]
@jennmalcolm Those are the same green shades we're using in the horizontal bar charts that were the most differentiated I could make 4 shades of green looking at an accessibility checker.

**Comment by mcharg** [comment]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4abb103c-f14d-4894-9a5c-fc6562284f06)

**Comment by jennmalcolm** [comment]
Ok @mcharg I guess it was not the shades that I'm having trouble with. I think I was not realizing that the inside ring is divided up for each section of the outside ring and so we have three royalty slices on the inside.

**Comment by mcharg** [comment]
@jennmalcolm Does removing the borders between slices help?
![image](https://user-images.githubusercontent.com/38465926/56429668-bea86e00-6291-11e9-8d8f-f92c82864b1d.png)

**Comment by mcharg** [comment]
This pulls all of the options together to include with the weekly update email, so we can try to get some feedback.
[https://app.zenhub.com/files/21627244/5aa23726-6c88-40ce-afdf-176f96fdfbb0/download](https://app.zenhub.com/files/21627244/5aa23726-6c88-40ce-afdf-176f96fdfbb0/download)

**Comment by jennmalcolm** [comment]
I like it better without the borders, but it's hard for me to tell if that makes it clearer since now I know how it works. Let's discuss our options with the team.
