### ISSUE TITLE
Downloads file names

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3952]
Currently, we are updating monthly files in two places (data-graphql and downloads) for the monthly updates. @master12 is going to change the graphql reference for the homepage garph builds to the downloads folder and create subfolders for each data type so that we will only need to update the file in one place. 

![image](https://user-images.githubusercontent.com/30806839/56223947-bdcace80-603c-11e9-8807-6228a98ebef7.png)

We need to change the downloads references for production and revenue to the standard names that Jeff will be using so we do not have a new downloads file name each month. The file name and reference should remain the same. 

After these changes, we should delete all of the old files (like below) that we do not need anymore. 

![image](https://user-images.githubusercontent.com/30806839/56224041-e9e64f80-603c-11e9-83bc-b92e0316dfe8.png)

**Comment by master12** [comment]
Also update web page to connect to the github api to pull in comments, file size and other info to display on the web page

**Comment by brentryanjohnson** [comment]
This has been resolved.
