### ISSUE TITLE
Build updated filterable table design

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3954]
https://t81vx1.axshare.com/#g=1&p=revenue_table_-_stats_plus

Differences from current state:
- Add drop-downs to select land category and location
- Land category rolls up the current land owner and source columns
- "organize by" changes to "first column"
- "add columns" changes to "second column" and users can only add one second column
- Second column that's added is broken out
- Shading on total rows

**Comment by mcharg** [comment]
@jennmalcolm Should this go into the current sprint or wait until next sprint?

**Comment by jennmalcolm** [comment]
I think it will need to wait until next sprint in looking at the workload. I did remove two filterable table issues from this sprint that I think we may need to discuss more before implementing. If @master12 has any extra time in this sprint, we could bring this issue in.
