### ISSUE TITLE
Check fiscal year data files against monthly graphs

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#3955]
I will verify that the revenue annual fiscal year data numbers match the monthly graphs on the home page.

**Comment by jennmalcolm** [comment]
Since the monthly graphs are not working, just use the monthly file to check against the fiscal year file.

**Comment by Maroyafaied** [comment]
There is a slight difference ($7,991) and its from onshore. I will email the excel sheet.

**Comment by jennmalcolm** [comment]
@mentastc is working with DORC about these differences. We may need to do #3983 to resolve these types of differences.
