### ISSUE TITLE
Investigate suspected missing value for location in revenue table

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3973]
There's a comma leading the location values for "Other Revenues" in the revenue table. This issue seems to be indicative of a missing value, but we should investigate to confirm.

![table row showing states and offshore regions with a comma at the beginning highlighted](https://user-images.githubusercontent.com/32855580/56397168-50af6880-61f7-11e9-83c8-025c55611163.png)

**Comment by mcharg** [comment]
I bet it’s items with blank locations because they’re not tied to a lease.  See #3911.

**Comment by jennmalcolm** [comment]
This might be fixed through #3911.

**Comment by mcharg** [comment]
Closing in favor of #3911.
