### ISSUE TITLE
Change 404 message

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#3976]
Our "Not found" 404 currently shows the following:

>NOT FOUND
>You just hit a route that doesn't exist... the sadness.

While [there's been a trend for some time](https://www.cnbc.com/2015/07/31/13-of-the-internets-best-404-error-pages.html) to add humor to 404 pages, it's presumably best done when (1) the humor is related to the content somehow and (2) the tone of other site content facilitates humor. I don't believe either of these to be true of our current 404 message.

We should consider revising the message and format ("NOT FOUND" shouldn't be shouting, followed by an attempt at humor).

**Comment by jennmalcolm** [comment]
Ok,, @brentryanjohnson, I agree. Do you have suggested wording?

**Comment by brentryanjohnson** [comment]
Pulling this into sprint, @jennmalcolm. I'm still working on the wording, but I should have a PR soon.

**Comment by brentryanjohnson** [comment]
Current state:

![404 page says Not Found, you just hit a route that doesn't exist...oh the sadness](https://user-images.githubusercontent.com/32855580/57000201-5dbd4780-6b67-11e9-8d33-1794f848df34.png)

**Comment by brentryanjohnson** [comment]
Fix in PR #4029
