### ISSUE TITLE
Explain where data for homepage graphs comes from.

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#3980]
Due to variances in our data sets, and until we can get to the point of having one file for each data type, we need to make it clear where the homepage graph data is coming from. Right now, the annual numbers are coming from the annual data sets and the monthly numbers are coming from the monthly data sets. There are many variances between those data sets for production, and slight variances in the revenue files.

Could we add a "Where does this data come from?" link somewhere on the homepage to provide this explanation and maybe links to the specific download pages for the files.

**Comment by Maroyafaied** [comment]
I think this issue kind of relates to issue #3942 which @lpgoldstein and I are working on. If we add a link that explains where the graph data is coming from, it should also include a brief description of how to use the data.

**Comment by jennmalcolm** [comment]
Another thing we need to think about here, even before explaining it is if the homepage graph data sources are all the best option. FY annual numbers are coming from the fiscal year files, which I think makes sense because they will match with the FY numbers in the data table. Monthly obviously needs to come from the monthly files. Right now, are the CY numbers coming from the monthly files? If so, perhaps we need to change this to the CY files for consistency.

**Comment by jennmalcolm** [comment]
First steps: come up with a design on how to make the explanation easy to access from the home page and write copy for explanation.

**Comment by mcharg** [comment]
Explain the relationship between monthly and annual numbers.

**Comment by Maroyafaied** [comment]
@lpgoldstein @jennmalcolm looks like we already explain the variance on summing the totals on the monthly download page 
![image](https://user-images.githubusercontent.com/40175688/70087345-63817c80-15d1-11ea-9003-a1815374ba9f.png)

**Comment by Maroyafaied** [comment]
We created a file listing all the source files from the charts on homepage and did a prototype on axure for the source file links.  I will close this issue, and open another one to create the links on the homepage.

https://sjzq35.axshare.com 

https://doimspp-my.sharepoint.com/:w:/r/personal/goldstel_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B7B57AFC1-6A10-4602-8C06-1DF8CB62A4AB%7D&file=Data%20for%20homepage%20graphs.docx&action=default&mobileredirect=true
