### ISSUE TITLE
Explore consolidated data spreadsheets  (monthly instead of yearly)

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#3983]
-Explore with Data Retrieval and with Data Display what it would look like and what what the issues would be if we received only monthly revenue, production, and disbursement files. that included UDR and location information but would not go to the planning area.

**Comment by jennmalcolm** [comment]
DORC is working on giving us an example dataset.

**Comment by jennmalcolm** [comment]
DORC is working on getting us the files in this format.
