### ISSUE TITLE
Practice Government UX Summit Presentation

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3998]
We have a session set up when Shannon is in the office and there's one to figure out the remote technology that will be used the day of the conference.

**Comment by mcharg** [comment]
@Maroyafaied I decided to add more images to the presentation while I was practicing.
[UX Summit Presentation_043019.pptx](https://github.com/ONRR/doi-extractives-data/files/3133102/UX.Summit.Presentation_043019.pptx)

@jennmalcolm You might be able to use some of the images for the DotGovDesign presentation.

**Comment by jennmalcolm** [comment]
Thanks @mcharg I was taking too much time looking for images, so I asked @lpgoldstein to help me. These could make it easier of her.

**Comment by mcharg** [comment]
Updated presentation after practicing: 
[UX Summit Presentation_050219.pptx](https://github.com/ONRR/doi-extractives-data/files/3138882/UX.Summit.Presentation_050219.pptx)
