### ISSUE TITLE
Update production filterable table to match new revenue filterable table design

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#3999]
So they match.

**Comment by mcharg** [comment]
This isn't done yet because I had to pull in the new production data format.

**Comment by mcharg** [comment]
@jennmalcolm Are we going to start with just FY production to match revenue?

**Comment by mcharg** [comment]
Default view:
https://wm3k5u.axshare.com/#g=1&p=production_table

Oil (single commodity - adds a column and moves sorting from the drop-down to column headers):
https://wm3k5u.axshare.com/#g=1&p=oil

California (single location - adds County as a column to add ):
https://wm3k5u.axshare.com/#g=1&p=california

**Comment by jennmalcolm** [comment]
Yes, we can start with FY.

**Comment by mcharg** [comment]
Closing until we decide what to do with the revenue table.  We still need to figure out what to do with withheld data, which maybe we can address as part of #4051.
