### ISSUE TITLE
Revenue by county maps missing on state pages

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4004]
Revenue by county maps are missing on state pages.

## Production
![Revenue from production on federal land by county section with drop down but no content](https://user-images.githubusercontent.com/32855580/56707462-c58a1300-66cd-11e9-90ec-478b576df897.png)

## Before
![Revenue by county section showing choropleth map of relative revenue](https://user-images.githubusercontent.com/32855580/56707491-f79b7500-66cd-11e9-9c09-56abea6d827e.png)

**Comment by mcharg** [comment]
@master12 is this done?  It's sitting in Ready to Review without being assigned to a sprint.
