### ISSUE TITLE
Update Wiki data type table

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#4011]
After completing the data documents audit, we need to update this [data types overview page](https://github.com/ONRR/doi-extractives-data/wiki/Data-Types)

**Comment by Maroyafaied** [comment]
![image](https://user-images.githubusercontent.com/40175688/62878071-97b0f480-bce5-11e9-86e9-9ad0bd1edd43.png)

**Comment by Maroyafaied** [comment]
![image](https://user-images.githubusercontent.com/40175688/62882991-5114c780-bcf0-11e9-8cdb-ab1f966933d9.png)

**Comment by Maroyafaied** [comment]
@jennmalcolm @brentryanjohnson @lpgoldstein please review the updated data types table.  I did not add a separate row for Native American revenue since the plan is to consolidate the files. 

https://github.com/ONRR/doi-extractives-data/wiki/Data-Types

**Comment by lpgoldstein** [comment]
@Maroyafaied this looks good to me. Maybe just capitalize "states" in the row for consistency.
