### ISSUE TITLE
Mobile State selection Wheel

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#4013]
When in mobile the state selection scroll is alphabetized but with several states out of order. For instance Colorado is at the end and Washington DC is in the C's. 

![IMG_2624 (1)](https://user-images.githubusercontent.com/15347998/56918048-06e24000-6a8b-11e9-9759-07d3073da59e.jpg)

**Comment by jennmalcolm** [comment]
This is not just mobile, but it is probably more obvious there since you need the drop down to navigate. Ryan did create #3520 for this issue.

**Comment by mcharg** [comment]
Fixed with #5320
