### ISSUE TITLE
Update Native American Production Page

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#4037]
Update Native American production Page with new numbers and correct text. Or when we create the Production tables this page should maybe be deleted.

Data file:
[FY Indian Production Data 2009-2018.xlsx](https://github.com/ONRR/doi-extractives-data/files/3142804/FY.Indian.Production.Data.2009-2018.xlsx)

**Comment by jennmalcolm** [comment]
We didn't get this done with the refactor, so this still needs to be done. We can just hard code it for now to get the updated numbers live.

**Comment by brentryanjohnson** [comment]
Closing this issue because we have the data in the query tool now. I have an open PR to remove the data from how-it-works.
