### ISSUE TITLE
Due 5/15: Proposal for Global LEAP book case study

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4046]
http://globalleapbook.com/

Maybe an opportunity to reuse some of what was in the other book chapter.

**Comment by mcharg** [comment]
Draft proposal:
https://docs.google.com/document/d/1gQMpbsy-pz3ZNE4f-HQM8_wkY5M7E3GF_bPC8Cxdq28/edit

@jennmalcolm @lpgoldstein @brentryanjohnson Do any of you have time to take a quick look before I submit?  It's due tomorrow.

**Comment by jennmalcolm** [comment]
I added a few suggestions.

**Comment by mcharg** [comment]
Submitted
