### ISSUE TITLE
Build national revenue choropleth map

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4048]
Our current national map (with offshore areas) shows land ownership by type, but we've discovered a revenue choropleth map would be more useful and informative to DOI leadership and users.

We've [explored styles for this](https://github.com/ONRR/doi-extractives-data/issues/3281) and prototyped a [revenue by county choropleth map](https://github.com/ONRR/doi-extractives-data/issues/3861).

We determined that building a state choropleth would allow us to both present the revenue for each state _and_ retain the navigational behavior of the map (to link to state and offshore pages).

**Comment by jennmalcolm** [comment]
For the homepage, we should build a version of revenue by state so that the map can be used to navigate to state pages. An example is in @mcharg's design https://88sw92.axshare.com/#g=1&p=back_to_tabs
