### ISSUE TITLE
Add note under Location drop-down when an option including Native American data is selected for Land Category

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4055]
![image](https://user-images.githubusercontent.com/38465926/57374097-17b84300-7168-11e9-9606-dc9b3f244d7f.png)

@brentryanjohnson to draft final copy.

**Comment by brentryanjohnson** [comment]
> For privacy reasons, location is <GlossaryTerm>withheld</GlossaryTerm> for Native American data.

**Comment by mcharg** [comment]
@master12 Can you make the note be a smaller font and also move up the Apply button into the same horizontal row, so it's not so separated from the drop-downs?

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/85ae2a06-4af2-450e-9144-d3def366d054)
