### ISSUE TITLE
Recruit participants for revenue filterable table user research

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4060]
Once we release the table, we'll be ready to start testing, so we should start reaching out to participants.

**Comment by Maroyafaied** [comment]
@mcharg @jennmalcolm , two of the people we reached out to are available to participate in user testing next week. Do you think we are ready to test then or should we wait till next sprint?

**Comment by mcharg** [comment]
I think we'll be ready.

**Comment by Maroyafaied** [comment]
@mcharg Do we have a recruiting email template for people we interviewed previously?
