### ISSUE TITLE
Update revenue download and documentation page 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/doi-extractives-data#4064]
https://revenuedata.doi.gov/downloads/federal-revenue-by-month/
https://revenuedata.doi.gov/downloads/federal-revenue-by-location/
https://revenuedata.doi.gov/downloads/federal-revenue-by-company/
https://revenuedata.doi.gov/downloads/native-american-revenue/

**Comment by jennmalcolm** [comment]
End goal is to follow the decisions from data documentation to implement to implement consistency across the field names and the definitions.
