### ISSUE TITLE
Add county/CPS as a column option when filtered to a single location in the revenue filterable table

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4070]
So we can get to a view like this:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e4d2389f-9328-4e9b-801d-2bded2a25195)

**Comment by jennmalcolm** [comment]
Should be an option for group by or additional column

**Comment by mcharg** [comment]
Fixed in query tool.
