### ISSUE TITLE
Add drop-down logic to remove redundant option in the revenue filterable table

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4071]
If the user selects "federal onshore", "federal offshore", or "Native American" from Land Category, Land Category shouldn't be an option in the Group by drop-down.

If the user selects anything except "All" from the Location drop-down, Location shouldn't be an option in the Group by drop-down.

**Comment by jennmalcolm** [comment]
This could also be handled by taking the approach to walk the user through the steps one by one.

**Comment by mcharg** [comment]
Will be addressed with new design.
