### ISSUE TITLE
Update CY Revenue data on site

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#4075]
- [x] Review CY Revenue from DR

- [ ] Update Site visuals with new CY Revenue data (you may notice we got data going back to 03

Data: 
[CY 03-18 Federal Revenues.xlsx](https://github.com/ONRR/doi-extractives-data/files/3192443/CY.03-18.Federal.Revenues.xlsx)

**Comment by jennmalcolm** [comment]
First step because we haven't been able to refactor for new consolidated file is to break into onshore and offshore and then we can run existing make files.

**Comment by mentastc** [comment]
CY revenue files broke out into 3 files so that the data update can use the old process:

Federal Onshore:
[federal_revenue_onshore_acct-year_FY06-18.xlsx](https://github.com/ONRR/doi-extractives-data/files/3188180/federal_revenue_onshore_acct-year_FY06-18.xlsx)

Federal Offshore: 
[federal_revenue_offshore_acct-year_FY06-18.xlsx](https://github.com/ONRR/doi-extractives-data/files/3188183/federal_revenue_offshore_acct-year_FY06-18.xlsx)

Not Tied to Lease: 
[federal_revenue_civil-penalties_other-rev_not-tied-to-lease_acct-year_FY06-18.xlsx](https://github.com/ONRR/doi-extractives-data/files/3188185/federal_revenue_civil-penalties_other-rev_not-tied-to-lease_acct-year_FY06-18.xlsx)

**Comment by brentryanjohnson** [comment]
@mentastc They all appear to be FY files.

**Comment by mentastc** [comment]
The data is CY, sorry I used an FY file to get file headers, I'll make sure the fix the file name.

**Comment by mentastc** [comment]
@brentryanjohnson, I'll attempt to do the download files

**Comment by mentastc** [comment]
@brentryanjohnson, in checking the data a found about 40 lines of data that incorrectly labeled commodity and "other products" I've updated the onshore and offshore files that need to be used. I'm sorry that it wasn't caught earlier. I only noticed it because of the graphs on the site looked strange. 

Federal Onshore
[federal_revenue_onshore_acct-year_CY06-18.xlsx](https://github.com/ONRR/doi-extractives-data/files/3228384/federal_revenue_onshore_acct-year_CY06-18.xlsx)

Federal Offshore
[federal_revenue_offshore_acct-year_CY06-18.xlsx](https://github.com/ONRR/doi-extractives-data/files/3228385/federal_revenue_offshore_acct-year_CY06-18.xlsx)

**Comment by brentryanjohnson** [comment]
Okay, @mentastc. I won’t be able to change it this week, because I won’t have my Mac while traveling. Also, @master12 used my branch with the revenue data updates for #4115, so he’ll need to change that branch, too.

**Comment by jennmalcolm** [comment]
I think the updates in #4115 should be fine since the revenue county maps are not done by commodity, and the issue was just the commodity labels for some lines.  

Also, @master12 is going to work on refactoring the revenue data update first this sprint, so we shouldn't need to do it again the old way @brentryanjohnson.

**Comment by jennmalcolm** [comment]
Should be done as part of #4121

**Comment by jennmalcolm** [comment]
Closing in favor of #4121.
