### ISSUE TITLE
Update Revenue by Company homepage link

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4092]
It's still linking to the 2017 page, but now that we have the 2018 page it should link to that.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/2e014ad3-3763-46f7-a1d6-75147a89a995)

**Comment by jennmalcolm** [comment]
Also need to update links and year reference on main how it works page
![image](https://user-images.githubusercontent.com/30806839/57808811-2b4c4680-7732-11e9-8e51-e08af9dfe7da.png)
