### ISSUE TITLE
Duplicate sparklines, oh my!

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4097]
Here's a weird one...

The sparklines load as expected...
![homepage showing sparklines, which are trend lines, for royalties, bonuses, rents, other revenues, and total revenues](https://user-images.githubusercontent.com/32855580/57813859-80825b00-7726-11e9-8548-f657d97855ff.png)

But when one clicks an in-page link, for instance this one...
![homepage showing sparklines, which are trend lines, for royalties, bonuses, rents, other revenues, and total revenues, with a link Data by state highlighted](https://user-images.githubusercontent.com/32855580/57813931-c3dcc980-7726-11e9-8360-823996a2eb9e.png)

...and scrolls back up, one finds duplicate sparklines!
![homepage showing sparklines, which are trend lines, for royalties, bonuses, rents, other revenues, and total revenues, but now there are two sets of sparklines for each entry](https://user-images.githubusercontent.com/32855580/57813965-e7077900-7726-11e9-9ae2-72b1ae3b690f.png)

I personally think this is a cool easter egg, but we should fix it anyway. ;)

**Comment by mentastc** [comment]
Guess what happens if you click the in page link a second time????

**Comment by brentryanjohnson** [comment]
Yes, another round of sparklines are added for each in-page link click.

**Comment by brentryanjohnson** [comment]
This no longer appears to be a problem. Closing.
