### ISSUE TITLE
Remove "null sdass" for not tied to location on revenue table 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#4110]
fix the highlighted wording below when there is no data for not tied to location 
![image](https://user-images.githubusercontent.com/40175688/58184128-c03ccb80-7c6d-11e9-9ebf-8e6ddd593756.png)

**Comment by jennmalcolm** [comment]
Issue is that we shouldn't have "not tied to location" if onshore, or offshore is slected in the land category.

**Comment by mcharg** [comment]
This appears to be fixed in the query tool.
