### ISSUE TITLE
Add space between static content and data variables

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4112]
We have a few instances in which we lack space between static content and variables injected from the data updates, which is difficult to read. We should add space between them.

![shows revenue for oil, gas, and NGL, but the labels run into the data - no space between them](https://user-images.githubusercontent.com/32855580/58212717-a10d6080-7ca4-11e9-969b-9057c4691803.png)

![Shows value of $111,832,792, with a note explaining the number includes revenues not tied to specific commodities, but inspection fees and the comma after lacks space before the number $3,072,809](https://user-images.githubusercontent.com/32855580/58212741-b1bdd680-7ca4-11e9-8080-87ba4d7e1008.png)

**Comment by jennmalcolm** [comment]
The issue is on the megachart.
