### ISSUE TITLE
Refactor revenue data update

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4121]

**Comment by mentastc** [comment]
Below are combined (Federal and Native American) FY and CY Files & the Monthly Revenue file:

Annual FY Revenue
[FY 03-18 Federal and Native American Revenues.xlsx](https://github.com/ONRR/doi-extractives-data/files/3233007/FY.03-18.Federal.and.Native.American.Revenues.xlsx)

Annual CY Revenue
[CY 03-18 Federal and Native American Revenues.xlsx](https://github.com/ONRR/doi-extractives-data/files/3233006/CY.03-18.Federal.and.Native.American.Revenues.xlsx)

Monthly Revenue 
[monthly_revenue_04-2019.xlsx](https://github.com/ONRR/doi-extractives-data/files/3233015/monthly_revenue_04-2019.xlsx)

**Comment by jennmalcolm** [comment]
Revenue by location data references:
[Homepage revenue chart (FY/CY)](https://revenuedata.doi.gov/)
[Revenue table (FY)](https://revenuedata.doi.gov/explore/revenue/)
[Explore data mega chart and resource graphs (CY)]( https://revenuedata.doi.gov/explore/#revenue)
[Downloads (FY and CY)](https://revenuedata.doi.gov/downloads/federal-revenue-by-location/)
[Native American revenue page (FY)](https://revenuedata.doi.gov/how-it-works/native-american-revenue/#revenue-data)

**Comment by jennmalcolm** [comment]
I forgot to mention that the state and offshore pages also reference the revenue data.

**Comment by mcharg** [comment]
@master12 Is this done?
