### ISSUE TITLE
Audit Native American and federal revenue data downloads pages 

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4126]
Chris combined the federal and Native American downloads into one file each for FY and CY to simplify the download experience for users. Now we need to update the download page structure to reflect this change.

**Comment by jennmalcolm** [comment]
combined files in #4121

**Comment by jennmalcolm** [comment]
This includes rewriting the documentation as necessary.

**Comment by jennmalcolm** [comment]
@mentastc will document what needs to happen with the downloads pages to accomplish the cosolidation

**Comment by mentastc** [comment]
Edits to main download page:
![image](https://user-images.githubusercontent.com/15347998/62377312-88c18980-b510-11e9-8599-5e3f343b864b.png)
Edits to Revenue by year:
![image](https://user-images.githubusercontent.com/15347998/62377809-7bf16580-b511-11e9-9fa1-4799ebffcc6a.png)

**Comment by brentryanjohnson** [comment]
@jennmalcolm: @mentastc suggests adding Native American to the Federal revenue by company section (see above), but I assume that's a mistake, and he means revenue by year. Can you confirm?

**Comment by mentastc** [comment]
Sorry, here's that edit applied to the paragraph above it. 

![image](https://user-images.githubusercontent.com/15347998/62479348-4354c480-b77b-11e9-9578-e4a29f93d848.png)
