### ISSUE TITLE
Find contact info for NGOs

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4130]
These were recommended someone who I met at the Code for America Summit.  I put them in the People tab of the market map, but we should find people to contact at each organization.

- [x] World Resources Institute (WRI)
- [x] Natural Resources Governance Index (NRGI)
- [x] Green Info
- [x] Wildlabs.net
- [x] Conservation x Labs

**Comment by mentastc** [comment]
Daniel Kaufmann, CEO NRGI, info@resourcegovernance.org

**Comment by mcharg** [comment]
The person who introduced me to Kate Winger just sent me a message saying she'll introduce me to someone from GreenInfo Network.
