### ISSUE TITLE
Find data journalism contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4131]
Look into ways to engage with the following organizations.

- [ ] National Institute for Computer-Aided Reporting https://www.ire.org/nicar
- [ ] Reveal - the Center for Investigative Reporting

**Comment by lpgoldstein** [comment]
Can contact through the website: https://www.ire.org/about/contact 
If that doesn't work then we can start contacting individuals on staff.

**Comment by lpgoldstein** [comment]
info@revealnews.org I think we should just send requests and see if they get back to us.
