### ISSUE TITLE
Post Virtual Student Federal Service Project (VSFS)

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/doi-extractives-data#4132]
Due June 10, 2019. The[ Virtual Student Federal Service (VSFS)](https://vsfs.state.gov/faq#supervisor_faqs) is an eight-month remote internship program for U.S. citizen students, college-level and above, who would like to make a real difference in the work of the U.S. government. Since 2009, thousands of eInterns have expanded the efforts of the U.S. government, working remotely from their school, dorm room, apartment, local library or coffee shop – wherever they happen to be! Virtual interns work only on unclassified projects. They report to their supervisors across the federal government at agencies in the U.S. and around the world by email, phone, or video chat. VSFS is managed by the Office of eDiplomacy in the U.S. Department of State’s Bureau of Information Resource Management. VSFS collaborates with federal agencies across government on this program. Students contribute 10 hours a week 

Needed Info: 
Agency
Office
Supervisors
Project title
Project summary
Project description
Desired Skills and Interests
Language requirements
Any other helpful information
How do mentors write a great project? Write a catchy title, Be as specific as you can, Say what you want, use plain language, Explain why your project matters

**Comment by mcharg** [comment]
Project title: UX Apprenticeship

Project summary: Explore all facets of user experience research and design at the Department of the Interior's Office of Natural Resources Revenue.  Work on our open data website that presents revenue brought in from natural resources extracted on federal lands and waters and other websites managed by our team.
 
Project description:
We are informing policy debates and raising public awareness by building the definitive source of timely and useful data about how the government manages federal energy and mineral resources, revenue, and disbursements.  You will participate in all aspects of user experience including recruiting participants, conducting user research, creating designs, and learning about how all of these fit into the overall process of developing a live, open source government product.  The exact tasks will depend on the intern's expertise and interest areas and the needs of our team throughout the internship period.

Desired Skills and Interests:
User experience design, user experience research, visual design, product management

**Comment by mcharg** [comment]
We should link to the blog in the descriptions to give people a sense for the team they'll be working with.
