### ISSUE TITLE
Add contact info to the bottom of the documentation pages

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4133]
Frame it to entice data journalists to contact us.  Something like "Want additional details about the data?" or "Want to ask us questions about the data?"

**Comment by jennmalcolm** [comment]
We have contact info to DORC on these pages, so maybe this is as easy as adding something like "or want to ask us questions on the data" to what's there.

**Comment by jennmalcolm** [comment]
Also remove the team name.
