### ISSUE TITLE
Explore date column in spreadsheet

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#4136]
We received feedback from BSEE Director staff (Via DORC) that the date being displayed in two column is hard to work wit hand that they would prefer the date appear in one column. 
-Explore options on for date column, that would make it easier to pivot

**Comment by jennmalcolm** [comment]
@mentastc could you ask DORC for the contact info of the person who provided the feedback? I would like to be able to talk to them to make sure we understand the problem (what task is hard to accomplish) before we move forward with solutions. The fact that it is hard is a good start, but just putting the month and year back in two columns would make some tasks harder. You and I discusses the possibility of adding a fiscal year column, but we should confirm if fiscal year is really the problem before we look at options for the date format.
