### ISSUE TITLE
Fix ambiguous units for production in choropleths

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4140]
The volume unit is being misinterpreted by users as a depth measurement (meters), rather than "millions". We should change it to eliminate this ambiguity.

![gulf production by region with units with the letter m highlighted](https://user-images.githubusercontent.com/32855580/59049569-2401ef80-883d-11e9-84fb-0414edffd69d.png)

It probably makes sense to do this when we refactor these offshore pages to Gatsby.

**Comment by jennmalcolm** [comment]
So, should we just spell out "million"?

**Comment by brentryanjohnson** [comment]
Yes, I think so @jennmalcolm. The only problem there is that it becomes "million-million cubic feet," but perhaps that's unavoidable given the ubiquity of "mcf" for the measurement?

**Comment by jennmalcolm** [comment]
The m in mcf is actually a thousand, another reason not to use m for million.

**Comment by brentryanjohnson** [comment]
Ah yes, because the "m" is a Roman numeral! So, yes, even trickier to convey it properly.
