### ISSUE TITLE
Program Analyst Blog Post

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#4153]
Write a blog post on data upload procedures or first pull request

**Comment by mentastc** [comment]
Blog post is currently being reviewed and can be found here:
https://docs.google.com/document/d/1jT_I1eaBW-3Ryygw0jHzx5nV0M4Dw8j0OLyjydW9Au0/edit?ts=5d0a53e5

**Comment by jennmalcolm** [comment]
Work to continue in #4195
