### ISSUE TITLE
Consistent commodities in revenue files

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4157]
With the consolidation of federal and Native American files, we should have the oil & gas category showing up as one consistent label. Right now, the federal lines show "Oil  & Gas (Non-Royalty)" and some lines show up with "Oil & Gas (Non Royalty)" (no hyphen), and the Native American lines just say "Oil & Gas." We should remove "non-royalty" since that is clear from the revenue type column and doesn't fit into the commodity field.

Related to #4121 and #4126.

**Comment by mentastc** [comment]
I updated the combined native american and federal files here:
[FY 03-18 Federal and Native American Revenues.xlsx](https://github.com/ONRR/doi-extractives-data/files/3302775/FY.03-18.Federal.and.Native.American.Revenues.xlsx)
[CY 03-18 Federal and Native American Revenues.xlsx](https://github.com/ONRR/doi-extractives-data/files/3302776/CY.03-18.Federal.and.Native.American.Revenues.xlsx)

We will need to restructure the download pages or to accommodate the combined files.

**Comment by jennmalcolm** [comment]
The download page restructure is in #4126, so @lpgoldstein could you do a peer review of these spreadsheets to make sure we didn't lose anything from the origin files, and then we could close this issue?

**Comment by lpgoldstein** [comment]
@jennmalcolm and @mentastc these files look good. I filtered the columns to make sure we had the correct labels in each column and then created pivot tables to make sure that the revenues matched the origin files.
