### ISSUE TITLE
Update on-boarding wiki page

### ISSUE THREAD

**Issue by echang97** [ONRR/doi-extractives-data#4159]
Some things to update on the wiki
- [x] Change references of Mural to [ZenHub](https://www.zenhub.com/)
- [x] Remove references to Waffle
- [ ] Remove references to Slack
- [ ] Change references of Styleguide to Pattern Library
- [x] Fix link to [Oblivious Orangutan](https://github.com/ONRR/doi-extractives-data/tree/research/research/21_obliviousorangutan_aug2018_keyfacts_exploredata) & [Fledgling Fox](https://github.com/ONRR/doi-extractives-data/tree/research/research/20_fledglingfox_jun2018_keyfacts)
- [x] Federalist Access

**Comment by jennmalcolm** [comment]
Made necessary updates to the Wiki. Thanks for keeping track of these @echang97. Next we will need to work on adding something for the development checklist.  Created #4161 for that next step.
