### ISSUE TITLE
Research and practice for initial data quality script

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4160]
After decisions on how to approach the data quality script in #4154, perform necessary research and practice potential solutions on real files.

**Comment by jennmalcolm** [comment]
@mentastc could you provide sample files in this issue?

**Comment by mentastc** [comment]
I'm going to give you a base file and then a new file to check against the base file.
Base file:
[monthly_production_05-2019.xlsx](https://github.com/ONRR/doi-extractives-data/files/3311614/monthly_production_05-2019.xlsx)

New file:
[monthly_production_06-2019.xlsx](https://github.com/ONRR/doi-extractives-data/files/3311615/monthly_production_06-2019.xlsx)

**Comment by jennmalcolm** [comment]
Next step in #4196
