### ISSUE TITLE
Write conditional logic to change 'county' to 'parish' or 'borough'

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4164]
#4115 adds back our state-level county choropleths for revenue, but "County" is hard-coded in. Some states, e.g., Louisiana and Alaska, refer to "county-level" local government divisions as Parishes or Boroughs instead. 

We should write conditional logic that determines which political subdivision terms we should use for the relevant states.

**Comment by brentryanjohnson** [comment]
Moving this into the sprint since we also need to refresh data before releasing.

**Comment by brentryanjohnson** [comment]
@master12 This is only relevant for two states:

- Alaska (should be "Borough" instead of "County")
- Louisiana (should be "Parish" instead of "County")

**Comment by mcharg** [comment]
@master12 Is this one done?
