### ISSUE TITLE
Document what each data file updates on the site

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/doi-extractives-data#4172]
Document what each data file updates on the site - such as charts and downloads. This will be within the update process documentation for each file.

**Comment by jennmalcolm** [comment]
@mentastc and @lpgoldstein I didn't notice this issue during our review. Is this being worked as part of your documentation?

**Comment by lpgoldstein** [comment]
@jennmalcolm Yes it is. I'll try to catch up with @mentastc tomorrow to get an update.
