### ISSUE TITLE
Explain "Mining-Unspecific"

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4185]
The terminology of the commodity "Mining-Unspecific" semantically transgresses the site's purpose, which (in this context) is to make transparent the revenue generation for specific commodities.

We should explain this commodity term, and add specificity and/or explanation.

**Comment by jennmalcolm** [comment]
This comes from the Native American revenue file. We should check with DORC on the reason and define it at a minimum.

**Comment by mentastc** [comment]
Response from DORC:

Right now the only product that falls under Mineral lease type Mining Unspecified is Humate.  Humate is a fertilizer.

-Andrew

**Comment by jennmalcolm** [comment]
@hasketta or @mentastc, does that mean that we could just replace the "commodity-unspecific" label for those lines in the data file with "Humate"? I'm not sure whether right now means currently produced or that it would apply to all the "mining-unspecific" data in the file.

**Comment by brentryanjohnson** [comment]
This is a low priority issue. Closing until it comes up again.
