### ISSUE TITLE
Add tag manager tags for additional in-page anchors to better track homepage usage

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4187]
- [x] Tabs on the homepage
- [x] Each section on the Explore Data page, so we can track clicks on links from the homepage
- [x] Each section on the Downloads page, so we can track clicks on the links from the homepage
- [x] Each section on the How It Works page, so we can track clicks on the links from the homepage

**Comment by mcharg** [comment]
We should also tag the tabs on the new homepage when we do this.

**Comment by brentryanjohnson** [comment]
The tags are applied to events (clicks) on the homepage, not the sections of the other pages, but the result should be the same...harvesting interaction with the tabs and links on the homepage.

![List of event categories, with scroll depth, outbound, download, explore data links, homepage tabs, and homepage links](https://images.zenhubusercontent.com/5c58ca90dcf5235c18769998/b35c92e9-9db6-4099-ab0b-e18beee6136a)
