### ISSUE TITLE
Review and post blog post

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#4195]
review and post blog found here: https://docs.google.com/document/d/1jT_I1eaBW-3Ryygw0jHzx5nV0M4Dw8j0OLyjydW9Au0/edit?ts=5d0a53e5

**Comment by jennmalcolm** [comment]
Since we're publishing the internship blog post wit h the release tomorrow, we should target the next release for yours @mentastc. So, I will move it into the next sprint.

**Comment by mentastc** [comment]
sounds good!

**Comment by mentastc** [comment]
@brentryanjohnson  do you want to do one last editorial review, I added a paragraph since you last looked at it.

**Comment by brentryanjohnson** [comment]
I added suggestions, @mentastc. Let me know if you have any questions or concerns!

**Comment by jennmalcolm** [comment]
Fixed by #4591
