### ISSUE TITLE
Prepare and test data quality script

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4196]
@echang97 will prepare the data quality script for testing and assign team members to test the script and provide feedback. @echang97 will incoporate feedback to finalize script.

**Comment by echang97** [comment]
Ready for use
[Script Repository](https://github.com/ONRR/Revdoi-Data-Quality)
[Wiki Page](https://github.com/ONRR/Revdoi-Data-Quality/wiki)
[Slides](https://docs.google.com/presentation/d/1XJdBBoNqYbQjuKaMyVAfvaBBBWTCFJiZg_B4RlUHs8Q/edit)
