### ISSUE TITLE
Onboard Mojo

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4203]
**Jennifer:** If you can’t complete any of the items on your checklist personally, you are responsible for ensuring that someone with the correct access completes that item.

**Mojo:** Take judicious notes on what about this onboarding process or the NRRD website is confusing or frustrating. If you notice a problem (especially with things like documentation), you are more than welcome to fix it! At the very least, please share this information with your buddy so we can make the team/platform better. You can also file issues and pull requests as soon as you feel comfortable doing so.

## Get access to GitHub so that you can complete this checklist
- [x] **Create a GitHub account that you can use for government work**  
GitHub is a platform for collaborative web development. 

  - [x] Follow [18F’s setup instructions](https://handbook.18f.gov/github/#setup) to create a GitHub account, or link an existing account to your government work. 
  - [x] Let the Product Manager know when your account has been created, and what your username is. Ask them to add you as a member or contributor to the project repository so that you can make contributions, and to add you to the ONRR GitHub organization.
  - [x] Subscribe to the [doi-extractives-data repository](https://github.com/ONRR/doi-extractives-data) (through the [GitHub watch feature](https://help.github.com/articles/watching-and-unwatching-repositories/)) to get notifications of project activity.
  - [x] Ask the product manager to request you be given access for federalist.
## Get access to other project tools and services that the team uses to communicate
- [x] Jennifer: **Ask the 18F team PM to invite Mojo to the #nrrd-partners slack channel**
  - [ ] Mojo: Accept the slack invitation via email, and set up your Slack account with 2-factor authentication. Set up your profile with your name, location, and any other information you wish to provide.
- [x] **Log in to [ZenHub](https://app.zenhub.com/workspaces/nrrd-portal-5464fa79c3cc8d7f4c384eaf/board?repos=21627244&showPRs=false&showPipelineDescriptions=false) with your GitHub account so that you can view the project planning board**  
Select the “Public Repos Only” option when prompted to log in. We use ZenHub as a project management tool to track tasks. ZenHub connects to GitHub and displays the issues from the the project’s repository in columns that show its progress—Unprioritized, Product Backlog, Sprint Backlog, In Progress, Awaiting Review, or Done.

## Learn about the project background and how the team works
- [x] Read the [Product Framing](https://github.com/ONRR/doi-extractives-data/wiki/product-framing) document

- [x] Read about the current status of the project on the [homepage of the wiki](https://github.com/ONRR/doi-extractives-data/wiki/home)
- [x] Jennifer: Add Mojo to the [project team](https://github.com/ONRR/doi-extractives-data/wiki/Joining-the-Natural-Resources-Revenue-Data-project-team#current-project-team) list
- [x] Read the [Basics for making distributed work work](https://github.com/ONRR/doi-extractives-data/wiki/Basics-for-making-distributed-work-work)
- [x] Meet with the Product Manager for an introduction to project routines, expectations, and rituals
  - [x] Discuss [NRRD project meetings](https://github.com/ONRR/doi-extractives-data/wiki/Joining-the-Natural-Resources-Revenue-Data-project-team#meetings): what they are, how they are run, and how the new person is expected to participate at each
  - [x] Review the most recent [NRRD project roadmap](https://app.zenhub.com/workspaces/nrrd-portal-5464fa79c3cc8d7f4c384eaf/reports/release?release=5cf68acf8d690c7080bd3b2b)
## Design checklist
- [ ] **Learn about our user research practice**  
Our research plans and findings are documented in the open as part of our GitHub repository. You can find the research at any time by changing the branch in the repo to the “research” branch.
  - [ ] Learn about our [user types](https://github.com/ONRR/doi-extractives-data/blob/research/research/00_UserTypes/00_UserTypes.md)
  - [ ] Read through the research work from a few recent sprints. Each sprint has its own folder that contains a plan and the results:
    * [Research and findings from BodaciousBaboon](https://github.com/ONRR/doi-extractives-data/tree/research/research/25_bodaciousbaboon_leases_filterabletables)
    * Read through the rest at your own pace  
  You can find everything together in the branch index: https://github.com/ONRR/doi-extractives-data/tree/research  
- [ ] **Review the [content guide](https://github.com/ONRR/doi-extractives-data/wiki/Content-guide)** to get a sense of how to write and talk about NRRD content
- [ ] **Read about [how to design with NRRD data](https://github.com/ONRR/doi-extractives-data/wiki/Little-rules-for-designing-with-data)**  
- [ ] **If you are new to GitHub, learn about how it works, and how to make it work for you**  
GitHub is traditionally a development tool, not a design tool. It may take some time and experimenting to figure out how to work within its framework as a designer. Some places to start:
  * **Understand the [GitHub workflow](https://guides.github.com/introduction/flow/) that code-based changes to the website go through.**  
    Even if you won’t be contributing code changes, it helps to share the same vocabulary as your team.  
  * **Learn about [GitHub issues](https://guides.github.com/features/issues/)**  
    Issues are how the team tracks tasks to work on or bugs to fix.
## Development checklist
- [ ] Mojo help us document what we need on this checklist

**Comment by mojobnichols** [comment]
- [ ] Complete the Gatsby Fundamentals Tutorial [https://www.gatsbyjs.org/tutorial/](url)

**Comment by jennmalcolm** [comment]
We should also include the process for requesting elevated access and admin rights in the section on development checklist.

**Comment by mojobnichols** [comment]
I attempted to edit wiki directly as markdown.  I didn't get the format I wanted but got the list in place for basic onboarding of a developer and therefore I am closing issue.
