### ISSUE TITLE
Audit 'diving graphics' content

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4210]
There's at least one instance of out-of-date content on the diving graphics [offshore oil and gas _example_](https://revenuedata.doi.gov/how-it-works/offshore-oil-gas/):

> YouTube
> Comment on the leasing program. Planning for the 2019–2024 Five Year Program is underway. BOEM wants input from anyone that may be affected, positively or negatively, by Outer Continental Shelf oil and gas development activity. Watch the video and visit BOEM’s website for more details.

We should audit the content and update as needed.

**Comment by jennmalcolm** [comment]
Also figure out the role of the diving graphics and ensure the scope aligns with the role.

6 diving graphics to review:
onshore oil & gas
offshore oil & gas
coal
onshore renewables
offshore renewables
non-energy minerals

**Comment by lpgoldstein** [comment]
@brentryanjohnson - here is the first pass at our audit. We should probably set up a meeting to discuss scope. 

https://docs.google.com/spreadsheets/d/1cbPoR7tTx7AnI4d0dNIcziYPUN5dQ64gpLrEATF-bAc/edit?ts=5d38a2f8#gid=1280972422

**Comment by mcharg** [comment]
Done
