### ISSUE TITLE
Write blog post on internship experiences and contributions

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4214]
@echang97 has been building a data quality script that will help our team find and correct issues with data quality, and allow us to quickly review the data for anomalies.

An account of his work and experiences with the team would be a great addition to our blog.

**Comment by brentryanjohnson** [comment]
This might work best as a Q&A. I'll come up with some questions for @echang97 about his experience.

**Comment by jennmalcolm** [comment]
I agree a Q&A would be a good format.

**Comment by brentryanjohnson** [comment]
I've compiled the questions in [this google doc](https://docs.google.com/document/d/1Fc5K4t9tHrZX0-F_5rOCu0tgEiR_lZIbIfiNOMMvEB0/edit?usp=sharing) (limited access), and @echang97 has started to add replies.
