### ISSUE TITLE
Find contact info from DORC requestors, so we can ask them to participate in user research

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4216]
Contact info isn't in the spreadsheet, so we'll need to get it from the emails.

**Comment by Maroyafaied** [comment]
@mentastc here is the DORC requests spreadsheet https://docs.google.com/spreadsheets/d/168U5ngJE0ry5xzHSCOJMnd23nuy86ip7riYls3SUASc/edit#gid=0

**Comment by Maroyafaied** [comment]
@mentastc I made a list of people to find contact info for from the DORC requests https://docs.google.com/spreadsheets/d/116lH0W7z4WiAk1ovgdfRKVknZOcpotxLaTJcn5x2Zhc/edit#gid=0 (limited access)
