### ISSUE TITLE
Discuss state page intro

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4231]
Following up on #3512, I'd like to meet with (at least) @jennmalcolm and @mcharg to discuss state page intro content refactoring. We should decide how to add the most value to users (from what we've heard so far), while avoiding unnecessary maintenance burdens.

---
These notes relate to evaluating the portion of commodity production in a state from federal lands compared to all lands in the state. This approach requires continued use of the EIA data via API.

## Method
Evaluated states with high relative share of federal commodity production to overall production in the state (e.g., Wyoming) versus states with high overall commodity production but lower federal production as a percentage (e.g., Texas). So in Wyoming, the share of coal production from federal land is between 82% and 86% of total, while in Texas, the share of federal oil production is 0.02%.

The goal is to evaluate whether it makes sense to maintain nation-wide, all-lands production for context (we’ve heard this from time to time from users). This would allow us to retain the context, without the confusion that resulted from charting all national production figures along with federal production.

Some commodities don’t work: for instance, geothermal units are a problem.

## Questions
What to do about states that only have mineral production? Any QUARTZ CRYSTAL (tickets/pounds) fans out there?

Is “crude oil” as defined by EIA the same as “oil” as defined by ONRR? Are there oil products rolled up in one or the other that complicates the comparison?

## Alternatives
We could simply list the commodities the state produced in the intro (for those that produced commodities).

Offshore is all federal, so we'll need a different pattern regardless of what we decide for states.

We could simply eliminate the summary and get into the date (if there is any).

The choropleth will provide summary data up front...we may not need dedicated state pages at some point. For instance, we could toggle summary state data when that state is selected on the map, assuming we pare down the content.

**Comment by jennmalcolm** [comment]
Next steps: @Maroyafaied will evaluate EIA categories (#4402)
@brentryanjohnson will explore options for states that do not have production and those that don't have sufficient data to populate template categories
Also look into technical considerations of pulling in EIA data via API with GraphQL
