### ISSUE TITLE
Due 7/31: Write article for Apolitical's Women in Government Writing Competition

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4253]
* Your article must be between 700-900 words.
* Your article can either be about your personal experience as a woman in government OR an issue, policy or project which is affecting women in government today. It is up to you to choose the angle you want to write about.

**Comment by mcharg** [comment]
For this, I'm thinking about writing about how even when the top of government tweets things that are disparaging to women, the siloed nature of government and the way political appointees come in and out means that there are pockets, like our team, where the culture is women-friendly that don't get too affected by viewpoints at the top.  Anyone have thoughts about whether this would be an interesting topic?

@jennmalcolm @usEITI @brentryanjohnson @lpgoldstein @Maroyafaied

**Comment by jennmalcolm** [comment]
I think we need to keep it apolitical. You could focus it on your personal experience with our organization's culture.

**Comment by mcharg** [comment]
I'm thinking of abandoning this to say because I don't have much to say other than that our agency supports flexible work schedules and has women in leadership.  This is what I have so far: https://docs.google.com/document/d/16f7UBectuB15jGbHUHIS8Tv3h0YWSi2xnacwU4VSi9s/edit (limited access)
