### ISSUE TITLE
Add copy indicating that no results were found in search

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4256]
It's a bit jarring for there to be nothing there.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6c99afeb-89fb-4e5c-a049-2ea24f645b9a)

**Comment by brentryanjohnson** [comment]
Thank you for adding this, @mcharg. I wrote some [next steps in the PR](https://github.com/ONRR/doi-extractives-data/pull/4217), but hadn't created all the issues yet.
