### ISSUE TITLE
Dive in Graphic Content Incorrect 

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#4258]
Fix dive in graphic content for Onshore Oil and gas, currently it has BOEM and BSEE in the upper right corner.
![image](https://user-images.githubusercontent.com/15347998/61379638-ea79c680-a875-11e9-8e6a-0ae91f81f006.png)

**Comment by brentryanjohnson** [comment]
I'll fix this. It looks like it didn't get updated in the transition to Gatsby. We also have an issue (#4210) to audit all of these pages, since they haven't been looked at closely in a while.
