### ISSUE TITLE
Update PR review procedures in Wiki to include data source/flow

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4441]
Now that Jeff refactored almost all of the data update processes (just mising Native American production) we should include in the Wikit PR review procedures what elements of the site we need to review when we change a data file. 

E.g., When we update the monthly revenue file, we need to review the site data for the revenue trends and the homepage revenue bar graph.

**Comment by Maroyafaied** [comment]
@jennmalcolm please review https://docs.google.com/spreadsheets/d/1ENrgRrPzuF6VWxjGwjP8ES7oavSr0Tbp_0IZim67FKA/edit#gid=0

**Comment by Maroyafaied** [comment]
@jennmalcolm  I added this under updating the data in the wiki under checklist. Is this where you wanted it to be or should it be somewhere else?

https://github.com/ONRR/doi-extractives-data/wiki/Updating-the-Data

**Comment by Maroyafaied** [comment]
This checklist is now on the wiki under Development releasing changes https://github.com/ONRR/doi-extractives-data/wiki/Releasing-changes-to-production
