### ISSUE TITLE
Update choropleth to use greens in our color palette

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4448]
These are the greens in the palette from darkest to lightest. 

$green-dark #2f4d26
$green-state-hex #46653c
$green #587f4c (This is the primary green, so if it needs to be based off a single color, this should be it.)
$green-land #69995a
$green-mid #9dbd92
$green-light #cde3c3

**Comment by mojobnichols** [comment]
Closing as issue has been released to dev.
