### ISSUE TITLE
Update external links based on audit

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#4458]
We to recommend a solution and update the links that were either broken or outdated from the audit #3664

**Comment by jennmalcolm** [comment]
Develop a list of links that need to be checked and their locations.

**Comment by lpgoldstein** [comment]
See spreadsheet for recommendations for the broken or outdated links. 

https://docs.google.com/spreadsheets/d/1ziZsTGwh1Vuk4YDaycCRGlsNiWxwN06E8GNv5QxhCXc/edit#gid=0
