### ISSUE TITLE
Fix map in Edge and Firefox

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4475]
It currently only builds the top corner.  This is a lot of work to fix and users can still get to state pages using the drop-down, so we're breaking this out from the homepage PR.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/42d158ee-569f-4c7d-84ac-3b312c05e1ca)

**Comment by mojobnichols** [comment]
I applied fix in branch 4174 directly

**Comment by mcharg** [comment]
The fix is working for me.
