### ISSUE TITLE
Find a new way to capture user research participant consent

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4483]
We currently use a Google Form and we've been told there is no equivalent product in the Microsoft ecosystem, so we need to find an alternative way to capture consent.

**Comment by lpgoldstein** [comment]
Can we still use google forms with an external account? or fillable pdf?

**Comment by lpgoldstein** [comment]
Here is a fillable pdf option. 
[Consent form fillable pdf.pdf](https://github.com/ONRR/doi-extractives-data/files/3627563/Consent.form.fillable.pdf.pdf)

**Comment by mcharg** [comment]
@lpgoldstein Looks good.
