### ISSUE TITLE
Confusion about production units on home page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4486]
The only place where the units are referenced in the production graph on the homepage is on the dotted line that represents about the maximum, and I have witnessed this cause confusion about what units the numbers represent. For example, a user thought the oil production numbers were in units of billion barrels.

Possible solution: We could add the units somewhere close to the numbers in the table. Maybe we could put it where the year is now and move the year or just add it right after the year (E.g. "2018 (barrels))."

**Comment by mcharg** [comment]
We had it next to the year and by the commodity label at the top of the graph in the original designs.
![image](https://user-images.githubusercontent.com/38465926/63695120-f7c79080-c7e5-11e9-892f-b11aaf32bf12.png)

**Comment by mojobnichols** [comment]
Do we only want these units on Production?

**Comment by mcharg** [comment]
@mojobnichols Yes, revenue and disbursements are in dollars.

**Comment by jennmalcolm** [comment]
Fixed by #4611
