### ISSUE TITLE
Explore options for providing help at the line item level in the filterable tables

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4490]
We know that users have questions about things like "why is geothermal in so many different types of units?", "what's included in "other revenue"?", or "what does withheld mean?".  Putting a glossary on as many lines as we would need it could get overwhelming, so we should explore other options available in material UI.

**Comment by mcharg** [comment]
@brentryanjohnson Can you please draft some content for @cmbrydges to include in her concepts?

| **Term** | **User question** | **Answer** |
|----------|-------------------|-------------|
| Withheld | Why is this number withheld? | |
| Geothermal | Why are there different units for geothermal? | |
| Not tied to a commodity | What does this mean? | |
| Not tied to a location | What does this mean? | |
| Tickets/pounds | What does this mean? | |
| Other revenue | What's included in other revenue? | |

**Comment by brentryanjohnson** [comment]
| **Term** | **User question** | **Answer** |
|----------|-------------------|-------------|
| Withheld | Why is this number withheld? | We withhold data if it can be used to identify individuals or if the data is protected by the Trade Secrets Act. |
| Geothermal | Why are there different units for geothermal? | The standard unit of measurement for geothermal energy is kilowatt hours, but there are a few counties that report it differently. Most of the time, the units cannot be converted to a common standard. |
| Not tied to a commodity | What does this mean? | Some revenue, such as civil penalties and inspection fees, do not directly result from the production of a commodity. |
| Not tied to a location | What does this mean? | Some revenue, such as civil penalties and inspection fees, do not directly result from production at a specific location. |
| Tickets/pounds | What does this mean? | ? |
| Other revenue | What's included in other revenue? | Other revenue includes revenue not tied to a commodity or location, such as civil penalties and inspection fees. |

**Comment by brentryanjohnson** [comment]
☝️ I'll trim these down over time. We're still looking into defining "tickets".

**Comment by mcharg** [comment]
Here are three options:
https://1t8b9p.axshare.com

@jennmalcolm Can we review these in synch up tomorrow?

**Comment by mcharg** [comment]
Next steps are in #4670
