### ISSUE TITLE
onrr.gov content audit -About section

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4499]

**Comment by mcharg** [comment]
We're going to assess how long this is going to take and whether we need to split it up across multiple people after we see how far @alenahuang gets by next week.

**Comment by mcharg** [comment]
This is 90% done and should be done by the end of sprint.

**Comment by alenahuang** [comment]
completed 9/14/19

**Comment by mcharg** [comment]
Here's the link to the content audit (limited access): https://docs.google.com/spreadsheets/d/1UWkeHQVtfnlT71lrvEgc9OhEV5g0WqVFsBXu81jM6Cs/edit#gid=1098885924
