### ISSUE TITLE
Review onrr.gov analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4502]

**Comment by mcharg** [comment]
I compiled a bunch of the unsampled FY19 reports into this spreadsheet (limited access.
https://docs.google.com/spreadsheets/d/1UCh7kDRAS1psl5wE3yW3ykRzgNxM0qdWgMD0aNsPpmo/edit#gid=0

I also created a placeholder page in the Research branch that we can use to post whatever we decide we want to share and then we can move the page or copy the markdown once we have an onrr.gov repository with a wiki.
https://github.com/ONRR/doi-extractives-data/blob/research/research/onrr.gov/FY19_analytics.md

**Comment by Maroyafaied** [comment]
The tabs that are colored red are the analysis that I have done, I also started a google doc with tables and charts that could be added to the wiki 

https://docs.google.com/document/d/14t3DG4Rkasm3tqNd_60N82w8OWtao8D3YINtWfYFNb4/edit

**Comment by mcharg** [comment]
I'm going to mark this as done.  We'll wait to put any of the analytics on GitHub until after we figure out how we're using them to create personas and have a place to put them in the onrr.gov repo.
