### ISSUE TITLE
Normalize explore navigation

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4506]
Our explore page navigation is inconsistent:

![navigation list with top, nationwide, production, revenue, and federal disbursements with a disbursements subnav item](https://user-images.githubusercontent.com/32855580/63891191-7fa1cc00-c999-11e9-857d-b374370866a6.png)

- Remove nationwide
- Remove "federal" from disbursements

**Comment by brentryanjohnson** [comment]
Also, this was working properly in [a recent branch](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/archive-taxonomy/explore/)

**Comment by mcharg** [comment]
Should we close this, since we won't have a right nav on the new Explore Data page or do we want to fix this in the interim? @brentryanjohnson @jennmalcolm

**Comment by brentryanjohnson** [comment]
Closing to revisit in our explore data rebuild.
