### ISSUE TITLE
Fix usability issues with revenue filterable table/build query tool- Continued

### ISSUE THREAD

**Issue by master12** [ONRR/doi-extractives-data#4524]
https://2r64il.axshare.com/#id=vxtk8t&p=data_query_tool

And here's the logic for the drop-downs and columns (limited access).
https://docs.google.com/spreadsheets/d/1ZAsu6su6m-Z6SXWA_F767-si5ccLDydOfDePq-8-Afg/edit#gid=0

**Comment by mcharg** [comment]
What we decided about blanks:

* Only display rows when there is data for at least one year the user has selected.
* If there are years with no data in the user's selection, but numbers for other visible year, the years with no data get a dash.
* For production, don't display rows with only withheld data for the visible years, but have a checkbox that allows the user to opt to display rows with only withheld data.

**Comment by jennmalcolm** [comment]
Continued in #4616
