### ISSUE TITLE
Conduct user interviews with interns

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4530]
Lindsay and Maroya will be facilitating and the focus will be the new homepage and the site in general, using the new user scenarios as tasks to familiarize the interns with common use tasks.  We also hope to do the same with the Carnegie Mellon students.

**Comment by Maroyafaied** [comment]
Should we close this issue?

**Comment by mcharg** [comment]
Are you and @lpgoldstein going to do a summary of the findings?

**Comment by Maroyafaied** [comment]
I will close this one. I started another issues for the findings summary.
