### ISSUE TITLE
List withheld commodities on state template

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4552]
Now that we're listing the number of commodities produced in a given state in a given year, we need to add a withheld summary under Production. For instance, Wyoming produced 11 commodities in 2018, but only 8 are listed under the production section. The other three were withheld for the entire 10 years of production.

We should add a withheld summary to the state pages, as we have for the explore data page, so the numbers in the intro and production sections match.

![Production volume was withheld for the following products: 19 products](https://user-images.githubusercontent.com/32855580/64283430-496dca80-cf0c-11e9-957b-541fe0c47e0b.png)

**Comment by jennmalcolm** [comment]
Closing since we are moving to no withheld and no state pages/integration with explore data application.
