### ISSUE TITLE
Remove "Nationwide" out of the navigation menu in Explore Data Page

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#4553]
[image](https://user-images.githubusercontent.com/40175688/64288223-c86bfe80-cf1e-11e9-9e4d-ce5564bff147.png)

**Comment by brentryanjohnson** [comment]
Good catch, @Maroyafaied. I noticed this a bit ago and attempted to change it, but the component has changed. I opened #4506 then to address, so I'm closing this one. 👍
