### ISSUE TITLE
Refactor state page disbursements data

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4554]
We still need to refactor the disbursements data for state pages. It's still driven by a `yml` file generated from `Makefile`.

`import FEDERAL_DISBURSEMENTS from '../../data/federal_disbursements.yml'`

**Comment by mojobnichols** [comment]
GoMESA is still pulled in through yml files.   2019 GoMESA data was manually  added so there is no way to get this to work off data for the moment.
