### ISSUE TITLE
Determine direction for OGOR B data  

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4566]
We received this OGOR B Data for Oct 2009 - July 2019. We should use this spreadsheet to help figure out the MVP for presenting/providing this data on NRRD and determine if we need to request any changes to the spreadsheet.
[Production by Disposition and State as of 9-5-19 (1).xlsx](https://github.com/ONRR/doi-extractives-data/files/3595296/Production.by.Disposition.and.State.as.of.9-5-19.1.xlsx)

**Comment by mcharg** [comment]
Disposition code descriptions: https://www.onrr.gov/ReportPay/pdfdocs/dispAdj.pdf

**Comment by jennmalcolm** [comment]
Work on MVP in #4820
