### ISSUE TITLE
Plan Explore Data design studio

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4582]
@jennmalcolm was going to schedule this for the first week in October, but since she didn't do that before she left on vacation, I'm not sure if that's still the plan.  If it is, we need to get it planned this sprint.

**Comment by lpgoldstein** [comment]
Chris is going to look at if we can use the smart board software

**Comment by mcharg** [comment]
We have a plan (limited access): https://docs.google.com/presentation/d/1t5F29AJhN6pX3hyke3x9nLUPCz3xPNIr5Hw0kvJUoYg/edit#slide=id.g60b8eae9c1_0_654

The plan assumes 4 sessions a few days apart from each other with offline sketching and hole poking.  I'll look at calendars and get placeholders in for the sessions.
