### ISSUE TITLE
Update Data Portal Publication Plan for 2020

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#4598]
Update plan for 2020
-Add monthly production and revenue data to schedule

**Comment by mentastc** [comment]
Updated schedule link: https://docs.google.com/spreadsheets/d/1sF_vwC1FCivRBotH25js2hKCxYUeQ4sAoNb3uVZgFMk/edit#gid=0

**Comment by jennmalcolm** [comment]
@mentastc did you work with DORC on this? It looks like we're thinking that all datasets beside the UDR will be provided ona monthly basis at the detailed level (probably without planning area?). Has DORC said this is doable by January?
