### ISSUE TITLE
Establish goals and metrics for blog

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4635]
Figure out and document our overall goals for the blog, and how we measure our success against those goals.

**Comment by brentryanjohnson** [comment]
We have a ["purpose" section](https://github.com/ONRR/doi-extractives-data/wiki/Publishing-a-blog-post#purpose-of-the-blog) already drafted:

> The purpose of our innovation design blog is to share our user-centered design and development process at the Office of Natural Resources Revenue. The strategic purpose of the blog is to:
> 
> - provide a venue for long-form publishing about our process, decision making, and workflow
> - nurture and support the adoption of our process, or elements of our process, in other federal agencies
> - create another outreach vehicle for Natural Resources Revenue Data (NRRD)
> - introduce a tool for Information and Data Management team collaboration and sharing
> - continue telling the story of the NRRD site, started on 18F's blog in 2014

We can expand on this for goals and metrics.

**Comment by jennmalcolm** [comment]
You draft looks good. I added a couple of comments in the document.

**Comment by jennmalcolm** [comment]
Ryan's work here: [Blog goals and metrics](https://docs.google.com/document/d/19BuxI0EjtToXrzEPe0NmnGWKO6Zvv9r2_YikBEfFNgA/edit?ts=5d9cc635) (limited access)

Next step: add to Wiki?
