### ISSUE TITLE
Compile FY 2019 NRRD metrics

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4636]
Ensure we have the data for all metrics and compile summary of how we're doing at meeting our goals for team meeting to come later.

**Comment by lpgoldstein** [comment]
Moving to next sprint because I'm still waiting on a few items from team members.

**Comment by lpgoldstein** [comment]
https://docs.google.com/presentation/d/1srpQIp7WKBx05SqtymBdqQgfJ2o3QJvK_rZOCljUBjo/edit?usp=sharing
