### ISSUE TITLE
Document content audit 

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4637]
We should document our purpose and schedule for auditing content.

**Comment by brentryanjohnson** [comment]
First draft of content audit docs: [Content audits: a (sort of) guide](https://github.com/ONRR/doi-extractives-data/wiki/Content-audits%3A-a-%28sort-of%29-guide)

**Comment by jennmalcolm** [comment]
@mentastc please review draft

**Comment by mentastc** [comment]
@brentryanjohnson This looks really good, my only suggestion would be adding an example spreadsheet maybe the one from your initial audit. Also, it might be helpful to make the sections into steps and number them, but that might just be me and how I like to look at things.

**Comment by brentryanjohnson** [comment]
Thank you, @mentastc. I've created a new issue to incorporate your suggestions.
