### ISSUE TITLE
Edit disbursements by month intro

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4642]
> We have disbursements data by month from October 2018 through the most recent month .

- Remove space before period
- "...through the most recent month" might not be the most accurate way to phrase this. Elsewhere, we have written "...most recently available month," but we should probably put the actual date range in the file link so users know the scope before downloading the file.

**Comment by jennmalcolm** [comment]
If we get the date reference coming from the file working correctly in #4644, we should be able to use that here in the intro content for the download page too.

**Comment by jennmalcolm** [comment]
@mojobnichols how hard would it be to use the date reference you built for the disbursement trends on the download page too? I know we have one built for the revenue and disburesment trends, so we could use those on the monthly revenue and disbursements download pages and maybe replicate for monthly production downloads too?

**Comment by brentryanjohnson** [comment]
Should we revisit this in the context of MDX @master12 and @jlouis-onrr?
