### ISSUE TITLE
Disbursements trends month referencing wrong most recent month - Not mobile only

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4644]
I’m assuming this should be getting the most recent month from the data file, but it appears to be off. The most recent month of data we have now is August 2019. 
![140DB164-D864-45BE-8495-8C2A9AF78B04](https://user-images.githubusercontent.com/30806839/65927104-57592300-e3c6-11e9-8b27-e422ca2caab6.jpeg)

**Comment by jennmalcolm** [comment]
This is only on mobile. I just looked at desktop, and it says August 2019.

**Comment by jennmalcolm** [comment]
I guess this is actually only a problem on Safari?

**Comment by jennmalcolm** [comment]
Actually it seems to also be a problem on Chrome for Chris and Firefox for me (on our phones).

**Comment by jennmalcolm** [comment]
Just found Firefox on my desktop shows July. 
![image](https://user-images.githubusercontent.com/30806839/65992856-0d238080-e45e-11e9-8f77-a5f7afb6546f.png)

**Comment by mcharg** [comment]
My phone is saying November 2019.
![image](https://user-images.githubusercontent.com/38465926/65997822-1dd8f400-e468-11e9-87ba-5a82400f6303.png)

**Comment by mcharg** [comment]
Chrome on my Android is showing August 2019.

**Comment by mcharg** [comment]
IE is also showing November.

**Comment by mojobnichols** [comment]
In generating a date for each monthly record I didn't pad the month with two digits which was a problem for safari.   Both Safari and Firefox handled the UTC timezone differently causing it to think  the day was 1 day prior and then reporting the month to be the previous month.  I have  just generated the day to the 2 day of the month as it is quick and easy.
