### ISSUE TITLE
Picky about rounding

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4645]
The grand totals (depending on grouping) on the filterable table vary by about $20. Could we do the rounding later in the process or something to get these closer? Also, the numbers I looked at when compared to Excel all seemed to be rounded down even when up was closer, so we should just review our rounding protocol for that table.

**Comment by mentastc** [comment]
What the totals in the revenue detail chart should be:
![image](https://user-images.githubusercontent.com/15347998/66422491-c4c50f00-e9d7-11e9-9a5f-dbacf9e2a14d.png)
