### ISSUE TITLE
Due 10/18: Code for America Summit proposal

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4649]
Call for proposals:
https://www.codeforamerica.org/summit/proposals?utm_campaign=Summit%202020&utm_source=hs_email&utm_medium=email&utm_content=77602673&_hsenc=p2ANqtz--AlFFt1NJTgE3Cg4QOu4CtpygQZ3aEKdMP5hpB42G6_zANXxTRTqfjjtaAGuLSmTkQyx3T0BEi_bZfjpsOJA5wM12S_g&_hsmi=77602673

They're looking for talks in 4 tracks:

Design + Delivery
From introducing attendees to human-centered design to product management, from user research to managing products that focus on outcomes, this track will concentrate on how teams design and deliver government services.

Operations + Management
Our Operations + Management track focuses on the processes, practices and people that help us be more effective. What’s working across procurement, project management, oversight and governance? What have we learned about culture, development and hiring? And underscoring all of this, how will we change sustainably, without burning out?

Civic Innovation + Data
Civic Innovation is where government and technology come together for a more just and equitable society. Where we learn how smart, new uses of technology (but not necessarily new technology!) supports deep, authentic relationships between government and the people. Where promises meet reality and where we focus on cities and grass-roots involvement. New for 2020, we'll also focus on data: from ethics to privacy, from putting out fires to building for the future, from the practicalities of sharing across silos to clearly communicating how and why data is being used.

Technology + Policy
The new Technology + Policy track explores how researchers, designers and technologists working with policy and program managers reduces the risk of implementations that check the requirements of policy, but don’t deliver intended policy outcomes. We’ll cover what leaders need to know and how effective collaboration happens, how delivery-driven policy applies to existing programs, and the hot and up-and-coming technology issues policy and program managers need to know about.

**Comment by mcharg** [comment]
I pulled this into this sprint because it's due a couple days into next sprint and we need to brainstorm what a good topic would be.

**Comment by mcharg** [comment]
They do allow multiple submissions, so we could put together more than one proposal.  We could probably talk about slowing down agile using the shaping process for the design + delivery track and something about data for the civic innovation + data track.

**Comment by lpgoldstein** [comment]
https://docs.google.com/document/d/1eiqjImxiP-Sr4IeURy82wKx40BQx1T_d5tYFGWN7fAE/edit?usp=sharing

**Comment by mcharg** [comment]
@brentryanjohnson I put together a first pass description for our talk. Please review.

@jennmalcolm We have a place in here for you to put in a description of your becoming a manager talk - we assumed you'd like the 7 minute lightening talk format.

@lpgoldstein Have you talked with @master12 about the data/Gatsby idea?

@mentastc Did you want to put together something about Sunshine Week?

**Comment by mcharg** [comment]
@jennmalcolm I submitted your proposal.

**Comment by mcharg** [comment]
They extended the deadline to Friday, so we have a little more time to review proposals.

**Comment by mcharg** [comment]
All the proposals have been submitted.  We should hear back by Dec 2.
