### ISSUE TITLE
Fix accessibility issues from Pa11y audit of Explore Data Page

### ISSUE THREAD

**Issue by jlouis-onrr** [ONRR/doi-extractives-data#4657]
$ pa11y --wait 1000 --debug https://revenuedata.doi.gov/explore/

Welcome to Pa11y

 > Running Pa11y on URL https://revenuedata.doi.gov/explore/
 > Debug: Launching Headless Chrome
 > Debug: Opening URL in Headless Chrome
 > Debug: Browser Console: document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
 > Debug: Loading runner: htmlcs
 > Debug: Injecting Pa11y
 > Debug: Injecting runner: htmlcs
 > Debug: Running Pa11y on the page
 > Debug: Waiting for 1000ms
 > Debug: Document title: "Explore data | Natural Resources Revenue Data"

Results for URL: https://revenuedata.doi.gov/explore/

• Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #OffshoreRegionsMap > g:nth-child(1) > a
   └── <a xlink:href="/explore/offshore-alaska/" href="/explore/offshore-alaska/"><g class="state offshore-area f...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #OffshoreRegionsMap > g:nth-child(2) > a
   └── <a xlink:href="/explore/offshore-atlantic/" href="/explore/offshore-atlantic/"><g class="state offshore-area f...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #OffshoreRegionsMap > g:nth-child(3) > a
   └── <a xlink:href="/explore/offshore-gulf/" href="/explore/offshore-gulf/"><g class="state offshore-area f...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #OffshoreRegionsMap > g:nth-child(4) > a
   └── <a xlink:href="/explore/offshore-pacific/" href="/explore/offshore-pacific/"><g class="state offshore-area f...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(2) > a
   └── <a xlink:href="/explore/AL" href="/explore/AL"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(3) > a
   └── <a xlink:href="/explore/AK" href="/explore/AK"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(4) > a
   └── <a xlink:href="/explore/AZ" href="/explore/AZ"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(5) > a
   └── <a xlink:href="/explore/AR" href="/explore/AR"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(6) > a
   └── <a xlink:href="/explore/CA" href="/explore/CA"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(7) > a
   └── <a xlink:href="/explore/CO" href="/explore/CO"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(8) > a
   └── <a xlink:href="/explore/CT" href="/explore/CT"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(9) > a
   └── <a xlink:href="/explore/DE" href="/explore/DE"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(10) > a
   └── <a xlink:href="/explore/FL" href="/explore/FL"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(11) > a
   └── <a xlink:href="/explore/GA" href="/explore/GA"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(12) > a
   └── <a xlink:href="/explore/HI" href="/explore/HI"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(13) > a
   └── <a xlink:href="/explore/ID" href="/explore/ID"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(14) > a
   └── <a xlink:href="/explore/IL" href="/explore/IL"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(15) > a
   └── <a xlink:href="/explore/IN" href="/explore/IN"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(16) > a
   └── <a xlink:href="/explore/IA" href="/explore/IA"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(17) > a
   └── <a xlink:href="/explore/KS" href="/explore/KS"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(18) > a
   └── <a xlink:href="/explore/KY" href="/explore/KY"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(19) > a
   └── <a xlink:href="/explore/LA" href="/explore/LA"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(20) > a
   └── <a xlink:href="/explore/ME" href="/explore/ME"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(21) > a
   └── <a xlink:href="/explore/MD" href="/explore/MD"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(22) > a
   └── <a xlink:href="/explore/MA" href="/explore/MA"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(23) > a
   └── <a xlink:href="/explore/MI" href="/explore/MI"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(24) > a
   └── <a xlink:href="/explore/MN" href="/explore/MN"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(25) > a
   └── <a xlink:href="/explore/MS" href="/explore/MS"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(26) > a
   └── <a xlink:href="/explore/MO" href="/explore/MO"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(27) > a
   └── <a xlink:href="/explore/MT" href="/explore/MT"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(28) > a
   └── <a xlink:href="/explore/NE" href="/explore/NE"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(29) > a
   └── <a xlink:href="/explore/NV" href="/explore/NV"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(30) > a
   └── <a xlink:href="/explore/NH" href="/explore/NH"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(31) > a
   └── <a xlink:href="/explore/NJ" href="/explore/NJ"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(32) > a
   └── <a xlink:href="/explore/NM" href="/explore/NM"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(33) > a
   └── <a xlink:href="/explore/NY" href="/explore/NY"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(34) > a
   └── <a xlink:href="/explore/NC" href="/explore/NC"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(35) > a
   └── <a xlink:href="/explore/ND" href="/explore/ND"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(36) > a
   └── <a xlink:href="/explore/OH" href="/explore/OH"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(37) > a
   └── <a xlink:href="/explore/OK" href="/explore/OK"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(38) > a
   └── <a xlink:href="/explore/OR" href="/explore/OR"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(39) > a
   └── <a xlink:href="/explore/PA" href="/explore/PA"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(40) > a
   └── <a xlink:href="/explore/RI" href="/explore/RI"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(41) > a
   └── <a xlink:href="/explore/SC" href="/explore/SC"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(42) > a
   └── <a xlink:href="/explore/SD" href="/explore/SD"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(43) > a
   └── <a xlink:href="/explore/TN" href="/explore/TN"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(44) > a
   └── <a xlink:href="/explore/TX" href="/explore/TX"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(45) > a
   └── <a xlink:href="/explore/UT" href="/explore/UT"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(46) > a
   └── <a xlink:href="/explore/VT" href="/explore/VT"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(47) > a
   └── <a xlink:href="/explore/VA" href="/explore/VA"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(48) > a
   └── <a xlink:href="/explore/WA" href="/explore/WA"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(49) > a
   └── <a xlink:href="/explore/DC" href="/explore/DC"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(50) > a
   └── <a xlink:href="/explore/WV" href="/explore/WV"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(51) > a
   └── <a xlink:href="/explore/WI" href="/explore/WI"><g class="state feature"><title...</a>

 • Error: Anchor element found with a valid href attribute, but no link content has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent
   ├── #StateAreasMap > g:nth-child(52) > a
   └── <a xlink:href="/explore/WY" href="/explore/WY"><g class="state feature"><title...</a>

 • Error: Duplicate id attribute value "production" found on the web page.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
   ├── #production
   └── <h2 class="state-page-overview" id="production">Production</h2>

 • Error: This select element does not have a name available to an accessibility API. Valid names are: label element, title undefined, aria-label undefined, aria-labelledby undefined.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Select.Name
   ├── #federal-production-trends-by-resources-2018-2017-2016-2015-2014-2013-2012-2011-2010-2009 > select
   └── <select class="chart-selector flex-row-icon"><option value="2018">2018</opti...</select>

 • Error: This form field should be labelled in some way. Use the label element (either with a "for" attribute or wrapped around the form field), or "title", "aria-label" or "aria-labelledby" attributes as appropriate.
   ├── WCAG2AA.Principle1.Guideline1_3.1_3_1.F68
   ├── #federal-production-trends-by-resources-2018-2017-2016-2015-2014-2013-2012-2011-2010-2009 > select
   └── <select class="chart-selector flex-row-icon"><option value="2018">2018</opti...</select>

 • Error: Duplicate id attribute value "revenue" found on the web page.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
   ├── #revenue
   └── <h2 id="revenue">Revenue</h2>

 • Error: Not all th elements in this table have a scope attribute. These cells should contain a scope attribute to identify their association with td elements.
   ├── WCAG2AA.Principle1.Guideline1_3.1_3_1.H63.1
   ├── #revenue-types
   └── <table id="revenue-types" is="bar-chart-table" class="revenue table-arrow_box"><thead id="revenue-phase"><tr><...</table>

 • Error: Duplicate id attribute value "icon-coal" found on the web page.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
   ├── #icon-coal
   └── <g id="icon-coal"><g id="coal-icon-resources" dat...</g>

 • Error: Duplicate id attribute value "coal-icon-resources" found on the web page.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_1.F77
   ├── #coal-icon-resources
   └── <g id="coal-icon-resources" data-name="1.0-Resources-to-Revenue-Landing"><g><g><path d="M24.05,40.18a4.3...</g>

 • Error: This select element does not have a name available to an accessibility API. Valid names are: label element, title undefined, aria-label undefined, aria-labelledby undefined.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Select.Name
   ├── #revenue-trends > select
   └── <select class="chart-selector flex-row-icon"><option value="2018">2018</opti...</select>

 • Error: This form field should be labelled in some way. Use the label element (either with a "for" attribute or wrapped around the form field), or "title", "aria-label" or "aria-labelledby" attributes as appropriate.
   ├── WCAG2AA.Principle1.Guideline1_3.1_3_1.F68
   ├── #revenue-trends > select
   └── <select class="chart-selector flex-row-icon"><option value="2018">2018</opti...</select>

 • Error: This select element does not have a name available to an accessibility API. Valid names are: label element, title undefined, aria-label undefined, aria-labelledby undefined.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Select.Name
   ├── #by-fund > select
   └── <select class="chart-selector flex-row-icon"><option value="2018">2018</opti...</select>

 • Error: This form field should be labelled in some way. Use the label element (either with a "for" attribute or wrapped around the form field), or "title", "aria-label" or "aria-labelledby" attributes as appropriate.
   ├── WCAG2AA.Principle1.Guideline1_3.1_3_1.F68
   ├── #by-fund > select
   └── <select class="chart-selector flex-row-icon"><option value="2018">2018</opti...</select>

66 Errors

**Comment by jlouis-onrr** [comment]
@brentryanjohnson, Would you be able to help me trouble shoot why my commits to the branch are not appearing in the branch preview?

[4657-FixAccessibilityIssuesExplorePage - BRANCH PREVIEW](https://federalist-proxy.app.cloud.gov/preview/onrr/doi-extractives-data/4657-FixAccessibilityIssuesExplorePage/explore/)

**Comment by brentryanjohnson** [comment]
It looks like they might be there now, @jlouis-onrr. 

Federalist must build the branch every time you push, which can take up to 40 minutes. You can [check the branch status here](https://github.com/ONRR/doi-extractives-data/branches) by clicking on (what is right now) the red "X". The last item will show the status of the Federalist build. The latest commits won't show up in the preview until the build is finished.

**Comment by jlouis-onrr** [comment]
@brentryanjohnson  Ah yes, forgot about the build times. Thanks!
