### ISSUE TITLE
Content audit: audits and assurances...audit squared!

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4658]
[Audits and assurances](https://revenuedata.doi.gov/archive/audits-and-assurances/) presents a tricky content problem...it's quasi-EITI.

We should audit<sup>2</sup> and assure<sup>2</sup> the content is up to date, relevant, and serves our audience.

_Note: I moved this content to the `/archive/` directory, but I think it might still be relevant to how it works. There's a PR to re-path it.

**Comment by Maroyafaied** [comment]
I started a document for the audit, I checked all the links and they work fine. 
https://docs.google.com/document/d/1H30XfZ69enzNSewJd0WqWyWW7VU4_ktqKtKd9IWewZU/edit#
