### ISSUE TITLE
Create Data Display page on onrr resource

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#4666]
We have the IDM page created but still need to create the Data Display page.

**Comment by mentastc** [comment]
Hi All (@jennmalcolm @lpgoldstein @Maroyafaied @mcharg @master12 @mojobnichols @brentryanjohnson @jlouis-onrr ),

Please check out the Data Display ONRResource page and let me know if you have any additions or edits you'd like made.  Below is a link to the page, I believe you'll need to be on the network to view the page. 

https://onrresource/data-display/

**Comment by lpgoldstein** [comment]
@mentastc Looks good! The only thing I noticed that is that when you click on the email button it opens in google mail. Is that going to be an issue?

**Comment by jennmalcolm** [comment]
@lpgoldstein that should be a setting on your computer. 

@mentastc could you change it to "program analysis" instead of "program analysts" or change the others to titles ("content manager," "web developer," "user experience designer")?

**Comment by brentryanjohnson** [comment]
I have some suggestions in the version below, mostly breaking it up more and using a more personal tone. The list of responsibilities probably needs at least one more item to work as a bulleted list. Also, if you're able to edit "Helpful Links," I recommend doing so. It's better to let readers decide if the links are helpful or not. "Our links" or "Our work" might be better...or simply, "Links." Take what you want and ignore the rest!

## Suggestions
Our team is responsible for implementing ONRR's mission priority to build trust and improve and streamline ONRR's data publication.

We perform a range of duties with the goal of enhancing public access to information and increasing public engagement in the natural resource revenue management work performed by ONRR and the rest of the department. 

Our responsibilities include: 

- maintaining and enhancing the [Natural Resources Revenue Data (NRRD) website](https://revenuedata.doi.gov/) 

- engaging with a wide range of stakeholders by supporting ONRR Federal Advisory Committee Act committees

We are committed to working in the open. All our work and projects can be viewed on [GitHub](https://github.com/ONRR/doi-extractives-data/), where we welcome comments and contributions. 

We also maintain a [blog](https://revenuedata.doi.gov/blog/) on a wide range of topics that include technologies we use and how and why the NRRD website was created. We're always looking for new blog topics; if you have one please send it to our [team mailbox](mailto:nrrd@onrr.gov).

**Comment by mentastc** [comment]
Comments have been incorporated closing issue.
