### ISSUE TITLE
Implement Material UI theme and layout components

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4678]
Add a global theme provider for all components to use. Remove old layout components from previous css.

**Comment by jlouis-onrr** [comment]
@brentryanjohnson @mcharg In my journeys through the Material UI docs and getting into implementing the UI Theme approach and layout components.  I realize we dont have a current base theme defined yet.  Material UI has what is known as a themeProvider component and makes the theme styles available down the react tree.  Pretty fancy! Let me know your thoughts on this tool and what might be the best approach to getting a base theme started!

[MUI Theme Generator](https://cimdalli.github.io/mui-theme-generator/)

**Comment by mcharg** [comment]
@jlouis-onrr I took a look at the theme generator, but it won't let me put in hex values to test it out with our existing colors.

**Comment by jlouis-onrr** [comment]
@mcharg, thats no fun!  After reviewing the material-ui docs further I believe the following is going to be the better approach.  2 - will be necessary for me generating the code necessary for React, all I need will be the url from the generated tool colors.

Create Material-UI Theme
1. Open https://material.io/tools/color and create a new material-ui theme.

2. Copy & Paste URL from browser address bar into the left panel on this page and press the "ADD" button.

(or you can simply drag URL by your mouse from material.io and drop it here in any place)

3. You can repeat it as much as you need. All themes will be listed on the left panel. You can select any to inspect.

4. As you select a theme you'll find a code that you can copy-paste in your project and use this theme. There are JS and JSON variants for your choice.

**Comment by mcharg** [comment]
@jlouis-onrr What page am I supposed to copy and paste the url into?

**Comment by mcharg** [comment]
Try this one:
<p class="jss48 jss57 jss70 jss223 jss224">https://material.io/resources/color/#!/?view.left=0&amp;view.right=1&amp;primary.color=1478a6&amp;secondary.color=587f4c</p>

**Comment by jlouis-onrr** [comment]
Perfect, the name that got generator for this theme is, "Matisse Hippie Green Mice".  :smile:

**Comment by mcharg** [comment]
@jlouis-onrr If it's too much with the green as the secondary color, we can also try using the gray color as the secondary.

https://material.io/resources/color/#!/?view.left=0&view.right=1&primary.color=1478a6&secondary.color=d3dfe6

**Comment by jlouis-onrr** [comment]
@mcharg That sounds good.  Once I get everything implemented we should see how the secondary color plays out across the styles.

**Comment by jennmalcolm** [comment]
Creating new issues by component
