### ISSUE TITLE
Export Google Analytics Reports and User Segments

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4697]
In case we lose access in the switch to Microsoft.

This is what we think might happen when we switch, but nobody knows for sure.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8f55ca37-e182-45a1-acf9-1988479d5b4e)

**Comment by mcharg** [comment]
Moving this into this sprint, since it needs to be done before the 11th.

**Comment by mcharg** [comment]
I'm done with mine.  @brentryanjohnson Are you doing anything as part of this issue or just in the GTM one you added?

**Comment by brentryanjohnson** [comment]
@mcharg I only have a user segment defined, and that's trivial to re-launch. I don't have a lot of custom reports or anything. I'm more concerned about the GTM container, which I've exported. 👍
