### ISSUE TITLE
Explore data: Card functionality

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4698]
Define how the cards will work.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/29615e78-3992-447d-885f-593f45454e1c)

Should also think about how the state drop-down will function in the new card-based world.

**Comment by mcharg** [comment]
Prototype: https://935313.axshare.com/#g=1&p=revenue

Federal card expands and collapses using a plus/minus.  State and offshore region cards are added by selecting a state.  On select, the outline of the state is darker and the card displays.  On click of the close X, the card hides and the outline of the state goes back to the default outline color.

**Comment by master12** [comment]
cards work
