### ISSUE TITLE
Explore Data: Access to data by state tool

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4701]
* Primary nav changes
* What we call it
* What to do with Data by State tab on homepage

**Comment by jennmalcolm** [comment]
This issue is to figure out how/where to provide access to new explore data.

**Comment by mcharg** [comment]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f876ad16-38bf-4eac-96bb-96ac54d97ab8)

**Comment by mcharg** [comment]
@jlouis-onrr Can you build this this sprint or do we need a separate issue for building next sprint?

**Comment by jennmalcolm** [comment]
@mcharg will you go over this in syncup today so the whole team has a chance to review this design?

**Comment by mcharg** [comment]
@jennmalcolm Sure

**Comment by mcharg** [comment]
Tweaked the data by location to reflect the decision to change the link depending on which tab the user is on and created #4844 for implementation.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d19e59c1-267d-416d-906e-a3e75d5e35ac)
