### ISSUE TITLE
Explore Data: Explain how the datasets work together

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4725]
Decide on a strategy and create new scopes, as needed.
- Do we rename How It Works?
- Do we reorganize How It Works?
- Do we put content on the Explore Data page?
- How do we link between sections?

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/7eccc3bb-c89b-46b2-91ea-23939eade3b0)

**Comment by jennmalcolm** [comment]
With the goal of adding two new datasets (sales and OGOR B) to downloads by the end of the year, I would like to work on drafting/drawing a prototype for an explanation that we can include on the main download page (or somewhere else appropriate) as an MVP of this. It should be as simple as possible while still providing the context needed for a user to know how the data relates and whic dataset they should use for their purposes. 

I'm assigning this to @Maroyafaied and @lpgoldstein to come up with some sketches/drafts/thoughts on how to do this. You can start with what @mcharg put together during the shaping process.

**Comment by mcharg** [comment]
Here's a link to the full page from shaping: https://935313.axshare.com/#g=1&p=explore

**Comment by Maroyafaied** [comment]
I started this document which is basically just the content pieces of the shaping process that Shannon put together. We will start by editing the content and ensurin the right description is given for each data set and  include an explanation of the  OGOR B and sales data sets.
https://doimspp-my.sharepoint.com/:w:/r/personal/faiedm_mms_gov/_layouts/15/Doc.aspx?sourcedoc={50e8548d-45ba-42f9-9960-b96e8cd7eb7b}&action=editnew&wdPreviousSession=b8b4313d%2Dda6f%2D44ba%2D9822%2Dd0516161e867&wdNewAndOpenCt=1575310051842&wdo=4&wdOrigin=wacFileNew&wdTpl=blank&wdLcid=1033&wdPreviousCorrelation=2bbd3270%2Dbbc8%2D4749%2Da33f%2De9cd5e31344b

**Comment by mcharg** [comment]
FYI - We renamed "How It Works" as part of the link to the map issue.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f6dbcef9-966c-4245-8957-6f381b5a1360)

**Comment by Maroyafaied** [comment]
Here is the summary table for how to use the data, it would be added along with the content on the main download page. @jennmalcolm please review. https://doimspp-my.sharepoint.com/:x:/r/personal/faiedm_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B7A39F36D-4C1F-4851-BC59-3428E50D0F96%7D&file=Best%20use%20of%20data.xlsx&action=default&mobileredirect=true

**Comment by jennmalcolm** [comment]
@Maroyafaied the rows don't exactly represent the use of data, more like attributes of the data or available fields. What do you think about creating something similar that includes potential data  uses such as: understand sales price/royalty rate trends, find vented/flared volumes, see revenues collected by the government, see moneys sent for LWCF, see how much money states received, etc? I'm just thinking something that explains the potential uses in plain language could be more helpful to the type of user who doesn't know too much about the datsets or what they represent.

**Comment by Maroyafaied** [comment]
@jennmalcolm Ok, I changed it to represent use of data, feel free to make changes.

**Comment by Maroyafaied** [comment]
We provided a draft to be included in the main download page, we decided to create a summary table for best use of data and another summary table for characteristics of the data sets. We will create another issue to continue this work and will reference search terms and user questions spread sheet for ideas on best use of data.

**Comment by mcharg** [comment]
@Maroyafaied Can you move the document you created into Teams, so the interns can access?

**Comment by Maroyafaied** [comment]
@mcharg I added a folder called "Explanation of data sets" and put both files in there.
