### ISSUE TITLE
Document peer review process in procedures for revenue and disbursements files

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4736]
Since we receive a new montly file with just one month's data, we manually combine the new numbers with the old numbers to get the file we will post on the site. We should have a better way of doing this in the future, but for now, we should create a checklist of items for the peer reviewers to check (e.g. line count, totals, etc.) to make sure we don't miss anything when going through these data updates each month. 

We can include the checklist in the wiki and the procedure files we have offline.

**Comment by Maroyafaied** [comment]
I have started a check list, please feel free to add to it. https://doimspp-my.sharepoint.com/:w:/r/personal/faiedm_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B9B39192B-CC6E-4C2E-8F55-D396A728EC2A%7D&file=Document.docx&action=default&mobileredirect=true

**Comment by Maroyafaied** [comment]
@lpgoldstein @mentastc , can you review the document and add anything I missed? I will post it on the wiki after your review. Thanks!

https://doimspp-my.sharepoint.com/:w:/r/personal/faiedm_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B9B39192B-CC6E-4C2E-8F55-D396A728EC2A%7D&file=Document.docx&action=default&mobileredirect=true

**Comment by lpgoldstein** [comment]
@Maroyafaied I looked at this yesterday and added one step - to check the non-date cells for correct formatting issue. We always seem to have trouble with the disbursement files. Otherwise it looks great! Thank you.

**Comment by Maroyafaied** [comment]
@lpgoldstein awesome, thanks!

**Comment by Maroyafaied** [comment]
@jennmalcolm I have added this checklist to the wiki, please review and let me know if there is any changes you'd like for me to make. Thanks
https://github.com/ONRR/doi-extractives-data/wiki/Peer-Reviewing-and-Updating-the-Data

**Comment by jennmalcolm** [comment]
I think it could add clarity to specify where where the new and combined source files are coming from (e.g. email, website, repo files, etc.

@mentastc did you review?

**Comment by Maroyafaied** [comment]
@mentastc if you can let me where you get the files from, I will add that to the wiki.

**Comment by mentastc** [comment]
added that in and added an additional step to check sums

**Comment by Maroyafaied** [comment]
@mentastc thank you, I'll add the changes to the wiki.

**Comment by Maroyafaied** [comment]
The wiki is updated. @jennmalcolm let me know if this is good to close. Thanks

**Comment by jennmalcolm** [comment]
Looks good. I will go ahead and close this.
