### ISSUE TITLE
Write a blog post highlighting Judy's role championing our website

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4739]
We should write a retrospective of everything @usEITI  did to set us up for success and what makes a good product champion.

**Comment by mcharg** [comment]
@jennmalcolm @brentryanjohnson I think this is ready for you to review. (limited access)
https://docs.google.com/document/d/1ZudRKKKxVHyKo7c0i1yrxftuLXi99WK5-U6t_wSuVpk/edit

**Comment by mcharg** [comment]
@jennmalcolm I think this is ready to send to Judy, if you have an email address.

**Comment by jennmalcolm** [comment]
Ok @mcharg I will send it to her
