### ISSUE TITLE
Document shaping process

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4741]
After the retro, we should document the process for use going forward.

**Comment by mcharg** [comment]
Here's a first pass (limited access): https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B987C3349-8F06-41EE-A5FB-679ECC38C641%7D&file=Shaping%20Process.docx&action=default&mobileredirect=true

@jennmalcolm @brentryanjohnson Thoughts?

**Comment by jennmalcolm** [comment]
I added my comments. It's looking good, and I think we could use this as a starting point for a blog post. We could write about how the Basecamp book inspired us to try a new process with designing and building new features. Perhaps we could divide it into 2--one about our shaping process and one about how the building goes with the new process.

**Comment by mcharg** [comment]
Thanks. @jennmalcolm 

@brentryanjohnson Can you take a look today?

**Comment by brentryanjohnson** [comment]
Yes, I looked this morning, @mcharg. It looks good. 👍

**Comment by mcharg** [comment]
@jennmalcolm I was thinking it makes sense to wait until we actually have something built to make sure this works before we do a blog post.

**Comment by mcharg** [comment]
Here it is on the wiki: https://github.com/ONRR/doi-extractives-data/wiki/Shaping-Process
