### ISSUE TITLE
Document WIthheld Strategy

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#4744]
-Document justification on withheld strategy and make decision on whether to consult with SOL.

**Comment by mentastc** [comment]
Withheld strategy has been documented here: 
[Withheld Strategy.docx](https://github.com/ONRR/doi-extractives-data/files/3876305/Withheld.Strategy.docx)

**Comment by jennmalcolm** [comment]
I added my comments and made a few changes within the document to correct typos.
