### ISSUE TITLE
Historic Preservation Fund Disbursement missing in 2006

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#4779]
The excel download has a dash for 2006 for the Hisitoric Preservation Fund, and it shows up as zero in the explore data page and the query tool. I'm not sure if this has been verified that there was no disbursement or if this data is missing?

![image](https://user-images.githubusercontent.com/40175688/68686122-61735300-0528-11ea-8362-76a04cbe4dce.png)
![image](https://user-images.githubusercontent.com/40175688/68686174-73ed8c80-0528-11ea-9d6e-455b9fc5dda5.png)

**Comment by jennmalcolm** [comment]
I think there was no disbursement in 2006, but @lpgoldstein can confirm that.

**Comment by lpgoldstein** [comment]
@Maroyafaied @jennmalcolm Correct. No hpf disbursement in 2006.

**Comment by jennmalcolm** [comment]
@master12 can you get the message that shows up for 2016 about no Historic Preservation Fund disbursement to show up for 2006 too? 
![image](https://user-images.githubusercontent.com/30806839/68764763-4ddbf100-05e9-11ea-9391-d55ed0ad3a97.png)

**Comment by jennmalcolm** [comment]
Thanks @lpgoldstein
