### ISSUE TITLE
Review/Identify outreach opportunities

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4783]
Review outreach opportunities and ensure they're reflected in content calendar.
Identify presentation opportunities (based on blog posts).

**Comment by Maroyafaied** [comment]
@brentryanjohnson can you please put the link here for the calendar after you migrate it from google sheets? Thanks

**Comment by Maroyafaied** [comment]
ESRI Federal GIS conference (Washington, DC) - Feb 11-12

**Comment by Maroyafaied** [comment]
ESRI Federal GIS conference Feb 11-12 (Washington, DC),  Colorado Oil & Gas annual energy summit (no dates announced, check in July ), USAEE conference (no dates announced check in September), RMMLF onshore oil & gas Oct 8-9 (Westminister, CO). EIA energy conferences (no dates announced yet, check in April )

**Comment by master12** [comment]
Added to content calendar
