### ISSUE TITLE
Fix homepage production units (what an absolute unit!)

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4815]
I've written a hack in with #4805 that deals with our duplicate production unit issue on the homepage (when toggled to Monthly and/or Calendar year), but that's brittle and doesn't fix the underlying problem(s).

One problem appears to be the use of different unit references for fiscal year relative to the others.

![three charts, one each for oil, gas, and oil, with bbl for oil unit when monthly data is toggled and barrels when fiscal year is toggled](https://user-images.githubusercontent.com/32855580/69268474-0ecb1400-0b84-11ea-8a49-9dbe3a34bbfd.gif)

Additionally, I think we overuse the units on the production charts. They are listed in three different places.

I propose we:

- Remove the units from the top of each chart, currently listed in parentheses next to the commodity
  - The units will still be listed in two places: where the threshold is listed and next to the year in the table

- Retain an option for long units declarations (and add "thousand cubic feet" for mcf long units)

- Consider an option to use short units (since industry folks are familiar with them), but wrap as glossary terms (all three are units of measurement are in the glossary).

**Comment by jennmalcolm** [comment]
We are having double units too ![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/0760812e-b130-4cdd-bb4f-b45cc514471e)

**Comment by jennmalcolm** [comment]
This should be taken care of in new graphs in cloud.gov, and if there are issues continuing we will make those in the new repo.
