### ISSUE TITLE
Create OGOR B Download page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4820]
Things we need to consider:

What should we call it? Probably not "OGOR B", maybe not "Disposition of Production"
Can we think of something else that will explain what it is to a user who may want the data (e.g. flaring and venting) but may not know much about the data set and our terms?

We'll need some new scope and definitions documentation with this new dataset. We should draft something and then work with DORC to make sure they agree with the way we're describing new fields.

**Comment by mentastc** [comment]
I statrted an OGOR B page in word and shared it with you both. Here's the link to the page: 
https://doimspp-my.sharepoint.com/personal/mentastc_mms_gov/Documents/OBOR%20B.docx?web=1

**Comment by Maroyafaied** [comment]
@mentastc for some reason I get a 404 error when I click on the link for the document

**Comment by jennmalcolm** [comment]
The link doesn't work. Maybe @Maroyafaied and @brentryanjohnson can brainstorm what to call this data set while we wait for @mentastc to share what he has so far. That will probably need to be next sprint.

**Comment by Maroyafaied** [comment]
@brentryanjohnson here are a few names I came up with for calling the OGOR B data.

Production placement data 
Production by use  
Production by allocation 
Detailed description of product use

**Comment by Maroyafaied** [comment]
@brentryanjohnson I found the right link to Chris's document. 
https://doimspp-my.sharepoint.com/:w:/r/personal/mentastc_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B0F24833D-8E41-41A5-88AC-74AFCAAADDC3%7D&file=OGOR%20B.docx&action=default&mobileredirect=true

**Comment by brentryanjohnson** [comment]
Waiting on data

**Comment by Maroyafaied** [comment]
We have a draft of the OGOR B download page but still waiting to receive the updated data set to finalize the download page.

**Comment by jennmalcolm** [comment]
This issue is done. Since we're waiting on data, work will continue in #4822 once we get it.
