### ISSUE TITLE
Move roadmap into ZenHub Roadmap feature

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4823]

**Comment by lpgoldstein** [comment]
@jennmalcolm I'm closing this issue and have the following recommendations that I can tackle in the next Sprint. 

Road maps notes and recommendations 

- It is my understanding that we are converting our release notes to “Projects” within the Roadmaps feature and then using “Epics” nested under each project to categorize relevant issues during each Project.  
- We also have “Epics” that are independent of “Projects”.  

Current state 

- In the Roadmap, we have a Project created for Eggnog and several Epics within that Project. We have several goals within Eggnog that are not yet represented by Issues.  
- We have several independent dated Epics within the Roadmap.  
- We also have ~10 Epics that are undated and not in the Roadmap.  

Questions:  
- What do we do about Epics that are old but all issues aren't finished? Do we need to go through as a team and convert to dated Epics?  
Example: https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/doi-extractives-data/3580,  

Recommendations 
- We should create issues for the goals that aren’t reflected in Eggnog.  
   - Blog #2 
   - Outreach/social media for LWCF 
   - Blog metrics 
- We should add dates to Epics so they are represented in the Roadmap.  
- Have a team meeting to tackle together.

**Comment by jennmalcolm** [comment]
@lpgoldstein I was thinking that each of the top-level goals from the previous roadmap version would be an epic, with the features as issues (one or more for each feature) that are categorized under the epics/goals. We should discuss this as well as using epics vs labels and whether epics should always be discreet projects with some kind of end point at our syncup today.
