### ISSUE TITLE
State cards that never have data (Maine)

### ISSUE THREAD

**Issue by mojobnichols** [ONRR/doi-extractives-data#4835]
State revenue cards that never have data should display a message that states that

**Comment by mcharg** [comment]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6f3d0949-3c20-47b5-9c6e-5c105fa73c87)

**Comment by mojobnichols** [comment]
Okay started putting in the logic but I'm curious if this shouldn't be an alert that just says the the state has no data.... so that a card slot isn't wasted on no data....

**Comment by mojobnichols** [comment]
Follow up question do we know of a state that has data since 2003 but doesn't in current year

**Comment by mcharg** [comment]
Looks like Tennessee has revenue for some years, but not others.  Since we're going to have some sort of view of revenue over time in the charts below, we need to allow selecting states without data in the current year to compare and get the view over time.

**Comment by mojobnichols** [comment]
Closing as this issue is working in dev
