### ISSUE TITLE
Update nav to reflect new location for map & other changes

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4844]
Design:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/350fd0f5-e1fa-44b3-8b31-8e7263f1e2e8)

"Revenue by location" link should change to "Production by location" and "Disbursements by location" depending on which tab the user is on and select the appropriate data set on the Explore Data page when clicked.

**Comment by jlouis-onrr** [comment]
These updates can be reviewed here:

[REVIEW](https://1-implementmaterialuithemeandlayout.app.cloud.gov/)
