### ISSUE TITLE
Create nationwide revenue card

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4846]
Default view:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c1d8159a-9003-4449-94ee-49b66ef79525)

Collapsed:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d22db7f5-973b-4159-b8c1-2c9ae00243b2)

**Comment by mojobnichols** [comment]
A style issue is minimize doesn't pull it from card stack.   It should but I'm letting that be a separte issue as the mechanics are (should) all be working for revenue cards.

**Comment by mojobnichols** [comment]
Closing  issue has been released to dev
