### ISSUE TITLE
Create Outline for Code for America Summit Presentation

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4853]
Proposal:

Track: Design + Delivery 

Title (160 characters max) 

Slowing down agile to government speed: bringing the whole team along - Shannon & Ryan 

Description (130 words max) 

Two-week agile sprints are so focused on delivery, they don’t leave much time to collaborate and properly scope features. Additionally, with a lot of team members new to working on digital products, some don’t know what kind of feedback to provide or are afraid to speak up with their insights. We often miss things that should have been taken into account., Inspired by the book Shape Up: Stop Running in Circles and Ship Work that Matters by Basecamp’s Ryan Singer, we’re trying to solve these problems by exploring ways to slow down our process into cross-functional phases and allow for more collaboration and teaching moments during both the design and build phases. We’ll share a case study and lessons learned.

**Comment by brentryanjohnson** [comment]
@mcharg What do you think about breaking this into two issues: one, scoping the problems we were trying to solve, the research we did, selling the idea to the team, modifying the implementation, and so on; and two, building the deck?

One major question we'll have to answer: the introduction of agile to government was meant, at least in part, to bring effective, modern practices to government, helping government become more effective and responsive. How does slowing down agile for government not revert us back to the problems agile is trying to solve?

**Comment by mcharg** [comment]
@brentryanjohnson Sure, feel free to split it up.

**Comment by mcharg** [comment]
Beginnings of an outline (limited access):
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Proposals/FY20/Code%20for%20America%20Summit/Shaping%20Presentation%20Outline.docx?d=w3053210747334dedb78d849030ae5d44&csf=1&e=NOx7Gp

**Comment by mcharg** [comment]
@brentryanjohnson This is ready for you to take another pass through.

https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B30532107-4733-4DED-B78D-849030AE5D44%7D&file=Shaping%20Presentation%20Outline.docx&action=default&mobileredirect=true

**Comment by brentryanjohnson** [comment]
I added a few lines, but I think it looks great!

**Comment by mcharg** [comment]
@jennmalcolm This is ready for you to review.

https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B30532107-4733-4DED-B78D-849030AE5D44%7D&file=Shaping%20Presentation%20Outline.docx&action=default&mobileredirect=true

**Comment by jennmalcolm** [comment]
I added a few comments.

**Comment by mcharg** [comment]
I think this is good enough, for now. We can revisit when we create the presentation and as we finish up the Explore Data project.
