### ISSUE TITLE
Disbursement trends data

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4858]
Determine what data should be shown on the disbursements trends vs rolled up into "other funds" or an alternative.

**Comment by mcharg** [comment]
We already have #4476 for this, which @mojobnichols said we should wait until the database is ready to do because of the calcs he has to do to split out funds.

**Comment by jennmalcolm** [comment]
Ok but I think we still need to have a discussion on what is the best strategy and what to split out vs combine, so I want to keep this one open for that discussion and decision on strategy.

**Comment by jennmalcolm** [comment]
closing in favor of https://github.com/ONRR/nrrd/issues/3
