### ISSUE TITLE
Change link for 1970 Act in Laws and Regulations

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4863]
We currently link to regulations for the Mining and Mineral Policy Act of 1970. The others I looked at link to the actual act. Shoudl we use this link instead?

https://legcounsel.house.gov/Comps/Mining%20And%20Minerals%20Policy%20Act%20Of%201970.pdf

**Comment by brentryanjohnson** [comment]
It's a good question...we cite the U.S. Code after the link, but we would no longer be linking to the code, but rather the act.

How do think we should handle that, @jennmalcolm? It seems to me we should still reference the code, since it's the practical application of the act.

**Comment by jennmalcolm** [comment]
Seems to me that if we can link to the act/law, we should since that is under the laws section, but I took a look at some more of the links and there is a mix between the actual laws and the US code (regulations) implementing the laws. We should be consistent I would think. What about doing both. Could we have the law title link to the act whenever available, and the parenthetical link to the referenced code? 

Also, maybe this is not that important if this section doesn't have a lot of use, so you can just close the issue if you think it's not worth the effort of reviewing and updating these links.

**Comment by brentryanjohnson** [comment]
I definitely think it's worth exploring. I'll record the inconsistencies in the content audit I'm doing now, and then we can form a plan from that. 👍
