### ISSUE TITLE
Due 1/15: Write article for Apolitical's writing competition

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4879]
•	The prompt: What’s your story of change in government? 
•	Articles can be on any policy, project, trend, or debate. However, they must: 
•	Be interesting and directly relevant for a global, influential public-sector audience 
•	Argue a specific point of view 
•	Be clear and engaging
•	Make sense to someone without detailed local knowledge or expert topic knowledge 
•	Articles will be more likely to succeed if they draw on your personal work experiences. For example, they could draw on:
•	A policy or project you’ve worked on
•	A policy or project your federal, state, or local government has worked on that you are very familiar with
•	A discussion of new evidence or research you’ve seen or been involved in
•	A debate or trend on policy/public service that you’ve witnessed or researched
•	Your personal experiences as a public servant or policymaker e.g. around digital, diversity, values, or success
•	An innovative solution to a social problem you want your government to implement
•	This list is not exclusive, and you are welcome to use your imagination!  

Articles are due 1/31, but ones in before 1/15 get editing.

**Comment by mcharg** [comment]
Thoughts on re-purposing either the [teaching digital skills](https://revenuedata.doi.gov/blog/usability-testing-training/) or [journey mapping as communication tools](https://revenuedata.doi.gov/blog/journey-mapping/) blog posts for this?

I don't see anything in the rules that say it can't be content that is published elsewhere.  If I used either one, I would update it to make it fit to the requirements and make it current with our progress since the original post.

@jennmalcolm @brentryanjohnson @Maroyafaied @lpgoldstein

**Comment by Maroyafaied** [comment]
I don't see an issue in doing that. An idea that I just had for a topic for you is talking about the explore data shaping process and the four sessions you led for the team and the outcome that came out of it.

**Comment by mcharg** [comment]
The shaping process is what we're presenting at the Code for America Summit and they wanted to know if the content was going to be presented elsewhere, so I'm thinking that's out for this particular contest.  I'd also like to have something completed using the process before we talk about it.

**Comment by mcharg** [comment]
This post on making open data useful is another contender. https://revenuedata.doi.gov/blog/open-data-useful/

**Comment by mcharg** [comment]
Here's a start at turning the teaching usability testing topic into an article.  I'll work on bringing it into alignment with Apolitical's template on Thursday. (limited access)
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Proposals/FY20/Apolitical%20Writing%20Challenge%20-%20January/Teaching%20Technical%20Skills.docx?d=w35ff35df918546c98a00d95623f69a9f&csf=1&e=rgfePM

**Comment by mcharg** [comment]
@jennmalcolm @brentryanjohnson Will you please review?
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Proposals/FY20/Apolitical%20Writing%20Challenge%20-%20January/Teaching%20Technical%20Skills.docx?d=w35ff35df918546c98a00d95623f69a9f&csf=1&e=rgfePM

**Comment by jennmalcolm** [comment]
Looks good. I reviewed and added a couple of comments.

**Comment by mcharg** [comment]
Submitted
