### ISSUE TITLE
Explain best use and misuse of each data set in the main download page.

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#4884]
Relates to issue #4849. Come up with a simple design/display to let the user know best use cases and misuse of each data set such as a green check mark for correct use and a red X for misuse. This would let the user know the fields and tasks the raw data could be used for.

**Comment by Maroyafaied** [comment]
@mcharg @lpgoldstein here is what I have worked on so far, I'm not sure if the design is something we can do but we can discuss next week when we are all working. https://doimspp-my.sharepoint.com/:w:/r/personal/faiedm_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B50E8548D-45BA-42F9-9960-B96E8CD7EB7B%7D&file=Explanation%20of%20data%20sets.docx&action=default&mobileredirect=true

**Comment by mcharg** [comment]
Here's a checkmark icon from CFPB that matches our other icons:
https://thenounproject.com/cfpb_minicons/uploads/?i=89605

And an x mark:
https://thenounproject.com/cfpb_minicons/uploads/?i=89608

Or we could use an exclamation mark instead of the x:
https://thenounproject.com/cfpb_minicons/uploads/?i=89607

**Comment by Maroyafaied** [comment]
@brentryanjohnson @jennmalcolm This is ready to review, I will move the issue to next sprint so we can decide on next steps.

**Comment by jennmalcolm** [comment]
I added my comments. After the comments have been addresses and @brentryanjohnson has had a chance to review, could you see if someone in DORC will take a look too? Thanks

**Comment by Maroyafaied** [comment]
@jennmalcolm I just worked through all your comments, it's ready for @brentryanjohnson review then I'll send it to DORC.

**Comment by Maroyafaied** [comment]
@jennmalcolm Andrew provided two comments , one is to change the word calculate to analyze, and a comment to change the introduction sentence we have in the download page. I will close this issue and create another one to decide how we will move forward with this.
