### ISSUE TITLE
Document methodology for data collection, validation, and management

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4901]
We should consider adding comprehensive methodology documentation for how we collect, validate, and manage data. We can then add a section to the documentation for each dataset with the respective methodology.

**Comment by jennmalcolm** [comment]
Does this refer to how ONRR collects, validates, and manages data, or just our work for NRRD?

**Comment by brentryanjohnson** [comment]
@jennmalcolm Yes, that's the idea. I think it would benefit users to publish plain-language information about how the data gets to and moves through ONRR before landing on the website.

**Comment by jennmalcolm** [comment]
Ok, that makes sense. I just wanted to make sure I understand the suggested scope.

**Comment by Maroyafaied** [comment]
![image](https://user-images.githubusercontent.com/40175688/72451969-ff2e0d00-3779-11ea-9e11-5b830f51c841.png)

**Comment by Maroyafaied** [comment]
@mentastc @lpgoldstein I added a description under disbursement. I also added a summary on top that talks about how ONRR collects and verify data through it's compliance program including audits, compliance reviews and data mining. Please review. https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc={51963a36-4551-4d06-9364-b062548ed785}&action=edit&wdPid=5ae7321d

**Comment by Maroyafaied** [comment]
@jennmalcolm @brentryanjohnson please review.

**Comment by Maroyafaied** [comment]
I will close this issue since we have another one open (#4936) to continue this work .
