### ISSUE TITLE
Decide what we're doing with labels and epics

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4902]
We need to collectively decide how we're using meta data for issues.

**Comment by mcharg** [comment]
For reference, these are the definitions we landed on for the priority labels a while back.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ed489c8d-8f19-444e-b485-5169807f2260)

**Comment by jennmalcolm** [comment]
Perhaps we can also discuss documenting some guidelines for what types of work should become issues and in which repo. I think now that we have more than one repo, this would be a worthwhile conversation to have. I will set up an initial meeting with you @lpgoldstein to begin the brainstorming.
