### ISSUE TITLE
Due 1/25: Proposal for Boston UXPA Conference

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4903]
Conference is May 29 in Boston.
http://uxpaboston.org/uxpa-boston-events/user-experience-conference/2020-call-for-proposals/

**Comment by mcharg** [comment]
@jennmalcolm This should be ready for you to review. (limited access)

https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B191BDF0F-106C-413F-83F4-4B073F9B0CD4%7D&file=UXPA%20Boston%20Conference%20Submission%20Template.docx&action=default&mobileredirect=true

**Comment by jennmalcolm** [comment]
Looks good. I made a couple suggestions in the comments.

**Comment by mcharg** [comment]
Submitted.
