### ISSUE TITLE
Document a list of Data Display's processes and procedures

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#4911]
This issue is for  IDM's initiative "Establish how/where to document and share all IDM processes and procedures (SOPs) ".  The first step is for each team to make a list of process names, description and it's location.

**Comment by Maroyafaied** [comment]
@jennmalcolm @mcharg  this is the list of documented process I have so far, is there anything I missed? Also, can you think of any process within our team that we have no documented yet?

**Comment by Maroyafaied** [comment]
[](url)
![image](https://user-images.githubusercontent.com/40175688/72282392-cebf6500-35f9-11ea-80d3-1ad546bdc18e.png)

**Comment by jennmalcolm** [comment]
What do you think about includign the FACA procedures that we have, just in case IDM has to support one in the future again?

**Comment by Maroyafaied** [comment]
@jennmalcolm that's a good idea, do you know the location of where it's documented? I can look in that folder.

**Comment by Maroyafaied** [comment]
I added the RPC procedures 
![image](https://user-images.githubusercontent.com/40175688/72291824-67abab80-360d-11ea-8421-bf9e02793c89.png)

**Comment by Maroyafaied** [comment]
DD list of processes has been documented , I can always add to it as we think of any processes that still need to be documented.
