### ISSUE TITLE
Due 1/31: Edit submission for Apolitical writing competition

### ISSUE THREAD

**Issue by mcharg** [ONRR/doi-extractives-data#4916]
They sent me feedback via email.

**Comment by mcharg** [comment]
@jennmalcolm This is ready for you to review (limited access).
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc={3c2af97c-af7b-425c-95b5-5d1ec07d65fc}&action=edit&wdPid=1

**Comment by jennmalcolm** [comment]
I reviewed it and left one comment.

**Comment by mcharg** [comment]
Edits submitted.
