### ISSUE TITLE
Data checking checklist

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#4928]
The calendar year numbers on the homepage production and revenue graphs are coming from the monthly files, so we need to update the review checklists to reflect this.

**Comment by Maroyafaied** [comment]
@jennmalcolm I just made the edits, let me know if this is what you meant! 
![image](https://user-images.githubusercontent.com/40175688/72367229-11944200-36b9-11ea-8124-e8ad8310eccc.png)

**Comment by jennmalcolm** [comment]
yes @Maroyafaied
