### ISSUE TITLE
Decide how to move forward with best use of data in the main download page. 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#4935]
Related to issue #4884 
https://doimspp-my.sharepoint.com/:w:/g/personal/faiedm_mms_gov/EY1U6FC6RflCmWC5bozX63sBgQklYhD-qZbdGLYanJGN5Q?e=LhoAqF&CID=8b1e0694-53a6-bea5-1778-e271f4d66530

**Comment by Maroyafaied** [comment]
@jennmalcolm @brentryanjohnson , Lindsay and I discussed this and we think we should wait on putting this on the main download page till we have the sales and OGOR B data from DORC.  The other options is to add the sections for the data we have available now then add the OGOR B and sales data later when we have them. Any thoughts?

**Comment by jennmalcolm** [comment]
Yes I think that makes sense.

**Comment by lpgoldstein** [comment]
Added a link to the file to Sales Data and OGOR B issues. #125 in NRRD and #124 in NRRD
