### ISSUE TITLE
Decide on location & finalize ONRR's data collection, validation, and management. 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/doi-extractives-data#4936]
Relates to issue #4901

**Comment by Maroyafaied** [comment]
@brentryanjohnson @jennmalcolm this is the document. 
 https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc={51963a36-4551-4d06-9364-b062548ed785}&action=edit&wdPid=5ae7321d

**Comment by lpgoldstein** [comment]
@jennmalcolm @brentryanjohnson please review document. @mentastc and I incorporated Jennifer's comments https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B51963a36-4551-4d06-9364-b062548ed785%7D&action=edit&wdPid=5ae7321d&cid=83b8a41d-a0ff-4558-bba9-e62de4520d20
