### ISSUE TITLE
Older blog posts missing images

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/doi-extractives-data#4953]
Broken image paths in older blog posts.

[Example](https://revenuedata.doi.gov/blog/homepage-revamp-part-two/)

**Comment by mcharg** [comment]
This brings up a question about the research branch.  We link to the user research findings that live in the research branch from a number of places in the blog and wiki, so we'll need to make a decision about what to do with that when we move over to the new repo.

**Comment by mcharg** [comment]
We need to either do this or move the blog to cloud.gov to get any further blogs posted.
