### ISSUE TITLE
Update CY production data for 2019

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/doi-extractives-data#5018]
Update CY production download file to include 2019 data.

**Comment by lpgoldstein** [comment]
@Maroyafaied It's not a file we can put together ourselves.  DORC hasn't provided us with the updated monthly files going back to 2003 to be able to do this.

**Comment by jennmalcolm** [comment]
have to put on hold due to refactor to account for loss of offshore planning area column

**Comment by jennmalcolm** [comment]
File is on site, and we're not updating explore data due to move to cloud.gov, so I'm closing this issue.
