### ISSUE TITLE
Review and publish onrr.gov blog post

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#5020]
Here's the [draft for review (limited access).](https://doimspp-my.sharepoint.com/:w:/g/personal/malcolmj_mms_gov/Eff1On-3M-lAs5uYO4btU9QBLaR4qmCJ2_e9cNRnpm0Gow?e=Nqddkj) 

@Maroyafaied and @mcharg please review and provide your comments, and after incorporating comments, I will create a branch and PR.

**Comment by mcharg** [comment]
@jennmalcolm I reviewed and put comments in the doc.

**Comment by Maroyafaied** [comment]
@jennmalcolm Great blog post, I made minor changes.
