### ISSUE TITLE
NRRD datasets on data.json

### ISSUE THREAD

**Issue by meiqimichelle** [ONRR/doi-extractives-data#557]
We need to confirm that EITI's unique datasets are catalogued on data.gov by making sure it is represented on DOI's data.json.

/cc @gbinal @harrisj

**Comment by harrisj** [comment]
So, it doesn't seem to be part of https://data.doi.gov/data.json yet. Do we care about pursuing this or leave it up to Interior to figure out?

**Comment by harrisj** [comment]
I think we will table this for now. Feel free to close this issue.

**Comment by meiqimichelle** [comment]
Let's leave this because it is something ONRR's soon-to-be-hired team will tackle when they're on board in FY17. Thank you @harrisj !

**Comment by coreycaitlin** [comment]
Renaming to reflect current situation.

Next step: @brentryanjohnson to investigate how data.doi.gov is maintained, and how we might share data with that site/team.

**Comment by gbinal** [comment]
FYI, the Data.gov team (can be found in #opp-data-analytics in Slack) should have some points of contact over there for that.

**Comment by jennmalcolm** [comment]
Next step: @brentryanjohnson check in with Ralph Johnson to see if he can help us on this.

**Comment by brentryanjohnson** [comment]
I've contacted Ralph Johnson at ONRR and will set up time to discuss.

**Comment by jennmalcolm** [comment]
Closing as we have not be advised that this is a Data Display responsibility.
